### ISSUE TITLE
chromium x86_64 crashes on arch

### ISSUE THREAD

**Issue by 95Cardboard** [Facepunch/garrysmod-issues#5982] opened 2024-08-25 17:08 UTC
### Details
when launching x86_64 chromium beta on arch linux everything is fine until “initiating serverside” and then gmod crashes

### Steps to reproduce
launch x86_64 chromium beta on arch linux

**Comment by robotboy655** [comment] 2024-08-26 14:49
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5092 or related to it.

Please keep in mind that GMod is not officially supported on Arch, only on Debian, this is reflected in the System Requirements on the Steam Store page.

**Closed by robotboy655** 2024-08-26 14:49 UTC
Labels: Platform: Linux, Crash
