### ISSUE TITLE
Using combine turret in multiplayer server (hosted) crash the server

### ISSUE THREAD

**Issue by hanm13** [Facepunch/garrysmod-issues#2061] opened 2015-06-02 15:52 UTC
Console error ./srcds_run: line 354:  3690 Segmentation fault      (core dumped) $HL_CMD
Linux centos 6.5

**Comment by hanm13** [comment] 2015-06-02 20:03
More information I have problem when I use AddEntityRelationship afer the last update it's just crashes the server when it been called.
Before the update I did not get this bug.
I dont get any lua error on the server console
the only error I get when the server crash is :
./srcds_run: line 353: 25695 Segmentation fault      (core dumped) $HL_CMD
cat: hlds.25227.pid: No such file or directory
After I mapped my gamemode.

I also can add the code of the gamemode
Exmaples of lines that crash the server when they been called : 
if( t[3] == 1 ) then ent:AddEntityRelationship( v, D_HT, 99 ) end
if( t[3] == 2 ) then ent:AddEntityRelationship( v, D_LI, 99 ) end

**Comment by hanm13** [comment] 2015-06-02 20:06
Information about the vps by command uname --all
2.6.32-504.12.2.el6.x86_64 #1 SMP Wed Mar 11 22:03:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by hanm13** [comment] 2015-06-02 20:14
ent = npc_turret_floor

**Comment by hanm13** [comment] 2015-06-02 20:36
Also, its happened only when I spawn the turret NPC, in multiplayer and singleplayer.
I tried to disable all addons (only the gamemode running)
it's 100% are not gamemode / lua error because before this update I did not have this bug.
It's happen in all maps.
Sorry about grammer mistakes, english are not my first lang.

**Comment by deinemudda32** [comment] 2015-06-03 03:06
How about you reinstall gmod fully on youre server and test again.
Mostly some files doesnt get updated completly.
Happend on me on TTT

**Comment by hanm13** [comment] 2015-06-03 05:11
I reinstalled the server, again the same bug...

**Comment by hanm13** [comment] 2015-06-04 16:51
Any update from devs?

**Comment by 00875** [comment] 2015-06-05 07:36
My server host is Windows 10 and 'killing' turret causes server crash

**Comment by hanm13** [comment] 2015-06-05 08:39
Same here.
When the turret fall to the ground the server crashed.
Rubat, please remove the invalid label.

**Comment by robotboy655** [comment] 2015-06-05 11:38
Alright, I manager to reproduce it ( Apparently I can only make it crash with friendly turret and only in multiplayer ).

It seems to be related to the Vector changes @UnderscoreKilburn did in this update.

**Comment by robotboy655** [comment] 2015-06-05 12:45
Ok, I think I found out why it crashes when you pick it up with Gravity Gun.

If you know of any other 100% causes, let me know.

**Comment by hanm13** [comment] 2015-06-05 13:02
Press E on the turret and make it fall on the ground it will shoot few shots and the server will crash.

**Comment by 00875** [comment] 2015-06-05 13:11
Server crashes if turret got 'killed' by any way

**Comment by robotboy655** [comment] 2015-06-05 14:27
The +use ( E ) pickup is the same. I cannot reproduce the crash as soon as it gets killed, it just doesn't happen.

**Comment by 00875** [comment] 2015-06-05 14:48
Interesting...
```
hook.Add("OnNPCKilled","testhooks",function(npc) print(npc:GetClass().." was killed") end)

local turret = ents.Create("npc_turret_floor")
turret:SetPos(Vector(0,0,0))
turret:Spawn()
turret:Activate()

for k,v in pairs(ents.GetAll()) do
	if v:IsNPC() then
		turret:AddEntityRelationship(v,D_NU,99)
	end
end
```
On sandbox does nothing.
![2015-06-05_21-48_garry s pony mod -light](https://cloud.githubusercontent.com/assets/6339511/8008466/96232f76-0bcc-11e5-9ddd-a145c2a7d8f7.jpg)

**Comment by robotboy655** [comment] 2015-06-05 17:32
Look for other OnNPCKilled hooks and AddEntityRelationship calls/overrides.

**Comment by hanm13** [comment] 2015-06-05 19:13
Hey @00875 Try to change it to turret:AddEntityRelationship( v, D_LI, 99 )

**Comment by robotboy655** [comment] 2015-06-05 19:34
I'll close this for now, I will commit a fix for the pickup crash, once Dev branch updates please test if you still have issues.

**Closed by robotboy655** 2015-06-05 19:34 UTC
Labels: bug, crash

**Comment by hanm13** [comment] 2015-06-06 15:44
Okay, I checked the dev branch I saw in the dev website "Fixed a crash issue with npc_turret_floor"
I downloaded the game dev branch version and changed the server to the dev branch version, and I have the same bug.

**Comment by robotboy655** [comment] 2015-06-06 17:04
The goddamn build server has not published the update yet.

See here: https://steamdb.info/app/4000/history/

**Comment by Bo98** [comment] 2015-06-06 17:06
Could it be because of it trying to build OS X (which it hasn't successfully since the manual build)?

**Comment by robotboy655** [comment] 2015-06-06 17:16
It is that. We just have to wait for Garry to fix it.

**Comment by hanm13** [comment] 2015-06-07 14:44
I saw Garry released the dev branch update, and I checked it in my dev branch server
And there is no bug anymore.
Thank you.

**Comment by hanm13** [comment] 2015-06-07 14:57
Rubat what is the name of the lua file that you fix inside the turret problem, it's server side so I can update it manually without wait to official update.

**Comment by robotboy655** [comment] 2015-06-07 16:50
You can't fix it. Wait for next update.
