### ISSUE TITLE
False compile errors on autorefresh

### ISSUE THREAD

**Issue by sanny-io** [Facepunch/garrysmod-issues#2996] opened 2016-12-30 06:40 UTC
On autorefresh, scripts may report a compile error even though the scripts compile correctly. The error is usually related to parentheses, and appears to happen more frequently, if not exclusively, on Linux.

The scripts initially execute with no compile errors, and is only when autorefreshed that they raise one. The scripts execute correctly regardless of the fact that they apparently do not compile. 

Some recent examples of this occurring:

1. https://facepunch.com/showthread.php?t=1545911&p=51555577&viewfull=1#post51555577
2. https://facepunch.com/showthread.php?t=1546998&p=51600385&viewfull=1#post51600385

The examples include code that this issue occurred in.

**Comment by ARitz-Cracker** [comment] 2016-12-30 06:47
To me it always seemed like the files were bead read before they were fully written. But I'm just speculating.

**Comment by shadowndacorner** [comment] 2016-12-30 07:01
I only seemed to notice the issue when the file was larger than 5kb.  Didn't think about the fact that it could be a partial write since I was modifying files over SFTP, whereas I generally hosted my Windows server locally.  If that was the case however, wouldn't it refresh again after it detected that the file was written again?

**Comment by ARitz-Cracker** [comment] 2016-12-30 07:27
Yes it would. In fact, in my experience, it does.

**Comment by birdbrainswagtrain** [comment] 2016-12-30 07:51
Noticed this as well. Generally isn't a big deal, since the script will fail to compile the first time. Would be nice if there were a way to fix this on gmod's side though, since this is pretty annoying and I have no idea how you'd go about fixing it on the file transfer side.

**Comment by robotboy655** [comment] 2016-12-30 08:15
Does this happen with lua_openscript(_cl)?

**Comment by sannysc** [comment] 2016-12-30 08:44
I don't think so. I've only seen this happen with autorefresh, but I no longer have a Linux server, so I can't test it myself. Maybe @shadowndacorner or one of these other guys can help.

**Comment by robotboy655** [comment] 2016-12-30 08:54
https://facepunch.com/showthread.php?t=1546998&p=51600658&viewfull=1#post51600658

According to this, its not a bug with GMod.

**Comment by Bo98** [comment] 2016-12-30 13:58
This could be fixed if `IN_MODIFY` is changed to `IN_CLOSE_WRITE`: https://github.com/garrynewman/bootil/blob/master/src/Bootil/File/Changes.cpp#L100

`IN_CLOSE_WRITE` event is triggered when a modified file is closed while `IN_NOTIFY` is triggered as soon as a write is made, which will be several times during an upload in the case of FTP.

**Comment by Luabee** [comment] 2017-01-03 07:06
I also have this problem.

**Comment by Kefta** [comment] 2019-06-10 12:12
Just got a message about this issue appearing on someone's server, does @Bo98's solution not work?

**Comment by TiberiumFusion** [comment] 2020-02-25 03:51
Coming from #4388, which was just closed as a duplicate (among many), I am curious if this bug will ever get fixed. It has been reported several times over several years and nothing has been done to date.

**Comment by robotboy655** [comment] 2020-02-25 16:17
This is not exactly a vital issue, especially considering its Linux only and only due to FTP with large files, and your file is still executed normally despite the error (because it is refreshed multiple times due to FTP)

Of course I could just slap the proposed solution above, but I cannot verify it actually works on my end, or whether it has any obvious side effects.

**Comment by Kefta** [comment] 2020-02-25 21:35
I mean, there are currently users here experiencing the issue who would test any fix. I think it should be put on the dev branch at least.

**Comment by robotboy655** [comment] 2020-02-26 17:16
Alright I applied the fix just for you, let me know if it works.

**Comment by TiberiumFusion** [comment] 2020-02-26 22:16
@robotboy655 How can I test this change? `app_update 4000 -beta dev` makes zero changes to my server install. Is there a password?

Just for kicks, I updated my client to dev and joined my server install (which is running whatever the vanilla flavor of gmod is, since `-beta` in steamcmd does nothing) and the bug persists, as expected.

**Comment by robotboy655** [comment] 2020-02-26 23:03
You need your server on Dev, `app_update 4020 -beta dev`, not 4000

**Comment by TiberiumFusion** [comment] 2020-02-27 01:17
@robotboy655 Thanks much, using the correct app ID certainly does help... aghhh

**Comment by robotboy655** [comment] 2020-02-27 18:22
So it works then?

**Comment by TiberiumFusion** [comment] 2020-02-27 23:45
@robotboy655 I just tested several minutes ago. Server is on dev circa 2020-02-27 23:28 UTC and client is on dev 2020.02.27. On cursory examination, the glitch is fixed. Overwriting a >32KB Lua file with FTP (specifically SFTP v3) seems to work fine. The parser makes it completely through the file. I tested files up to 1MB in size, all were correctly parsed.

**Closed** 2020-02-28 00:03 UTC
