### ISSUE TITLE
Includes break if gamemode name starts with "game"

### ISSUE THREAD

**Issue by CptDinosaur** [Facepunch/garrysmod-issues#4629] opened 2020-08-09 12:33 UTC
### Details
I was trying to fix an old fretta gamemode, but includes were broken.

I narrowed it down, finally, to the name starting with "game". Any gamemode in which the name starts with "game" seems to have this issue.

Creates errors like this:
```
Couldn't include file 'shared.lua' (File not found) (@gamemodes/game/gamemode/init.lua (line 1))
[AddCSLuaFile] Couldn't find 'shared.lua' (@gamemodes/game/gamemode/init.lua (line 2))
[AddCSLuaFile] Couldn't find 'cl_init.lua' (@gamemodes/game/gamemode/init.lua (line 3))
```

![image](https://user-images.githubusercontent.com/26852749/89732170-e2726300-da44-11ea-8d9d-e353aafee522.png)

Other user reproducing:
https://cdn.discordapp.com/attachments/567617926991970306/741997098211213362/unknown.png

### Steps to reproduce
- Create a gamemode with "game" at the start
- Try to include a file in init.lua

I ran on an SRCDS server on both Linux and Windows, same issue. Renaming gamemode immediately fixed the error.

Example gamemode attached
[game.zip](https://github.com/Facepunch/garrysmod-issues/files/5047482/game.zip)

Reproduced by 2 other users in Garry's Mod discord.
One confirmed it occurred when just renaming darkrp to "gamemaster" (i.e. the folder, text file, and first line of said text file)

**Comment by Kefta** [comment] 2020-08-10 11:02
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/2808.

**Closed by Kefta** 2020-08-10 11:02 UTC
