### ISSUE TITLE
HL2 Not Responding...

### ISSUE THREAD

**Issue by Hilligoss17** [Facepunch/garrysmod-issues#1805] opened 2015-02-26 18:47 UTC
Every game I try to join, it'll begin loading addons and what not, and then ultimately get stuck on one item about 1 minute into it and get stuck. The game then crashes and says that Hl2_osx stopped responding... I've been trying to fix this for 5 days now and nothing works.

I've tried restarting computer, restarting steam, uninstalling game and reinstalling, using the recommended settings under options on  Garrys mod main menu, I feel like I've done everything I could that people have said worked yet it doesnt work for me.

PLEASE HELP ME!

**Comment by robotboy655** [comment] 2015-02-26 22:09
Duplicate of #888
This is not a place to get help, this is a bug tracker.

**Closed by robotboy655** 2015-02-26 22:09 UTC
