### ISSUE TITLE
Bug with concommands?

### ISSUE THREAD

**Issue by arduinium** [Facepunch/garrysmod-issues#1902] opened 2015-03-18 12:35 UTC
Hello,

I posted this on forum but got little to no attention, so I decided to post here

Look at this simple code:
```Lua
local function testcc( ply, cmd, args )
	print( SERVER and "sv" or "cl" )
end
concommand.Add( "testcc", testcc )
```
Put this code in a file in lua/autorun, in both your game and on a dedicated server. Then do the following:

1. Start Gmod and your dedicated server.

2. Start a Single Player game, type "testcc" from in-game console, it will print "sv". This is normal behavior, but doing this step (starting Single Player game just after starting Gmod) is what's causing the issue described in the next step.

3. Connect to the dedicated server, type "testcc" from in-game console: problem! It should print "cl" in the in-game console, but instead, it prints "sv" in the server console.

4. Restart Gmod (you don't need to restart dedicated server).

5. Connect to the dedicated server, type "testcc" from in-game console, this time it will now print "cl", as it should.

6. From now on, until Gmod is closed, the problem will not happen: you can disconnect from dedicated server and start a Single Player game: command will print "sv", reconnect to dedicated server: it will print "cl", etc...

So it appears to me that there is a bug if you first start a Single Player game and then connect to a dedicated server, like if the concommand wasn't "unregistered" correctly from the Single Player session.

**Comment by robotboy655** [comment] 2015-03-18 15:41
Defining console commands shared will cause these problems. Define them strictly serverside or clientside.

**Comment by arduinium** [comment] 2015-03-18 16:31
That doesn't solve the problem.
If for example I put this in lua/autorun/client:
```Lua
local function testcc( ply, cmd, args )
    print( "cl" )
end
concommand.Add( "testcc", testcc )
```
And this in lua/autorun/server:
```Lua
local function testcc( ply, cmd, args )
    print( "sv" )
end
concommand.Add( "testcc", testcc )
```
Exactly the same problem is happening :(

**Comment by robotboy655** [comment] 2015-03-18 16:34
That's because you use the same console command names. Two console commands with same name cannot exist on both client and server on the client.

**Comment by arduinium** [comment] 2015-03-18 16:40
But it's working as long as you don't start a Single Player game prior to joining the dedicated server :/

**Comment by thegrb93** [comment] 2015-03-18 17:10
Yeah I can confirm. You get the blue text in chat that says "Unknown command" or whatever.

**Comment by Commodore64Hank** [comment] 2015-03-18 17:13
Arduinum, your problem stems from running both of those commands as the same command. You can not define a console command with the same name if it is both clientside and serverside. 

Try this instead.

local function testcc( ply, cmd, args )
    print( "cl" )
end
concommand.Add( "testcc", testcc )

and 

local function testcc1( ply, cmd, args )
    print( "sv" )
end
concommand.Add( "testcc1", testcc1 )

That will fix the issue.

**Comment by arduinium** [comment] 2015-03-18 19:04
@Commodore64Hank

No it will print "sv" if SERVER is true, "cl" otherwise. It's called the ternary operator.


Forget about the steps 4, 5, 6 from the first post, in case this wasn't clear enough: they are the same as doing steps 1, 2 and 3, but in this order: 1 -> 3 -> 2

There should be no problem having both commands with the same name: one is client side, the other one is server side, they shouldn't conflict, AND THEY DON'T, UNLESS you reproduce steps 1 -> 2 -> 3.

If you do steps in that order instead: 1 -> 3 -> 2 then both commands work as intended, and you can then repeat step 3 and they will still work as intended. As long as step 1 is NOT followed by step 2, it will work.

I hope it's clear :/

**Comment by thegrb93** [comment] 2015-03-18 21:07
It looks like they are saying the behavior of having concommand with the same name on server and client is undefined. Even though it sometimes works, it may not work.

**Comment by neico** [comment] 2015-03-18 23:13
The issue is that on the client you have commands for the client AND for the server, so it's pure luck which of the function get's called, if you try it on a dedicated server only the server one will be available and therefore work.

here's a little trick (not counting the MENU lua state which can complicate things further):

```lua
if CLIENT || game.IsDedicated() then
	concommand.Add( "testcc", function( pPlayer, szCmd, pArgs )
		MsgN( "I'm either a client or a dedicated server console :D" );
	end )
end
```

**Comment by 0tt** [comment] 2016-05-15 00:16
Solution: Unregister console commands when leaving a game.

**Comment by Bo98** [comment] 2016-05-15 00:52
Console commands are removed with the Lua state in the dev branch.

**Comment by arduinium** [comment] 2016-05-15 19:49
@Bo98 so this issue is fixed in the dev branch?

**Comment by robotboy655** [comment] 2016-05-15 19:58
Dev branch is free and available to every GMod player, you can test it yourself:
http://wiki.garrysmod.com/page/Dev_Branch

**Comment by arduinium** [comment] 2016-05-15 20:10
Will do, thanks :)

**Comment by arduinium** [comment] 2016-05-16 01:44
Had to reinstall both Gmod and dedicated server completely, but that was worth it because this issue appear to be fixed! Should I close this issue now, or wait until this change is applied in a future Gmod update?

**Comment by zerfgog** [comment] 2016-05-16 01:45
Go ahead and close it now.

**Closed** 2016-05-16 10:40 UTC
