### ISSUE TITLE
Crashing on "Sending Client Info"

### ISSUE THREAD

**Issue by SkiMcgee** [Facepunch/garrysmod-issues#2739] opened 2016-07-21 19:52 UTC
This issue just randomly popped up. I can't play on DarkRP/MilitaryRP servers. But others I can. And the thing is that I have played on that server for a while. I closed the Game and the next day it just stopped working.

I have verified files, fully delete and install, any commands, joining single player first, delete             addons/unsub from them and its all failed.

It has taken so long to get where I have gotten to and Im just desperate I have been dealing with this for 2-3 days now. HELP PLEASE

I am running on a MAC OS X El Capitan 10.11.5
I have enough RAM/Memory and etc
And My graphics Card is fine.
CRASH REPORT:
http://pastebin.com/dYz1EFtj

Yes I have read you can Fix it, the #888 etc, But i have read that tons and tons of people have fixed it some how.

**Comment by robotboy655** [comment] 2016-07-21 20:08
Duplicate of #2558

**Closed by robotboy655** 2016-07-21 20:08 UTC
Labels: crash, osx

**Comment by SkiMcgee** [comment] 2016-07-21 23:09
I have actual console logs from MY own computer, not the games.
http://pastebin.com/cU1s94ym

Here is what I said in the original post: 
#2739

Please take a look at my original post and then look at the crash logs That i have put up above. And I'm not trying to reopen my old post or spam. I'm adding some new information

**Comment by Kefta** [comment] 2016-07-21 23:28
Post it in the issue Robotboy listed.
