### ISSUE TITLE
Calling CNewParticleEffect.StopEmissionAndDestroyImmediately after the Entity has been destroyed, leads to a crash

### ISSUE THREAD

**Issue by WinterPhoenix96** [Facepunch/garrysmod-issues#3515] opened 2018-06-22 01:39 UTC
### Details
If the Entity that the CNewParticleEffect was created with is destroyed before StopEmissionAndDestroyImmediately is called, GMod will crash.

MDMP Here: https://winteris.moe/share/2018-06-21_21-39-23.mdmp

### Steps to reproduce
Spawn an entity using this code, and then remove/destroy it:
```lua
ENT.Base = "base_anim"
ENT.Type = "anim"

game.AddParticles("particles/gmod_effects.pcf")

if SERVER then
	AddCSLuaFile()
else
	function ENT:Initialize()
		self.Effect = self:CreateParticleEffect("generic_smoke", 0)
	end

	function ENT:OnRemove()
		local tempEffect = self.Effect
		timer.Simple(0, function()
			tempEffect:StopEmissionAndDestroyImmediately()
		end)
	end
end
```

It should also be noted that at the point that `StopEmissionAndDestroyImmediately` is called, `IsValid(tempEffect)` will return `true`, despite that obviously being false.

**Comment by robotboy655** [comment] 2018-06-22 14:21
Ok, so, the issue is fixed now, however there are some extra "things" about this function (and addcontrolpoint) and that was not properly documented. The 2 functions that are affected have their wiki pages updated.

That being said, IsValid is not wrong, and particles ARE valid after the entity has been removed until their particles are all gone and then they are being cleaned up after <1s, after which the system is indeed invalid.

**Closed by robotboy655** 2018-06-22 14:21 UTC
Labels: crash
