### ISSUE TITLE
Server fonts keep redownloading

### ISSUE THREAD

**Issue by Gen420** [Facepunch/garrysmod-issues#3831] opened 2019-04-28 23:19 UTC
### Details
When joining a server which uses custom specific fonts, the game 'downloads' the font, but is nowhere to be found. Rejoining the server will trigger the download again, but with the same result.
### Steps to reproduce
Join a server with custom fonts.
Example server: Forerunner Gaming Lobby Server (Runescape font, FRG font)

**Comment by robotboy655** [comment] 2019-04-29 03:50
Essentially duplicate of https://github.com/Facepunch/garrysmod-issues/issues/3406

**Comment by robotboy655** [comment] 2019-12-03 17:09
The server you are joining most likely has a misconfigured FastDL server (i.e. the files are not actually on the FastDL).

Check your console log after those files 'download', you are likely to find `HTTP Error ` messages for the font files.

**Closed by robotboy655** 2019-12-03 17:09 UTC
