### ISSUE TITLE
BASS drops the game if content is unmounted/uninstalled during playback

### ISSUE THREAD

**Issue by FlorianLeChat** [Facepunch/garrysmod-issues#5775] opened 2024-03-02 07:51 UTC
### Description ℹ️ 

Some addons, including [this one](https://steamcommunity.com/sharedfiles/filedetails/?id=2583415009), seem to cause a crash ([dump file](https://cdn.discordapp.com/attachments/589120351238225940/1212688590765826048/f8a3e927-19f2-4ae4-b592-cab239948a85.dmp?ex=65f2bf42&is=65e04a42&hm=b66e8ce78eff07d5ada3059f4ae90400271280f70db1c4f11f0e385867467283&)) when uninstalled, or when other addons are uninstalled while a playback is in progress. Read more about this issue on Discord : https://discord.com/channels/565105920414318602/589120351238225940/1212688590732136459

### Game info 💻 

```
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 15:46:59 Mar  1 2024 (9246) (4000)
GMod version 2024.03.01, branch: x86-64, multicore: 1
Windows 64bit
```

### Tests 🧪 
✔️ Tested in singleplayer/peer-to-peer (Windows), *dedicated servers are unaffected*.
✔️ Tested in `x86-64` branch, *other branches are unaffected*.
✔️ Tested with `-noaddons` launch parameters.

### Reproduction steps 📑 

- Install this addon: https://steamcommunity.com/sharedfiles/filedetails/?id=2583415009
- *You must have two/three other addons installed*.
- Launch a singleplayer or p2p game and wait for the background music to play.
- Uninstall a first addon.
- Observe how the music now loops on itself, almost like it's buggy.
- Uninstall a second (or third) addon until the game closes.

**Comment by robotboy655** [comment] 2024-04-11 11:09
Should be fixed on `dev` beta. I suspect this is also a duplicate of https://github.com/Facepunch/garrysmod-issues/issues/3806

**Closed by robotboy655** 2024-04-11 11:09 UTC
Labels: Bug, Crash
