### ISSUE TITLE
still missing Episodic model fixes

### ISSUE THREAD

**Issue by ALIEN31ITA** [Facepunch/garrysmod-issues#5958] opened 2024-07-31 16:13 UTC
The episodic fix is great in this update, but i notice few things were forgotten in the update, leaving some stuff still broken/unplayable
like i've read the patch notes, but i was wondering if it's planned by any chance?...

**Gamebreaking (Softlocking progress)**
- Advisor (Same name & directory)
- Dropship (Animations - just take the EP2 Model [Combine_dropship_Animations.mdl])
- Normal Strider (Animations - just take the EP2 Model [Both animations & Model])
- Headcrabs (Animations (such as Drop from ceiling, and Lamarr related)
- Normal Antlion (EP2 - Used when Alyx gets injured)
- Gman (Postures & Gestures)
- Dog (Animations, Postures & Gestures too)
- Eli ( Same ^^)
- Barney ( Same ^^)

not sure if i am missing something else, this is all i compared between the update and a fanmade fix i was working on before

**Minor issues (Not really gamebreaking but Details)**
- models/props_lab/huladoll.mdl (Missing loop animation from EP2)
- models/props_combine/combine_intmonitor001.mdl - Missing red skin option
- models/props_combine/combine_intmonitor003.mdl - Ditto ^
- Rollermines (Red, Orange skins)
- Mossman (Snowcoat/Transmission) - Same issue as Advisor
- EP2 Eli (sweater) - Texture swap
- EP2 Kleiner (Dirty) - Ditto ^
- Fisherman (Unrelated but, giving him ragdoll collision?)

i could contribute with my fixed models if possible i guess?... just saying lol

**Comment by ALIEN31ITA** [comment] 2024-07-31 16:16
i legit just saw a similiar issue that was posted 1 week ago right after i posted this one 💀

**Comment by robotboy655** [comment] 2024-07-31 16:20
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5945

**Closed by robotboy655** 2024-07-31 16:20 UTC
Labels: Content
