### ISSUE TITLE
HL1 lights screwing up due to post processing

### ISSUE THREAD

**Issue by LilyMcFluffyButt** [Facepunch/garrysmod-issues#3969] opened 2019-09-02 23:13 UTC
https://cdn.discordapp.com/attachments/486270190208679938/618221580572557333/7F3F54005EBD8E5875738B90270A266554C44632.png

This seems to occur when any post processing is activated in maps utilizing HL:S textures. Weirdly, if a prop is made to glow either with the physgun or Prop Glow Tool, it fixes itself until the prop stops glowing.

**Comment by robotboy655** [comment] 2019-09-02 23:35
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/3745

**Closed by robotboy655** 2019-09-02 23:35 UTC
