### ISSUE TITLE
Game crash if use rerty on singleplayer session.

### ISSUE THREAD

**Issue by FalseGM** [Facepunch/garrysmod-issues#4521] opened 2020-05-30 23:43 UTC
### Details
The game crashes (Freezes) if you enter retry in the console to re-enter a single game.

### Steps to reproduce
1) open singleplayer game (max one player).
2) open console.
3) write retry.

**Comment by robotboy655** [comment] 2020-06-01 13:48
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/2713

**Closed by robotboy655** 2020-06-01 13:48 UTC
