### ISSUE TITLE
Serverside GetAimVector broken when sitting in chair with nonzero pitch and roll

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#4927] opened 2021-04-26 04:04 UTC
Old bug, can't shoot straight or use buttons while sitting correctly if the chair is rotated. Should be an easy fix if I can find where the source engine does this.

The problem is most likely due to adding Euler angles. Instead, AngleMatrix and ConcatTransforms needs to be used.

Related https://github.com/wiremod/wire/issues/2154

**Comment by thegrb93** [comment] 2021-04-26 04:07
https://streamable.com/ve9003

**Comment by thegrb93** [comment] 2021-04-26 04:08
GetEyeTrace also affected

**Comment by thegrb93** [comment] 2021-04-26 07:13
Works fine if the player has 'rolled' eyeAngles. Something specific to vehicles.

Am I on the right track here?
SV: https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/player.cpp#L6956


CL: https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/client/c_baseplayer.cpp#L2200

**Comment by thegrb93** [comment] 2021-04-26 07:37
Both of those lead here

SV: https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/baseentity.cpp#L5755

CL: https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/client/c_baseentity.cpp#L4362

Not sure if gmod's source matches this code but this looks like this should be working fine

**Comment by thegrb93** [comment] 2021-04-26 07:41
Maybe you can debug and see what's not matching up between server and client?

**Comment by robotboy655** [comment] 2021-04-26 08:37
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/1150

**Closed by robotboy655** 2021-04-26 08:37 UTC
