### ISSUE TITLE
Too Many Indices

### ISSUE THREAD

**Issue by InklingBoy** [Facepunch/garrysmod-issues#2211] opened 2015-08-27 00:20 UTC
![bug](https://cloud.githubusercontent.com/assets/13989651/9509619/b73a04c0-4c16-11e5-820d-1850266e14ca.png)
Has something like this happened to anyone before?
It usually happens when I'm moving a ragdoll
And how can I fix it?

**Comment by P4sca1** [comment] 2015-08-27 05:09
This is really often happening to one of my clients.

InklingBoy <notifications@github.com> schrieb am Do., 27. Aug. 2015 02:20:

**Comment by deinemudda32** [comment] 2015-09-04 14:53
I had this happen often on my ttt server as I had some pony model installed :P

**Comment by robotboy655** [comment] 2016-12-06 15:47
One of the causes was fixed in a recent update. If you manage to find other causes, please post steps to reproduce, etc.

**Closed by robotboy655** 2016-12-06 15:47 UTC
Labels: crash

**Comment by In-line** [comment] 2017-03-21 10:04
@robotboy655 Game crashed with error "too many indices in index buffer"
Map: ttt_dolls
Mode: TTT
OS: Linux Mint Cinnamon 18 64bit

```
user@user-pc ~ $ screenfetch
                                       user@user-pc
 MMMMMMMMMMMMMMMMMMMMMMMMMmds+.        OS: Mint 18 sarah
 MMm----::-://////////////oymNMd+`     Kernel: x86_64 Linux 4.4.0-pf8-pf
 MMd      /++                -sNMd:    Uptime: 3h 0m
 MMNso/`  dMM    `.::-. .-::.` .hMN:   Packages: 3175
 ddddMMh  dMM   :hNMNMNhNMNMNh: `NMm   Shell: bash 4.3.42
     NMm  dMM  .NMN/-+MMM+-/NMN` dMM   Resolution: 1280x1024
     NMm  dMM  -MMm  `MMM   dMM. dMM   DE: Cinnamon 3.0.7
     NMm  dMM  -MMm  `MMM   dMM. dMM   WM: Muffin
     NMm  dMM  .mmd  `mmm   yMM. dMM   WM Theme: Minty (Mint-Y)
     NMm  dMM`  ..`   ...   ydm. dMM   GTK Theme: Mint-Y [GTK2/3]
     hMM- +MMd/-------...-:sdds  dMM   Icon Theme: Mint-Y
     -NMm- :hNMNNNmdddddddddy/`  dMM   Font: Noto Sans 9
      -dMNs-``-::::-------.``    dMM   CPU: Intel Core i5-3470 CPU @ 3.6GHz
       `/dMNmy+/:-------------:/yMMM   GPU: GeForce GTX 650 Ti
          ./ydNMMMMMMMMMMMMMMMMMMMMM   RAM: 2335MiB / 7898MiB
             \.MMMMMMMMMMMMMMMMMMM    

```

![Screenshot](https://i.imgur.com/i62bGID.png)

**Comment by In-line** [comment] 2017-03-22 15:20
One more time after jihad bomb explosion
![](https://i.imgur.com/VTsPn9a.png)

**Comment by robotboy655** [comment] 2017-03-22 15:30
Posting pictures of error messages is not useful. Unless you can reproduce the error on demand or send crash logs at the very least, nothing can be done.

**Comment by In-line** [comment] 2017-03-22 15:40
@robotboy655 Where are they located?
