### ISSUE TITLE
Scrolling still broken in MacOS

### ISSUE THREAD

**Issue by rudeustudeus** [Facepunch/garrysmod-issues#3443] opened 2018-04-19 11:27 UTC
Using your mousewheel on garry's mod on MacOS is next to impossible. You can't reliably scroll through anything derma/gwen, you can't scroll a prop in or out and you can hardly even switch weapons.

This has been broken for years now, if you lack the skills to maintain this unplayable mess then stop serving it on steam.

**Comment by robotboy655** [comment] 2018-04-19 11:30
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/2772

**Closed by robotboy655** 2018-04-19 11:30 UTC
