### ISSUE TITLE
Hydraulics, Motors, Winches can be controlled by other players in vanilla Sandbox servers

### ISSUE THREAD

**Issue by pauliewalnut** [Facepunch/garrysmod-issues#4994] opened 2021-06-27 05:13 UTC
Hello,

I have witnessed a bug that I'm not sure anyone else has ever reported, and I feel that here would be the best place to report it. When I spawn a duplication with Hydraulic, Motor, or Winch constraints, or simply create said constraints in a basic contraption (binded to a specific key), **other players** have the ability to control my contraption by pressing the same key I set to move the constraints. For instance, if I set a winch to move up with the up arrow key and down with the down arrow key, another player has the ability to move my winch by pressing the up and down arrow keys (even though they don't have special privileges to control my contraption). This effectively makes contraptions with said constraints to be almost completely uncontrollable (unless the other players don't know what button to press). I should stress that I have witnessed this issue in completely bare-bone Sandbox servers with no addons, and that this issue does **not** happen with wheels, thrusters, and hoverballs. 

Probably the best way to verify the issue at hand would be to have two players join a completely bare-bone Sandbox server (i.e. NFO Servers), player 1 spawns a duplication with Hydraulic, Motor, or Winch constraints, and player 2 tries to control it with the key assignments. If this issue could be addressed (or resolved) in the coming updates to this game, that would be greatly appreciated. Thank you for your time.

**Comment by robotboy655** [comment] 2021-06-27 18:14
Last time I tried to reproduce this I couldn't.

**Comment by pauliewalnut** [comment] 2021-06-28 05:11
Good evening; thank you for the reply. As of today the problem is still noticeable in vanilla sandbox servers; judging by user feedback on my duplications (including a tank with a winch-powered turret), if anyone in the same server presses the up and down arrow keys when the tank is deployed by a given user, it traverses the turret upside down without the user's permission. The same issue occurs with my plane dupe's hydraulically-operated landing gear and parachute. I am surprised that this bug can't be replicated, as I nearly always have the issue in sandbox servers with >2 other players. Especially as a player who wants to make useable, completely vanilla dupes, these issues are particularly game-breaking in this regard. If there is anything the development team can do to address and fix the issue, it would be dearly appreciated.

Dupes with this issue: 
https://steamcommunity.com/sharedfiles/filedetails/?id=2097522274
https://steamcommunity.com/sharedfiles/filedetails/?id=2466187078

**Comment by robotboy655** [comment] 2021-06-28 10:45
Ah, thanks for the dupes, I didn't realize it's only dupes, and only those that are loaded from a file.

Should be fixed on 'dev' beta and in a future update for all players.

**Closed by robotboy655** 2021-06-28 10:45 UTC
Labels: Bug
