### ISSUE TITLE
x86_64 crashes when trying to grab .dylib files it thinks "does not exist", MacOS Monterey 12.6

### ISSUE THREAD

**Issue by bedrockperson** [Facepunch/garrysmod-issues#5340] opened 2022-10-12 22:54 UTC
Gmod keeps crashing on the blue loading screen because it thinks that .dylib files that are in the directory just "don't exist". 

I've been using -condebug to get a console log of the crashes, [seen here](https://pastebin.com/p5hBtxMv). The .dylib files its saying don't exist are all there, exactly where the console is saying they don't exist. This shit is getting very stupidly out of hand.

Steps to reproduce:
have mac
open gmod
suffer for wanting simple things

**Comment by robotboy655** [comment] 2022-10-13 11:57
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5001

**Closed by robotboy655** 2022-10-13 11:57 UTC
Labels: Bug, Duplicate, Platform: MacOS, Crash

**Comment by bedrockperson** [comment] 2022-10-14 22:18
OK so... what the hell is being done to fix it? Like the bug has apparently been out there for more than 16 months.
