### ISSUE TITLE
C++ weapons invisibility issue

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3985] opened 2019-09-06 19:44 UTC
### Details
When using the command to switch to the grav gun and lastinv at the same time, the next equipped C++ weapon is invisible until you switch it away.

### Steps to reproduce
Run lastinv and then use the command to switch for Grav gun (I don't know the actual command, I bound it to MOUSE5).
=> Invisible weapon

https://www.dropbox.com/s/n9jy3l39yhve9fo/asiRX1S3k3.mp4?dl=0

**Comment by robotboy655** [comment] 2019-09-06 21:21
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/2668

**Closed by robotboy655** 2019-09-06 21:21 UTC
