### ISSUE TITLE
Prop Hunt Disappeared 

### ISSUE THREAD

**Issue by Karlarei2003** [Facepunch/garrysmod-issues#1915] opened 2015-03-22 00:33 UTC
So, I go to the bottom right and click on "Sandbox" to change it to "Prop Hunt" but it is gone.  The only things there now are "Sandbox" and "TTT".

-The game is updated.
-I've uninstalled and reinstalled Prop Hunt

Thanks in advance.

**Comment by robotboy655** [comment] 2015-03-22 00:34
Pretty sure it is duplicate of #1904

**Closed by robotboy655** 2015-03-22 00:34 UTC
