### ISSUE TITLE
VEHICLE:SetVehicleParams() is acting inconsistent and breaking vehicle handling

### ISSUE THREAD

**Issue by G-Force007** [Facepunch/garrysmod-issues#4812] opened 2021-01-29 07:59 UTC
### Details
VEHICLE:SetVehicleParams() no longer acts as it once used to. If you perform VEHICLE:SetVehicleParams(VEHICLE:GetVehicleParams()) or VEHICLE:SetVehicleParams({}), it will cause handling issues, aka slow turning circles and inconsistent behaviour.

VERSION = 210122
Windows Server 64bit
SRCDS x64 version

### Steps to reproduce
Spawn a vehicle (preferably something like TDM cars not just a regular jeep) and test out turning circle while moving forward. Then apply VEHICLE:SetVehicleParams(VEHICLE:GetVehicleParams()) or VEHICLE:SetVehicleParams({}) on said vehicle and the handling will now be altered from default behaviour.

**Comment by bigdogmat** [comment] 2021-01-29 12:41
Duplicate? #2625

**Comment by G-Force007** [comment] 2021-01-29 13:05
> 
> 
> Duplicate? #2625

That issue is relating to configuration reverting to default. This issue is relating to differences between default without specifying anything. This was not an issue a few months ago and is from a recent change.

**Comment by robotboy655** [comment] 2021-01-29 15:41
> This was not an issue a few months ago and is from a recent change.

There were no changes to that function since Feb 2020. It simply cannot be a "recent change".

I can see the speed of some vehicles does get slower with `VEHICLE:SetVehicleParams({})`, which would in turn change its turning angle since it's directly dependent on the vehicle's speed.

I also found a pretty big oopsie with the "steering" part of the function, where it tries to grab the data from "engine" table and not the correct "steering" one.

**Comment by robotboy655** [comment] 2021-01-29 15:52
As far as I can tell the issue is with vphysics yet again, specifically this shit:
```
// compute torque normalization factor
	m_torqueScale = 1;
	// Clear accumulation.
	float totalTorqueDistribution = 0.0f;
	for ( int i = 0; i < m_vehicleData.axleCount; i++ )
	{
		totalTorqueDistribution += m_vehicleData.axles[i].torqueFactor;
	}

	if ( totalTorqueDistribution > 0 )
	{
		m_torqueScale /= totalTorqueDistribution;
	}
```
m_torqueScale is 1 by default, and only gets recalculated when reloading the vehicle script.

This behavior is actually consistent with `vehicle_flushscript`

**Comment by robotboy655** [comment] 2021-01-29 15:55
I could fix this and #2625 but existing scripts will break.

**Comment by G-Force007** [comment] 2021-01-29 16:08
> 
> 
> I could fix this and #2625 but existing scripts will break.

The issue with #2625 seems to relate to a different issue that has the most likelihood of breaking existing scripts, however the issue that I have noted here completely breaks the functionality of the intended behaviour of the function itself. E.g. I can now no longer modify the maximum speed/RPM/HP of a vehicle as it breaks the handling. A solution to issue #2625 would be to add an additional function to set a specific value but I digress.

**Comment by robotboy655** [comment] 2021-01-29 16:24
The fix for this will also fix that issue, there's no way around it. Or you can just settle for manually editing torqueFactor on all the axles to sum to 1.

**Comment by G-Force007** [comment] 2021-01-29 16:28
How do you feel about fixing this one? Ultimately it is your decision to proceed further with this one @robotboy655

**Comment by robotboy655** [comment] 2021-01-29 17:25
You are really not grasping what I am saying, but I guess I will just fix everything to how it was supposed to be in the first place and force people to update their shit. It should only affect the people who take

**Closed by robotboy655** 2021-01-29 17:25 UTC

**Comment by G-Force007** [comment] 2021-01-29 17:33
Thank you @robotboy655

**Comment by Heavybob** [comment] 2021-01-30 00:08
Thanks @robotboy655
