### ISSUE TITLE
Critical bug Disappears weapons

### ISSUE THREAD

**Issue by godred2** [Facepunch/garrysmod-issues#2941] opened 2016-11-27 17:05 UTC
This bug appears almost in all modes
In this mode, the bug appears often
When it comes to the other player with a random player missing texture weapons
But when a player says "record" In the console, then weapons appear textures
Watch the video
https://www.youtube.com/watch?v=HL4ruI4sIdI&feature=youtu.be

**Comment by Jake3231** [comment] 2016-11-27 17:15
Does this only happen with specific weapons?  I would assume that it's just an addon issue.

**Comment by godred2** [comment] 2016-11-27 17:17
This happens with all weapons
It occurs in various modes
 Discussion
http://steamcommunity.com/workshop/filedetails/discussion/734532818/360670708789252336/

**Comment by Jake3231** [comment] 2016-11-27 17:20
Interesting... Just to confirm, this even occurs with the built in HL2 weapons, even in the sandbox gamemode?  The linked discussion seems to focus on the Homicide game mode, but people are saying that it applies to sandbox as well...

**Comment by godred2** [comment] 2016-11-27 17:29
I personally have not seen this bug in the sandbox
But this bug had seen my friends

**Comment by kem008** [comment] 2016-11-27 17:59
I had the same problem. But somehow for me disappeared after I disabled instant spawn back from death.

**Comment by LuaTenshi** [comment] 2016-11-28 08:47
This bug seems to actually happen due to big lag spikes. Not sure how we could recreate it in a controlled environment. Can any one provide some more details on how to replicate this?

**Comment by godred2** [comment] 2016-11-28 09:18
kem008, How do you disabled back from death?

**Comment by kem008** [comment] 2016-11-28 18:59
I mean. When I died I added Spawn() to the PlayerDeath function. Not always happened. Many people reported me that their weapons disappeared when someone died.

**Comment by godred2** [comment] 2016-11-29 09:12
Okay.Thx you

**Comment by robotboy655** [comment] 2019-08-13 16:13
Fairly certain this is a duplicate of https://github.com/Facepunch/garrysmod-issues/issues/2668

**Closed by robotboy655** 2019-08-13 16:13 UTC
Labels: invalid
