### ISSUE TITLE
Two player animations for flinching are tied to nonexistent activities?

### ISSUE THREAD

**Issue by Vuthakral** [Facepunch/garrysmod-issues#4862] opened 2021-03-08 22:04 UTC
### Details
The following two sequences for the base gmod player animations, `flinch_shoulder_l` & `flinch_shoulder_r` are assigned to the nonexistent activities `ACT_FLINCH_SHOULDER_LEFT` & `ACT_FLINCH_SHOULDER_RIGHT` respectively. 

Conversely, there are two regionally similar activities to this naming convention that go unused in the base gmod player animations, possibly just an oversight or an update that changed this? They are `ACT_FLINCH_LEFTARM` & `ACT_FLINCH_RIGHTARM` respectively.

The end result is that left/right arm flinch animations cannot be called within lua without using a workaround, limiting their usage.

### Steps to reproduce
Check the source data for the male/female player animations. It can be seen the sequences are tied to these nonexistent activities, and that the similar two go unused in either animation model.

Attempting to call for either activities normally, unsurprisingly, does nothing outside of singleplayer due to them not registering.

### Workaround for anyone who happens to find this in Google
`ply:GetSequenceActivity(ply:LookupSequence("flinch_shoulder_l"))`

**Comment by robotboy655** [comment] 2021-03-08 23:36
Duplicate of /related to https://github.com/Facepunch/garrysmod-issues/issues/3075

**Closed** 2021-04-08 09:29 UTC
Labels: Duplicate
