### ISSUE TITLE
Point_viewcontrol is not working in multiplayers

### ISSUE THREAD

**Issue by kem008** [Facepunch/garrysmod-issues#2397] opened 2016-01-18 17:31 UTC
``` point_viewcontrol ``` If more players in the game point_viewcontrol only work for one player other players wont get the view from ``` point_viewcontrol ```

**Comment by robotboy655** [comment] 2016-01-18 17:39
Duplicate of #1200

**Closed by robotboy655** 2016-01-18 17:39 UTC
