### ISSUE TITLE
file.IsDir does not produce expected output for directories mounted by AddCSLuaFile

### ISSUE THREAD

**Issue by WilliamVenner** [Facepunch/garrysmod-issues#3592] opened 2018-09-05 20:22 UTC
### Details
When using `file.IsDir` with the `LUA` path, the function does not return true for directories that were created by `AddCSLuaFile`. This is contrary to the results that `file.Find` and `file.Exists` return.

`file.IsDir` does appear to work for directories created by `AddCSLuaFile` which were added by the gamemode, however, as shown in steps to reproduce.

![](https://i.imgur.com/8shWfFw.png)

### Steps to reproduce
The following code produces the issue described above when running DarkRP and ULX.

```lua
local files, directories = file.Find("*", "LUA")
PrintTable(directories) -- show all directories found in mounted lua/
-- this will show us that the "darkrp" directory is present
-- this will also show us that the "ulx" directory is present

print(file.IsDir("darkrp", "LUA"))
-- returns true

print(file.IsDir("ulx", "LUA"))
-- returns false

print(file.Exists("ulx/cl_init.lua", "LUA"))
-- returns true
```

**Comment by robotboy655** [comment] 2018-09-06 09:58
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/1038

**Closed by robotboy655** 2018-09-06 09:58 UTC
