### ISSUE TITLE
Using SetClip1 on a weapon while time scale is below 1 causes the players movement to desync for a frame or two

### ISSUE THREAD

**Issue by MagentaIris** [Facepunch/garrysmod-issues#4601] opened 2020-07-26 16:40 UTC
While moving and using SetClip1 on a weapon, the players movement freezes in place for a very very short period of time.

Only seems to happen if timescale is below 1 though, I'm not sure why.

Working on a work around but i wanted to report this just in case there's something that was overlooked.

**Comment by Kefta** [comment] 2020-07-26 16:59
Are you setting Clip1 shared?

**Comment by robotboy655** [comment] 2020-07-26 17:39
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/3572 (Same cause)

**Closed by robotboy655** 2020-07-26 17:39 UTC

**Comment by MagentaIris** [comment] 2020-07-26 20:57
> Are you setting Clip1 shared?

No, I was setting it purely serverside otherwise the clients check on the next 2-10 frames would be inconsistant with the client check i do, Thus it needed to be serverside only.

Apologies if this re-opened the issue, i've finish my work around so it's no problem anymore but it would be neat if in the future this didn't happen.

**Comment by Kefta** [comment] 2020-07-27 05:28
You should set it shared in a predicted hook, otherwise, it will cause a prediction error and result in movement stutter.

**Comment by MagentaIris** [comment] 2020-07-27 11:58
> You should set it shared in a predicted hook, otherwise, it will cause a prediction error and result in movement stutter.

Yeah but then the clientside check will be inconsistant and cause the state to be wrong in both realms due to the slight delay, It doesnt update the client frame perfectly even with it in a shared instance so i had to go and make my own library for it instead.

I don't have the problem anymore due to a work around, I just wanted to let you know that it happens.

Not sure why changing a Numbered variable on the client via a server instanced function that automatically updates the clients side via networking would cause the players movement prediction to hitch, perhaps i'm overthinking it.

Sorry for the bother.
