### ISSUE TITLE
_p:HasGodMode( ) result is not synced between client and server.

### ISSUE THREAD

**Issue by Acecool** [Facepunch/garrysmod-issues#2038] opened 2015-05-24 02:58 UTC
http://wiki.garrysmod.com/page/Player/HasGodMode

Test... RCON:

``` lua
lua_run Entity( 1 ):GodEnable( )
> Entity( 1 ):GodEnable( )...
lua_run print( Entity( 1 ):HasGodMode( ) )
> print( Entity( 1 ):HasGodMode( ) )...
true
lua_run BroadcastLua( "print( Entity( 1 ):HasGodMode( ) )" )
> BroadcastLua( "print( Entity( 1 ):HasGodMode( ) )" )...
lua_run Entity( 1 ):GodDisable( )
> Entity( 1 ):GodDisable( )...
lua_run BroadcastLua( "print( Entity( 1 ):HasGodMode( ) )" )
> BroadcastLua( "print( Entity( 1 ):HasGodMode( ) )" )...
lua_run print( Entity( 1 ):HasGodMode( ) )
> print( Entity( 1 ):HasGodMode( ) )...
false
lua_run Entity( 1 ):GodEnable( )
> Entity( 1 ):GodEnable( )...
lua_run print( Entity( 1 ):HasGodMode( ) )
> print( Entity( 1 ):HasGodMode( ) )...
true
lua_run BroadcastLua( "print( Entity( 1 ):HasGodMode( ) )" )
> BroadcastLua( "print( Entity( 1 ):HasGodMode( ) )" )...
```

Clientside:

``` lua
false   
false   
false   
```

But it should read true, false, true... on the client if the function was properly in sync when using GodEnable / GodDisable...

Using latest dev-build both client and server. Using my dev-base which doesn't overwrite GodEnable / GodDisable or HasGodMode, but does overwrite NW/Networking vars so it can be output to a table; nothing shows up for god-mode for NW vars until I redirect GodEnable, GodDisable and HasGodMod..

**Comment by TheFreeman193** [comment] 2015-05-25 18:16
This is an issue with entity flags. As far as I can tell, no bitflags >1024 are sent to clients. *FL_GODMODE* is 32768. No idea if this is intentional or not, though.

**Comment by Acecool** [comment] 2015-05-27 20:12
Thanks for that +1! Also, seeing as HasGodMode is shared I'd say it isn't intentional...

**Comment by andreblue** [comment] 2016-07-23 05:22
Has there been any updates towards this? I have come across this still happening.

**Comment by RenTec** [comment] 2016-11-01 11:59
@andreblue Still an issue over here, not working on my client.

**Comment by CaptainPRICE** [comment] 2018-11-28 20:30
Hm. This were opened over 3 years, and the issue is still **not fixed**. (Version 2018.10.10.)
```lua
lua_run Entity(1):GodEnable()
> Entity(1):GodEnable()...

lua_run print(Entity(1):HasGodMode())
> print(Entity(1):HasGodMode())...
true

lua_run_cl print(Entity(1):HasGodMode())
false

lua_run_cl print(Entity(1):IsFlagSet(FL_GODMODE))
false
```

**Comment by Kefta** [comment] 2018-11-28 20:52
I think some internal flag restructuring might have to be done to fix this since the engine has a hardcoded limit/upper-bound for flags it will send over the network.

**Comment by CaptainPRICE** [comment] 2019-07-26 09:12
Ok. Just to summarize stuff here:
Player functions (i.e. `HasGodMode`) are defined in the following file:
https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/includes/extensions/player.lua
We can see GLua then calls into C functions (reconstruction):
```
void C_BaseEntity::AddFlags(int nFlagMask) { m_fFlags |= nFlagMask; }
void C_BaseEntity::RemoveFlags(int nFlagMask) { m_fFlags &= ~nFlagMask; }
bool C_BaseEntity::IsFlagSet(int nFlagMask) { return (m_fFlags & nFlagMask) != 0; }
```
[GLua reconstruction](https://gist.github.com/CaptainPRICE/6d74b463b7a125535e52bb8ff311eaf2).
Nothing special there.

-----

Alright. So, it seems there is a limit on the engine, how many bits are transmitted to client(s). Expanding on the topic (`m_fFlags` is part of the `DT_BasePlayer` datatable):
https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/player.cpp#L8007

I wonder.. what these does..
https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/public/const.h#L156-L157
https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/player.cpp#L7920-L7923

🤔 😺

Need more info? Observe the following results:
- Player with godmode in water (fully submerged):
(**serverside**) m_fFlags = 165121 (`FL_ONGROUND | FL_CLIENT | FL_INWATER | FL_GODMODE | FL_AIMTARGET`)
(**clientside**) m_fFlags = 1281 (`FL_ONGROUND | FL_CLIENT | FL_INWATER`)

- Bot with godmode in water (fully submerged):
(**serverside**) m_fFlags = 33537 (`FL_ONGROUND | FL_CLIENT | FL_FAKECLIENT | FL_GODMODE`)
(**clientside**) m_fFlags = 769 (`FL_ONGROUND | FL_CLIENT | FL_FAKECLIENT`)

- Bot, forced with all flags set:
(**clientside**) m_fFlags = 2023 (`FL_ONGROUND | FL_DUCKING | FL_ANIMDUCKING | FL_INRAIN | FL_FROZEN | FL_ATCONTROLS | FL_CLIENT | FL_FAKECLIENT | FL_INWATER`)

From what I can tell, it seems very likely that `PLAYER_FLAG_BITS` is the key here.
Did anyone try increasing it from 11 to 16?

**Comment by Hadrien100** [comment] 2020-07-13 22:57
Can't Facepunch fix this? It has been 5 years...

**Comment by RyanTheTechMan** [comment] 2020-08-24 23:58
@Hadrien100 I posted a [temporary fix on the Garry's Mod Wiki](https://wiki.facepunch.com/gmod/Player:HasGodMode) a few months ago. Scroll to the bottom of the page :)

**Comment by Kefta** [comment] 2020-08-25 02:32
@RyanTheTechMan Do not use NWBools for unpredicted data, use net messages.

**Comment by Hadrien100** [comment] 2020-08-30 21:06
> @Hadrien100 I posted a [temporary fix on the Garry's Mod Wiki](https://wiki.facepunch.com/gmod/Player:HasGodMode) a few months ago. Scroll to the bottom of the page :)

Alright but your "fix" needs to be applied both on the server and client, and I want to access this only by using clientside scripting.

**Comment by Kefta** [comment] 2020-08-31 00:11
Then it's not possible right now since it's not networked to the client at all.

**Comment by Lexa013** [comment] 2020-12-28 17:18
It's not even fixed yet ?

**Comment by Hadrien100** [comment] 2020-12-28 19:49
It basically won't get fixed, we should mark this as server side only.

**Comment by robotboy655** [comment] 2023-06-27 19:26
Should be fixed.

**Closed by robotboy655** 2023-06-27 19:26 UTC
Labels: Complexity: Low, Intentional, Net compat
