### ISSUE TITLE
r_flushlod crashs the game whenever a material of a precached model has changed

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#4401] opened 2020-03-02 01:42 UTC
### Details
Whenever I r_flushlod after editing a vmt file for example or adding new materials that belong to a loaded model, the game crashes.
If this gets fixed, it could be used to clear model cache after disconnecting.

https://www.dropbox.com/sh/mi0v47clkelwlye/AAB1mDRHBIY3xFsqOFwj7esOa?dl=0

### Steps to reproduce
Change material of precached model.
Run the command

**Comment by bizzclaw** [comment] 2020-03-28 21:44
I always find that regardless of editing a model or material, if I look directly up at the sky (so I'm rendering as few models as possible) I rarely crash when using this command. Whenever I look down and around, the game freezes a bit as it reloads all of the other models, but rarely crashes unless I run the command while looking at a bunch of models.

It's always been inconsistent for me and I've only ever relied on it as "well, either this will work or I'll have to restart my game anyways" sort of thing.

**Comment by thegrb93** [comment] 2020-03-28 21:50
There's lots of cases it will crash I've found. I don't think its intended to be used if you aren't a dev. This isn't a garrysmod-issue anyway, this is a valve issue.

**Comment by mcNuggets1** [comment] 2020-03-28 22:11
> 
> 
> There's lots of cases it will crash I've found. I don't think its intended to be used if you aren't a dev. This isn't a garrysmod-issue anyway, this is a valve issue.

I'm a dev and actually use this.
Also theres an issue with garrys mod not clearing model/material cache or whatever cache after dcing, corrupting textures on reload, if the same model is loaded again.

**Comment by thegrb93** [comment] 2020-03-28 23:02
I agree that the caches not clearing on disconnect is very problematic especially for gmod. I don't think hot-loading changes with r_flushlod will ever be feasible though.

**Comment by Kefta** [comment] 2020-03-28 23:10
Fixing the crash should be done regardless.

**Comment by thegrb93** [comment] 2020-03-28 23:16
Just don't remove the command, it is very useful if you know what not to do.

**Comment by robotboy655** [comment] 2020-06-04 18:13
The link is 404 and editing material of let's say the default crate does not cause any crashes for me.

**Comment by mcNuggets1** [comment] 2020-06-04 18:16
Can't get it to crash anymore.

**Comment by robotboy655** [comment] 2020-06-04 18:20
Alright, going to close this then for now.

If it happens again, just post here with a dump/way to reproduce or open a new issue.

**Closed by robotboy655** 2020-06-04 18:20 UTC
Labels: cannot confirm/reproduce, crash
