### ISSUE TITLE
Garry's Mod crashing when touching a hint brush / soundscape for some reason.

### ISSUE THREAD

**Issue by benjamen50** [Facepunch/garrysmod-issues#2195] opened 2015-08-15 08:35 UTC
Reproduced bug with following steps:

Walking outside of my house in a map I created causes the game to crash (Possibly due to hint brush rendering issue / soundscape switching.) This issue wasn't there before the latest Garry's Mod update.

Minidump here:
https://www.dropbox.com/s/ytnciwft812o5wa/hl2_150812_crash_2015_8_15T8_26_3C0.mdmp?dl=0

**Comment by robotboy655** [comment] 2015-08-15 08:38
Is that map made with TF2 hammer?

**Comment by benjamen50** [comment] 2015-08-15 08:43
No, I compiled and made the map using Valve Hammer with a Half-Life Episode 2 configuration.
CS:S + HL2 props.

**Comment by robotboy655** [comment] 2015-08-15 08:44
Hammer from what game did you use? HL2? Can you attach the map itself? Did you add any content into the map? ( PAKRAT, etc )

**Comment by benjamen50** [comment] 2015-08-15 08:47
I'm using the Valve Hammer from: Source SDK Base 2013 Singleplayer
Sure, here is the Map BSP:  https://www.dropbox.com/s/zwgwbr8nwq2z7sb/zs_dl_genericwarehouse_v2.bsp?dl=0

Yes, Pakratted soundscape sound files and soundscape manifest txt. All configured correctly and working as it should be.

**Comment by robotboy655** [comment] 2015-08-15 19:54
Ok, the problem is with the sound loading from the .bsp, I will fix it in the next update.

**Comment by robotboy655** [comment] 2015-08-17 12:50
Will be fixed in the next version of the game.

**Closed by robotboy655** 2015-08-17 12:50 UTC
Labels: bug
