### ISSUE TITLE
ENT:GetTouchTrace sometimes cause crash when called in NEXTBOT:OnContact

### ISSUE THREAD

**Issue by ShadowBonnieRUS** [Facepunch/garrysmod-issues#4836] opened 2021-02-14 08:20 UTC
### Details
I can't say what can cause it, its random for me. I call GetTouchTrace in OnContact because when something like weapon parented to bot, OnContact called even when i don't touch bot, just stay close. And its called even for bot itself. GetTouchTrace helps me skip that.

Piece of code with GetTouchTrace:
```Lua
function ENT:OnContact(ent)
	print(ent)

	local trace = self:GetTouchTrace() -- crash here
	
	if trace.Hit then
		self:OnTouch(ent,trace)
	end
end
```

And crash minidump:
[hl2_210205_crash_2021_2_14T8_7_18C0.txt](https://github.com/Facepunch/garrysmod-issues/files/5977184/hl2_210205_crash_2021_2_14T8_7_18C0.txt)

**Comment by robotboy655** [comment] 2021-02-16 19:03
I have pushed a few changes to Dev beta regarding this crash, would be nice if you'd jump onto Dev and let me know if it still happens. If it does, please attach a new dump or two.

**Comment by ShadowBonnieRUS** [comment] 2021-02-17 14:56
Still crash on dev.


[hl2_210216_crash_2021_2_17T14_56_7C0.txt](https://github.com/Facepunch/garrysmod-issues/files/5996493/hl2_210216_crash_2021_2_17T14_56_7C0.txt)

**Comment by robotboy655** [comment] 2021-02-17 15:48
How often does it happen? (Say within an hour?)
Are you able to send me the file(s) & instructions needed to reproduce this? You can send them to my email.

I have updated the dev branch again, but the dumps are not making much sense on this crash.
Looks like maybe an entity is getting deleted somewhere it shouldn't be but I can't say for sure.

**Comment by ShadowBonnieRUS** [comment] 2021-02-17 16:21
I just using spawn platforms that spawns combine soldiers and my bots and they shoot each other. But much often it happens to me when i trying complete hl2 d3_c17_05 map with group of bots. I not often can reach the end of map without crash.

Maybe they collide with each other. But i see that code:
```C++
void NextBotCombatCharacter::Touch( CBaseEntity *other )
{
	if ( ShouldTouch( other ) )
	{
		// propagate touch into NextBot event responders
		trace_t result;
		result = GetTouchTrace();

		// OnContact refers to *physical* contact, not triggers or other non-physical entities
		if ( result.DidHit() || other->MyCombatCharacterPointer() != NULL )
		{
			OnContact( other, &result );
		}
	}
	
	BaseClass::Touch( other );
}
```
Here OnContact called because of result of GetTouchTrace(), so it already called before OnContact and i trying call it again in OnContact (if lua hook called from here, and if this code correct for gmod version). The point is first c++ GetTouchTrace() always called to call OnContact and there no crash.

**Comment by robotboy655** [comment] 2024-03-26 00:40
Hey, I am not sure if this is still a bug that you are experiencing or not.

I have made some more changes based on what I think may be the issue based on your last crash dump, but I obviously cannot be sure since there's no way for me to reproduce the issue.

I am going to close this report as I am not sure you even care after all this time, but in case you do and the issue still remains, let me know.

**Closed by robotboy655** 2024-03-26 00:40 UTC
Labels: Crash
