### ISSUE TITLE
No crosshair drawn when spectating in OBS_MODE_IN_EYE or OBS_MODE_ROAMING while being dead

### ISSUE THREAD

**Issue by Lightoner** [Facepunch/garrysmod-issues#5817] opened 2024-04-01 19:05 UTC
The default behaviour on how the crosshair should be drawn in the source engine is that even if the local player is dead, the crosshair should be drawn when the observer mode of the local player is OBS_MODE_IN_EYE or OBS_MODE_ROAMING (with cl_observercrosshair 1). But it's not the case in Garry's Mod, no crosshair is drawn.

https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/client/hud_crosshair.cpp#L130

In addition, the condition seems to be true and not modified in Garry's Mod because after that HUDShouldDraw hook is called with CHudCrosshair and in sandbox (or base) gamemode nothing prevent to draw the crosshair in the HUDShouldDraw implementation with no addons. But in result no crosshair is drawn. So it seems a bug to me and something else is conflicting with this behaviour. 

If ever it's the behaviour wanted by Garry's Mod, I think that the default source engine feature of seeing the crosshair while spectating is a great feature and Garry's Mod should have it.

**Comment by robotboy655** [comment] 2024-04-08 08:32
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/3936

**Closed by robotboy655** 2024-04-08 08:32 UTC
