### ISSUE TITLE
OTFs fonts aren't applied after sent

### ISSUE THREAD

**Issue by gonzalologorg** [Facepunch/garrysmod-issues#3262] opened 2017-08-07 18:03 UTC
_Correct behavior:_

`resource.AddFile("resource/fonts/BebasNeue.otf")`

**Above code SHOULD send the font and then apply it, then game would load it correctly and show in game**

_What happens?_

Nothing, game won't apply the font (Only if you have it installed via font viewer)
Although file is downloaded

![image](https://user-images.githubusercontent.com/7375225/29039273-ffb67968-7b80-11e7-9384-ffdc139e6c61.png)

###Workaround

`resource.AddFile("resource/fonts/bebas.ttf")`

Although sending a ttf file, it works, but some licenses doesn't allow you to edit the font or make those changes, it's otf even allowed in gmod? It worked in my client but not for new users, that's why i've decided to distribuite ttf fonts than otf

**Troublemaker font**
[bebas.zip](https://github.com/Facepunch/garrysmod-issues/files/1205688/bebas.zip)

**Comment by robotboy655** [comment] 2017-08-07 18:11
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/2009

**Closed by robotboy655** 2017-08-07 18:11 UTC
