### ISSUE TITLE
Particles from Left 4 Dead branch and newer engines don't work correctly

### ISSUE THREAD

**Issue by siobhan-saoirse** [Facepunch/garrysmod-issues#6055] opened 2024-11-04 20:40 UTC
### Details

While testing some particles from Left 4 Dead 2 for October 2024's update, The particles fail to load, and they create an error message in the developer console.
```
Unable to read particle definition particles/error.pcf! UtlBuffer is the wrong type!
Unable to read particle definition particles/blood_impact.pcf! UtlBuffer is the wrong type!
Unable to read particle definition particles/fire_01.pcf! UtlBuffer is the wrong type!
Unable to read particle definition particles/burning_fx.pcf! UtlBuffer is the wrong type!
```

### Steps to reproduce
1. Extract .pcf files from Left 4 Dead or newer games
2. Put them the 'particles' inside an addon folder that you just created
3. Launch the game and check console for errors
4. The errors should now appear, and the particles will refuse to load until you delete the files.

**Comment by robotboy655** [comment] 2024-11-05 01:02
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1757

**Closed by robotboy655** 2024-11-05 01:02 UTC
