### ISSUE TITLE
Server downloaded/mounted GMA's don't mount properly on map changes or rejoins.

### ISSUE THREAD

**Issue by Brassx** [Facepunch/garrysmod-issues#4950] opened 2021-05-18 21:14 UTC
A bunch of my players were reporting models/textures randomly breaking ever since the change that unmounts server-downloaded addons upon map shut down. I download, cache, then mount gma's in-game for my clients. None are bigger than ~20mb.
### Issue
Basically, if you have a gma in the data folder then mount it via game.MountGMA, and the map changes or you type retry in console, it will cause some or all of the mounted content to either be pink and black, or be completely invisible, once they load back in. I have no idea if the same issue occurs with steamworks.DownloadUGC but I assume it does.

### Steps to reproduce
Add a .gma file to your data folder, mount it via game.MountGMA. Disconnect, then rejoin and remount it. Textures will be pink and black for the models in that gma, sometimes the models will just be invisible completely with no error messages for them.

Happens on dev branch and x86 - 64 currently.

**It is also worth noting that using mat_reloadmaterial "models/*" fixes the missing materials.** 

First join (items in first 2 inventory slots are mounted via a gma in the data folder):
![image](https://user-images.githubusercontent.com/6100996/118723842-73fad680-b808-11eb-9244-980419a1d24a.png)

Disconnect:
![image](https://user-images.githubusercontent.com/6100996/118723904-883ed380-b808-11eb-89fb-69f456bb012a.png)

Second join  (items in first 2 inventory slots are mounted via a gma in the data folder):
![image](https://user-images.githubusercontent.com/6100996/118724200-e23f9900-b808-11eb-89fe-f387f22b1694.png)

**Comment by robotboy655** [comment] 2021-05-19 08:41
> Add a .gma file to your data folder, mount it via game.MountGMA. Disconnect, then rejoin. Textures will be pink and black for the models in that gma, sometimes the models will just be invisible completely with no error messages for them.

This is basically expected behavior though If you do not remount the .gma, wouldn't you agree?

**Comment by Brassx** [comment] 2021-05-19 08:52
> 
> 
> > Add a .gma file to your data folder, mount it via game.MountGMA. Disconnect, then rejoin. Textures will be pink and black for the models in that gma, sometimes the models will just be invisible completely with no error messages for them.
> 
> This is basically expected behavior though If you do not remount the .gma, wouldn't you agree?

Sorry for being unclear, I remount the gma from cache upon join every single time.

**Comment by robotboy655** [comment] 2021-05-19 16:23
Should be fixed on Dev. Let me know if there are any problems. Will commit to x86-64 tomorrow.

**Closed by robotboy655** 2021-05-19 16:23 UTC

**Comment by TheLight91** [comment] 2021-05-19 18:11
I have the same problem, on a different TTT community that uses the same system.

I'm on dev now, it this caused by the fix?

About to remove bad mats
	Removing materials/trails/laser_rendermode_0
	Removing materials/trails/laser_rendermode_1

Does the fix remove bad mats and force you to reload them or is it a workaround coded by the server owner? Because it causes the game to freeze for a few seconds.

**Comment by robotboy655** [comment] 2021-05-19 20:19
Oh that wasn't supposed to make it in, it will be removed.

**Comment by TheLight91** [comment] 2021-05-20 00:02
I am gonna properly test the fix soon. Right now the server I play on, I think is forcing every user to reload all the materials once you join or change maps, fixing the problem but causing the whole game to freeze.

**Comment by Brassx** [comment] 2021-05-20 00:12
Fixed on dev branch for me. Can't see any issues other than the debug messages listed above.

**Comment by TheLight91** [comment] 2021-05-20 00:19
> Fixed on dev branch for me. Can't see any issues other than the debug messages listed above.

So you don't have any weird freezing?

**Comment by Brassx** [comment] 2021-05-20 00:28
> 
> 
> > Fixed on dev branch for me. Can't see any issues other than the debug messages listed above.
> 
> So you don't have any weird freezing?

None. If the server you're playing on is reloading materials every join, that would cause the freezing. They should be able to stop doing that once this is pushed to the x86-64 build.
