### ISSUE TITLE
Alyx doesn't enter the Jalopy

### ISSUE THREAD

**Issue by daunknownman2010** [Facepunch/garrysmod-issues#1518] opened 2014-09-26 15:11 UTC
It seems that the input to make Alyx enter the vehicle doesn't exist or it simply doesn't work. This makes Alyx just stand and do nothing.

![2014-09-26_00001](https://cloud.githubusercontent.com/assets/5220286/4422694/89ced5f4-458e-11e4-9579-78f7ce38a221.jpg)

**Comment by robotboy655** [comment] 2015-11-01 18:54
This is technically fixed in Dev, but the problem is that if you do not use the EP2 Alyx model, she still will not be able to enter the vehicle.

**Closed by robotboy655** 2015-11-01 18:54 UTC
Labels: bug

**Comment by IsuckAtcomputering** [comment] 2023-08-06 22:43
how do i change it to the ep 2 model?

**Comment by FlorianLeChat** [comment] 2023-08-07 05:54
Its original model is `models/alyx.mdl`, but Episode 2 uses `models/alyx_ep2.mdl` after the attack, which I assume is the one used to get it into the Jalopy.

**Comment by ExtReMLapin** [comment] 2023-08-07 07:55
She has no driving license bro

**Comment by robotboy655** [comment] 2023-08-07 12:38
Get a fix from workshop. The culprit is `models\alyx_animations.mdl` and similar files.
