### ISSUE TITLE
Crash when superphyscannon punts an NPC without a ragdoll physics but have an ACT_DIERAGDOLL 

### ISSUE THREAD

**Issue by BREEDNKMs** [Facepunch/garrysmod-issues#4934] opened 2021-05-02 12:17 UTC
Some SNPCs in the workshop use ACT_DIERAGDOLL as their reference pose, but do not actually have a physics or any ragdoll defined in their QC. CanBecomeRagdoll() also checks only for ACT_DIERAGDOLL and FL_TRANSRAGDOLL activity on the npcs that are being punted or pulled by super physcannon. 

Ways to reproduce: 

1-) Compile a basic model with ACT_DIERAGDOLL and without any $collisionjoints 
2-) Create the npc using "ent_create cycler_actor model model/compiledmodel.mdl" 
3-) physcannon_mega_enabled 1 
4-) Punt / pull the npc with super physcannon 

I guess the game crashes when physcannon tries to interact with an invalid physobj, as they assume the created ragdoll has a physobj after the ragdoll is created. Probably some extra checks whether the created ragdoll has a physics object before applying motion will solve the issue.

**Comment by robotboy655** [comment] 2021-05-03 10:21
Either provide a model this works with or the crash dump from the crash.

**Comment by BREEDNKMs** [comment] 2021-05-03 10:58
Here are two mdls I compiled from crab synth, one with a collisionjoints and one without it. 
Spawn both with 
"ent_create cycler_actor model models/crabsynth.mdl"
"ent_create cycler_actor model models/crabsynth_ragdoll.mdl"


[crabsynth mdls.zip](https://github.com/Facepunch/garrysmod-issues/files/6414402/crabsynth.mdls.zip)

Alternate link: https://cats.iku.edu.tr/access/content/user/1700002526/public_closed/132d3c001e5f80604c9f2f9e1d05213a/crabsynth%20mdls.zip

**Comment by robotboy655** [comment] 2021-05-03 12:53
Cannot reproduce a crash here. It just makes a console warning and nothing crashes.

```
] physcannon_mega_enabled 1
*** ERROR: C_ServerRagdoll::InitModel: models/crabsynth.mdl missing vcollide data ***
] ent_create cycler_actor model models/crabsynth_ragdoll.mdl
] ent_create cycler_actor model models/crabsynth.mdl
*** ERROR: C_ServerRagdoll::InitModel: models/crabsynth.mdl missing vcollide data ***
```

Tested on 'dev' beta, singleplayer and local mutiplayer.

**Comment by robotboy655** [comment] 2021-05-03 13:14
Ok, it works only with punting like the title says, not with pulling like steps to reproduce suggest.

**Comment by robotboy655** [comment] 2021-05-03 13:39
Should be fixed on Dev.

**Closed by robotboy655** 2021-05-03 13:39 UTC
Labels: Bug, Crash
