### ISSUE TITLE
HTTP() errors with "invalid url" when "10." is in the URL

### ISSUE THREAD

**Issue by mitterdoo** [Facepunch/garrysmod-issues#4565] opened 2020-06-30 00:37 UTC
# Details
When using `HTTP()`, if the string "10." is in the URL for the request, the failure callback is called, with the error "invalid url".

This occurs on the default branch, `chromium` branch, and `x86-64` branch on clientside. Happens on server, too, but only tested on 32-bit default branch dedicated server.

### Steps to reproduce
Run this code:
```lua
HTTP({
   failed=function(err) print("error", err) end,
   success=function(code) print("success", code) end,
   method="GET",
   url="http://www.google.com/10.txt"
})
```
It *should* print `success 404`, but instead does not even make the request, as it believes the URL is malformed, and prints `error invalid url`.

**Comment by viral32111** [comment] 2020-06-30 09:17
Duplicate of #4133.

**Closed** 2020-06-30 15:33 UTC
