### ISSUE TITLE
Kleiner using the wrong idle and walking animations

### ISSUE THREAD

**Issue by marigi64** [Facepunch/garrysmod-issues#5929] opened 2024-07-04 16:43 UTC
Minor issue but Kleiner is using the wrong animations for standing and walking. He uses standard citizen animations rather than his unique hunched-over ones.

Those incorrect animations are "idle_subtle" & "walk_all" (I'm not certain if there are any more than those)

"idle_subtle" in HL2
![k1](https://github.com/Facepunch/garrysmod-issues/assets/53112738/1be4992f-e372-4a31-aef5-520d7beb0483)

"idle_subtle" in GMOD
![k2](https://github.com/Facepunch/garrysmod-issues/assets/53112738/a335c090-1db8-4b5e-bd84-cf717d86fa68)

Tested on the x86-64 Branch

**Comment by robotboy655** [comment] 2024-07-04 17:10
This must be a result of merging episodic animations into the base model, episodic animations might be overwriting the HL2 ones.

**Comment by Mmmmm-Chicken-Leg** [comment] 2024-08-08 11:38
This problem is caused by the shared animations superseding the animations unique to the model. This is fixed by loading the shared animations AFTER the model's animations.

For Kleiner's case, currently the $includemodel statements are in this order:

$IncludeModel "humans/male_shared.mdl"
$IncludeModel "Kleiner_postures.mdl"
$IncludeModel "Kleiner_gestures.mdl"
$IncludeModel "Kleiner_animations.mdl"
$IncludeModel "Kleiner_post_ep1.mdl"
$IncludeModel "Kleiner_gest_ep1.mdl"
$IncludeModel "Kleiner_animat_ep1.mdl"
$IncludeModel "Kleiner_post_ep2.mdl"
$IncludeModel "Kleiner_gest_ep2.mdl"
$IncludeModel "Kleiner_animat_ep2.mdl"

To fix it, simply put the "humans/male_shared.mdl" animations at the end:

$IncludeModel "Kleiner_postures.mdl"
$IncludeModel "Kleiner_gestures.mdl"
$IncludeModel "Kleiner_animations.mdl"
$IncludeModel "Kleiner_post_ep1.mdl"
$IncludeModel "Kleiner_gest_ep1.mdl"
$IncludeModel "Kleiner_animat_ep1.mdl"
$IncludeModel "Kleiner_post_ep2.mdl"
$IncludeModel "Kleiner_gest_ep2.mdl"
$IncludeModel "Kleiner_animat_ep2.mdl"
$IncludeModel "humans/male_shared.mdl"

In regards to this topic, Alyx is also having this issue where her running animation with her gun out is replaced by the female_shared animations. You can see this when you load the map ep1_citadel_04, where you can see her flailing her arms about with her gun out.

The same fix can be applied here, from:

$IncludeModel "alyx_animations.mdl"
$IncludeModel "alyx_postures.mdl"
$IncludeModel "alyx_gestures.mdl"
$IncludeModel "humans/female_shared.mdl"
$IncludeModel "humans/female_ss.mdl"
$IncludeModel "alyx_animat_ep1.mdl"
$IncludeModel "alyx_post_ep1.mdl"
$IncludeModel "alyx_gest_ep1.mdl"
$IncludeModel "alyx_animat_ep2.mdl"
$IncludeModel "alyx_post_ep2.mdl"
$IncludeModel "alyx_gest_ep2.mdl"

To:

$IncludeModel "alyx_animations.mdl"
$IncludeModel "alyx_postures.mdl"
$IncludeModel "alyx_gestures.mdl"
$IncludeModel "alyx_animat_ep1.mdl"
$IncludeModel "alyx_post_ep1.mdl"
$IncludeModel "alyx_gest_ep1.mdl"
$IncludeModel "alyx_animat_ep2.mdl"
$IncludeModel "alyx_post_ep2.mdl"
$IncludeModel "alyx_gest_ep2.mdl"
$IncludeModel "humans/female_shared.mdl"
$IncludeModel "humans/female_ss.mdl"

**Comment by robotboy655** [comment] 2024-08-08 14:25
That fixed Kleiner, but not Alyx. I tried different permutation of loading EP1/EP2/Normal animation files first, and none of them resulted in fixing the running with gun animations.

**Closed by robotboy655** 2024-08-08 14:25 UTC
Labels: Content
