### ISSUE TITLE
Checkboxes do not appear in Linux

### ISSUE THREAD

**Issue by SharpOB** [Facepunch/garrysmod-issues#3126] opened 2017-04-09 15:45 UTC
### Details
On Linux, checkboxes do not show up at all.

### Steps to reproduce
Use a linux-based OS, such as Ubuntu 16.04 and attempt to mount a game or create a new server - checkboxes are missing!

## Solution
Create a stylesheet specifically for the Linux version of the game that will render checkboxes (see below).

## Workarounds
- Add this code to `main.css`:
```
/* RADIOS & CHECKBOXES STYLES */

/* base styles */
input[type="radio"], 
input[type="checkbox"] {
    height: 16px;
    width: 16px;
    vertical-align: middle;
    margin: 2px;
    border: 1px solid #A5A5A5;
    background: -webkit-linear-gradient(#FCFCFC, #DADADA);
    -webkit-border-radius: 8px;
    border-radius: 8px;
    -webkit-appearance: none;
    -webkit-transition: box-shadow 200ms;
}

/* inset shadows */
input[type="radio"]:not(:disabled), 
input[type="checkbox"]:not(:disabled) {
    box-shadow:inset 1px 1px 0 #fff, 0 1px 1px rgba(0,0,0,0.1);
}

/* decrease border radius for checkbox */
input[type="checkbox"] {
    -webkit-border-radius:2px;
    border-radius:2px;
}

/* hover state */
input[type="radio"]:not(:disabled):hover,
input[type="checkbox"]:not(:disabled):hover {
    border-color:rgba(0,0,0,0.4);
    box-shadow:inset 1px 1px 0 #fff, 0 0 4px rgba(0,0,0,0.2);
}

/* active state */
input[type="radio"]:active:not(:disabled),
input[type="checkbox"]:active:not(:disabled) {
    background-image: -webkit-linear-gradient(#C2C2C2, #EFEFEF);
    box-shadow:inset 1px 1px 0 rgba(0,0,0,0.2), inset -1px -1px 0 rgba(255,255,255,0.6);
    border-color:#707070;
}

/* focus state */
input[type="radio"]:focus,
input[type="checkbox"]:focus {
    outline:none;
    box-shadow: 0 0 1px 2px rgba(0,240,255,0.4);
}

/* input checked border color */
input[type="radio"]:checked,
input[type="checkbox"]:checked {
    border-color:#707070;
}

/* radio checked bg */
input[type="radio"]:checked,
input[type="radio"]:checked:active {
    background: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJCAMAAADXT/YiAAAAVFBMVEX///9eXl5RUVEzMzMbGxszMzNRUVEiIiJRUVFFRUUzMzMiIiJFRUUzMzNRUVFRUVE6OjorKysiIiJRUVFFRUU6OjozMzMrKytRUVFFRUUzMzMrKyvGHNe0AAAAHHRSTlMAERERESJmZnd3d3eIiJmqqqqqzMzMzMzd3d3dIlELBQAAAEFJREFUCNdjYEACLOxC3CwgBrOgtLi4ICuQxSUlBgS8QJaAKAgIAFmckiIiIpI8QBYTn4SwBD8TSAsjGz8HI7JhAH1fArjBaKLrAAAAAElFTkSuQmCC") center no-repeat, -webkit-linear-gradient(#FCFCFC, #DFDFDF);
}

/* checkbox checked bg */
input[type="checkbox"]:checked,
input[type="checkbox"]:checked:active {
    background: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJCAMAAADXT/YiAAAAOVBMVEX///8zMzMqKipCQkI8PDwzMzNISEhISEhISEhCQkIqKio8PDwzMzMqKipISEhCQkI8PDwzMzMqKipFad0NAAAAE3RSTlMAIiIzMzNEZnd3qru7u8zMzMzMuKlnZwAAADhJREFUCNdjYIACJhjNJQRl8ApBWIw8goKsDDw8UAaDgAA3t4AAC1CGkx8ImMGKOPj42KAmsEMYAEUyAa2GdxXhAAAAAElFTkSuQmCC") center no-repeat, -webkit-linear-gradient(#FCFCFC, #DFDFDF);
}

/* disabled input */
input:disabled {
    opacity:.6;
    border-color:#aaa;
    box-shadow:0;
}

/* style label for disabled input */
input:disabled + label {
    color:#666;
    cursor:default;
    -webkit-user-select: none;
}
```

- Manually mount a game using `mount.cfg` (this will not help with making a server, of course).

_also please get rid of awesomium thanks_

**Comment by robotboy655** [comment] 2017-04-09 15:57
Duplicate of #2826

**Closed by robotboy655** 2017-04-09 15:57 UTC
