### ISSUE TITLE
SetupDataTables not working properly in player_manager classes.

### ISSUE THREAD

**Issue by Donkie** [Facepunch/garrysmod-issues#892] opened 2014-03-18 11:19 UTC
It's not being called for anybody else on the client, meaning only the localplayer will get the NetworkVar methods and updates. I can see why it's made this way, but there's a lot of headscratching and  hacky code needed to work around this.

**Comment by robotboy655** [comment] 2015-06-17 19:14
Ok, so it's caused by this piece of code: https://github.com/garrynewman/garrysmod/blob/ead2b4d7f05681e577935fef657d4a4d962091e6/garrysmod/lua/includes/modules/player_manager.lua#L389 Only running on Local Player and Server.

Easiest workaround would be to call ```player_manager.RunClass( ply, "someFunction", ... )``` on all players on client. ( Or call it if certain method on player doesn't exist or some shit ).

I guess it should be networked and be called from ```player_manager.SetPlayerClass```.

**Comment by kklouzal** [comment] 2016-03-02 02:36
`local PLAYER = FindMetaTable("Player")

function PLAYER:SetupDataTables()
	self:NetworkVar( "Int", 0, "Wallet" )
	self:NetworkVar( "Int", 1, "Bank" )
	self:NetworkVar( "Int", 2, "InfectionTotal" )
end

hook.Add( "OnEntityCreated", "SetupPlayerDataTables", function( ent )
	if ent:IsPlayer() then
		ent:InstallDataTable()
		ent:SetupDataTables()
	end
end )`

problem solved, DataTable's on players. Put that in a shared file.

**Comment by Bo98** [comment] 2016-05-23 06:50
It would be a good idea to have a way to specify whether you want it only networked to the local player or broadcast to everyone. Garry did plan this back in 2013 before he went over to Rust.

**Comment by Noiwex** [comment] 2018-08-04 14:48
Same problem in 2018

**Comment by meepen** [comment] 2018-12-11 13:03
feelsBadMan

**Comment by robotboy655** [comment] 2019-01-28 17:21
This should be fixed on Dev.

The class is set via ```player_manager.SetPlayerClass``` on both client and server, automatically on client via a new clientside hook ```GM:PlayerClassChanged( ply, id )```.

This also means that ```PLAYER:Init()``` and subsequently ```PLAYER:SetupDataTables()``` are called when the class is set, instead of when the first class hook happens to be called.

**Closed by robotboy655** 2019-01-28 17:21 UTC

**Comment by Noiwex** [comment] 2019-01-28 17:48
Finally some real use for player classes.
