### ISSUE TITLE
gm_load: Couldn't decode from json!

### ISSUE THREAD

**Issue by CrunchySoap** [Facepunch/garrysmod-issues#4099] opened 2019-12-21 19:11 UTC
This error will happen when attempting to load a save with an undetermined amount of props/ragdolls/entities placed in the map. It's difficult to nail down why this happens, some maps will fail to load with only a couple props added, some you can add 50 and still save/load without issues. Make it 51 props, save, then to try to load it and nothing will happen. This is what shows in the console "gm_load: Couldn't decode from json!". This is a new and major issue for builders and animators, such as myself.

**Comment by robotboy655** [comment] 2019-12-21 20:14
Send me the offending saves (preferably on a non custom map) so it can be looked into. Email is in the readme.md of this repository.

**Comment by CrunchySoap** [comment] 2019-12-22 01:02
Will do, thanks.

**Comment by CrunchySoap** [comment] 2019-12-24 00:32
Don't close it, I send the incorrect saves. I have since sent the correct samples.

**Comment by robotboy655** [comment] 2019-12-24 23:07
Looks like its is caused by some addon TFA, specifically the weapon `tfa_mmod_crowbar`.

I will look into making addons not able to break saves in this way next year.

**Comment by CrunchySoap** [comment] 2019-12-25 05:59
> Looks like its is caused by some addon TFA, specifically the weapon `tfa_mmod_crowbar`.
> 
> I will look into making addons not able to break saves in this way next year.

That's interesting.. I've had saves do that with and without TFA weapons placed. I've sent you another e-mail containing what seems like an entirely different save corruption using the old HL2 system. I hope we (you) can get to the bottom of this. Cheers.

**Comment by robotboy655** [comment] 2020-01-02 15:51
This should be fixed on Dev beta branch (and in the next update naturally).
Please note that this will **NOT** make your existing saves work, only prevent new saves from breaking.

**Closed by robotboy655** 2020-01-02 15:51 UTC
Labels: bug
