### ISSUE TITLE
After save changes in any files gmod server stop work

### ISSUE THREAD

**Issue by Bacring** [Facepunch/garrysmod-issues#5789] opened 2024-03-11 09:20 UTC
### Details

When i edit any lua file in gamemodes/darkrp folder then my server freeze and i can't write in server console anymore
![image](https://github.com/FPtje/DarkRP/assets/101855368/19167d82-bec8-4454-837d-43f3703d17db)
![image](https://github.com/FPtje/DarkRP/assets/101855368/938a1d77-b694-44e4-afd8-507d50cc7ac5)
![image](https://github.com/FPtje/DarkRP/assets/101855368/0a96a9dc-09fe-4278-988f-ba995b89dd17)

### Steps to reproduce

When i edit some files in darkrp,
before in prev years if i save changes then server freeze for 5 seconds and server continue work, but now after i enter/save changes in lua file darkrp gamemode then server freezing and go down, see screenshots
with other gamemodes when i edit files then i don't have this problem
1.
2.

**Comment by robotboy655** [comment] 2024-03-11 16:28
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5788 and my original point still stands.

After looking into this issue, turns out this is a bug with DarkRP, not Garry's Mod, specifically this change: https://github.com/FPtje/DarkRP/commit/1b778981033ee472dea57820bd0e99958e68d19a

**Closed by robotboy655** 2024-03-11 16:28 UTC
Labels: Invalid/No-info

**Comment by Bacring** [comment] 2024-03-11 17:00
how fix it?

**Comment by robotboy655** [comment] 2024-03-11 17:16
Update DarkRP.
