### ISSUE TITLE
Server crashs when spawning props outside of the world.

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#2831] opened 2016-09-25 11:22 UTC
### Details

Server crashs, when spawning props outside of the world.
### Steps to reproduce

Spawn a prop like 100,000 units outside of the world.

**Comment by mcNuggets1** [comment] 2017-01-02 12:10
This is still present, is there any news or a way to fix this?

**Comment by Kefta** [comment] 2017-01-02 12:17
Why are you spawning a prop that far out of the world limits, anyway? And shouldn't crazy physics already bound this if you have the convar enabled?

**Comment by mcNuggets1** [comment] 2017-01-02 12:19
Spawning bugs can lead to that.
Stacker either.

I clamped stacker, but I can't clamp the gm_spawn function to spawn JUST in world.

Crazy physics does remove it, withhin like 7600 units aways from the map, but if it goes above that limit, it just crashs or completly fucks up the physics leading to a crash.

**Comment by Kefta** [comment] 2017-01-02 12:37
You can, actually, if you wanted to override it to check, but I still don't get why you're spawning props out that far.

**Comment by mcNuggets1** [comment] 2017-01-02 12:43
It is quite a heavy crashbug which is actually used to crash several servers and there is currently no real fix out there.

In 90% cases this bug is the fault for crashing my server, so actually it is quite a problem for me.

**Comment by robotboy655** [comment] 2017-01-02 12:44
And why I can't even reproduce it? Post crash logs from said crashes?

**Comment by mcNuggets1** [comment] 2017-01-02 12:48
Well wow
lua_run e = ents.Create("prop_physics") e:SetModel("models/pigeon.mdl") e:SetPos(Vector(0,0,999999999999999999999)) e:Spawn() e:Activate()

**Comment by mcNuggets1** [comment] 2017-01-02 12:48
Crashed my local game without addons.

**Comment by mcNuggets1** [comment] 2017-01-02 12:49
Do you still want the crash log?

**Comment by Kefta** [comment] 2017-01-02 12:51
Yeah, crashed my game in single-player on main branch.

**Comment by mcNuggets1** [comment] 2017-01-02 13:00
If this is going to get fixed, then I guess I'll have to visit my favorite servers one last time.

**Comment by robotboy655** [comment] 2017-01-02 22:24
That specific case should be fixed in Dev.

**Closed by robotboy655** 2017-01-02 22:24 UTC
Labels: crash

**Comment by mcNuggets1** [comment] 2017-01-04 15:55
Still happens.

**Comment by robotboy655** [comment] 2017-01-04 16:18
```
] lua_run local e = ents.Create("sent_ball") e:SetPos(Vector(0,0,99999999999999999999999999999999999999)) e:Spawn() e:Activate()
> local e = ents.Create("sent_ball") e:SetPos(Vector(0,0,99999999999999999999999999999999999999)) e:Spawn() e:Activate()...
sent_ball[173]:SetPos( 0.000000 0.000000 99999996802856925000000000000000000000.000000 ): Ignoring unreasonable position.
] lua_run local e = ents.Create("sent_ball") e:SetPos(Vector(0,0,9999999999999999999999999999999)) e:Spawn() e:Activate()
> local e = ents.Create("sent_ball") e:SetPos(Vector(0,0,9999999999999999999999999999999)) e:Spawn() e:Activate()...
Crazy origin on entity [184][sent_ball]
	Origin:           [0.000000, 0.000000, 9999999848243207300000000000000.000000]
	Angles:           [0.000000, 0.000000, 360.000000]
	Velocity:         [0.000000, 0.000000, -9.000000]
	Angular Velocity: [0.000000, 0.000000, -0.000000]
Defusing!
Not defusing position, avoiding potential crash!
Removing!
```

**Comment by mcNuggets1** [comment] 2017-01-04 16:20
gm_construct.
Use the same code and spam it like 25 times.
The balls then fall from the sky in the size of 1.

Wait 1 minute.
Leads to a crash.

Tested on sandbox without addons.

Game just closes or closes with a weird error message saying something with TPS or TVS.

**Comment by robotboy655** [comment] 2017-01-04 16:37
nothing happens even with hundreds of them.

![image](https://cloud.githubusercontent.com/assets/3299036/21650149/b8aef428-d2ac-11e6-9ba0-5d515bc2d549.png)

**Comment by mcNuggets1** [comment] 2017-01-04 16:46
https://www.dropbox.com/s/btl84y12r6eyan9/hl2_170102_crash_2017_1_4T16_41_36C0.mdmp?dl=0
https://puu.sh/tb29z/84a50ebcd2.png

Hopefully this can help you.

**Comment by robotboy655** [comment] 2017-01-04 17:39
It's a generic physics crash that cannot be analyzed or fixed.

**Comment by mcNuggets1** [comment] 2017-01-04 17:45
So it is not really fixed, just fixed in specific scenarios.
Maybe just remove the entity entirely, when spawned outside of the map?
Why keeping Size 1 Balls floating around the ap crashing the game?

**Comment by robotboy655** [comment] 2017-01-04 17:46
That's what crazy physics stuff is doing. The entities get removed.

**Comment by mcNuggets1** [comment] 2017-01-04 17:48
Why do these entities then spawn and getting higher indexing numbers, when it says it got removed?

**Comment by robotboy655** [comment] 2017-01-04 17:50
Because you fucking create them??!!?!

**Comment by mcNuggets1** [comment] 2017-01-04 17:51
When they get removed, why do they still exist, then?
They should not be spawned outside of the map, should they?

**Comment by robotboy655** [comment] 2017-01-04 17:52
They don't jesus christ

In your crash log only 1 entity was outside of the map, and it got removed. The other ones were never removed because they were never moved outside of the map due to safeguards in Entity.SetPos.

I am done here.

**Comment by mcNuggets1** [comment] 2017-03-30 14:24
Still happens when resizing a prop with "Prop Resizer" tool and moving it outside of the world.

Crashdump:
https://www.dropbox.com/s/gwxb8o0l43n1z76/hl2_170329_crash_2017_3_30T14_23_21C0.mdmp?dl=0

**Comment by robotboy655** [comment] 2017-03-30 16:44
That's an entirely different crash inside vphysics, nothing can be done about that.

**Comment by mcNuggets1** [comment] 2017-03-30 16:48
Sad story.

I actually wanted to use that tool someday.

Well, anyways thanks for the new shit next update.
I appreciate your work.

**Comment by thegrb93** [comment] 2017-03-30 18:29
Non-english speakers probably think you're calling the next update shit fyi.
