### ISSUE TITLE
FCVAR_REPLICATED with FCVAR_ARCHIVE can be loaded from client.vdf

### ISSUE THREAD

**Issue by roboderpy** [Facepunch/garrysmod-issues#3323] opened 2017-10-31 23:34 UTC
Causing https://github.com/Facepunch/garrysmod-issues/issues/1234

and i thought it was never fixed, because i didnt even knew it was *fixed?*, because this still happens with many of my code and others addons as well

If you think it was fixed, it **wasn't**

**Comment by Kuma96** [comment] 2018-05-06 20:11
I am also having this issue. In my case, I have a DCheckBoxLabel handling a Server ConVar that was created using FCVAR_ARCHIVE and FCVAR_REPLICATED, so users (admins) can change it and send the new value to the server. Then the server change it, but if the last value of the convar was not the default value, the ConVar is not updated on clients. When this happens I click a couple of times on the DCheckBoxLabel and then I can edit it normally.

**Comment by thegrb93** [comment] 2018-08-02 18:40
Does only applying the FCVAR_ARCHIVE flag in serverside fix it?

**Comment by Kuma96** [comment] 2018-09-09 20:06
@thegrb93 did you try that?

**Comment by robotboy655** [comment] 2018-09-11 17:02
> I have a DCheckBoxLabel handling a ConVar that was created using FCVAR_ARCHIVE and FCVAR_REPLICATED, so users (admins) can change it and send the new value to the server.

This isn't what FCVAR_REPLICATED does. It only supposed to send data from server to all clients.

From VDC:
> FCVAR_REPLICATED
When the game server and clients are using shared code where it's important that both sides run the exact same path using the same data (e.g. predicted movement/weapons, game rules). If this code uses console variables, they must have the same values on both sides. **The flag FCVAR_REPLICATED ensures that by broadcasting these values to all clients. While connected, clients can't change these values and are forced to use the server-side values.**

**Comment by Kuma96** [comment] 2018-09-18 19:26
> > @Kuma96 I have a DCheckBoxLabel handling a ConVar that was created using FCVAR_ARCHIVE and FCVAR_REPLICATED, so users (admins) can change it and send the new value to the server.
> 
> This isn't what FCVAR_REPLICATED does. It only supposed to send data from server to all clients.
> 
> From VDC:
> 
> > FCVAR_REPLICATED
> > When the game server and clients are using shared code where it's important that both sides run the exact same path using the same data (e.g. predicted movement/weapons, game rules). If this code uses console variables, they must have the same values on both sides. **The flag FCVAR_REPLICATED ensures that by broadcasting these values to all clients. While connected, clients can't change these values and are forced to use the server-side values.**

I mean, the client sends a message with the boolean value and when the server gets the message, It changes the value of the ConVar. Something like:

`		net.Receive("foo", function(len, ply)
			local checkvalue = net.ReadBit()
			if checkvalue == 1 then
				GetConVar("myconvar"):SetBool(true)
			else
				GetConVar("myconvar"):SetBool(false)
			end
		end)
`

Therefore, once the server makes the change, the ConVar should be updated on all clients, since It was created with FCVAR_REPLICATED, but in some circumstances it is not the case and the ConVar changes Serverside, but it is not updated clientside.

**Comment by menof36go** [comment] 2020-01-30 19:42
@robotboy655 I feel like there is a misunderstanding of this issue and they should have provided steps to replicate. This bug can be reproduced by following these steps:

1. Create a replicated convar with default value 1
2. Change the convar value to anything else, 0 for example.
3. Connect to the server. It should be replicated correctly and say 0 clientside.
4. Disconnect.
5. Change the convar back to its default value 1.
6. Connect.
7. The convar value wasn't replicated correctly. Serverside it is 1, but clientside it will still say 0.

This only happens when you change the convar value to the default value while a player is disconnected. Convar changes while a player is connected are always replicated correctly.

Here is [a demonstration of this bug](https://youtu.be/tywjpLwYNYU) (v2020.01.25)
Please note that the server was running TTT, but it doesn't matter at all and the same bug appears regardless of gamemode.

**Comment by robotboy655** [comment] 2020-01-31 15:59
Now was it that difficult to include this info when the issue was first opened?

Either way, it should be fixed on Dev, by removing FCVAR_ARCHIVE from replicated lua convars on the client.

**Closed by robotboy655** 2020-01-31 15:59 UTC

**Comment by TimGoll** [comment] 2020-02-01 15:06
I'm not entirely sure about that. Shouldn't a replicated convar overwrite the archive setting on clients? Sounds really unintuitive to me.

Also, Fabian and I found this error a few days ago, the person that reported it a few years ago was someone else.

**Comment by thegrb93** [comment] 2020-02-01 15:22
I think he meant that Dev branch now removes the Archive flag internally.

**Comment by menof36go** [comment] 2020-02-01 15:33
> I think he meant that Dev branch now removes the Archive flag internally if the replicated flag is present.

That would be a good solution. Regardless, I am happy that I can use FCVAR_REPLICATED again. I'll add a bug tag to this function in the wiki to tell people to not use FCVAR_ARCHIVE in combination with FCVAR_REPLICATED on the clientside convar for now.

**Comment by Alf21** [comment] 2020-02-01 15:48
Uff, asked a few times, got told that it can‘t happen, rewrote the entire ConVar replication on my own with a GlobalVar workaround. That was the reason people doing this for years. Nice and happy to see this is fixed now, I think I can rework and simplify the entire code now (back to the roots) 😅

Maybe in your release notes, you should mention this bug clearly :)
