### ISSUE TITLE
Half-Life: Source Characters still not fixed

### ISSUE THREAD

**Issue by RiccyRod** [Facepunch/garrysmod-issues#3303] opened 2017-09-17 08:48 UTC
### Details

1.monster_apache, monster_osprey, and monster_sentry, monster_turret, monster_miniturret aren't even in the game. It is commented, but you can't
 spawn them.

### Steps to reproduce

Console > npc_create monster_sentry 
The console should instead be returning "Attempted to create unknown entity type monster_example!".  ( In our case - "Attempted to create unknown entity type monster_sentry!" )
And repeat this with monster_turret, monster_miniturretm, monster_apache, monster_osprey.
![noname](https://user-images.githubusercontent.com/32031537/30519397-8517de54-9ba6-11e7-8b15-2e7cc4355440.png)

**Comment by Kefta** [comment] 2017-09-17 16:53
Thus was never fixed. Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/3170

**Closed** 2017-09-17 17:02 UTC
