### ISSUE TITLE
Concerning "Servers with ping under 60 now have identical ranking impact from ping" change

### ISSUE THREAD

**Issue by osiris-plus** [Facepunch/garrysmod-issues#4501] opened 2020-05-14 05:40 UTC
Hello. I have a few points to talk about the ping equalization.

1. This is really just a terrible band-aid solution to a problem. It doesn't fix the issue when people use anycast technology in their advantage to appear as if they're in your region.

**Yes, we know that anycast helps you (clients of gmc and others (?)) with anti-ddos measures and reduce the load with A2S_INFO.** Please don't start this incoherent rambling about how terrible ddos is and how _lower pings are just a side effect_. I'm talking about what we have from actions of such hosters.

Basically, GMChosting is almost a no-brainer choice for well establishes servers nowadays. It's almost as if GMC is holding a monopoly in US server market. Clearly there is an unfair advantage in the fact that by utilizing anycast technology it is possible to appear as if you're in the same region as player searching for server (Europe for example), while in fact the real server is somewhere in Texas.

Honestly, I don't know the true way to go about this. Everyone is at the mercy of Facepunch's decisions. Maybe FP could prohibit the use of anycast in such manner and punish gmchosting for enabling such behavior. Maybe it's about moving away from pings and instead approximating rating by server geolocation (which should be singular).

I don't think that it should be OK to just flock around ONE hosting provider.

2. Any ping fluctuation incurred from srcds handling A2S requests with everything else can be resolved by making changes to the game, specifically implementing the same thing that gmsv_serversecure does in the game code itself (handling A2S on separate thread). I think this was initial problem of this pull request's author https://github.com/Facepunch/garrysmod/pull/1671

3. **Here I'm talking from my own perspective, but it might be also true for someone else.** Previously in Russia the users of anycast didn't bother us as much, because they don't operate in our country. Now with recent change we just have another problem, apart from situation with rampant usage of fake servers in Russian community. Fake servers alone bring enough headaches to us. Please don't crush us with american ping spoofing servers. This is absolutely absurd how these american servers appear HIGHER than russian servers. In no way this is OK and how this problem should be treated. The server that is in the same city as me gets absolutely dominated by foreign servers.

This is TTT section in Russia now:

![TTT in Russia](https://cdn.discordapp.com/attachments/589120351238225940/710346820118773780/unknown.png)

This is absolutely horrendous and doesn't make situation better. It just plays in hand of those who host at GMChosting.

And this is what we have in DarkRP section:

![DarkRP in Russia](https://cdn.discordapp.com/attachments/589120351238225940/710324827478687855/unknown.png)

American servers getting on top of russians plus blatant fakes.

I don't think that GMC has nodes in every country. It helps some servers that they host in country of their audience, for example French server is in France, German server is in Germany, Russian server is in Russia. These servers shouldn't be punished and equalized, just because of actions of others.

I don't think russian players would be very pleased to see american servers on the top and have to dig in the list to find the server that is hosted in their country, where people speak in their native language, where interface is also in their native language. Let alone the fact that they surely don't like to see fake servers.

**Comment by Kefta** [comment] 2020-05-14 06:49
> This is really just a terrible band-aid solution to a problem. It doesn't fix the issue when people use anycast technology in their advantage to appear as if they're in your region.

The ping change wasn't meant to solve the anycast problem, it was just a weighting rebalancing. This just seems like another issue complaining about anycast which has already been well-documented. Do you have any actual complaints about the ping change specifically?

**Comment by osiris-plus** [comment] 2020-05-14 06:55
> 
> 
> > This is really just a terrible band-aid solution to a problem. It doesn't fix the issue when people use anycast technology in their advantage to appear as if they're in your region.
> 
> The ping change wasn't meant to solve the anycast problem in entirety, it was just a weighting rebalancing. This just seems like another issue complaining about anycast which has already been well-documented. Do you have any actual complaints about the ping change specifically?

This issue is not really about complaining about anycast. It's about how this issue now also affects our region and how it might bring negative effects to native servers.

Really, the third part is what made me post this.

**Comment by osiris-plus** [comment] 2020-05-14 07:05
Also that pull request specifically mentions that it's made to lower anycast advantage. But in my region it works the other way.

**Comment by WilliamVenner** [comment] 2020-05-15 15:32
I think the ping change should stay but region filtering/sorting would fix this.

**Comment by Leystryku** [comment] 2020-05-16 12:05
@osiris-plus 
You're talking about multiple issues at once in this issue ticket.

## Lots of servers with fake players in russia

**Fake Players are forbidden** but especially in the russian garrysmod community they seem to be really popular. If you **see such servers, report them**. The garrysmod devs added GSLT now to combat this more effectively, but there's not a lot we can do.

## Now seeing (more) non russian servers while in russia
As I've seen you've marked everything on russian red.
Why did you do that?
This is **intended behaviour**. Why should you not see a server not from russia when your ping to the server is good? **Why should people be region locked to servers to their specific region**?

## Seeing anycasted TTT servers which have high playercounts
In my opinion the effects of this change will only be visible after it's been done. Because right now, all players join based on the old ranking and playercount is a big factor. In your screenshot the playercounts go all the way down to 0. There's **simply not a single russian server online at that time with 16+ players.** All **popular servers in your screenshot** are **non russian.**

The reason why you're seeing the moat.gg ones on top is because **besides anycast** their **playercounts are all high**, essentially the **highest of any TTT servers**. The reason why you're seeing the moat.gg servers on the top is **not just because of their ping, but because they're having playercounts** of  because they're having.


small note:

To be honest, moat.gg plays a second manipulation card besides ping spoofing. They flood the serverlist with ~12 to 24 identical servers with max of e.g. 32 players to make it more likely that people join one of his servers. The players can then ingame get redirected to more popular moat.gg servers or motivated to join the more popular moat.gg ones.

**Comment by osiris-plus** [comment] 2020-05-17 03:43
@Leystryku 
For last couple of months I've been reporting these servers, but I can only do so much. There's not a lot of people who can ban these servers from appearing.

The GSLT system is not working as intended due to how much Steam C++ API sucks. It trusts anything server says in A2S.

Right now we're observing how list behaves while players do not have this change yet. What I'm afraid of is that this change will be confusing to players, especially when they don't have any favorite servers yet.

Think of this scenario: it's early morning in eastern europe, not a lot of population on eastern european servers, while american servers rocket to the top with their high playercounts and ping spoofing. What's gonna happen next? I think this only hurts fair servers and benefits malicious ones.

Indeed later in the day the situation may improve. But what's going to happen when the update comes out?

**Comment by osiris-plus** [comment] 2020-05-17 03:47
I'm not really against experimenting, but what I'm afraid of is that FP's gmod team is not swift enough to monitor all negative feedback and this change will be left there for months.

**Comment by Kefta** [comment] 2020-05-17 03:52
The PR to change the ping weighting was created and merged within 4 days. What speed is swift enough for you?

**Comment by osiris-plus** [comment] 2020-05-17 03:56
I think you got me wrong. I don't mean to bash on FP, there's only 2 people working on the game after all.

What I'm saying if any negative effects arise, any rants about this will be lost in oblivion of thousands of others things devs have to take care of.

**Comment by Kefta** [comment] 2020-05-17 05:09
Anycast/ping sorting is a very hot-button issue right now so I doubt it will be lost.

**Comment by Leystryku** [comment] 2020-05-17 09:17
@osiris-plus 

Honestly, I don't think it's a bad thing when non russian servers get more russian players **if the russian servers aren't played as much and the ping is fine**.

If people get **more variety/"foreign servers" that's a good thing**.
If **russians only want to play with russians**, they **still can** after this.


Infact, back in the day, the main factor **always was players**. **Nationality/region did not matter at all**. This change as a side effect does the same thing for **pings under 60** (playable servs).

**Comment by Kefta** [comment] 2020-12-15 15:31
I have seen no complaints about the ping change since it was released.

**Closed by Kefta** 2020-12-15 15:31 UTC
