### ISSUE TITLE
Crash when generating spawn icons for Left 4 Dead 2 props

### ISSUE THREAD

**Issue by TheBerkin** [Facepunch/garrysmod-issues#2104] opened 2015-06-17 04:10 UTC
The game crashes when I search for certain terms in the spawnmenu (specifically "door" or "roof") and have Left 4 Dead 2 mounted. The last thing I see is the search results with several ungenerated spawn icons (showing the "broken image" graphic), so I assume it is trying to generate the icons when the crash happens.

The crash occurs with all addons disabled and no other game content mounted, but it doesn't matter if other games are mounted as well. Generating spawn icons for other games' content does not cause the game to crash.

This does not happen with all Left 4 Dead 2 props, however; I can search "stair", for example, and get several staircases from the game.

This crash occurs on version 2015.06.01.

**Steps to reproduce:**

1. Mount Left 4 Dead 2.
2. Load a new singleplayer game in any map.
3. Open the spawnmenu.
4. In the search bar in the top left, search for "roof" or "door".
5. Enjoy.

**Comment by robotboy655** [comment] 2015-06-17 12:20
Duplicate of #951

**Closed by robotboy655** 2015-06-17 12:20 UTC
