### ISSUE TITLE
PNG materials get cut off by a few pixels

### ISSUE THREAD

**Issue by WilliamVenner** [Facepunch/garrysmod-issues#4715] opened 2020-10-31 17:32 UTC
### Details
![image](https://user-images.githubusercontent.com/14863743/97785506-626c1d00-1b9d-11eb-973c-91e08e4fefe7.png)

```lua
local TEXTUREFLAGS_CLAMPS = 4
local TEXTUREFLAGS_CLAMPT = 8
local flagMask = bit.bnot(bit.bor(TEXTUREFLAGS_CLAMPS, TEXTUREFLAGS_CLAMPT))

local logoWhitePNG = Material("bkeypads/logo_tall_white.png", "noclamp smooth")

local logoWhite = CreateMaterial("bKeypads.LogoWhiteXXXXXXXXXXXXXXXXXXX", "UnlitGeneric", {
	["$ignorez"] = 1,
	["$translucent"] = 1
})

logoWhite:SetTexture("$basetexture", logoWhitePNG:GetTexture("$basetexture"):GetName())
logoWhite:SetInt("$flags", bit.band(logoWhite:GetInt("$flags"), flagMask))
logoWhite:Recompute()
```

The first logo and the logo shown on the toolscreen are `logoWhite`. The logo below that is `logoWhitePNG`.

`noclamp` seems to be fixing it - when logoWhitePNG doesn't have `noclamp` the below logo is also cut off. However this seems to be completely ignored by CreateMaterial, and masking it away from $flags appears to do nothing, even after calling Recompute. I also tried setting logoWhite's $flags to logoWhitePNG's $flags but this had no effect either.

#### Original Image

![logo_tall_white](https://user-images.githubusercontent.com/14863743/97785680-78c6a880-1b9e-11eb-9b41-43d621ba0928.png)

**Comment by CornerPin** [comment] 2020-10-31 18:09
#3173
`surface.DrawTexturedRect` doesn't work well with materials created with `CreateMaterial`. Instead, you can use [render.DrawScreenQuadEx](https://wiki.facepunch.com/gmod/render.DrawScreenQuadEx) or apply the workaround described in the [surface.DrawTexturedRectUV](https://wiki.facepunch.com/gmod/surface.DrawTexturedRectUV) notes.

**Comment by WilliamVenner** [comment] 2020-10-31 18:20
Thank you surface.DrawTexturedRectUV worked best for me.

**Comment by robotboy655** [comment] 2020-11-06 17:27
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/2425

**Comment by robotboy655** [comment] 2020-11-06 17:30
> However this seems to be completely ignored by CreateMaterial, and masking it away from $flags appears to do nothing, even after calling Recompute

That's because you are trying to use TEXTURE flags on a MATERIAL.

**Comment by robotboy655** [comment] 2020-11-06 17:47
Related issue https://github.com/Facepunch/garrysmod-issues/issues/3173

**Comment by robotboy655** [comment] 2020-11-06 17:58
it is in fact a duplicate of https://github.com/Facepunch/garrysmod-issues/issues/3173

**Closed by robotboy655** 2020-11-06 17:58 UTC

**Comment by robotboy655** [comment] 2020-11-06 18:23
> noclamp seems to be fixing it - when logoWhitePNG doesn't have noclamp the below logo is also cut off. However this seems to be completely ignored by CreateMaterial, and masking it away from $flags appears to do nothing, even after calling Recompute. I also tried setting logoWhite's $flags to logoWhitePNG's $flags but this had no effect either.

Cannot reproduce this. Here's my code and the resulting image:
 ```
local mat = Material("icon16/picture.png", "noclamp")
local whatthef = CreateMaterial("whatthef411", "UnlitGeneric", { ["$basetexture"] = mat:GetName(), ["$vertexalpha"] = 0 })

hook.Add( "HUDPaint", "PutAUniqueHookNameHere", function()
	surface.SetDrawColor( 255, 255, 255, 255 )
	surface.SetMaterial( whatthef )
	surface.DrawTexturedRect( 0, 513, 512, 512 )
	surface.DrawTexturedRectUV( 512+1, 513, 512, 512, 0, 0, 1, 1 )
	surface.DrawTexturedRectUV( 512+512+2, 513, 512, 512, 0 - 1/32, 0 - 1/32, 1 + 1 / 16 /2 , 1 + 1/32 )

	surface.SetMaterial( mat )
	surface.DrawTexturedRect( 0, 0, 512, 512 )
	surface.DrawTexturedRectUV( 512+1, 0, 512, 512, 0, 0, 1, 1 )
	surface.DrawTexturedRectUV( 512+512+2, 0, 512, 512, 0 - 1/32, 0 - 1/32, 1 + 1 / 16 /2 , 1 + 1/32 )
end )
```

![image](https://user-images.githubusercontent.com/3299036/98400918-87fd9880-206d-11eb-9ab0-c75d91c1c472.png)

Only the UV adjusted image shows the full 1px border on the far right.
