### ISSUE TITLE
Linux server crash problem (TTT)

### ISSUE THREAD

**Issue by CrypticNetwork** [Facepunch/garrysmod-issues#4960] opened 2021-05-30 03:07 UTC
I have recently made a ttt server which is about 1 month now. From the beginning the server crashed almost around 20 to 40 rounds. This was just with the gamemode and damagelogs (Which is necessary for the game mode.). To find the problem I installed gcrash. From there I ran many tests. After, I ran a TTT2 server for at least for 500 rounds, and it did not crash, so I tried to transferred over the TTT2 cleanup function as a test. The ending result made the TTT server crash way less. It finally crashed after 5 days of playing with the server restarting every night. On the day it crashed we played 120 rounds with only 7 players. It seems very random.  

Something to note: This is not the first time I decided to make a TTT server. Last year (summer 2020) I made a TTT server, and it was crashing, and I couldn't find a solution, so I gave up and deleted the server. I recently decided to give it another shot to see if the problem still exist. As it turns out, it is still a problem. When I first opened up in July 2020, I did not have this problem.

**Info about the crash/how to reproduce:**
Problem:  The server crash is after the round ends and when game.CleanUpMap() is called upon. 
1. With damagelogs the server crashes within 30 rounds on average with some exceptions (No other addons).
2. Without damagelogs the server crashes on average after 50 rounds (No addons).
3. With TTT2 cleanup function and damgelogs it crashed after about 1000 rounds played. It lasted over 150 rounds before it crashed since the server restarted. (5 days after implementation) (Important note: this # includes server restarts and not using script and with real players) 

- The dedicated server is on the regular branch of gmod. 
- The tests # 1 - 2 was tested with a script and with 23 bots with a player (myself) (Script is below).
- 3 was with only 7 players that was currently on the server.

**NOTE 1:** The TTT settings are set to 999 rounds before map change and the time is set to 20000 minutes before map change.

**NOTE 2:** The CPU only goes up and down each round end and start. With TTT regular function, the CPU each time goes up to 20% to 40% down to 20% to 60% on like a pattern then the 60% turns into 80% then on the next round restart it spikes to 100% (Don't know it a real #) but the server crashes. With the modified function I didn't catch the CPU usage when it about to crash, although it was usually at 60% on round restarts. [All tests used 1 player and 23 bots]

**NOTE 3:** The map was ttt_minecraft_b5 and on many other maps. It seems to matter on the map on how bad it is. Although I can not say fur sure.

**NOTE 4:** I have used 3 different hosting companies with all the same problem. One was a dedicated gmod hosting company and the other 2 were vps hosting companies. The vps servers was running on Ubuntu 20.04. 

**Test Script:**
Purpose: To kill all players to restart the round to speed the process | Location: garrysmod/lua/autorun/server
```lua
local function hahafunny(ply)
    local lol = player.GetAll()
    for i=1, #lol do
    local v = lol[i]
        v:Kill()
    end
end 

hook.Add( "TTTBeginRound", "EndRoundRespawn", hahafunny )
hook.Add( "TTTPrepareRound", "EndRoundRespawn", hahafunny )
hook.Add( "TTTEndRound", "EndRoundRespawn", hahafunny )
```

**TTT default cleanup function:** [1 - 2]
Location: garrysmod/gamemodes/terrortown/gamemode

```lua
local function CleanUp()
   local et = ents.TTT
   -- if we are going to import entities, it's no use replacing HL2DM ones as
   -- soon as they spawn, because they'll be removed anyway
   et.SetReplaceChecking(not et.CanImportEntities(game.GetMap()))

   et.FixParentedPreCleanup()

   game.CleanUpMap()

   et.FixParentedPostCleanup()

   -- Strip players now, so that their weapons are not seen by ReplaceEntities
   for k,v in ipairs(player.GetAll()) do
      if IsValid(v) then
         v:StripWeapons()
      end
   end

   -- a different kind of cleanup
   hook.Remove("PlayerSay", "ULXMeCheck")
end
```

**TTT2 Cleanup function:**
```lua
local function CleanUp()
	game.CleanUpMap()

	-- Strip players now, so that their weapons are not seen by ReplaceEntities
	local plys = player.GetAll()

	for i = 1, #plys do
		local v = plys[i]

		v:StripWeapons()
		v:SetRole(ROLE_NONE) -- will reset team automatically
	end

	-- a different kind of cleanup
	hook.Remove("PlayerSay", "ULXMeCheck")
end
```

**My modified cleanup function for TTT** [3]
```lua

local function CleanUp()
   game.CleanUpMap(false, {"env_fire", "entityflame", "_firesmoke"})

	-- Strip players now, so that their weapons are not seen by ReplaceEntities
	local plys = player.GetAll()

	for i = 1, #plys do
		local v = plys[i]

		v:StripWeapons()
		v:SetRole(ROLE_NONE) -- will reset team automatically
	end

	-- a different kind of cleanup
	hook.Remove("PlayerSay", "ULXMeCheck")
end
```

**Crash Log**
This is the gcrash log every time. The only difference is when the damagelogs is not in the server it just has everything else except that line

**Last crash before the cleanup change:** 

```log
Seg fault occured.

Main Lua stack:
#0	lua/autorun/server/gcrash.lua:27 in anonymous function() <27-46>
#1	[C] in CleanUpMap()
#2	addons/damagelogs/lua/damagelogs/shared/sync.lua:37 in field CleanUpMap() <34-39>
#3	gamemodes/terrortown/gamemode/init.lua:384 in upvalue CleanUp() <376-397>
#4	gamemodes/terrortown/gamemode/init.lua:463 in anonymous function() <447-515>

Lua crash handler:

Frame #0:
  write = function: 0xe6077fd8

Frame #1:
  (*temporary) = nil
  (*temporary) = table: 0xe6077fb0

Frame #2:
  send_to_clients = nil
  filters = table: 0xe6077fb0

Frame #3:
  et = table: 0xf0b56070

Frame #4:
  delay_round = false
  delay_length = nil


```

**Latest crash with change:**
```log

Seg fault occured.

Main Lua stack:
#0	lua/autorun/server/gcrash.lua:27 in anonymous function() <27-46>
#1	[C] in CleanUpMap()
#2	addons/damagelogs/lua/damagelogs/shared/sync.lua:37 in field CleanUpMap() <34-39>
#3	gamemodes/terrortown/gamemode/init.lua:377 in upvalue CleanUp() <376-391>
#4	gamemodes/terrortown/gamemode/init.lua:457 in anonymous function() <441-509>

Lua crash handler:

Frame #0:
  write = function: 0xf04e5010

Frame #1:
  (*temporary) = false
  (*temporary) = table: 0xe7b87f88

Frame #2:
  send_to_clients = false
  filters = table: 0xe7b87f88

Frame #3:

Frame #4:
  delay_round = false
  delay_length = nil
```

**Is there a way to completely fix this crashing problem?**

**Comment by robotboy655** [comment] 2021-05-31 13:30
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/4954

**Closed by robotboy655** 2021-05-31 13:30 UTC
Labels: Crash, Dependency: IVP
