### ISSUE TITLE
Game crashes upon using mini-teleporter at d1_trainstation_05

### ISSUE THREAD

**Issue by dounai2333** [Facepunch/garrysmod-issues#5642] opened 2023-12-14 04:49 UTC
### Details
This issue only exist on dev and x86-64 branch.
Game will crashes when the mini-teleporter animation is about to stop, and it happens 100%.

![mini-teleporter2](https://github.com/Facepunch/garrysmod-issues/assets/45044404/c894ed43-62b7-45e9-88c2-ed6ebd73e1ae)

Crash dump: [fa6896c4-6181-4325-863d-cb54a4f10a56.dmp](https://github.com/Facepunch/garrysmod-issues/files/13668485/fa6896c4-6181-4325-863d-cb54a4f10a56.dmp)

### Steps to reproduce
1. Start a sp/mp game with map d1_trainstation_05
2. Press E on the mini-teleporter at kleiner's lab
3. Game will crash when the mini-teleporter animation is about to stop

**Comment by robotboy655** [comment] 2023-12-14 11:54
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5639

**Closed by robotboy655** 2023-12-14 11:54 UTC
