### ISSUE TITLE
Linux game crash on connect

### ISSUE THREAD

**Issue by chelog** [Facepunch/garrysmod-issues#2465] opened 2016-02-22 16:27 UTC
It happens every time I connect to any updated server for the latest update (22.02.2016)

Log:
Client “xxx” connected (xxx.xxx.xxx.xxx:xxxxx).
STEAMAUTH: Client xxx received failure code 6
STEAMAUTH: Client xxx received failure code 6
Dropped xxx from server (Client left game (Steam auth ticket has bee
been canceled)

Linux x64
My friend on Linux x64 confirms the same bug

**Comment by xDShot** [comment] 2016-02-22 16:47
Confirming crashing on 64-bit Linux when I try to host my game.
Plz fix it!

**Comment by robotboy655** [comment] 2016-02-22 17:02
Possible duplicate of #590

**Closed by robotboy655** 2016-02-22 17:02 UTC

**Comment by Bo98** [comment] 2016-02-22 17:08
"Steam auth ticket has been canceled" is vague and is just what the server says. Please look for a clientside crash log or something. I know Linux SRCDS can create a debug.log but I have no idea if the client does anything.

**Comment by chelog** [comment] 2016-02-22 17:12
@Bo98 tried with `log on` but I guess it's only for hosting server. I have no logs. Do you have any Idea where to look for?

**Comment by Bo98** [comment] 2016-02-22 17:19
Check for any files with the extension .dmp or .mdmp in your GarrysMod directory in steamapps.

If you can't find any such files there, try open Steam from the command line (`~/.steam/steam/steam.sh`), launch GMod until it crashes, and copy the last 10 lines or so and post it here.

**Comment by chelog** [comment] 2016-02-22 17:24
@Bo98 yep, I got it (btw I don't have `steam.sh` in steam dir so I just launched it with `steam`)

Here's the log, I see the problem is in `hl2.sh`:
```
Game.so loaded for "Garry's Mod"
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Gtk-Message: Failed to load module "pantheon-filechooser-module"
ERROR: ld.so: object '/home/chelog/.steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
Game update: AppID 4000 "Garry's Mod", ProcID 29841, IP 5.19.161.3:27017
pid 29902 != 29872, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/chelog/.steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
pid 29906 != 29872, skipping destruction (fork without exec?)
/storage/games/steam/steamapps/common/GarrysMod/hl2.sh: line 67: 29841 Segmentation fault      (core dumped) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 4000 "Garry's Mod", ProcID 29841
```

**Comment by willox** [comment] 2016-02-22 17:28
Do you have a file called 'core' in /storage/games/steam/steamapps/common/GarrysMod?

**Comment by chelog** [comment] 2016-02-22 17:29
@willox nope, this is all I have in game's root folder:
```
chelog@chelog-pc:/storage/games/steam/steamapps/common/GarrysMod$ l -la
total 44
drwxrwxr-x  7 chelog chelog 4096 Feb 22 19:34 ./
drwxrwxr-x 12 chelog chelog 4096 Feb 19 13:42 ../
drwxrwxr-x  4 chelog chelog 4096 Feb 22 20:22 bin/
drwxr-xr-x  2 chelog chelog 4096 Feb 17 18:17 fontconfig/
drwxrwxr-x 27 chelog chelog 4096 Feb 22 20:22 garrysmod/
-rwxrwxr-x  1 chelog chelog 7284 Feb 22 19:34 hl2_linux*
-rwxrwxr-x  1 chelog chelog 1950 Feb 22 19:34 hl2.sh*
drwxrwxr-x  9 chelog chelog 4096 Feb 22 19:34 platform/
drwxrwxr-x  6 chelog chelog 4096 Feb 22 19:34 sourceengine/
-rw-rw-r--  1 chelog chelog    6 Feb 22 20:22 steam_appid.txt
```

**Comment by willox** [comment] 2016-02-22 17:30
In that terminal could you run "ulimit -c unlimited" and then "hl2.sh" and reproduce the crash again. You should end up with a core dump we can analyse.

**Comment by chelog** [comment] 2016-02-22 17:33
@willox in this case game crashes in a second after `./hl2.sh` is executed. Do I send the core dump anyway?

**Comment by Bo98** [comment] 2016-02-22 17:34
Try `hl2.sh -steam -game garrysmod`

**Comment by chelog** [comment] 2016-02-22 17:35
@Bo98 same thing.

**Comment by robotboy655** [comment] 2016-02-22 18:20
This issue should be fixed soon enough.

**Comment by chelog** [comment] 2016-02-22 18:30
I can confirm that problem is fixed for me (just updated in dev branch)

**Comment by willox** [comment] 2016-02-22 18:39
That's actually really handy to know, thanks.

**Comment by chelog** [comment] 2016-02-22 18:40
@willox wish I could catch and fix those bugs with you guys, heh
sorry for off-top
