### ISSUE TITLE
Garry's Mod Doesn't Fully Close All The Time

### ISSUE THREAD

**Issue by MrUnknownGamer** [Facepunch/garrysmod-issues#2250] opened 2015-09-25 14:49 UTC
When clicking the quit button, hl2.exe will still be open in the background sometimes for me. This is on my old computer and my new, current GamingPC. 

I need to go into Task Manager and find hl2.exe to fully close it.

**Comment by thegrb93** [comment] 2015-09-25 15:58
Same here. Windows10 x64, Nvidia 520 GTX. I have about 27 .mdmp files from when it eventually does crash after hanging in the background because its the only thing that makes my gmod crash.

**Comment by robotboy655** [comment] 2015-09-25 16:02
Well then post the dumps?

I am fairly certain this is because of Steam, some times my hl2.exe becomes steamerrorreporter.exe and I have to close that.

**Comment by thegrb93** [comment] 2015-09-25 22:30
https://dl.dropboxusercontent.com/u/72472980/crashes.zip Might be one or two not caused by closing the game, but the majority definitely are.

**Comment by robotboy655** [comment] 2015-09-25 23:17
Half of those dumps are empty, half of the ones that are not are either awesomium.dll crash or your videocard driver crash. They are also all too old, I will need dumps that were generated AFTER last update.

**Comment by thegrb93** [comment] 2015-09-26 00:30
Okay I deleted them all. I'll put it here if I get another.

**Comment by deinemudda32** [comment] 2015-09-28 17:05
Same here, but mostly it doesnt crash for hours.
Its in no other Source Game, I dont know anything more about this shit.

**Comment by thegrb93** [comment] 2015-09-28 23:06
I made a dump of the process while it was hanging again. https://dl.dropboxusercontent.com/u/72472980/hl2.7z

**Comment by robotboy655** [comment] 2015-09-28 23:29
![image](https://cloud.githubusercontent.com/assets/3299036/10151604/daa4e966-6651-11e5-8488-b22a05e25dd0.png)

**Comment by thegrb93** [comment] 2015-09-29 01:00
Hm, I just used the task manager to create the dump. I'll see if there's a tool that provides the 32 bit option.

**Comment by thegrb93** [comment] 2015-09-29 01:42
https://dl.dropboxusercontent.com/u/72472980/hl2.exe_150928_200656.7z

**Comment by thegrb93** [comment] 2015-09-29 04:35
Also the windows problem reporting process will jump up to 15% after attempting to close gmod.

**Comment by thegrb93** [comment] 2015-09-29 04:35
Also just so it's clear. The window closes, but the process hl2.exe still hangs.

**Comment by robotboy655** [comment] 2015-09-29 07:30
Hm, it seems that it hangs when trying to unload resources.dll. Can you post a dump from latest Dev branch? ( Do a verification first )

**Comment by thegrb93** [comment] 2015-09-30 00:13
It either doesn't happen in dev branch or it doesn't happen if I quit from singleplayer or listenserver. I cant quit from my dedicated server like I usually do because my dedicated server is on the stable branch.

**Comment by Bo98** [comment] 2015-09-30 06:56
How about testing single player/listen server on the stable branch?

**Comment by thegrb93** [comment] 2015-09-30 08:02
Ah sorry. Just tried listen server on stable branch and it didn't happen. I'll try joining a dev server and see if that works.

**Comment by robotboy655** [comment] 2015-09-30 08:47
Can't you download srcds and host it yourself?

**Comment by thegrb93** [comment] 2015-10-01 11:54
Couldn't reproduce in the dev branch. If it happens after next update though I'll post here.

**Comment by robotboy655** [comment] 2015-10-28 18:50
#2069

**Closed by robotboy655** 2015-10-28 18:50 UTC
