### ISSUE TITLE
Garry's mod client/server crashing randomly after october update

### ISSUE THREAD

**Issue by ceifa** [Facepunch/garrysmod-issues#4712] opened 2020-10-27 21:11 UTC
### Details
My server is crashing like 5 times a day after the october update, one of the cases is when I set an entity model scale to 0 using `Entity:SetModelScale(0, 1)`, but is crashing in other cases which I can't find out too.

Server version:
```
Protocol version 24
Exe version 2020.10.14 (garrysmod)
Exe build: 15:56:58 Oct 14 2020 (7881) (4000)
GMod version 2020.10.23, branch: unknown
Linux 64bit Dedicated Server
```

Dump file when crashing because of the SetModelScale is available on:
https://drive.google.com/file/d/19st--Mj981WN7HPfZDk2QoxAMNvL7e_u/view?usp=sharing

Dump file when crashing randomly:
https://drive.google.com/file/d/1TW0IotyldhiwCVToQGoOec9shG_1qV2f/view?usp=sharing

### Steps to reproduce
Open a server(can be p2p) using any branch and type `lua_run Entity(1):SetModelScale(0, 1)` on console.

**Comment by Antizombie** [comment] 2020-10-28 05:00
I think it has to do with the change:
"Fixed collision / movement issues with Player.SetModelScale"
and with the fact that the Hull scale becomes the same 0
https://github.com/Facepunch/garrysmod-issues/issues/3365
But I don't know how much this information will help.
I have nothing to check with at the moment.
But after the update in the "Zombie survival" mod, there were problems with the fact that classes with SetModelScale now can not climb, where they could earlier and vice versa.

**Comment by robotboy655** [comment] 2020-10-28 19:45
Can you provide your `bin/linux64/libtier0.so`?

**Comment by ceifa** [comment] 2020-10-28 20:25
@Antizombie thanks for being involved with my problem, i'm sure your additions will be useful!
@robotboy655 I uploaded at https://drive.google.com/file/d/15P9bFiFcrxxnrJMvpC6XvwqJGU8w0C_C/view?usp=sharing

**Comment by ceifa** [comment] 2020-11-07 12:32
@robotboy655 updates?

**Comment by robotboy655** [comment] 2020-11-09 16:21
None. Visual studio refuses to accept the binaries even though its asking for them so I can't see the stack trace, and I don't have an x86 linux machine to debug this.

SetModelScale has been idiot proofed for players, so it will no longer crash.

**Comment by robotboy655** [comment] 2020-11-25 18:31
The random crash dump you sent is a Lua Panic, without the associated .txt file which should contain the actual information about why it Lua Panic'd there's nothing to be done here. Likely is a duplicate of https://github.com/Facepunch/garrysmod-issues/issues/4716

**Comment by ceifa** [comment] 2020-11-30 21:54
@robotboy655 I don't have the .txt file associated to that dump anymore.
Anyway I uploaded a new dump which probably leans to the same problem, now with the .txt file included: https://drive.google.com/file/d/15vCWwzbQd3nQYPgrZeOt60DKrwZnQT0N/view?usp=sharing

**Comment by robotboy655** [comment] 2020-12-01 15:46
It's not the same crash, but I should be fixed, so update your server.

**Closed** 2020-12-09 13:05 UTC
Labels: Crash
