### ISSUE TITLE
Crash on printing Unicode chracters to console with MsgC() and print()

### ISSUE THREAD

**Issue by daigennki** [Facepunch/garrysmod-issues#2968] opened 2016-12-16 05:53 UTC
### Details
Tell us exactly what happens, every single detail that you can think of

I think I have brought this up before but it has been over a year and it still has not been fixed, and I know for sure it is a problem with Garry's Mod. Whenever certain unicode characters such as "ϟ" and "☁" are printed to my console, my game crashes instantly and only leaves a minidump file in the GarrysMod directory. It seems to only be a problem on my computer, which has Windows 8.1 Pro (Japanese language) installed on it, but the only application with a problem like this on my computer seems to be Garry's Mod. I have tried setting my system locale to English (United States) but that did not seem to fix the problem.

Minidump files, you can see that the last thing printed in console were certain Unicode characters:
https://www.dropbox.com/s/typilafeb0jtc5n/hl2_161029_crash_2016_11_13T1_34_56C0.mdmp?dl=0
https://www.dropbox.com/s/puuutwvjfj0p14q/hl2_161029_crash_2016_12_4T1_50_30C0.mdmp?dl=0
https://www.dropbox.com/s/tjs03f74bab00re/hl2_161029_crash_2016_12_16T5_26_56C0.mdmp?dl=0

### Steps to reproduce
Tell us how to reproduce the problem, step by step

A friend, an addon developer, and I went through steps to attempt to reproduce this problem, and we found that printing Unicode characters like the ones I mentioned earlier into the console with the lua function **MsgC()** crashes instantly. We also found that the function **print( "ϟ" )** also crashes instantly, however **chat.AddText( "ϟ" )** does not crash.

**Comment by Kefta** [comment] 2016-12-16 06:25
How about Msg/MsgN? Player:PrintMessage()?

**Comment by daigennki** [comment] 2016-12-16 06:33
**Msg("ϟ")** seems to crash, but **MsgN("ϟ")** and Player:PrintMessage(HUD_PRINTCONSOLE, "ϟ") does not seem to.

**Comment by willox** [comment] 2016-12-16 11:57
Finally managed to reproduce it after messing with Windows for a while. It's quite interesting how it occurs with Msg and not MsgN, but that seemed to be what I was missing last time I tried it.

**Comment by willox** [comment] 2016-12-16 12:17
I'll move the fix for this to pre-release before the next update

**Closed by willox** 2016-12-16 12:17 UTC
Labels: crash

**Comment by Mista-Tea** [comment] 2016-12-16 19:00
@willox Just out of curiosity, what was the overall reason for the crash?

This one really stumped me because of how limited it was to the users it affected (daigennki being the only one I've known to crash from it).
