### ISSUE TITLE
Half-Life: Source Bugs

### ISSUE THREAD

**Issue by Cthutq295** [Facepunch/garrysmod-issues#3536] opened 2018-07-20 17:46 UTC
1. All brush-entities doesn't take lights from players flashlights:
Screenshot:
https://steamuserimages-a.akamaihd.net/ugc/934945136886204567/02FDF25EB40DEF06659524B127CFDA723B2B3128/
Screenshot:
https://steamuserimages-a.akamaihd.net/ugc/934945136886204363/679526440907A6F5545CBA6ED3D9E5DFB8BB4C54/
Screenshot:
https://steamuserimages-a.akamaihd.net/ugc/934945136886217749/BD82E881A003F724FDB31EB720BE0A8BA71DA83C/

2. Map c2a5f has bug with snark spawn:
When a player pass the trigger in the ventilation it activates a spawn point that spawns only 2 snarks while it have to spawn about 10 snarks.
Screenshot:
https://steamuserimages-a.akamaihd.net/ugc/934945136886204000/866E85E2C7B913A547B19BBD8C4072FE20C11C53/

3. All env_soundscapes from Half-Life: Source doesn't work in Gmod.
4. monster_tentacle can't deal damage to NPCs.

**Comment by Kefta** [comment] 2018-07-20 22:39
There's issues with lighting on HL1 viewmodels, as well

**Comment by TheMostUpset** [comment] 2018-07-21 07:31
> There's issues with lighting on HL1 viewmodels, as well
The issue is that $envmap is broken in gmod. Some materials don't have $basetexture (like HL1 chrome), but they do have $envmap. So it is always fullbright and does not take any lighting.

**Comment by robotboy655** [comment] 2018-07-23 15:00
1. I have got no clue. It must be something to do with how the map was compiled. The lighting on the Hazardous Materials chapter maps is a-ok for example. I don't think its the materials or the shader either.
2. The 3 extra snarks in Half Life Source are the weapons which are not in GMod. The amount of NPCs that spawn is the same.
3. HL:S doesn't have any custom soundscapes, only DSP effects, which ARE included in GMod, but I imagine they'd be different between HL2 (The ones we use) and HL1.
4. Already reported.

As for the chrome materials on models, they do work if you set the shader to VertexLitGeneric_DX6 (but with no reflections i think), that's the only shader that uses the material parameters that those chrome materials use.

**Comment by TheMostUpset** [comment] 2018-07-23 15:54
> As for the chrome materials on models, they do work if you set the shader to VertexLitGeneric_DX6 (but with no reflections i think), that's the only shader that uses the material parameters that those chrome materials use.

This is gmod related bug, any other Source Engine game works well with custom $envmap and regular VertexLitGeneric. I have also noticed that envmaps with only one face will not render on NVidias. You gotta fix them by adding 6 (or 7, don't remember) faces on texture. And lighting is still broken in that case.

**Comment by robotboy655** [comment] 2019-01-14 10:52
1. Got fixed
2. Will be fixed when weapons are added. There's a separate request for this.
3. Is probably also going to get fixed when 2 is
4. Already reported.

**Closed by robotboy655** 2019-01-14 10:52 UTC
