### ISSUE TITLE
Custom soundscapes aren't working correctly in Multiplayer

### ISSUE THREAD

**Issue by TFlippy** [Facepunch/garrysmod-issues#1552] opened 2014-10-19 20:33 UTC
I made a custom soundscape (file + included it in soundscapes_-mapname-.tx manifest), packed it in the .bsp and then tested it in Multiplayer with other players. However, it's been replaced by some default Half-Life 2 soundscape for all other players, making them unable to hear my wonderful sounds. 

Testing the soundscape in Singleplayer worked flawlessly, though. It appears that the servers aren't able to load them from the .bsp.

**Comment by robotboy655** [comment] 2015-08-20 11:47
Ok, I looked into the problem and I think I figured out what's up.

The problem, precisely, is that inconsistency of soundscapes on client versus server. That means that on server, portal/tf2 soundscapes are usually not mounted, so the soundscapes IDs are offset.

**Comment by robotboy655** [comment] 2015-08-20 17:13
Should be fixed in the next update.
https://github.com/garrynewman/garrysmod/commit/77efc3757047e0d0a1d8f22123ba2925c13c27c4

**Closed by robotboy655** 2015-08-20 17:13 UTC
Labels: bug

**Comment by Noiwex** [comment] 2015-08-20 21:02
So, no longer falling rocks on dedicated servers?

**Comment by Matt2468rv** [comment] 2017-10-10 12:25
@robotboy655 I'd like to bring this issue up again. I'm working on the release of a new map and I'm facing the same issues described in my post above.

If my map is run in singleplayer, soundscapes function just fine. However, if my map is run on a server, the soundscapes are all messed up. They end up playing random soundscapes rather than the ones I've correctly created and specified.

This was confirmed by multiple beta testers for my map and is not isolated to my install of Gmod. It's like the soundscapes IDs are offset or something, like you said in your previous post.

Could this issue please be looked into?  It's the only thing stopping me from releasing my map since the ambiance is ruined by noises of heavy machinery instead of my own soundscapes.

Much appreciated.

**Comment by Matt2468rv** [comment] 2017-10-17 17:58
Files added in #3314. Could either this issue or that issue be re-opened? Or should I create a new open issue?

**Comment by pizzadox11** [comment] 2020-04-21 17:58
Read the latest command if you get in trouble with custom soundscapes or custom particles https://github.com/Facepunch/garrysmod-issues/issues/3314
