### ISSUE TITLE
Entity:SetSubMaterial called clientside disappear

### ISSUE THREAD

**Issue by pilot22** [Facepunch/garrysmod-issues#4016] opened 2019-10-06 11:08 UTC
### Details

Entity:SetSubMaterial called clientside is working, but when the entity disappear from your field of view, the setsubmaterial become cancelled and once the entity will come back in your field of view, there will be not any material applied...

**Comment by robotboy655** [comment] 2019-10-06 13:39
Basically duplicate of https://github.com/Facepunch/garrysmod-issues/issues/3362

**Closed by robotboy655** 2019-10-06 13:39 UTC

**Comment by pilot22** [comment] 2019-10-06 17:31
This is not the same issue at all, but if you want;.....

**Comment by Kefta** [comment] 2019-10-06 17:36
It is the same:  the sub material is being reset because you are only changing it on the client, and when the server sends the client an update about that entity, the server's value overrides the client's.
