### ISSUE TITLE
Door closing sounds are broken for func_door and func_door_rotating in multiplayer.

### ISSUE THREAD

**Issue by Matt2468rv** [Facepunch/garrysmod-issues#1681] opened 2014-12-24 17:59 UTC
Door closing sounds specified in "func_door" and "func_door_rotating" entities function fine in single player, but are broken in multiplayer.  On any type of server, the doors make sound when they open, but are silent when closing, even with a closing sound specified.

**Comment by Matt2468rv** [comment] 2015-04-22 05:27
Is this issue simply going to be ignored? :(

It's definitely ruins the ambiance of a map as far as doors are concerned.  Very frustrating to mappers.

**Comment by robotboy655** [comment] 2015-04-22 09:44
Can you tell us at least some useful info, like the maps and positions for those doors?

**Comment by thegrb93** [comment] 2015-04-22 18:40
I don't know if this is related, or an issue caused by garrysmod, but prop_dynamic doors seem to suffer the same problem. I'll test on a hl2 map later and see if the combine doors make sound, but I know the door tool suffers from this problem.

**Comment by robotboy655** [comment] 2015-04-22 18:50
My door tool doesn't though.

**Comment by thegrb93** [comment] 2015-04-22 20:05
Is it this one? http://steamcommunity.com/sharedfiles/filedetails/?id=104479467

**Comment by robotboy655** [comment] 2015-04-22 20:06
Does it look like a someone with my avatar made it?

Mine is part of Half-Life 2 Tools, which is coded from scratch.

**Comment by thegrb93** [comment] 2015-04-22 20:08
Ahh sorry I should have mentioned it is specifically the combine doors that don't play sound. The rotating doors work fine though.

**Comment by robotboy655** [comment] 2015-04-22 20:13
You report addon bugs to addon authors, not here.

**Comment by thegrb93** [comment] 2015-04-22 20:14
I'll test it after class. I remember prop_dynamic playing animation sounds so I think there is a bug here.

**Comment by robotboy655** [comment] 2015-04-22 20:16
They still do. Stop wasting everyone's time, again.

**Comment by Matt2468rv** [comment] 2015-04-22 22:48
My map ttt_nuclear_power_b2 is experiencing this bug, but it's been confirmed by others I've talked to with other maps.

Link to my map: http://steamcommunity.com/sharedfiles/filedetails/?id=133138700

Here are my settings for a func_door and func_door_rotating in my map:

![func_door](https://cloud.githubusercontent.com/assets/7517366/7287063/eae35154-e916-11e4-9b8c-d49cd8b9c197.jpg)

![func_door_rotating](https://cloud.githubusercontent.com/assets/7517366/7287068/f4c944a8-e916-11e4-8cd9-d11a3d620895.jpg)

The func_door settings are from one of the double sliding doors, and the func_door_rotating settings are from one of the rotating doors that make up the floor of the reactor T trap.  The doors make sound when they open, but not when closing.  I've also tried adding a "start close sound" to the doors to no effect.  This issue didn't happen when I released my map but now it does.

**Comment by thegrb93** [comment] 2015-04-22 23:31
I've found that models/combine_gate_vehicle.mdl doesn't have any sound in its animation so no bug.

**Comment by Matt2468rv** [comment] 2015-04-23 01:07
This issue isn't even about prop_dynamic...

**Comment by robotboy655** [comment] 2015-04-23 16:12
There's no way this issue "didn't happen" before, neither there is a way that this doesn't happen in other Source Engine multiplayer games.

The problem is that the door moves into the map, and as a result, the door attempts to play the sound from a position player can't hear it. The weird part is multiplayer/singleplayer inconsistency.

![image](https://cloud.githubusercontent.com/assets/3299036/7301626/a11cce02-e9ec-11e4-9ca8-4e5e55f965b1.png)

The door origin must be in a visible to player spot for the player to hear the sounds from.

**Comment by robotboy655** [comment] 2015-04-23 16:17
Not weird at all, the sound filter just adds all players regardless of whether they should hear the sound or not.

**Comment by Matt2468rv** [comment] 2015-04-23 18:25
Even if it seems implausible, I'm pretty certain the issue "didn't happen" when I released the map.  I beta tested it thoroughly before releasing it a couple years ago and would have easily noticed the issue.  After a Gmod update (no idea which one) I noticed this issue when playing TTT on my map.

But the player visibility thing is something I certainly haven't heard of before.  It still makes me wonder why it's different in singleplayer vs multiplayer though.  I'll try moving the origin of the doors to a spot always visible to the player when I have time today and I'll get back to you.

Really appreciate your input by the way, thank you.

**Comment by Matt2468rv** [comment] 2015-04-23 18:54
I moved the origins to a location where they are visible in both the open and closed position and am still experiencing the same issue.  That doesn't appear to be the problem.

Here's a screenshot showing the origins in the open position:

![door_origins](https://cloud.githubusercontent.com/assets/7517366/7304944/09338bca-e9c0-11e4-976e-fb5eeac6ef67.jpg)

**Comment by robotboy655** [comment] 2015-04-23 19:27
https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/recipientfilter.cpp#L266-L275

This is why it works in singleplayer and not multiplayer.

The origin of the door must be the very edge that is visible when the door is fully open. You can see this foe yourself by opening the door and moving it to a room before it auto closes. You will hear the sound when you take the door out of position, but not when it is in position.

**Comment by robotboy655** [comment] 2015-04-23 19:31
I am not closing this because I am considering forcing the sounds to play on every player, or switching from PAS to PVS. We will see.

**Comment by Matt2468rv** [comment] 2015-04-23 20:42
I can confirm that moving the door into the room and letting it close plays the sound.  However I'm still having the issue even when I have the edge of the door visible and the origins set to the edge as seen here:

![door_bug_2](https://cloud.githubusercontent.com/assets/7517366/7307022/230a36e8-e9cf-11e4-9ced-1f3559dc55c2.jpg)

**Comment by Matt2468rv** [comment] 2015-04-23 20:57
If you could force the sounds to play on every player or if PVS would fix it, that would be wonderful.

I feel that this issue isn't something mappers should necessarily have to think about when creating doors.  Most mappers wouldn't even notice this problem because most of the testing is done in singleplayer.  It's a bit odd to create a map and have the map itself act differently in singleplayer vs. multiplayer.

Also, some doors simply cannot be created in a way that would avoid this issue.  For example, the func_door_rotating entities that make up the opening floor of the upper circular lab in my map are experiencing this issue and cannot be built another way.  And modifying the sliding doors has not fixed the issue thus far.

I appreciate you looking into this and also clearing up why it happens in multiplayer and not singleplayer.  That had me stumped for awhile.

**Comment by Matt2468rv** [comment] 2015-05-02 22:12
Any chance the fix for this could make it into the next update?

Now that ambient_generic is fixed this is the very last bug I'm experiencing with my map.  Which is essentially a bug with Garry's Mod since most maps that use sliding doors have them recede into walls.

**Comment by JohnOakman** [comment] 2016-03-21 18:07
Please have a solution for this, it's very disturbing that in my servers I can't hear the door closing sound of my own maps.

Also, the Opened sound isn't working (not the opening sound), so that makes 2 problem: 
Closing Sound et Opened sound (opening sound and closed sound work)

**Closed** 2016-03-21 19:17 UTC

**Comment by Matt2468rv** [comment] 2016-04-26 01:43
@willox Is there a reason this was closed?  I don't believe it's been fixed yet.

@robotboy655 I know you mentioned a way of fixing this issue, but has anything been done with it yet?

**Comment by robotboy655** [comment] 2016-04-26 11:01
It was fixed in Dev and Pre release branches.

**Comment by Matt2468rv** [comment] 2016-04-27 17:58
Great, thank you!!!  I now see it listed in the next update changelog!
