### ISSUE TITLE
Asking FastDL for maps after mounted via GMA

### ISSUE THREAD

**Issue by stickz** [Facepunch/garrysmod-issues#3162] opened 2017-04-23 19:37 UTC
### Details
When a BSP is mounted using a GMA file in loading, the client will still ask for the same map from FastDL. The only way to avoid this issue is to force a workshop subscription, so the map mounts before loading.

### Steps to reproduce
Use an if statement to mount the map during server initialize.
```
if game.GetMap() == "mor_chemical_labs_b3_re" then
	resource.AddWorkshop("658240507") -- mor_chemical_labs_b3_re
end
```

**Comment by robotboy655** [comment] 2017-04-23 20:25
Duplicate of #2951

**Closed by robotboy655** 2017-04-23 20:25 UTC
