### ISSUE TITLE
DTextEntry:AllowInput( string char ) didn't update when using BackSpace, Ctrl+V, Ctrl+Z.

### ISSUE THREAD

**Issue by MostRush** [Facepunch/garrysmod-issues#3861] opened 2019-05-21 18:03 UTC
### Details
On Gmod Wiki (https://wiki.garrysmod.com/page/DTextEntry/AllowInput) says: _Called whenever the value of the panel has been updated (whether by user input **or otherwise**)._

But actually when i use BackSpace, Ctrl+V, Ctrl+Z... the function does not work unlike OnTextChanged.

### Steps to reproduce
`DTextEntry.AllowInput = function( self, value )
        print("check")
 end`

enter in DTextEntry field, and press above listed keys.

**Comment by robotboy655** [comment] 2019-05-21 18:43
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/2756

**Closed by robotboy655** 2019-05-21 18:43 UTC
