### ISSUE TITLE
Welding entities to world no longer weld them to gmod_anchor, but weld directly to worldspawn instead

### ISSUE THREAD

**Issue by DBotThePony** [Facepunch/garrysmod-issues#5023] opened 2021-08-06 03:54 UTC
### Details
I don't know how long it is an issue, at least for 1 year it is sure an issue, but i couldn't think that the root cause is *this*.

I had several players complaining that when they dupe their props, they happen to also dupe someone else's. And when pasting them, they happen to be "constrained" to other's and both or more players end up being unable to interact with their contraptions (because prop protection disallows them to).

The underlying issue is, in fact, welding stuff to world directly, which make `constraint.GetAllConstrainedEntities` report false data:
![browser_8j6XwwxepW](https://user-images.githubusercontent.com/6339511/128453307-4090f342-f8b1-4a00-a80b-91fc1a45fff3.png)
![gmod_TzCE974ekz](https://user-images.githubusercontent.com/6339511/128453141-cef7f982-eabc-4f03-939a-7a8afaafe1b7.png)

...driving mine (and other) prop protections crazy:
![unknown (7)](https://user-images.githubusercontent.com/6339511/128453367-fc5e7a6d-e8b9-4f92-92f7-7fe9e68a5a04.png)
![gmod_UDJotsIL0b](https://user-images.githubusercontent.com/6339511/128458733-dcef04c8-8bf9-4a4b-b726-fea3c859c939.png)

...make toolgun `remover` delete everyone's props also welded to map:
https://github.com/Facepunch/garrysmod/blob/669d95b027dc319c88cf6679f202143325eec853/garrysmod/gamemodes/sandbox/entities/weapons/gmod_tool/stools/remover.lua#L70

### Steps to reproduce
0. Load up map
1. Spawn a prop, or several props
2. Weld them to map
3. Right click with remover on one of them or `PrintTable(constraint.GetAllConstrainedEntities(Entity(<>)))
4. ??????????????????????????

**Comment by Mista-Tea** [comment] 2021-08-06 04:16
Can confirm this issue, vanilla sandbox as well. 

My community discovered this in the last few months due to a specific tool using `constraint.GetTable(Entity)` to get constraints, which actually ended allowing said worldspawn-constrained entities to be duped by players that don't own the props (according to prop protection).

I made a naive workaround by modifying `constraint.GetTable()` line 1601 from
```lua
if ( con[ "Ent"..i ] && ( con[ "Ent"..i ]:IsWorld() || con[ "Ent"..i ]:IsValid() ) ) then
```
to

```lua
if ( con[ "Ent"..i ] && ( !con[ "Ent"..i ]:IsWorld() || con[ "Ent"..i ]:IsValid() ) ) then
```

Thereby excluding worldspawn from the results.

I wanted to reach out to other sandbox servers to see if the issue was stemming from my own code or from GMod itself, and was able to confirm it happen to one other major sandbox community. Time moved quickly and I forgot to report it though, so thanks for creating the issue :)

**Comment by Mista-Tea** [comment] 2021-08-06 04:20
https://i.gyazo.com/4803c9fc2a6158082071431469ae3d7a.gif

**Comment by robotboy655** [comment] 2021-08-06 10:25
I am fairly certain the problem is caused by this, and not any behavior change with the Weld tool (of which there were none):
https://github.com/Facepunch/garrysmod/commit/f9d774f2e4a4492de406b42424fc86b4e438c491

The point of that fix is to fix stuff like ropes not saved by gm_save when both ends are attached to world.
Obviously it has some unforeseen consequences.

**Comment by robotboy655** [comment] 2021-08-06 11:21
Should be fixed with https://github.com/Facepunch/garrysmod/commit/90be47f0cf76f5b069c09db3ab1c41ea2cbf1dc4

**Closed by robotboy655** 2021-08-06 11:21 UTC
