### ISSUE TITLE
Microphone doesn't work in Chromium.

### ISSUE THREAD

**Issue by Jetaime-Alexandria** [Facepunch/garrysmod-issues#5517] opened 2023-07-10 21:16 UTC
When-ever I'm using the `x86-64 - Chromium + 64 bit binaries ` Microphone doesn't pick up at all in Garry's Mod, I've adjusted Steam Voice Settings & everything and doesn't works. 

But when I leave the beta and switch to `None`, my microphone starts working, however my game tends to crash after a few minutes, so to avoid crashing and having gameplay issues, I have to use the Chromium beta. 

I've also tried different headsets, even a USB headset & Analog Headset, still same issue when in Chromium Beta, this issue only started to occur when the **April 2023 Patch** released.

**Comment by robotboy655** [comment] 2023-07-10 21:24
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5353

**Closed by robotboy655** 2023-07-10 21:24 UTC
