### ISSUE TITLE
Material system reload breaks RTs and custom mats

### ISSUE THREAD

**Issue by Dalenmar** [Facepunch/garrysmod-issues#4607] opened 2020-07-31 07:16 UTC
So I'm having the problem with source engine material system.
When it's reloading, all my custom textures and rts are being corrupted.

I'm constantly rendering a render target on the screen. Here's the example code:

```
local rt_tex = GetRenderTarget('TOPKEK',512,512)
local rt_mat = CreateMaterial('TOPKEK','UnlitGeneric',{['$basetexture']=rt_tex:GetName(),['$translucent']=1,['$vertexalpha']=1,['$vertexcolor']=1})

render.PushRenderTarget(rt_tex)
	cam.Start2D()
	render.Clear(0,0,0,0)
		-- RENDER HERE
	cam.End2D()
render.PopRenderTarget()

render.SetMaterial(rt_mat)
render.DrawScreenQuadEx(0,0,ScrW(),ScrH())

```
The issue I'm experiencing is material system restart.
When you open source engine related software (such as Hammer Editor or HLMV), or just change gmod graphics settings, the material system is being reloaded, or whatever it does.
After the reload my RT becomes black. All custom materials I create with "CreateMaterial" also becomes missing (pink), but "ITexture:IsErrorTexture()" and "IMaterial:IsError()" return false.

I can control video settings change with "GM:OnScreenSizeChanged" hook. But still, when running Hammer, the issue is here.

![hl2_GtjW2SBEOi](https://user-images.githubusercontent.com/28352937/89010198-c836d780-d316-11ea-912c-58fa19ae7b37.png)

**Comment by robotboy655** [comment] 2020-07-31 13:44
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/3811

**Closed by robotboy655** 2020-07-31 13:44 UTC
