### ISSUE TITLE
model animation error

### ISSUE THREAD

**Issue by Pop4484** [Facepunch/garrysmod-issues#5114] opened 2021-12-15 15:53 UTC
trying to play an animation but i get this error

Warning! 'player/chell/headless_player.mdl' animation requested bone 80, but model only has 55! (x20)

in sp_a4_finale04.bsp when trying to press the button

**Comment by robotboy655** [comment] 2024-07-04 16:37
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5218

**Closed by robotboy655** 2024-07-04 16:37 UTC
