### ISSUE TITLE
Sun and glow issues

### ISSUE THREAD

**Issue by CyberOne25** [Facepunch/garrysmod-issues#4032] opened 2019-10-20 14:35 UTC
If you look directly at the sun, it will disappear. But not just at one vector. In a 2D skybox however, this issue is not the case (very little at least). Normal glows also don't have this issue. The error should be in c_pixel_visibility.cpp (Source SDK, I obviously don't know the source code of gMod). Something is wrong with the pixel visibility tests, which seem to be used for the Update(Sky)GlowObstruction void func, which sets values for obstruction which are then used to draw the sprite. There shouldn't be any problems with the vectors I think. Also, glows don't work with mirrors. If you have a mirror in which you should see the glow but don't see it directly, it doesn't glow. But if you see it directly and see it in the mirror as well, it glows in the mirror. This is a very hard bug to fix tho in my opinion. Anyways, the more important bug is the sun bug. Hope this gets fixed soon. Thanks!

**Comment by robotboy655** [comment] 2019-10-20 14:56
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/3705 and you know it.

**Closed by robotboy655** 2019-10-20 14:56 UTC

**Comment by CyberOne25** [comment] 2019-10-20 15:12
This is a more detailed version about it, I'm just trying to help! The other one is also 10 months old, so I wanted to keep this bug up to date. Also, explanation of the bug in that other one might be misleading a little bit. I know there shouldn't be duplicates. What now? Do I have to write this as an answer in the other one? But it's very low on the list though.

**Comment by robotboy655** [comment] 2019-10-20 15:41
Please read the readme of this repo. Only do one bug report per issue. If you have more info on a bug, you add it to an existing bug report if there is one. This is not a forum, this is a bug tracker. How old an issue is has no bearing on the order of stuff that will be looked into next. There's also always the ability to 👍 the issues you want fixed the most.

**Comment by CyberOne25** [comment] 2019-10-20 16:02
Alright thx!
