### ISSUE TITLE
Script errors on lua-refresh

### ISSUE THREAD

**Issue by stickz** [Facepunch/garrysmod-issues#3163] opened 2017-04-23 21:52 UTC
Every time I change a Lua file and it goes through the refresh process, there's always the same script error: `unexpected symbol near '<eof>'`  This isn't an actual error with the file, it happens due to refreshing.

Example:
```
[ERROR] gamemodes/morbusgame/gamemode/client/cl_workshop.lua:64: unexpected symbol near '<eof>'
  1. unknown - gamemodes/morbusgame/gamemode/client/cl_workshop.lua:0
```

**Comment by Kefta** [comment] 2017-04-23 21:58
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/2996

**Closed** 2017-04-23 22:04 UTC
