### ISSUE TITLE
Entity:AddEffects + Entity:DrawModel crash

### ISSUE THREAD

**Issue by Be1zebub** [Facepunch/garrysmod-issues#5381] opened 2023-01-07 14:03 UTC
### Details
`Entity:AddEffects(EF_BONEMERGE)` + `Entity:DrawModel()` cause crash.

### Steps to reproduce
if you comment Entity:AddEffects or Entity:DrawModel, crash will not happen.
```lua
local test = ClientsideModel("models/eft_modular/gear/helmets/ops_core_fast_tan.mdl")
test:SetParent(LocalPlayer(), 0)
test:AddEffects(EF_BONEMERGE)
test:SetNoDraw(true)
test:DrawShadow(false)
test:DestroyShadow()
test:SetNotSolid(true)

hook.Add("PostPlayerDraw", "test", function(ply)
	test:DrawModel()
end)
```

**Comment by robotboy655** [comment] 2023-01-07 16:23
You are creating an infinite loop - by drawing the bonemerged model it draws the player, which calls the hook again, which draws the bonemerged model, etc.

Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/1558

**Closed by robotboy655** 2023-01-07 16:23 UTC
Labels: Crash
