### ISSUE TITLE
Crash rendering a mesh build multiple times on Linux/OpenGL

### ISSUE THREAD

**Issue by Sevii77** [Facepunch/garrysmod-issues#4592] opened 2020-07-19 21:10 UTC
### Details
Rendering a mesh build multiple times with mesh.Begin results in a crash on Linux/OpenGL.
Just building multiple times won't result in a crash.

> x86-64 - Chromium + 64-bit binaries:
gmod_mcore_test 1 = crash to desktop
gmod_mcore_test 0 = crash to desktop

> Default:
gmod_mcore_test 0 = crash with engine error:
	failed to lock index buffer in CMeshDX8::LockIndexBuffer

[Dump File](https://sevii.dev/file/2020/07/19/z011ce7m.dmp)

### Steps to reproduce
Code:
```lua
local m = Mesh()
mesh.Begin(m, MATERIAL_LINES, 1) mesh.Position(Vector(0)) mesh.AdvanceVertex() mesh.Position(Vector(1)) mesh.AdvanceVertex() mesh.End()
mesh.Begin(m, MATERIAL_LINES, 1) mesh.Position(Vector(2)) mesh.AdvanceVertex() mesh.Position(Vector(3)) mesh.AdvanceVertex() mesh.End()

hook.Add("PostDrawOpaqueRenderables", "", function()
	m:Draw()
end)
```

**Comment by robotboy655** [comment] 2024-03-26 00:07
I am not experiencing any crashes with provided code, but the issue may have been fixed last year, so I am closing this report.

If the issue is not fixed, feel free to let me know with some way to reproduce it.

**Closed by robotboy655** 2024-03-26 00:07 UTC
Labels: Platform: Linux, Crash
