### ISSUE TITLE
PhysicsInitMultiConvex Crash

### ISSUE THREAD

**Issue by CryptAlchemy** [Facepunch/garrysmod-issues#5229] opened 2022-05-29 00:49 UTC
### Details
Some players crash when loading into my server. Was using the collision resizer (advanced) tool which calls the `ENTITY:PhysicsInitMultiConvex` function. The exception that causes the crash is  caused by PhysicsInitMultiConvex, looks like, as per the crash dump (see attached).
The server is the on x86-64 beta branch of the game and the clients are on both the regular branch and the x86-64 branches of Gmod.

### Steps to reproduce
Using the collision resizer (advanced) on a model (it uses the `ENTITY:PhysicsInitMultiConvex` function).

[hl2_220317_crash_2022_5_28T22_5_34C0.zip](https://github.com/Facepunch/garrysmod-issues/files/8792412/hl2_220317_crash_2022_5_28T22_5_34C0.zip)

**Comment by robotboy655** [comment] 2024-03-26 18:34
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/4081

**Closed by robotboy655** 2024-03-26 18:34 UTC
Labels: Crash, Dependency: IVP
