### ISSUE TITLE
On the main/pause menu, letters type numbers if Caps Lock is disabled

### ISSUE THREAD

**Issue by cmdrneon** [Facepunch/garrysmod-issues#5158] opened 2022-02-04 22:06 UTC
### Details

When Caps Lock is disabled, typing into e.g. a Search box when searching maps/addons on the main menu instead types numbers/symbols (goes alphabetically, "a" types "1", "b" types "2" etc.)
Turning caps lock on fixes this, and you can type in lowercase, but not uppercase using Shift.
To type uppercase, you have to have Caps Lock OFF and hold Shift.

This doesn't seem to affect the in-game text chat.

Debian 11 Linux, x64 branch, Steam client Stable.

### Steps to reproduce

1. Open a menu (e.g. addons menu or map selection)
2. Type into a search box. It should type numbers (e.g. "a" types "1", "b" types "2" etc.)
3. Turn Caps Lock on. It should type normally this way
4. Turn Caps Lock off and type while holding Shift. You should be typing uppercase letters.

**Comment by robotboy655** [comment] 2022-02-05 01:31
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/4464

**Closed by robotboy655** 2022-02-05 01:31 UTC
Labels: Duplicate, Platform: Linux
