### ISSUE TITLE
ents.CreateClientProp Lose Parent on Full Update

### ISSUE THREAD

**Issue by Hazbelll** [Facepunch/garrysmod-issues#4507] opened 2020-05-16 22:09 UTC
### Details
*Game Version: `200511`*
*Game Branch: `x86-64`*

Props created via [`ents.CreateClientProp`](https://wiki.facepunch.com/gmod/ents.CreateClientProp) that are parented to an entity lose their parent if a full update is sent to the client.

**Note:** Seems if the parent was a `player`, the clientside model will have its position reset to `0, 0, 0`, however if it was *not* a `player`, its position remains what it was prior to being de-parented, at least when testing it parented to an `npc_citizen`.

### Steps to reproduce
1. Enable `sv_allowcslua`.
2. Create a Clientside Prop and Parent it to the `LocalPlayer` (Or another Entity if desired):
```lua
lua_run_cl local ply = LocalPlayer() local ent = ents.CreateClientProp() ent:SetModel("models/props_c17/furnitureStove001a.mdl") ent:SetPos(ply:GetPos()) ent:SetParent(ply) ent:Spawn()
```
3. Enable `sv_cheats`.
4. Run `cl_fullupdate` *OR* `net_fakeloss 100` for a few seconds before resetting it to `0`.

**Comment by robotboy655** [comment] 2020-05-18 17:14
Essentially duplicate of https://github.com/Facepunch/garrysmod-issues/issues/861

**Closed** 2020-07-01 03:28 UTC
