### ISSUE TITLE
Player.GetFOV returns int on server and float on client

### ISSUE THREAD

**Issue by meepen** [Facepunch/garrysmod-issues#2474] opened 2016-02-24 19:42 UTC
This messes up a lot of prediction.

**Comment by robotboy655** [comment] 2016-02-25 13:12
What prediction errors are you getting? Are they Lua caused or not?

**Comment by meepdarknessmeep** [comment] 2016-02-25 16:28
They are caused by trying to SetFOV in a swep, and testing if the fov is equal to what you set it to. For example, if you try to recreate the CSS AWP, which uses SetFOV and GetFOV to test if it is scoped, or which state of scoping it's in.

**Comment by robotboy655** [comment] 2019-10-24 17:39
Should be fixed on Dev.

**Closed by robotboy655** 2019-10-24 17:39 UTC
