### ISSUE TITLE
Skybox renders map particles/effects when it shouldn't.

### ISSUE THREAD

**Issue by mrwallace888** [Facepunch/garrysmod-issues#5430] opened 2023-03-27 19:25 UTC
Been bothering me for a long time. I don't know if it's a Source limitation, though, because I can't recall seeing this on any other Source games. But it's likely due to skybox placement on those other games.

When maps have their skyboxes located beneath the map, such as gm_flatgrass, anything in the map that emits particles/effects, such as light flares, physgun glow, explosions, etc., you'll see it being rendered up in the sky. Hence what I said earlier, it's possible this problem is on all Source games, but other game maps don't have their skybox underneath the map, which might be why you never see it. Like if you loaded a map up in TF2 or CS:GO, for example, with a map where the skybox was below the map, would it still render particles in the sky?

It's been an issue for ages. I mean it's not like you look up and see the entire map being rendered in the skybox, so skyboxes are good about that. But I don't understand why particles and effects are different, and why it wants to render them anyways.

I mean I remember playing with G-Bombs in 2013 on flatgrass and always being annoyed by how when my bombs exploded, I saw double effects, one on the ground, and then a duplicate up in the sky.

You can even look up in the sky in flatgrass and see your physgun glow.

It often grew a little irritating when playing on certain maps, and any time I'd drive a simfphys vehicle, or an scars vehicle, or other mods like that, as I was driving I would see a pair of headlight and taillight flares from my car hovering in the sky.

Is there no way to fix this (besides dodgy solutions such as turning off the 3D skybox entirely or disabling effects)? Is this a limitation of the Source engine?

Examples:
![image](https://user-images.githubusercontent.com/39398330/228045664-0b58bb1f-523c-4b26-9fda-4d096771a5d8.png)
![image](https://user-images.githubusercontent.com/39398330/228045687-12d1b362-80f0-46fc-ba1d-36aede0729a7.png)

**Comment by robotboy655** [comment] 2023-03-27 20:58
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5386

**Closed** 2023-03-27 20:58 UTC

**Comment by mrwallace888** [comment] 2023-03-31 22:18
Well the other one got buried and I didn't know what else to do. I'll see many issues get instantly noted but any time I ever make an issue it just gets lost immediately.

**Comment by Kefta** [comment] 2023-03-31 22:42
It can be located thru search terms.
