### ISSUE TITLE
game.GetMapVersion() returns the wrong number

### ISSUE THREAD

**Issue by grande1900** [Facepunch/garrysmod-issues#5351] opened 2022-11-09 17:53 UTC
### Details
The lua function `game.GetMapVersion()` returns the wrong number.

### Steps to reproduce
Run `print(game.GetMapVersion())`

![image](https://user-images.githubusercontent.com/54255077/200903242-95b809fe-511b-4ca4-a6f5-3fb83b9bd6ae.png)
test on gm_construct, which has map version 20
### Temporary fix
Use `string.byte(file.Read("maps/"..game.GetMap()..".bsp","GAME")[5])`

![image](https://user-images.githubusercontent.com/54255077/200903890-ab23eae8-af2c-4b1f-ad94-d761c973b70a.png)
returns correct map version of 20

**Comment by grande1900** [comment] 2022-11-09 18:00
Duplicate of #5350

**Comment by robotboy655** [comment] 2022-11-09 18:32
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5350

**Closed by robotboy655** 2022-11-09 18:32 UTC
