### ISSUE TITLE
Random Addons being enabled + Old addons being on top of the newly subbed list

### ISSUE THREAD

**Issue by reaperTheBoi** [Facepunch/garrysmod-issues#5709] opened 2024-01-26 15:36 UTC
### Details
Along with random addons being enabled
my entire addon menu is messed up
originaly i had newly downloaded addons at the top, but now its jumbled and i see addons that i've installed like 2 years ago and never used again at the top of my subbed list

### Steps to reproduce
i have no clue how to replicate it, but if its any help, i had to use my old laptop for a bit due to my pc being in repair
I didn't touch gmod on my laptop, i actually deleted it.

![image](https://github.com/Facepunch/garrysmod-issues/assets/86563517/95dc0e4e-3c96-4c11-b397-b6de9bac2523)

![gmod 2024-01-26 16-33-29](https://github.com/Facepunch/garrysmod-issues/assets/86563517/5848d873-6b38-445f-8711-bc0b283435c8)

**Comment by robotboy655** [comment] 2024-01-26 15:46
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5663

The addon order is exactly as you have set it in your Steam Workshop mount order:
![image](https://github.com/Facepunch/garrysmod-issues/assets/3299036/e4cee2ee-5c80-4de9-b8a5-c13c6b82016b)

As for the "Addons enabling themselves" issue, are you sure it still happens to you on the `x86-64` beta in the last day or so?

**Closed by robotboy655** 2024-01-26 15:46 UTC

**Comment by reaperTheBoi** [comment] 2024-01-26 15:55
> Duplicate of #5663
> 
> The addon order is exactly as you have set it in your Steam Workshop mount order: ![image](https://private-user-images.githubusercontent.com/3299036/300033386-e4cee2ee-5c80-4de9-b8a5-c13c6b82016b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyODQ3MjIsIm5iZiI6MTcwNjI4NDQyMiwicGF0aCI6Ii8zMjk5MDM2LzMwMDAzMzM4Ni1lNGNlZTJlZS01YzgwLTRkZTktYjhhNS1jMTNjNmI4MjAxNmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjZUMTU1MzQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWJlODk1Y2ExMGFjMDE4MGU4NzE5OWFkOTAwMDBhMjI4Mzg1YzkwNjQxM2RhODM0OGNmNWIzMmZlYjkyNTQ4ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.s0CdCJpc6sF1SYBTYBJiHuAl3i_BxQ0YJecCXlw0_1c)
> 
> As for the "Addons enabling themselves" issue, are you sure it still happens to you on the `x86-64` beta in the last day or so?

Yes it has, i jsut started gmod not long ago
also, how the hell do i get the gmod workshop to stay like that when i load in the game, it changes back into load order

**Comment by robotboy655** [comment] 2024-01-26 16:02
What does " i just started gmod not long ago" mean exactly?

Also I am really not sure what you are asking with "how the hell do i get the gmod workshop to stay like that when i load in the game, it changes back into load order".

**Comment by reaperTheBoi** [comment] 2024-01-26 16:13
Ok lemme explain
I started gmod today like 3 hours ago, i had old addons randomly enabling themselves that i didn't touch for a long while 
Example: i didn't have LFS: Apache enabled, and when i enterd the game, i suddenly had it enabled, even though LFS no longer exists

And the workshop thing changes from "date subscribed" back to "load order" (it would be a pain to set everything by hand due to having 3k addons)

**Comment by robotboy655** [comment] 2024-01-26 16:38
When exactly does the "addon enabling itself" issue happen? On game start up? Or map load? Is this something you can reproduce?

Can you please email me your Steam logs? (`C:\Program Files (x86)\Steam\logs` folder by default) My email can be found in my GitHub profile. Just put the folder into a zip archive and send it my way.

As for the order of this, this is more of a complaint to Valve, as it is a new Steam feature, we have nothing to do with it.
