### ISSUE TITLE
WE CAN'T DOWNLOAND DUPES FROM WORKSHOP

### ISSUE THREAD

**Issue by AssassinLordOmega** [Facepunch/garrysmod-issues#2952] opened 2016-12-06 17:43 UTC
actualy no one can acces dupes from workshop only if he is in gmod and downloanding from gmod dupes searcher i want  you to fix it beacuse i want to search dupes too

(maybe better version)
i can't acces dupes from work shop(only i can in gmod)
but when i'm searching and downloand dupe that i want i'm looking in gmod and dis says
"No addon unsubscribing" so please ifx it

to reproduce it

step 1 go to steam workshop

step 2 subscribe and dupe

step 3 go in gmod

step 4 just open the fucking console now and there is red text

fix it asap!

**Comment by AssassinLordOmega** [comment] 2016-12-06 17:44
how to install dupe with other softwares https://www.youtube.com/watch?v=opEj1dc_6F4

**Comment by AssassinLordOmega** [comment] 2016-12-06 17:44
this is the only way i can downloand an dupe

**Comment by robotboy655** [comment] 2016-12-06 18:12
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/1734

**Closed by robotboy655** 2016-12-06 18:12 UTC
