### ISSUE TITLE
Problems displaying textures in hammer

### ISSUE THREAD

**Issue by MARK2580** [Facepunch/garrysmod-issues#4054] opened 2019-11-08 15:39 UTC
![FCEWMFPK6m](https://user-images.githubusercontent.com/11617079/69460270-bf076b00-0d84-11ea-8411-5e192ce011c6.png)
![MDcdXKbrkn](https://user-images.githubusercontent.com/11617079/69460274-c2025b80-0d84-11ea-94f8-60ebd2d41073.png)

### Details
With the last update for November, a big problem appeared, most of the textures (even standard ones) are not displayed correctly, as if they were reduced by 2 times in the "shaded" mode. If you switch to the "3D textured" mode there is no such problem, but the perception of the world is very difficult.

**Comment by Python1320** [comment] 2019-11-16 17:58
You can start removing things to find the minimal thing that still causes the bug. Then generally your project will stay safe and robotboy doesn't have to do this task to reduce the possibilities.

**Comment by MARK2580** [comment] 2019-11-22 21:01
> You can start removing things to find the minimal thing that still causes the bug. Then generally your project will stay safe and robotboy doesn't have to do this task to reduce the possibilities.

This is another @robotboy655 fault after trying to fix squares on reflective textures. There is no such problem if you select "3D Textured".

**Comment by robotboy655** [comment] 2019-11-22 21:38
I cannot reproduce this, so you will either need to provide the map file or I can't do anything.

**Comment by MARK2580** [comment] 2019-12-18 02:11
@robotboy655   
Looks like I figured out what the problem is. This is the $ basetexturetransform parameter. Depending on the scale parameter, a “repetition” of neighboring textures appears on the brush. It’s hard to explain, but here are 2 screenshots of the example. So I also put in a map example on which it is seen that even the standard tile from hl2 is "buggy".

[BUG_basetexturetransform.zip](https://github.com/Facepunch/garrysmod-issues/files/3976295/BUG_basetexturetransform.zip)

![E6MIvp4NYi](https://user-images.githubusercontent.com/11617079/71049689-3d70e600-2154-11ea-906e-24c9735c25f2.png)
![tfLhlfgoDr](https://user-images.githubusercontent.com/11617079/71049690-3d70e600-2154-11ea-9c51-f0fff4ab03c2.png)

**Comment by robotboy655** [comment] 2020-10-16 16:59
This should be fixed, and no it wasn't my fault and it wasn't related to the previous Hammer fix with the squares on reflective surfaces. This bug also happens in Half-Life 2's Hammer.

**Closed by robotboy655** 2020-10-16 16:59 UTC
Labels: Complexity: High, Shaders
