### ISSUE TITLE
Crash with physgun double reload unfreeze parented props after duplicated.

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#1170] opened 2014-06-04 05:02 UTC
If I paste a contraption that has parented props, it will crash when I push r with physgun.

https://dl.dropboxusercontent.com/u/72472980/parentcrash.mdmp

**Comment by thegrb93** [comment] 2015-01-25 22:30
Double tapping R for unfreeze-all also seems to how a lot of instances where a crash will occur.

**Comment by robotboy655** [comment] 2015-01-25 22:34
Most likely a physics crash, which we can't really properly deal with.

**Comment by thegrb93** [comment] 2015-01-25 22:38
It seems to happen when you have parented props. Mind taking a quick look at the result?
https://dl.dropboxusercontent.com/u/72472980/crash.mdmp

**Comment by robotboy655** [comment] 2015-01-25 22:49
Can you give me step-by-step way to reproduce this?

**Comment by thegrb93** [comment] 2015-01-25 22:56
It seems that if the prop is welded or nocollided, the crash doesn't happen.

Spawn two props with and run this e2.
```
findIncludePlayersProps(owner())
findByClass("prop_physics")
A=findToArray()
A[1,entity]:parentTo(A[2,entity])
```

Then dupe the two props and try unfreezing using r with the physgun.

Weirdly though, if I add 
```
weld(A[1,entity],A[2,entity])
```
I can't make the crash happen. I'm going to try with a different constraint and see what happens.

**Comment by thegrb93** [comment] 2015-01-25 23:02
The nocollide constraint doesn't prevent the crash. Something tells me that the physobject of the parented prop is doing something weird. The weld might be preventing it from crashing, but if there's nothing holding it, it goes off and causes a crash.

**Comment by thegrb93** [comment] 2015-01-25 23:11
The only way I can get it to crash is with the physgun double r tap.

**Comment by thegrb93** [comment] 2015-01-25 23:25
Normal duplicator doesn't save parents so I can't test that.

Advanced duplicator isn't able to unfreeze-all

Advanced duplicator 2 crashes on unfreeze-all

**Comment by thegrb93** [comment] 2015-01-25 23:29
Here's a gif of some weirdness with the shadow that happens after unfreezing the duplication in a non-crashing manner. Not sure if just graphical error or if there's something going on with the physics.
https://dl.dropboxusercontent.com/u/72472980/weird.gif

**Comment by thegrb93** [comment] 2015-01-25 23:36
Okay I just made a discovery.

If I unfreeze all of the duped entities with lua, then do the double-r tap with the physgun, it still crashes. I think there might be something wrong with the physgun.

**Comment by thegrb93** [comment] 2015-01-26 00:17
I tried it again without freezing anything and duping everything unfrozen. When I double tapped r, my game froze and didn't crash.

**Comment by thegrb93** [comment] 2015-01-26 00:20
If I freeze both props, parent them, then double-tap r with physgun, there's no crash. So there's something going on with the duplication stage.

**Comment by thegrb93** [comment] 2015-01-26 00:43
I have a pile of crash dumps after testing this. Want to see if they'll help find the bug?

**Comment by Jack37** [comment] 2015-01-26 07:50
I guess there's a pull request to fix this https://github.com/garrynewman/garrysmod/pull/834

**Comment by thegrb93** [comment] 2015-01-26 23:45
Awesome. I'll add the fix to my server until garrysmod updates.

**Comment by robotboy655** [comment] 2015-01-30 19:19
Something tells me that this is caused more by Adv. Dupe 2 than parents.

Neither of the 3 duplicators can copy the parented entity made with E2 because E2 does not provide proper duplicator support for its parenting function. But yes, internally it crashes in the physics engine which we cannot edit/fix.

I will merge the pull request once my question gets answered.

**Comment by thegrb93** [comment] 2015-02-01 03:10
You can use the advdupe2 "area copy" feature to duplicate the parented entity. Shift+Rightclick the world to initialize an area copy. You can also nocollide the parented entity with the parent entity and it'll duplicate normally with the parent.

**Comment by robotboy655** [comment] 2015-02-15 00:45
Fixed by https://github.com/garrynewman/garrysmod/commit/411e9872a5b96364def66f02551ee03c9c4652e9

**Closed by robotboy655** 2015-02-15 00:45 UTC
Labels: crash
