### ISSUE TITLE
Gmod addons sometimes randomly gets enabled. And GMAS are bugged up.

### ISSUE THREAD

**Issue by Dacatzgoescodin5267** [Facepunch/garrysmod-issues#5663] opened 2023-12-24 02:11 UTC
Details

- Some of the workshop addons that I disabled sometimes get re-enabled without my consent
- Gmod's issues say Clean out Unused Gmas even though the mod I installed is still there and treats that addon as deleted unable to be searched for and enabled 

How to replicate it (so far)

- Downloading any addons seems to cause the GMA bug to show up and sometimes enables random add-ons 
- Going out with the cleanup_gmas  seems to not work since it removes the gmas to that addon and the workshop doesn't reinstall it until you download a new addon which causes another set of GMAS to break and causes more addons to get enabled

People who called the bug out 

-  witness 1, https://steamcommunity.com/workshop/discussions/18446744073709551615/4031349199265616450/?appid=4000&tscn=1703378300
- witness 2 https://steamcommunity.com/app/4000/discussions/1/4034726433722919479/ (The earliest recounting of the bug and it seems to started after the December 15th update due to the security update.
- witness 3 https://www.reddit.com/gallery/18mjd60

Verdict: Major issue and needs to be fixed immediately.

Edit/more further reading, Someone said the security update  probably messed up the cloud save which causes the add-on enabled/disabled preferences to not get saved in the cloud.  Also the update causes Cloud to save issues (which i came across numerous times sometimes)

**Comment by Wiimeiser** [comment] 2023-12-24 07:16
I had this problem, too. Check your console for errors, specifically one about CreateQueryUserUGCRequest and GetNumSubscribedAddons are reporting different numbers, as seen here: https://steamcommunity.com/sharedfiles/filedetails/?id=3114375703

![20231218014647_1](https://github.com/Facepunch/garrysmod-issues/assets/54897542/7dc0c027-a58e-45ad-981d-6e18bf561a9d)

If so, your best bet is to unsubscribe from all your addons and see if that fixes it. You can back up your subscriptions by going to your subscriptions list and clicking "Save to collection". Then delete addonnomount.txt and run the game once just to make sure. That's more or less what I did, and it fixed my problem.

**Comment by Dacatzgoescodin5267** [comment] 2023-12-24 07:25
So its just trying to duplicate i see. And also i hope the devolopers fixes this

**Comment by ZeroFighter17** [comment] 2023-12-29 21:02
> I had this problem, too. Check your console for errors, specifically one about CreateQueryUserUGCRequest and GetNumSubscribedAddons are reporting different numbers, as seen here: https://steamcommunity.com/sharedfiles/filedetails/?id=3114375703
> 
> ![20231218014647_1](https://private-user-images.githubusercontent.com/54897542/292658930-7dc0c027-a58e-45ad-981d-6e18bf561a9d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4ODM4OTMsIm5iZiI6MTcwMzg4MzU5MywicGF0aCI6Ii81NDg5NzU0Mi8yOTI2NTg5MzAtN2RjMGMwMjctYTU4ZS00NWFkLTk4MWQtNmUxOGJmNTYxYTlkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDIwNTk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjMWQ3YThkNmQzNTU0MGRlM2I5YjA4NGUxZDY4YWUyMzI4YzQzNzFkY2QxZjAwNzQwNTAyNjNhNWJjYTJiNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WfoBEGxgcTbjqcYGSg1CaNdhgh0x5jWtDFCedDoQFZQ)
> 
> If so, your best bet is to unsubscribe from all your addons and see if that fixes it. You can back up your subscriptions by going to your subscriptions list and clicking "Save to collection". Then delete addonnomount.txt and run the game once just to make sure. That's more or less what I did, and it fixed my problem.

I just tried this and this worked...kinda, all it did was shaft more of my addons than it fixed. Out of 972, 950 are present while 22(I'm guessing) aren't working correctly thanks to the new "Security" update. They've gotta revert this update and undo the damage they've done. Nobody asked for this "extra security" anyway.

**Comment by robotboy655** [comment] 2024-01-04 14:21
I suspect Steam's new Workshop changes are causing these issues for you:
![image](https://github.com/Facepunch/garrysmod-issues/assets/3299036/4d7e27b3-0b36-4844-94e4-b40ecc0b79b8)

**Comment by Wiimeiser** [comment] 2024-01-05 14:35
Interesting update: I subscribed to this: https://steamcommunity.com/sharedfiles/filedetails/?id=2559948175

It didn't show up in the game's addon browser, and I had a lower number of addons in game than I did in the Steam client, more than just one (It reported 1337 ingame when I had 1340 subscribed on Steam proper), similar to what happened last month. Unsubscribing from it after reinstalling a preset's uninstalled addons appears to have fixed it, at least the desync. There are no signs of corruption, but I'll have to investigate further to see if things are truly fixed. 

If this particular addon is one that won't mount in game due to illegal files, then this supports my theory from before that the security unmounting was what caused my previous corruption.

**Comment by robotboy655** [comment] 2024-01-05 15:10
The workshop item you linked is a save, not an addon. It would never appear in the Addons menu. GMod separates these (Demos, Saves, Dupes) from actual addons, while the Steam read out does not.

**Comment by Wiimeiser** [comment] 2024-01-05 15:13
Ah, that makes sense, then. Though the fact that I still got an odd addon desync for a bit may or may not be related. Alternatively, it could have been because I was messing around with addons, since it appears one of the WoS components broke in the most recent update. Don't know what could have caused it this time...

**Comment by Dacatzgoescodin5267** [comment] 2024-01-07 22:44
> I suspect Steam's new Workshop changes are causing these issues for you: ![image](https://private-user-images.githubusercontent.com/3299036/294205322-4d7e27b3-0b36-4844-94e4-b40ecc0b79b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2Njc3NDEsIm5iZiI6MTcwNDY2NzQ0MSwicGF0aCI6Ii8zMjk5MDM2LzI5NDIwNTMyMi00ZDdlMjdiMy0wYjM2LTQ4NDQtOTRlNC1iNDBlY2MwYjc5YjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDdUMjI0NDAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yzk3MzU2YjU0Y2RjNGNjMjcwN2Y1MjcyNzk0NzE4NzM2MWJjYTExMmNlM2RlODcyNGJiYTI5NjA0ZGMwYTZiZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SAJA-DJVyLRU20mlcibAs_wHeczIs37Inhsh8h-h86U)

Will you hopefully try and fix it since it happened again and i aint reinstalling all the addons over that and i feel like i am this upset and will not play GMOD again if this issue is not fixed

**Comment by robotboy655** [comment] 2024-01-08 15:51
Reinstalling your addons is probably not going to help.

I am not sure what is happening on your ends, as it does not happen to me no matter what I try. As I said, I think the issue is with Steam Beta's updates. **So make sure your Steam client is up to date.**
![image](https://github.com/Facepunch/garrysmod-issues/assets/3299036/f390e8a2-b324-4bb7-a56e-3e7e8657140d)


Looking at the Steam Discussions in the Bugs section, I do not see a single mention of this issue during 2024.

**Comment by Dacatzgoescodin5267** [comment] 2024-01-11 20:36
> Reinstalling your addons is probably not going to help.
> 
> I am not sure what is happening on your ends, as it does not happen to me no matter what I try. As I said, I think the issue is with Steam Beta's updates. **So make sure your Steam client is up to date.** ![image](https://private-user-images.githubusercontent.com/3299036/294956981-f390e8a2-b324-4bb7-a56e-3e7e8657140d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMDU2NzEsIm5iZiI6MTcwNTAwNTM3MSwicGF0aCI6Ii8zMjk5MDM2LzI5NDk1Njk4MS1mMzkwZThhMi1iMzI0LTRiYjctYTU2ZS0zZTdlODY1NzE0MGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTFUMjAzNjExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTI1NGE1MWNiOTcxOTI5YzExNzQ4MDQ4NGY0Njc0OTJhZjFjOTlmNTliYWJiNjg1MzJhOGI1ODliMmI4ZTY1ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.znQBCMmdgb4DsjyA2PD_KgZGcDlDthu0yHLzTz1gOq4)
> 
> Looking at the Steam Discussions in the Bugs section, I do not see a single mention of this issue during 2024.
> 
> Any information on how to reproduce the issue would be appreciated, or at least a video or it or something.

But sir, theirs still reports https://steamcommunity.com/app/4000/discussions/5/7091547146188284325/ https://steamcommunity.com/app/4000/eventcomments/4031350479982227945/?tscn=1704932615

**Comment by robotboy655** [comment] 2024-01-11 21:43
Does it happen to you specifically, still? What exactly are you doing to make it happen?

**Comment by Dacatzgoescodin5267** [comment] 2024-01-11 22:38
> Does it happen to you specifically, still? What exactly are you doing to make it happen?

Doesn't happen often. Its probably due to you updating Gmod and its security updates

**Comment by robotboy655** [comment] 2024-01-12 11:31
I know it's cool to blame every problem you get on new updates and on me, but that's just not the case and is not helpful. If I didn't "trust the witnesses", I would've just closed this report a long time ago.

Either way, I cannot help you if you don't cooperate. I need to know how to reproduce the issue if I am to look into it. Or at the very least record a video of it happening or something.
The steps provided in the first post do not do anything on my end no matter how many times I repeated them.

**Comment by robotboy655** [comment] 2024-01-22 18:11
I am still not receiving much of useful information from affected people, but I have made some changes to the game to try to mitigate whatever Valve did to the other method of getting subscriptions.

At the very least, this new method should prevent addons in the in-game subscription list being duplicated, and work better with the new mount order/addon disabling feature in Steam, as well as be faster to get subscriptions when you have hundreds of them.

If you are affected by the duplication issue, or if you have addons enabling themselves somehow, please let me know if these new changes (available on x86-64 and `dev` betas) fix the issues for you or not.

**Comment by robotboy655** [comment] 2024-02-28 18:55
I have stopped hearing about this issue, so I can only conclude either my recent changes fixed it for you, or whatever Valve broke with Steam was fixed.

**Closed by robotboy655** 2024-02-28 18:55 UTC
Labels: Cannot confirm, Regression
