### ISSUE TITLE
Single player retry crashing game

### ISSUE THREAD

**Issue by auskfc** [Facepunch/garrysmod-issues#2299] opened 2015-12-02 03:24 UTC
On single player once the map has loaded I hit retry and it loads the little bar most of the way than freezes since it is clearly not going to work it crashes on me when I hit escape to cancel.

I would attach a crash file but "Unfortunately, we don’t support that file type." so I am going to attach a txt file. If you need any more information just let us know.

Also I have tried both deleting local game content and deleting the gmod files to fix the problem.

[hl2_150913_crash_2015_12_2T3_5_44C0.txt](https://github.com/Facepunch/garrysmod-issues/files/49354/hl2_150913_crash_2015_12_2T3_5_44C0.txt)

**Comment by auskfc** [comment] 2015-12-02 03:31
This has been talked about on the forums but clearly nothing was done about it https://facepunch.com/showthread.php?t=1495153&highlight=retry+crash

**Comment by robotboy655** [comment] 2015-12-02 09:26
This crash is already fixed in the next update and is caused by you having too many addons installing and hitting the 8000 .lua file limit. ( Which is again, removed in the next version )

You can try out the next version of the game by switching to Dev branch:
http://wiki.garrysmod.com/page/Dev_Branch

**Closed by robotboy655** 2015-12-02 09:26 UTC
