### ISSUE TITLE
The Stanley Parable maps uses Portal 2 entities that don't exist in the game

### ISSUE THREAD

**Issue by siobhan-saoirse** [Facepunch/garrysmod-issues#6075] opened 2024-11-14 21:54 UTC
### Details

When launching "map1", I get several errors about nonexistent entities.
```
Attempted to create unknown entity type linked_portal_door! (x8)
Attempted to create unknown entity type logic_playmovie!
Attempted to create unknown entity type linked_portal_door! (x11)
Attempted to create unknown entity type trigger_still! (x7)
Attempted to create unknown entity type linked_portal_door! (x5)
Attempted to create unknown entity type env_instructor_hint!
Attempted to create unknown entity type linked_portal_door!
Attempted to create unknown entity type logic_playmovie!
Attempted to create unknown entity type linked_portal_door!
Attempted to create unknown entity type logic_script!
Attempted to create unknown entity type linked_portal_door! (x7)
Attempted to create unknown entity type vgui_movie_display!
Attempted to create unknown entity type linked_portal_door! (x8)
```
### Steps to reproduce

1. Launch map1.
2. Check console for errors.
3. Several messages involving various Portal 2 entities will be shown.

**Comment by robotboy655** [comment] 2024-11-15 02:48
Many mountable games require entities that are not supported by Garry's Mod.

This is effectively a duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1283

**Closed by robotboy655** 2024-11-15 02:48 UTC

**Comment by siobhan-saoirse** [comment] 2024-11-15 03:28
O
