### ISSUE TITLE
Menu freezes upon opening mounted games list.

### ISSUE THREAD

**Issue by Jookia** [Facepunch/garrysmod-issues#86] opened 2013-06-10 07:28 UTC
Clicking the mounted games list in the menu makes the GUI unresponsive, but still active.

**Comment by Gekazoid** [comment] 2015-01-27 02:05
When do you plan to fix this issue, any news?

**Comment by Bo98** [comment] 2015-01-27 07:47
Awesomium hasn't released the update for OS X yet.

**Comment by xalalau** [comment] 2015-03-11 18:27
I hate this bug.

**Comment by iTech278** [comment] 2015-04-02 18:33
Please update Awesomium!

**Comment by iTech278** [comment] 2015-04-02 18:34
Please update the version of Awesomium that GMod uses!

**Comment by Bo98** [comment] 2015-04-02 18:35
AFAIK we're still waiting on 1.7.5 to release for OS X.

**Comment by portaloffreedom** [comment] 2015-04-06 20:59
"Jookia opened this issue on 10 Jun 2013"
This is ridiculous.

**Comment by eddie-dunn** [comment] 2015-04-07 16:49
Am I understanding you correct in that you are not fixing this issue in Linux because  Awesomium 1.7.5 is not released for OSX yet?

Can't you just release an updated version for the Linux build of Garry's mod?

**Comment by jackwilsdon** [comment] 2015-04-12 13:07
@eddie-dunn It looks that way, visiting the [Awesomium download page](http://www.awesomium.com/download) you can see that the latest Windows/Linux versions are  v1.7.5.0, however the latest OS X build is v1.7.4. It would be nice if there was an updated Linux build, however I am assuming they are going to wait until OS X is ready.

**Comment by emoeba** [comment] 2015-04-27 06:54
I'm not sure if this has been done yet, but in a recent update of gmod Simon311's html fix broke (maps had no icons and the game froze when trying to start multiplayer).  I have updated his fix to reflect the changes to the game's code.  Just extract in /home/user/.steam/steam/SteamApps/common/GarrysMod/garrysmod and it should be working.

https://www.dropbox.com/s/ps2a14o95jicr7v/html.zip?dl=0

**Comment by toxxik** [comment] 2015-05-08 23:44
i think it could be an issue with selection boxes as they happen to appear in both places where the error occurs. on windows, it uses the system ones, which could be an issue on here.

**Comment by jackwilsdon** [comment] 2015-05-09 00:11
@toxxik The cause has [already been discussed](https://github.com/Facepunch/garrysmod-issues/issues/86#issuecomment-19466902) and it is indeed caused by checkboxes. It is a bug in Awesomium; it seems to have an issue with checkboxes on OS X and Linux.

**Comment by serin113** [comment] 2015-05-09 10:51
Just gonna pass by and say that there's now a 1.7.5 OSX download... in case that's what we're all waiting for here.

http://www.awesomium.com/downloads/awesomium_1_7_5_sdk_mac.dmg

**Comment by Simon311** [comment] 2015-05-09 11:49
Good to know it is getting fixed soon :)
09 мая 2015 г. 13:51 пользователь "Simon Clemente" <notifications@github.com>
написал:

**Comment by toxxik** [comment] 2015-05-09 16:41
@jackwilsdon Do you know when the issue is going to be fixed?

**Comment by xalalau** [comment] 2015-06-05 23:23
So here we are... 1.7.5 was already lauched for OSX ... 2015, June... Any news?

**Comment by Bo98** [comment] 2015-06-05 23:27
Very little happened last month as the last GMod update was about ready to ship. This finally happened on June 1st. That is why it wasn't looked at last month. No idea of the plans going forward though.

**Comment by Pernath** [comment] 2015-06-29 21:46
For the people who are still interested in a temporary solution to the multiplayer freeze in GMod. 
Scroll down in **control.NewGame.js** (usually located in **/home/user/.steam/steam/steamapps/common/GarrysMod/garrysmod/html/js/menu/**) near the line 130 (something), inside the curly braces of *$scope.StartGame = function() { ... }*  and replace the second parameter of the RunConsoleCommand( ) function call: 
*lua.Run( 'RunConsoleCommand( "maxplayers", "'+yourVariable+'" )' )*, where yourVariable holds the number of players. It would look something like this **var yourVariable = 4;**, or any other integer (positive) number you might need for your server. Remember to place the variable line inside the curly braces of the main function I mentioned and, of course, not after the edited line. Finally repeat the change inside this function call inside the main function: *setTimeout( function() { ... }, 200 );*, where you will find the same line to edit as before with your preferences. Save the changes, and restart GMod. By the time you start a SinglePlayer game it should now allow 3 more players if you chose number four as the value of your variable in the JavaScript file. No need to use the boxes that freezes the game.
Hope it works for you, it did for me. 
Ps. Wooo, this thread is really old.

**Comment by meepdarknessmeep** [comment] 2015-07-24 21:01
appears to be related to ng-click

**Comment by meepdarknessmeep** [comment] 2015-07-24 21:17
https://github.com/garrynewman/garrysmod/blob/master/garrysmod/html/js/menu/control.NewGame.js#L184

**Comment by CrypticScyther** [comment] 2015-08-04 17:31
i still have this problem also on ElementaryOS Freya linux

**Comment by MRebhan** [comment] 2015-08-12 07:43
Yep, same problem. Arch Linux x64, latest dev version of gmod

**Comment by RefletDeflet** [comment] 2015-08-16 19:31
Same here. Fedora 22 x64

**Comment by SwaginWagon101** [comment] 2015-09-03 20:28
same here on ubuntu 15.04. Sad to see this isn't resolved yet.

**Comment by QuantumSlag** [comment] 2015-09-09 02:56
Christ. I would expect it to be resolved by now. Dose anybody know a way to manually mount them. I’m not sure if you noticed but if i have no source games downloaded it doesn’t crash. And if a source game is installed it doesn’t crash unless you scroll down to it.

**Comment by portaloffreedom** [comment] 2015-09-09 09:52
Maybe is possible to just update the webkit library inside the folder to
the newest version and it should work. The library is called libawesonium.
Update us if this works

Il giorno mer 9 set 2015 alle ore 04:56 QuantumSlag <
notifications@github.com> ha scritto:

**Comment by Bo98** [comment] 2015-10-02 19:21
Can someone test the dev branch and see if it works? It should have Awesomium 1.7.5.1 now.

**Comment by robotboy655** [comment] 2015-10-02 21:05
Pretty sure it's fixed.

**Closed by robotboy655** 2015-10-02 21:05 UTC
Labels: awesomium, bug, linux, osx

**Comment by sonnydog830** [comment] 2015-10-25 02:30
@mmirate
can you show me the whole lua.js(just copy paste) sorry it broke my game before that DX

**Comment by gameslayer** [comment] 2015-11-02 10:32
Thanks for the fix but I have one issue with it which is after applying the patch the map images on the menu when selecting a map are all set to the grey image when a map has no screenshot and also the workshop button no longer works.

**Comment by julo42** [comment] 2015-11-02 13:44
Hi Gameslayer,

I fixed the grey map bug and cleaned up the html.zip workaround. It's way simpler now. I attached the new html.zip, but I had to rename it to html.zip.png for github to let me attach it.

Enjoy!

![html zip](https://cloud.githubusercontent.com/assets/11225568/10883099/034ac5a0-8170-11e5-812d-5399521c5d75.png)

**Comment by gameslayer** [comment] 2015-11-03 01:10
the image link is broken and where is the link to the zip?

**Comment by julo42** [comment] 2015-11-03 05:55
Actually, the image is fake: it is the zip renamed as a png. So, to download it, just right-click on the image link and "save link target as...". Then name the file "html.zip".

**Comment by julo42** [comment] 2015-11-03 05:58
OK, even simpler: just get it from there: http://julien.olivier.free.fr/html.zip

**Comment by gameslayer** [comment] 2015-11-03 06:00
The one you did broke my menu so I will try the other one you suggested, thanks anyways.

**Comment by sliceofcode** [comment] 2015-11-21 02:32
This is still not fixed for me.

**Comment by Bo98** [comment] 2015-11-21 07:42
It's only fixed on the dev branch because the update hasn't been released yet.

**Comment by sliceofcode** [comment] 2015-12-05 23:39
Ah, okay.
