### ISSUE TITLE
Server list is broken

### ISSUE THREAD

**Issue by estebanlobreau** [Facepunch/garrysmod-issues#5691] opened 2024-01-11 17:08 UTC
We saw all server to 0 player even if they are filled 
![image](https://github.com/Facepunch/garrysmod-issues/assets/19195363/5ffc62dc-c781-4baf-b903-b96af8fc3308)

**Comment by estebanlobreau** [comment] 2024-01-11 17:14
![image](https://github.com/Facepunch/garrysmod-issues/assets/19195363/7d56a8f3-2d28-4403-89dd-8a305169666f)
old navigator is working fine to its weird

**Comment by robotboy655** [comment] 2024-01-11 17:34
The "Favorites" tab works differently compared to the "Internet" tab which is why you are seeing a difference.

It is an issue on Steam/Valve side, there's nothing we can do about it.

Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5688

**Closed by robotboy655** 2024-01-11 17:34 UTC
Labels: Dependency: Steam
