### ISSUE TITLE
file.Find returns invalid directories

### ISSUE THREAD

**Issue by lebroomer** [Facepunch/garrysmod-issues#3785] opened 2019-03-10 19:53 UTC
### Details
We got a project, where we search through a folder to return all directories which resides there, to use them as base for a HUD. Appearently find.File returns a directory, which doesn't really exists in the parent folder. Its gets even weirder as this problem only occurs after the first mapchange. At the first time everything works fine. Furthermore a check of file.IsDir on the wrong directory returns false, which we use currently as a hotfix.

### Steps to reproduce
Since this problem happens only very rarely, the best way to reproduce it, is to check our our repository here: https://github.com/Alf21/TTT2 . In this commit: https://github.com/Alf21/TTT2/commit/46d3d837dc6e3d53fa6c1a61549956f0ff265bda you can see the hotfix I described above and the corresponding lines of code. Clone the repository, check out the commit, start GMod, load an instance of TTT and change the map (or quit to main menu and load another instance of TTT), to see the bug.

**Comment by robotboy655** [comment] 2019-03-10 20:38
Potential duplicate of https://github.com/Facepunch/garrysmod-issues/issues/1038 https://github.com/Facepunch/garrysmod-issues/issues/3437 https://github.com/Facepunch/garrysmod-issues/issues/3736

**Comment by lebroomer** [comment] 2019-03-17 16:41
We got an update. This problem appearently only happens when local files exist at a client, i.e., when creating a local Server (P2P and local). If a client requests the files from Server, everything works. But this isn't caused by caching or anything relatable. We installed a fresh GMod-version and added only the local repository, but it still finds the not existing directory.

**Comment by Alf21** [comment] 2019-05-06 22:12
seems to be fixed (btw.) with localizing a new var instead of reusing it: https://github.com/Alf21/TTT2/commit/e436856089d3f106b794c643757acc887e0066e7#diff-460c9d2e91c33dc54f5776ae7a39bb8aR99

**Comment by robotboy655** [comment] 2019-06-10 16:48
I cannot reproduce this with the [TTT2-0f4ef7818c82f3cdb681f9d2629c0683fc806b82](https://github.com/Alf21/TTT2/tree/0f4ef7818c82f3cdb681f9d2629c0683fc806b82) version of the gamemode. Nothing happens when launching the gamemode multiple times.

**Closed** 2024-04-01 09:22 UTC
Labels: Cannot confirm
