### ISSUE TITLE
crossbow fire and reload sprite in wrong position

### ISSUE THREAD

**Issue by marigi64** [Facepunch/garrysmod-issues#3920] opened 2019-07-20 09:17 UTC
When firing and reloading a crossbow bolt, the light sprite is in the incorrect position. (it changes depending where the player looks)

![20190720185856_1](https://user-images.githubusercontent.com/53112738/61576850-7879d980-ab22-11e9-833f-fe8aa03175fb.jpg)

![20190720185828_1](https://user-images.githubusercontent.com/53112738/61576854-8b8ca980-ab22-11e9-9574-e34408c6face.jpg)

**Comment by robotboy655** [comment] 2019-07-22 12:14
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/3047

**Closed by robotboy655** 2019-07-22 12:14 UTC
