### ISSUE TITLE
Entity Fade Min/Max Distance may not fading properly with Normal Rendering Mode

### ISSUE THREAD

**Issue by Vinzuerio** [Facepunch/garrysmod-issues#2926] opened 2016-11-17 05:37 UTC
### Details
It's been happening since before October update, but only few people might noticed this. 
So I Just noticed when I was compiling single map, then noticed some props were not fading but they just 'simply disappear'. Tested with other source games and they didn't do like this. (At first I thought I had to set the mistaken keyvalues, but I was right)

This shouldn't be happening in Garry's Mod since it _does_ makes visual problem for optimisation purposes, which they should fade out instead of instant disappearing, even though Fading scale has been set into any, they still doing the same.
Several entity that has `fademindist` and `fademaxdist` keyvalues are effected and they're always has their RenderMode set to Normal by default _(even in all source games)_.
**However**, this **do not** seems to be affected for static prop entities, which is kinda strange.

Video: https://www.youtube.com/watch?v=93WdNzZNvGs

Entity that affects:
```
prop_physics, prop_dynamic, prop_ragdoll,
func_lod,
info_overlay,
npc_barnacle, npc_antliongrub,
item_,
weapon_
```

### Steps to reproduce
(1) **GMod** - Make a prop_physics entity with default Normal RenderMode (or try any entities that listed above, and do the same way.)

```
local function MakeFadingEnt(ply)
	phys = ents.Create("prop_physics")
	phys:SetName("Barrel")
	phys:SetModel("models/props_c17/oildrum001.mdl")
	phys:SetPos(ply:GetPos())
	phys:SetRenderMode(RENDERMODE_NORMAL)
	phys:SetKeyValue("fademindist", 256) -- Make it variate, it still does the same.
	phys:SetKeyValue("fademaxdist", 300)
	phys:Spawn()
end
concommand.Add("spawn_barrel", MakeFadingEnt)
```

Walk away about 256 units to 300 units.
However, changing prop's rendermode with `phys:SetRenderMode(RENDERMODE_TRANSCOLOR)` or using from Color Tool works after, but _not for initializing/pre-made map entities_ since they always set with Normal RenderMode.

(2) **Hammer** - Create entity of :
- info_overlay
- prop_physics/_override/_multiplayer
- prop_static
- prop_dynamic/_override
- prop_ragdoll
- npc_barnacle
- npc_antliongrub
- item_suit
- weapon_ar2
- weapon_striderbuster
- func_lod

with Min Fade Distance (fademindist) to 256 (or any) and Max Fade Distance (fademaxdist) to 300 (or any). For func_lod, you might need to specify fade distance around 200 or so.

Result:
https://www.youtube.com/watch?v=A9WeaUYan6o
Some of them may fade or just simply disappearing (except prop_static). Compared and tested in Half-Life 2 all props were fading out, while in Garry's mod, they don't.

Not sure if this could be related to texture or Render Mode issue?

### Update:
I asked my friend to upload the video to his channel atm instead hosting the file, due of my network issues, sorry guys!

**Comment by kem008** [comment] 2016-11-17 10:45
There is no way to upload the video to a site to play it instead of downloading it. But the problem you talk happens often on Half Life 2.

**Comment by robotboy655** [comment] 2016-11-17 13:43
```There is no way to upload the video to a site to play it instead of downloading it.```

You do know YouTube exists?

**Comment by Vinzuerio** [comment] 2016-11-17 14:36
Sorry btw, firstly It's actually temporary upload and sometimes YouTube can crap the quality, secondly I had terrible connection on my home so decided to put on my server, but I'll try to re-upload it soon to YouTube if I got better connection here (that video upload was actually took literally like 3 hours to be exact)

on Half-Life 2, do which map it actually occurs? I only remember there was once in streetwar (`d3_c17_*`) map and I think it meant to be 'disappear' instead fading out

in EP1, I think I haven't noticed that but I'll go check

And to the main problem, it happens almost in all maps btw, that's why just to make sure if this happen to you guys too or not, or it just some of the maps

**Comment by kem008** [comment] 2016-11-17 15:08
Check also ep2_outland_09. Where you see an invisble door and when u go upstair u will see some prop fade out and in depends on distance.

**Comment by Vinzuerio** [comment] 2016-11-17 16:32
That's `func_areaportalwindow + func_illusionary` (or `func_brush`) that one works on both Garry's Mod and HL2/-EP2. 
Main thing here that any entities which affects (as described on details above) and have `fademin/maxdist` (or simply prop fading properties if we look from a distance), they seems do not 'fade-out' when you stay away, but they just simply 'disappear' (or like popped out).

That's why I put two reproduce steps so you can know what I mean.

Also, the one you were meaning of NPCs on EP1 maps were fading out was actually the same thing, it just func_areaportalwindow & illusionary tricks.

**Comment by robotboy655** [comment] 2020-06-09 15:35
I have looked into this, and this is at least partially caused by the fix to HL1 entities being pitch black. Not sure what the solution is for this yet. 

The issue on ep2_outland_09 was resolved, I didn't notice any other fading issues on any other maps.

**Comment by robotboy655** [comment] 2020-07-09 18:15
Fixed on Dev.

**Closed by robotboy655** 2020-07-09 18:15 UTC

**Comment by Vinzuerio** [comment] 2020-07-10 16:14
Thank you, it seems working for now
