### ISSUE TITLE
FollowBone on ragdoll breaks when ragdoll goes to sleep

### ISSUE THREAD

**Issue by Ramalayha** [Facepunch/garrysmod-issues#5216] opened 2022-05-07 11:19 UTC
If you use Entity:FollowBone with a ragdoll as the parent and physobj 0 is frozen or goes to sleep the attached entity will stop following the bone and stay in the last place it was when physobj 0 went to sleep. Through some testing I think I've nailed it down to the EFL_DIRTY_ABSTRANSFORM flag being unset for some reason when the ragdoll goes to sleep, a fix I found for now is to reset the flag in the draw function of the attached entity or a think hook.

Entity:SetPredictable does not fix this

**Comment by robotboy655** [comment] 2022-05-07 14:13
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/4588

**Closed by robotboy655** 2022-05-07 14:13 UTC
