### ISSUE TITLE
Add Black Mesa Mounting support

### ISSUE THREAD

**Issue by ecumber** [Facepunch/garrysmod-issues#4466] opened 2020-04-22 06:06 UTC
As of now, you have to mount it manually via the config file and you have to browse the files in the all games list.

**Comment by Kefta** [comment] 2020-04-22 06:47
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/599 and on the wrong repo. Someone already asked the BM devs and they said no.

**Closed** 2020-04-22 10:52 UTC

**Comment by ecumber** [comment] 2020-04-22 21:24
Sorry, didn't see that

**Comment by CybrFox-CC** [comment] 2026-03-18 15:49
Hey everyone, I'm replying on behalf of Crowbar Collective.  We are okay with having Black Mesa be apart of this, as long as it's used in a non-commercial/non-retail usage.  Feel free to reach out to me on our official Discord if needed.
