### ISSUE TITLE
Crash when player respawns on other team

### ISSUE THREAD

**Issue by ghost** [Facepunch/garrysmod-issues#3255] opened 2017-07-27 19:22 UTC
### Details
In the zombie survival gamemode, when a zombie player kills enough humans, they will "redeem", making them respawn back on the human team.

Using specific zombie classes, redeeming back to the human team with these two specific player models can _sometimes_ cause other players to crash.

models/player/combine_soldier_prisonguard.mdl
models/player/soldier_stripped.mdl

### Steps to reproduce

Use headcrab zombie class and get 4 human kills

[hl2_170725_crash_2017_7_27T19_6_27C0.zip](https://github.com/Facepunch/garrysmod-issues/files/1181023/hl2_170725_crash_2017_7_27T19_6_27C0.zip)

**Comment by robotboy655** [comment] 2017-07-28 00:37
Can you attach a dump from the very latest version of the game? Or at least make sure your client.dll is up to date.

**Comment by ghost0123** [comment] 2017-07-28 17:42
Another crash dump, on the dev branch this time.
[hl2_170728_crash_2017_7_28T17_39_12C0.zip](https://github.com/Facepunch/garrysmod-issues/files/1183838/hl2_170728_crash_2017_7_28T17_39_12C0.zip)

**Comment by robotboy655** [comment] 2017-07-28 17:53
Yeah its a known crash with outdated models ( not version 48 ), the combine_soldier_prisonguard should not cause any problems if your server is up to date, but there are 2 more models that cause the problem that need fixing.

**Comment by robotboy655** [comment] 2017-11-24 16:22
Basically duplicate of https://github.com/Facepunch/garrysmod-issues/issues/2353

**Closed by robotboy655** 2017-11-24 16:22 UTC
Labels: crash
