### ISSUE TITLE
Gmod Crash to desktop After loading screen.

### ISSUE THREAD

**Issue by Joker270** [Facepunch/garrysmod-issues#2652] opened 2016-06-02 09:35 UTC
Hello,
when i want join a server, garrysmod freeze and crash to desktop

I have already :
Reinstall Gmod, verify the game, uninstall and reinstall ..

I have other game in steam installed like :
CSGO, CSS, CS1.6, L4D/L4D2

"Dump File:   hl2_160424_crash_2016_6_1T20_38_25C0 : D:\Steam1\SteamApps\comm on\GarrysMod\hl2_160424_crash_2016_6_1T20_38_25C0
Last Write Time:   01/06/2016 22:38:42 p.m.
Process Name:   hl2.exe : D:\Steam1\SteamApps\comm on\GarrysMod\hl2.exe
Process Architecture:   x86
Exception Code:   0xC0000005
Exception Information:   The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
Heap Information:   Not Present"

http://www.partage-fichiers.com/upload/lebpe72d (my dump crash)

Thanks advance !

**Comment by robotboy655** [comment] 2016-12-07 12:24
Duplicate of #248

**Closed by robotboy655** 2016-12-07 12:24 UTC
Labels: crash, duplicate

**Comment by Joker270** [comment] 2016-12-07 12:59
Problem resolved, i just update my graphic card (Nvidia)
You need to upgrade or downgrade your graphic card if you have this problem!
