### ISSUE TITLE
Zombie NPCs set to different model and holding weapon freeze game when killed

### ISSUE THREAD

**Issue by sockpuppetclock** [Facepunch/garrysmod-issues#5029] opened 2021-08-18 03:13 UTC
### Details
Linux, x86-64 branch ( 2021.08.09 )
Source Engine 24 ( build 8277 )
### Steps to reproduce
lua_run example: `lua_run local ent = ents.Create( "npc_fastzombie" ) ent:Spawn() ent:Activate() ent:SetModel( "models/kleiner.mdl" ) ent:SetPos( Entity(1):GetPos() + Vector( 100, 0, 0 ) ) ent:Give( "weapon_crowbar" )`
1. Spawn a zombie, fast zombie, or zombine
2. Change the model ("models/Kleiner.mdl")
3. Give it a weapon (weapon_crowbar)
4. Kill it with a headshot or a powerful gun, like a 357 headshot or double shotgun shot or rpg round
5. Game freezes and eventually closes

**Comment by robotboy655** [comment] 2021-08-18 10:03
Cannot confirm. Check your mods, run the game without mods.

**Comment by sockpuppetclock** [comment] 2021-08-20 12:09
I was testing it without mods or any addons enabled, clean game folder. It doesn't freeze when the AI is disabled or when it isn't alert. Crossbow, pistol, and most bodyshot kills do not trigger the freeze but headshots, shotgun double shot (even bodyshot), and explosions do.

**Comment by robotboy655** [comment] 2021-08-20 13:26
I have tried the 357 headshot and explosives using your exact code with AI enabled, albeit on Windows.

**Comment by The-Horde** [comment] 2021-08-21 21:57
https://user-images.githubusercontent.com/88246300/130335766-8d82899f-5fb6-4533-8a75-fa8011987878.mp4

I can confirm this bug exists. I had no mods loaded, clean game on Windows 10, x86-64 branch.

**Comment by FlorianLeChat** [comment] 2021-08-22 08:54
![image](https://user-images.githubusercontent.com/26360935/130348658-e23e8969-3ae1-4127-b199-98a656115a57.png)
I'm unable to reproduce the crash on all branches with the `-noaddons` and `-noworkshop` launch parameters. So it's probably related to one of your addons.

**Comment by robotboy655** [comment] 2021-08-23 12:30
The NPC had to be on a specific animation for the crash to happen, should be fixed on 'dev' and 'x86-64' betas soon.

**Closed by robotboy655** 2021-08-23 12:30 UTC
Labels: Bug, Crash
