### ISSUE TITLE
gmod crash in Ubuntu 14.04 , 64bit

### ISSUE THREAD

**Issue by socialloser1** [Facepunch/garrysmod-issues#1621] opened 2014-11-27 02:22 UTC
I tried to start Gmod with Steam client in Ubuntu 14.04 64bit , the game started , displaying the loading screen with blue background , after that it crashed back to Steam . 
following is the terminal errror output  :

Game update: AppID 4000 "Garry's Mod", ProcID 3356, IP 0.0.0.0:0
ERROR: ld.so: object '/home/kowalski/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/kowalski/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 3359 != 3358, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/kowalski/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/kowalski/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
SDL video target is 'x11'
SDL video target is 'x11'
Setting breakpad minidump AppID = 4000
dlopen failed trying to load:
/home/kowalski/.local/share/Steam/linux32/libsteam.so
with error:
/home/kowalski/.local/share/Steam/linux32/libsteam.so: cannot open shared object file: No such file or directory
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198019395754 [API loaded no]
Did not detect any valid joysticks.
Could not load program cache file glbaseshaders.cfg
Could not find base GL shader cache file
Could not load program cache file glshaders.cfg
Could not find user GL shader cache file
Precache: Took 0 ms, Vertex 0, Pixel 0
ConVarRef mat_dxlevel doesn't point to an existing ConVar
Game.so loaded for "Garry's Mod"
/play/SteamLibrary/steamapps/common/GarrysMod/hl2.sh: line 67:  3361 Segmentation fault      (core dumped) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 4000 "Garry's Mod", ProcID 3361 
saving roaming config store to 'sharedconfig.vdf'
roaming config store 2 saved successfully

**Comment by robotboy655** [comment] 2015-11-24 18:13
Could it be related or possible duplicate of #179?

**Comment by robotboy655** [comment] 2024-03-25 20:17
Closing as stale.

**Closed by robotboy655** 2024-03-25 20:17 UTC
Labels: Bug, Platform: Linux, Crash
