### ISSUE TITLE
navmesh.BeginGeneration() causes crash right after saving .nav file.

### ISSUE THREAD

**Issue by Nak2** [Facepunch/garrysmod-issues#2332] opened 2015-12-17 15:36 UTC
Might be able to finish my gamemode with these awesome new functions :)
It ran perfectly fine until it finished and caused my client to crash right after it generated the .nav file.

Here is the generation code.
```
local function MapGen()
	--navmesh.IsGenerating()
 	--gmod.GetGamemode():SetStatus(-2)

	local SpawnPoints = ents.FindByClass( "info_player_*" )
	local tab = {"ins_spawnpoint","aoc_spawnpoint","dys_spawn_point","diprip_start_team_blue","diprip_start_team_red"}
	for I=1,#tab do
		table.Merge( SpawnPoints, ents.FindByClass( tab[I] ) )	
	end
	for I=1,#SpawnPoints do
		navmesh.AddWalkableSeed( SpawnPoints[I]:GetPos(), SpawnPoints[I]:GetAngles():Up() )
	end

	navmesh.BeginGeneration()
	PrintMessage(3,"[GAMEMODE] Generating navmesh. This will take some time.")
	timer.Create("MapNavGen",1,0,function()
		if !navmesh.IsGenerating() then
			-- Restart
			PrintMessage( 3, "[GAMEMODE] Restarting ...")
			timer.Destroy("MapNavGen")
			RunConsoleCommand( "changelevel", game.GetMap() )
		end
	end)
end
```
Not sure if it will automatically restart right after a generated .nav file .. but it looks like it never reached the changelevel command.
Here is the dump: https://dl.dropboxusercontent.com/u/14214411/hl2_151216_crash_2015_12_17T15_11_12C0.mdmp

**Comment by Raxsyz** [comment] 2015-12-27 23:15
My problem is that my game crashes when I try to use the in game nav_generate command in the console. :(
This was never a problem for me before, it was working flawlessly all this time till the latest update. Something got broken or something.

**Comment by robotboy655** [comment] 2015-12-28 01:29
I cannot reproduce the crash with arena_sawmill and your code. Everything seems to work as expected.

Either it is already fixed in Dev, or something else is causing it. Judging by your console log, it is not caused by saving, the last entries suggest the server was ( or did ) shutting down.

Tested on in singleplayer.

**Closed** 2016-05-19 22:46 UTC
Labels: crash
