### ISSUE TITLE
Hammer Clip tool sets semi-random texture on clip plane faces

### ISSUE THREAD

**Issue by stepa2** [Facepunch/garrysmod-issues#4911] opened 2021-04-15 19:13 UTC
### Details
Regularities:
- If primitive has a horizontal top, clip plane faces have material of the top
- If primitive has no horizontal top, but has a horizontal bottom, clip plane faces have material of the bottom
- If primitive has no horizontal top nor bottom, texture of some semi-random (but always the same) face, located in the upper part of the brush, is used.
- If primitive was rotated, original (unrotated) top and bottom directions are used in the above regularities.

### Excepted behavior
I would except the clip plane faces to have either toolsnodraw texture or currently active texture.

**Comment by robotboy655** [comment] 2021-04-16 08:03
Basically duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1834

Not a bug.

**Closed by robotboy655** 2021-04-16 08:03 UTC
Labels: Tools
