### ISSUE TITLE
pcalling require triggers script errors

### ISSUE THREAD

**Issue by Earu** [Facepunch/garrysmod-issues#5107] opened 2021-12-03 14:16 UTC
As mentioned in the title doing:
```lua
pcall(require, "module_name")
```

Running that code when the module is not available did not use to trigger script errors, now it does.

**Comment by Kefta** [comment] 2021-12-03 23:03
Semi-related to https://github.com/Facepunch/garrysmod-requests/issues/813

**Comment by robotboy655** [comment] 2023-11-10 13:38
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/2498

**Closed by robotboy655** 2023-11-10 13:38 UTC
