### ISSUE TITLE
Clientside NetworkVarNotify not triggered when Entity networkvar changes to NULL

### ISSUE THREAD

**Issue by wyozi** [Facepunch/garrysmod-issues#4568] opened 2020-07-04 08:56 UTC
```lua
ENT.Type = "anim"

function ENT:SetupDataTables()
    self:NetworkVar("Entity", 0, "MyEnt")

    self:NetworkVarNotify("MyEnt", function(...)
        print(SERVER and "SV" or "CL", ...)
    end)
end
```

and then running `SetMyEnt(player)` + `SetMyEnt(NULL)`:
```
SV Entity [1016][nwnotifyrepro] MyEnt [NULL Entity] Player [7][Me]
CL	Entity [1016][nwnotifyrepro]	MyEnt	[NULL Entity]	Player [7][Me]
SV Entity [1016][nwnotifyrepro] MyEnt Player [7][Me] [NULL Entity]
-- Missing CL notify here!
```

**Comment by Kefta** [comment] 2020-07-04 09:22
I believe this is intended behavior as clients no longer have knowledge of deleted ents once the deletion message is sent from the server. You can work around this in the short term by using the EntityRemoved hook to manually call the NetworkVarNotify callback clientside, though this behaviour should be changed in the engine as the client entity technically knows when it's gonna be deleted.

**Comment by wyozi** [comment] 2020-07-04 09:25
In my case I'm not deleting any entities though, just setting the network var to NULL.

**Comment by Kefta** [comment] 2020-07-04 17:52
Whoops, misread the issue.

**Comment by robotboy655** [comment] 2020-07-07 18:05
Fixed on Dev.

**Closed by robotboy655** 2020-07-07 18:05 UTC
