### ISSUE TITLE
render.RenderView() Culling Issues with Ortho View on 64-bit Branch

### ISSUE THREAD

**Issue by SageJFox** [Facepunch/garrysmod-issues#5810] opened 2024-03-22 05:19 UTC
### Details
`Protocol version 24`
`Exe version 2023.06.28 (garrysmod)`
`Exe build: 17:44:51 Mar 21 2024 (9246) (4000)`
`GMod version 2024.03.21, branch: x86-64, multicore: 1`
`Windows 32bit` + `Windows 64bit`

When using `render.RenderView()`'s ortho settings (both on the older individual entries and with the newer table), the world is clipped in a fashion similar to znear at the map origin, and entities between the view origin and map origin are culled. This issue is not present on the regular or dev branches, but is present on both the 32 and 64-bit versions of the x86-64 branch.

The view setup is 5 units away from the surface it is drawn on, and is marked with several crosses/texts to denote its origin and its ortho settings. The table for its settings in the following test shots is this:
```
{
	origin = self:GetPos() + self:GetAngles():Forward() * -5,
	angles = self:GetAngles(),
	drawviewmodel = false,
	x = 0,
	y = 0,
	w = ScrW(),
	h = ScrH(),
	ortho = {left = -92,
	right = 92,
	top = -92,
	bottom = 92},
	bloomtone = false,
	dopostprocess = false
}
```
Defining parameters like znear do not affect this issue, it is not because there is no znear defined. The default non-ortho view is also not affected.

Take this scene of two differently colored striders. The green one is at about -300 Y from the map origin, the red one is roughly +300 Y (as shown in shot 2). The combine chopper is placed roughly at the origin for ease of seeing it in the 3D space. The red one, being before the plane defined by the map origin from the view's origin, is culled.
![1](https://github.com/Facepunch/garrysmod-issues/assets/40696450/cb2171b6-21d0-4603-b1d5-d13bb0d0fc55)
![2](https://github.com/Facepunch/garrysmod-issues/assets/40696450/29805102-6594-45c2-92f9-7ba58cf86182)

These next two shots better show off the world clipping effect observed. This shot should just show the cabin wall, but instead shows everything past the origin. Fourth shot to better show off the geometry of the area.
![3](https://github.com/Facepunch/garrysmod-issues/assets/40696450/436b4cb6-129e-4b99-9376-762314260c4c)
![4](https://github.com/Facepunch/garrysmod-issues/assets/40696450/8d39504e-2e54-48a7-a0a4-d7d0b9579918)

Note that if we move the view to the +Y side of the origin and look back, the green one is culled and the red one shows.
![5](https://github.com/Facepunch/garrysmod-issues/assets/40696450/f20fc2c1-4e69-4362-bc5f-7071378d7520)

### Speculation
My *guess* would be this involves attempts at culling objects behind the camera, but something is causing the vector for the origin of the view to not be used/be unset and then it's using (0,0,0) instead. This issue doesn't seem to appear if the origin is behind the view, which would make sense with this guess, as that "back" plane would be totally behind it.

**Comment by robotboy655** [comment] 2024-03-22 15:48
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5363

**Closed by robotboy655** 2024-03-22 15:48 UTC

**Comment by SageJFox** [comment] 2024-03-22 19:02
Apologies, I hadn't thought to look that far back as this issue wasn't present for me prior to the March 19th update. It does seem to be the same issue, though it's not only affecting the Z as they reported.
