### ISSUE TITLE
Using double precision for CurTime could potentially fix CurTime's bugginess.

### ISSUE THREAD

**Issue by mrwallace888** [Facepunch/garrysmod-issues#5342] opened 2022-10-23 14:25 UTC
### Details
This was mentioned before back in 2016 (#2502) and it seems like a lot of people are pretty disappointed about this issue. I use CurTime for other purposes, but most need it for server-related stuff, as leaving a server on for 6+ hours causes significant problems like broken animations and positions. For some of the uses I use it for, within half an hour I can already start seeing discrepancies. So I can't even begin to imagine how bad it gets 6+ hours in.

Double precision would make this significantly better across the board. It'll be a pain in the ass to go through the code, but it's what matters in the long run that counts. I know a _lot_ of people would benefit if it was converted to double instead of single. I really hope time can be found to try to change all the code for Garry's Mod to use double precision instead of single for CurTime. Garry's Mod would benefit massively from it and it'd help to future-proof the game in order to increase its longevity.

Someone else said "you could just network a single float to clients and let clients CurTime increase as a double". Not sure how effective that would be.

**Comment by robotboy655** [comment] 2022-10-24 12:56
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/2502

**Closed by robotboy655** 2022-10-24 12:56 UTC
