### ISSUE TITLE
Gravity Gun Mega Mode No Longer Functions

### ISSUE THREAD

**Issue by Marxon1134** [Facepunch/garrysmod-issues#3780] opened 2019-03-02 19:49 UTC
Issue: Gravgun cannot have mega mode (turns blue, grab almost anything, plus kill and shock npcs) enabled anymore either by being set from an env_global or setting "physcannon_mega_enabled" to 1. On top of this 3 other issues seem derived from/related to it. First, normal grav guns can actually hold combine energy orbs when they normally shouldn't. Second is that the grav gun cannot pick up if mega mode is enabled. Third, when the global state is set npc dropped weapons do not disintegrate and can paradoxically be picked up unlike the gravity gun in the weapon stripper sequence. Parts 2 and 3 suggest its more related with the whole global state not just the gun itself.

To Reproduce: Simply use the console command, or run through the d3_citadel or ep1_citadel maps (after first one or two I think) to see how the issue makes it impossible to complete these maps without using console commands.

**Comment by Kefta** [comment] 2019-03-02 20:30
The super grav gun never worked in GMod, duplicate of https://github.com/Facepunch/garrysmod-requests/issues/91.

**Closed** 2019-03-03 11:37 UTC
