### ISSUE TITLE
Loading progress bar ignore gmod_language

### ISSUE THREAD

**Issue by roboderpy** [Facepunch/garrysmod-issues#4137] opened 2020-01-18 08:33 UTC
### Details
![gmod_akSFofmKdu](https://user-images.githubusercontent.com/6339511/72660970-b2f7fc80-3a07-11ea-9bf1-a45a70be59d6.png)
![gmod_DAvO7MxFEG](https://user-images.githubusercontent.com/6339511/72660972-b3909300-3a07-11ea-9841-e182ffcf2829.png)

### Steps to reproduce
Set steam language to something other than gmod_language?

**Comment by robotboy655** [comment] 2020-01-18 14:53
gmod_language doesn't affect Source Engine language, it is "intentional", you can use `-language "english"` to set the language to non Steam language.

**Comment by roboderpy** [comment] 2020-01-18 15:36
I mean, before update it was on english.

**Comment by robotboy655** [comment] 2020-01-18 19:51
Yeah it was forced to English and now it is tied to your Steam language. There is no way currently to tie it to gmod_language. Basically duplicate of https://github.com/Facepunch/garrysmod-issues/issues/4110

**Closed by robotboy655** 2020-01-18 19:51 UTC
