### ISSUE TITLE
c_hand position being set too late?

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#2226] opened 2015-09-07 00:23 UTC
https://www.youtube.com/watch?v=rQAbVLaNLtk

This is with the deploy speed scaled down to -50. The hands appear in the air for a second, then attach themselves to the viewmodel. This was just an example of an issue that happens quite often on player spawn in a multiplayer server; if the player initially spawns with a c_model weapon, the hands will go to the origin of the map and stay there until the player switches weapons. Also seems to happen with the physgun glow effect.

**Comment by willox** [comment] 2016-03-23 02:39
Finally reproduced by getting out of an airboat while looking at 0 0 0

**Comment by Kefta** [comment] 2016-04-24 20:40
I've been able to sparsely reproduce this by spawning, looking at a slightly negative angle, then switching from the physgun to a weapon that does not UseHands.

**Comment by willox** [comment] 2016-04-24 20:52
It's caused by the SetParent call (possibly because the entity's origin hasn't yet been set?)

**Comment by Kefta** [comment] 2016-12-30 06:31
Managed to replicate it today with this code in single-player: http://pastebin.com/3MqZkX02
https://a.pomf.cat/fntcoi.png

**Comment by robotboy655** [comment] 2020-04-21 15:49
Well technically this is now fixed. The root cause of the issue is `SetTransmitWithParent(true)` call on the `gmod_hands`, but I don't want to get rid of that just yet.

> This was just an example of an issue that happens quite often on player spawn in a multiplayer server; if the player initially spawns with a c_model weapon, the hands will go to the origin of the map and stay there until the player switches weapons. Also seems to happen with the physgun glow effect.

No idea what this is about, first time I hear of something like that. If you have a way to reproduce this, or have more info such as does this happen only to local player's hands or other player's hands on local player's screen. `physgun glow ` part also sounds very weird. 3rd person glow, 1st person glow?

**Closed by robotboy655** 2020-04-21 15:49 UTC
