### ISSUE TITLE
Checksum error

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3804] opened 2019-04-08 11:40 UTC
### Details
Error Vertex File for 'props_c17/light_domelight02_on.mdl' checksum 397824940 should be -935408350

This error extremely often appears and makes specific props invisible.
Especially after playing on a map and then visiting another.

### Steps to reproduce
Unknown how to reproduce

**Comment by robotboy655** [comment] 2019-04-08 11:47
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/2650

**Closed by robotboy655** 2019-04-08 11:47 UTC

**Comment by Doommarine1991** [comment] 2025-11-11 20:16
Error Vertex File for 'props_c17/door01_left.mdl' checksum 145318345 should be 972034250 (x264) spamms now......

**Comment by mr8109956-oss** [comment] 2026-08-25 19:01
seems its still a bug.............this needs to be fixed its 2026
