### ISSUE TITLE
Problems with compiling high-poly models

### ISSUE THREAD

**Issue by Sherlock2004** [Facepunch/garrysmod-issues#5100] opened 2021-11-22 14:10 UTC
**Describe the bug**
When I compile high poly models I get broken stretched polygons. Here are screenshots. Any other stuidomdl will compile everything correctly.
![screen](https://user-images.githubusercontent.com/88171363/142875982-905dcab5-f57e-4927-b150-526b63ba7183.jpg)

**To Reproduce**
Try to compile this mode
[xmastreeart_src.zip](https://github.com/Facepunch/garrysmod-issues/files/7581750/xmastreeart_src.zip)l

UPD: All gmod builds have this problem (stable / dev / 64)
So here's another example of a model.
[train.zip](https://github.com/Facepunch/garrysmod-issues/files/7581939/train.zip)
It doesn't matter how many parts the model is divided into, when a certain total number of polygons is reached, the model starts to compile incorrectly. I've tried other games like CSGO or SFM and it compiles correctly.
![WFZCW3eHVc](https://user-images.githubusercontent.com/88171363/142880248-f9316a79-d1b4-4a5f-8e20-5cbca70f745b.jpg)

**Comment by robotboy655** [comment] 2021-11-22 15:19
Possibly duplicate of https://github.com/Facepunch/garrysmod-issues/issues/4832

**Comment by Sherlock2004** [comment] 2021-11-22 15:37
> Possibly duplicate of #4832
Most likely, but I thought this problem was solved a long time ago.

**Closed** 2024-10-18 16:53 UTC
Labels: Tools
