### ISSUE TITLE
Game restart corrupting cvar number on x86-64 branch

### ISSUE THREAD

**Issue by timschumi** [Facepunch/garrysmod-issues#4359] opened 2020-02-01 18:56 UTC
### Details
My Setup:
- Linux
- Locally hosted, non-dedicated server for 8 players.
- TTT or Sandbox gamemode
- convar set up by `CreateConVar("discord_guild", "", FCVAR_ARCHIVE, "Some description.")`

This seems to only happen on the current x86-64 build (2020.01.30), not the dev build (2020.01.31) or the current default branch (2020.01.25)

### Steps to reproduce
1. Set convar to `364492944306077697`. (is correctly written to server.vdf)
2. Quit and restart the game (disconnect/reconnect does not trigger this).
3. Value turns into `-729808895`. (is updated in server.vdf as well)

**Comment by robotboy655** [comment] 2020-02-03 19:13
Cannot reproduce.

Code used: (in a serverside only file)
```
local c = CreateConVar("discord_guild", "0", FCVAR_ARCHIVE, "Some description.")

timer.Simple( 1, function()
	if ( c:GetDefault() != c:GetString() ) then return end
	print("discord_guild")
	RunConsoleCommand("discord_guild", "364492944306077697" )
end )
```
It just stays its proper value.
![image](https://user-images.githubusercontent.com/3299036/73682819-d38faa00-46c9-11ea-8491-c42c192a7931.png)
![image](https://user-images.githubusercontent.com/3299036/73682877-e86c3d80-46c9-11ea-8691-281452ecb5da.png)

**Comment by timschumi** [comment] 2020-02-03 23:43
Weird. I do have that problem on two different computers (running the same OS though), both on a clean installation on the game.

I copy-pasted your code into an autorun file and wrapping it in `if SERVER`, to test your exact setup:

First run:
![Bildschirmfoto_2020-02-04_00-38-04](https://user-images.githubusercontent.com/16820960/73700580-317eba80-46e7-11ea-8018-a0c78f287f50.png)
![Bildschirmfoto_2020-02-04_00-39-15](https://user-images.githubusercontent.com/16820960/73700582-33e11480-46e7-11ea-8cdb-f3544fb8e176.png)

After restarting game, without doing anything else:
![Bildschirmfoto_2020-02-04_00-40-03](https://user-images.githubusercontent.com/16820960/73700619-4c512f00-46e7-11ea-8014-8f87ea22b0f6.png)
![Bildschirmfoto_2020-02-04_00-40-28](https://user-images.githubusercontent.com/16820960/73700626-53783d00-46e7-11ea-8c0b-ef74203c743f.png)

**Comment by robotboy655** [comment] 2020-02-04 15:25
Are you on Linux?

**Comment by thegrb93** [comment] 2020-02-04 15:31
>My Setup:
    Linux

:v

**Comment by robotboy655** [comment] 2020-02-04 16:07
I am blind OK?

**Comment by timschumi** [comment] 2020-10-09 16:05
I've retested this on a more current version of the x86-64 branch (to be more precise, 2020.10.07), and this still happening. While testing, I noticed that the "corrupted" value is a clean 32-bit clip of the original value. I did not see that earlier because my original test values resulted in a negative number (which python doesn't properly translate into hex using the builtin function).

Choosing different values (e.g. `662980392193622036` for the "input" and `1908408340` for the "corrupted output") makes it quite obvious:

```
Python 3.8.5 (default, Sep  5 2020, 10:50:12) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> hex(662980392193622036)
'0x933612771c00014'
>>> hex(1908408340)
'0x71c00014'
```

I'm going out on a limb and say that somewhere during the startup phase that value is accidentally casted to a 32-bit integer (at least on Linux systems) and is then used and stored as usual.

**Comment by robotboy655** [comment] 2020-10-09 16:13
Yeah that was obvious from the start, the weird issue is that its Linux only.

**Comment by timschumi** [comment] 2020-10-21 17:05
Correction: It does affect OSX as well (which may or may not make it worse).

**Comment by robotboy655** [comment] 2020-11-26 18:33
It SHOULD be fixed.

**Closed by robotboy655** 2020-11-26 18:33 UTC
Labels: Bug, Platform: Linux

**Comment by timschumi** [comment] 2020-11-26 22:47
Can confirm that the issue is fixed on Linux.
