### ISSUE TITLE
Incorrect / missing materials in several TF2 maps

### ISSUE THREAD

**Issue by Fennecai** [Facepunch/garrysmod-issues#4591] opened 2020-07-18 01:02 UTC
### Details
I am on version 2020.6.26.

Several materials in several tf2 maps are either wrong or, in the case of skyboxes, completely missing.

screenshots: (first image: missing sky, wrong hl2 building texture. second image: wrong hl2 floor texture.)
![20200717152342_1](https://user-images.githubusercontent.com/10889213/87841003-9e35dd80-c85f-11ea-8abe-065a72688268.jpg)
![20200717153804_1](https://user-images.githubusercontent.com/10889213/87841008-a0983780-c85f-11ea-8e7f-ac24617cfba4.jpg)

### Steps to reproduce
1. play a few random Team Fortress 2 maps in sandbox with tf2 mounted
2. look up at the sky.
3. look at various buildings
4. notice that this issue is occuring

**Comment by viral32111** [comment] 2020-07-18 09:46
Do you have any other addons that could be overriding materials?

If you're not doing so already, make sure to add `-noaddons -noworkshop` to your startup parameters, then see if the issue still exists.

**Comment by Fennecai** [comment] 2020-07-18 15:32
> Do you have any other addons that could be overriding materials?

nope.

**Comment by viral32111** [comment] 2020-07-18 15:34
What are the names of the maps used in the screenshots so I can try reproduce this? (sorry, I don't play TF2 that much anymore)

**Comment by Fennecai** [comment] 2020-07-18 15:36
I don't play tf2 either; I just play the maps in gmod and I don't remember which ones those 2 were. but it shouldn't matter too much because this happens in quite a few of the tf2 maps; most notably in a lot of the ctf_ and cp_ maps. I will still try to find a couple of the maps that do this though and get back to you on that if this didn't help already

**Comment by viral32111** [comment] 2020-07-18 15:52
Yeah so I found this on `cp_steel` with just TF2 mounted & `-noaddons -noworkshop` as the startup params:
![](https://user-images.githubusercontent.com/19510403/87856263-861c9780-c90d-11ea-985f-c8e6edb52ba0.png)

Pretty sure it's the same issue as what's in your second screenshot. For reference, this is the same place but from within TF2:
![](https://user-images.githubusercontent.com/19510403/87856396-6df94800-c90e-11ea-83ef-3b6ee1840c6d.png)

I wasn't able to reproduce the skybox missing texture issues though. My best guess is that Garry's Mod must have it's own material somewhere with the same name that is taking priority.

**Comment by Fennecai** [comment] 2020-07-18 15:56
possibly; but yeah- seems like you were able to reproduce 1/2 of the problem. good. :) though tbh I probably should have reported the skyboxes separately cause that might be a different issue... my guess is that gmod mounts the hl2 content before the tf2 content, and so it loads hl2 textures instead of tf2 whenever they have the same name. maybe there should be a system in place to dynamically change the order based on whether the map is a tf2 map or not.....? Idk if that's possible but just an idea.

**Comment by viral32111** [comment] 2020-07-18 16:06
> my guess is that gmod mounts the hl2 content before the tf2 content, and so it loads hl2 textures instead of tf2 whenever they have the same name. 

Seems likely. From viewing the map from within TF2's hammer, the material is `concrete/concretefloor002b`:
![](https://user-images.githubusercontent.com/19510403/87856666-06dc9300-c910-11ea-9caf-23190ca02a0e.png)

I searched for that same material from within GMod's hammer and it shows the same name, but a different texture (Left is TF2, right is GMod):
![](https://user-images.githubusercontent.com/19510403/87856691-3a1f2200-c910-11ea-9886-23268dbe2744.png)

**Comment by Fennecai** [comment] 2020-07-18 16:18
I'm a modder for other source games, as well as a game developer, and I can definitely confirm that source tends to work in a way where content mounted first gets higher priority than whats mounted last. basically it's like, "if the file isn't in game 1, look inside game 2...if it's in game 2, don't load that file from game 3 even if it's there," etc. so that's probably what's happening. thing is though- how would you fix it without the exact opposite problem starting to happen on hl2-textured maps where suddenly tf2 textures are now everywhere? you'd have to somehow override the materials _only_ from within the tf2 maps. there's an addon on the workshop that can change map textures in-game, so I know its possible, I just have no clue how.

**Comment by robotboy655** [comment] 2020-07-20 13:17
Yeah that's the issue and it can't be easily fixed. Changing materials at runtime is not really an option for this, as certain things like footsteps will not update, etc, and the whole mounting order which I believe is already requested somewhere is too unstable, there were at least 2 or 3 attempts at it over the years.

**Comment by Fennecai** [comment] 2020-07-21 22:06
i mean...i change the mount order via gameinfo.txt and mount.cfg manually even, but the problem still occurs. lol

**Comment by robotboy655** [comment] 2020-07-22 01:57
gameinfo.txt doesn't do anything. I am not sure mount.cfg is ran before game mounting, altho you can just not mount games in game and only use mount.cfg.

Either way, Duplicate of #4445.

**Closed by robotboy655** 2020-07-22 01:57 UTC
