### ISSUE TITLE
Some model meshes created using util.GetModelMeshes are rotated

### ISSUE THREAD

**Issue by shadowscion** [Facepunch/garrysmod-issues#4582] opened 2020-07-13 15:22 UTC
### Details
I'm on x86-64 branch.
Seemingly random model meshes are generated with incorrect rotation (+90 degrees yaw). This is trivial to fix manually, but there is no automatic way that I can think of to determine in code when or why it happens. 

### Steps to reproduce
A few of the affected models I have found include:
* models/props_phx/construct/metal_plate1.mdl 
* models/props_c17/door01_left.mdl 
* models/props_c17/TrapPropeller_Blade.mdl 
* models/Gibs/helicopter_brokenpiece_01.mdl 

This is the code I've used to test. Simply spawn a prop and aim at it. 
```
    local meshes = {}
    local wire = Material("models/wireframe")
    local aimMat = Matrix()
    local aimEnt

    hook.Add("PostDrawOpaqueRenderables", "meshtest", function()
        local trace = LocalPlayer():GetEyeTrace().Entity
        if aimEnt ~= trace and trace:GetClass() == "prop_physics" then
            aimEnt = trace
            for i, m in ipairs(meshes) do
                if m.obj:IsValid() then
                    m.obj:Destroy()
                end
            end
            meshes = {}

            local modelpath = aimEnt:GetModel()
            local modelmesh = util.GetModelMeshes(modelpath)
            if modelmesh then
                for i, part in ipairs(modelmesh) do
                    local obj = Mesh()
                    obj:BuildFromTriangles(part.triangles)
                    meshes[i] = { obj = obj, mat = Material(part.material) }
                end
            end
        end

        if IsValid(aimEnt) then
            local ang = aimEnt:GetAngles()
            local pos = aimEnt:GetPos()
            aimMat:SetAngles(ang)
            aimMat:SetTranslation(pos)
        end

        cam.PushModelMatrix(aimMat)
        for i, m in ipairs(meshes) do
            if not m.obj:IsValid() then continue end
            render.SetMaterial(m.mat)
            m.obj:Draw()
            render.SetMaterial(wire)
            m.obj:Draw()
        end
        cam.PopModelMatrix()
    end)
```

**Comment by thegrb93** [comment] 2020-07-13 15:33
I assume it maybe due to the $origin command.

**Comment by thegrb93** [comment] 2020-07-13 15:35
For gibs, $autocenter may also cause it.

**Comment by robotboy655** [comment] 2020-07-13 15:51
I'd say it is very likely the default "idle" `$sequence` rotates them by that much and that is not taken into account by the function. (and won't be). Essentially you'd probably want this: https://github.com/Facepunch/garrysmod-requests/issues/1404

**Comment by shadowscion** [comment] 2020-07-13 16:01
So is a lookup table with known models the best approach to working around it?

**Comment by robotboy655** [comment] 2020-07-13 16:08
For the time being I suppose so. I am closing this as a Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1404
The extra data should solve your issues, no ETA on when that request will be fulfilled though

**Closed by robotboy655** 2020-07-13 16:08 UTC
