### ISSUE TITLE
Garry's Mod crashes when trying to save with DRGBase snpc's spawned.

### ISSUE THREAD

**Issue by Waltsalemastick** [Facepunch/garrysmod-issues#5406] opened 2023-02-13 23:16 UTC
Garry's Mod crashes every time I try to save with a DRGbase snpc spawned. It doesn't matter what DRGBase snpc I spawned, the game crashes with all DRGBase snpc's in general. I told the devs of DRGBase about it, and they said this is a Garry's Mod problem, not a DRGBase problem, meaning it's not something that can be solved on their end. So this seems to mean that Garry's Mod can't support saving with DRGBase Snpc's spawned. Can Garry's Mod be updated to support saving with DRGBase snpc's spawned? 
![bandicam 2023-02-13 17-06-21-402](https://user-images.githubusercontent.com/125315192/218585646-ce27608d-c599-4d1f-8d71-39a1311b6440.jpg)
If Garry's Mod can be updated to support saving with DRGBase snpc's spawned, than please do so. That would be great.

**Comment by Waltsalemastick** [comment] 2023-02-14 04:14
> Please refer to this article on how to properly report crash issues.
> 
> https://wiki.facepunch.com/gmod/Crash_Reporting



> Please refer to this article on how to properly report crash issues.
> 
> https://wiki.facepunch.com/gmod/Crash_Reporting

Okay, I put in more information to specify what the problem is better. Can you understand what I'm saying the problem is now?

**Comment by Kefta** [comment] 2023-02-14 12:24
Can you provide an mdmp?

**Comment by robotboy655** [comment] 2023-02-14 12:45
Or at least a link to addon that is affected and steps to reproduce?

**Comment by Waltsalemastick** [comment] 2023-02-14 16:02
I wish I could give you a mdmp, but it has to automatically close the game when it crashes, it freezes the game forever.
But giving you a link to the addon is something I can do. Here. https://steamcommunity.com/workshop/filedetails/?id=1560118657 All bases come with example snpc's. Just spawn one in and try saving and you'll see what happens.

**Comment by robotboy655** [comment] 2023-02-14 18:55
Will be fixed in a future game update. It was an infinite loop with `util.TableToJSON` due to that addon's weird usage of `__index`.

**Closed by robotboy655** 2023-02-14 18:55 UTC
Labels: Bug

**Comment by Waltsalemastick** [comment] 2023-02-14 20:04
Okay, that's great!
