### ISSUE TITLE
x86-64 Startup Crash on Linux

### ISSUE THREAD

**Issue by isopropyletherperoxide** [Facepunch/garrysmod-issues#5096] opened 2021-11-20 13:13 UTC
### Details
Each time i try to start Garry's Mod on the x86-64 branch it crashes with no error message.
The game runs fine on **dev** and normal branches, only crashing on **chromium** and **x86-64**
I have attempted factory resets and integrity checks to no avail.
OS: Gentoo/Linux x86_64 
UPDATE: **dev** branch crashes on map launch, but main branch works fine
Crash logs:
```
-Lua Stack Traces-
==================
  Client
    Lua Interface = NULL

  Server
    Lua Interface = NULL

  MenuSystem
    Lua Interface = NULL

-Console Buffer-
================
1(7.297573):  Attempting to load Chromium...
```

### Steps to reproduce
Start Garry's Mod via Steam.

**Comment by FlorianLeChat** [comment] 2021-11-20 13:42
Duplicate of #5092 ?

**Comment by isopropyletherperoxide** [comment] 2021-11-21 09:58
UPDATE: Trying to launch the game through terminal gives me a missing library error.
`Game_client.so loaded for "Garry's Mod"
[1121/114557.391686:INFO:cpu_info.cc(53)] Available number of cores: 8
[1121/114557.391765:VERBOSE1:zygote_main_linux.cc(215)] ZygoteMain: initializing 0 fork delegates
[1121/114557.396474:VERBOSE1:pref_proxy_config_tracker_impl.cc(184)] 0x7f24ac05bcc0: set chrome proxy config service to 0x7f24ac05c440
[1121/114557.397647:VERBOSE1:webrtc_internals.cc(120)] Could not get the download directory.
[1121/114557.420696:ERROR:gl_implementation.cc(277)] Failed to load /home/arylhalide/.local/share/Steam/steamapps/common/GarrysMod/bin/linux64/swiftshader/libGLESv2.so: /home/arylhalide/.local/share/Steam/steamapps/common/GarrysMod/bin/linux64/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[1121/114557.420768:VERBOSE1:gpu_init.cc(308)] gl::init::InitializeStaticGLBindingsOneOff failed
[1121/114557.421522:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[1121/114557.453341:VERBOSE1:sandbox_linux.cc(69)] Activated seccomp-bpf sandbox for process type: gpu-process.
[1121/114557.455391:WARNING:gpu_process_host.cc(1165)] The GPU process has crashed 1 time(s)
[1121/114557.477466:VERBOSE1:sandbox_linux.cc(69)] Activated seccomp-bpf sandbox for process type: gpu-process.
[1121/114557.479539:WARNING:gpu_process_host.cc(1165)] The GPU process has crashed 2 time(s)
[1121/114557.504306:VERBOSE1:sandbox_linux.cc(69)] Activated seccomp-bpf sandbox for process type: gpu-process.
[1121/114557.506494:WARNING:gpu_process_host.cc(1165)] The GPU process has crashed 3 time(s)
[1121/114557.506534:FATAL:gpu_data_manager_impl_private.cc(1034)] The display compositor is frequently crashing. Goodbye.
fish: './hl2.sh' terminated by signal SIGILL (Illegal instruction)`

**Comment by Zentropivity** [comment] 2022-03-14 20:28
Can confirm. For some reason the GLES libraries are looked for in `bin/linux64/swiftshader` while they really are just in `bin/linux64`.

In my case the game starts after making a symlink for it.
In `bin/linux` : `ln -s . swiftshader`

(No menu UI is visible though. oof)

**Comment by melvyn2** [comment] 2022-04-28 04:03
I had the same issue, same results with the swiftshader symlink, rather https://github.com/Facepunch/garrysmod-issues/issues/5092#issuecomment-1054453220 fixed it fully

**Comment by coreybruce** [comment] 2022-06-14 14:58
Is this being fixed?

**Comment by Ohio2** [comment] 2022-07-02 22:27
Sadly it does not seem to be fixed yet.

**Comment by coreybruce** [comment] 2022-07-02 22:47
That's a pain, like how is this a issue that still hasn't been fixed?

**Comment by Ohio2** [comment] 2022-07-03 20:18
No bloody idea, @robotboy655, could you perhaps get on this?

**Comment by stevenlafl** [comment] 2022-07-30 01:26
Same issue. Kubuntu Desktop

**Comment by Delofon** [comment] 2022-08-19 01:25
I second this. Not even Proton helps.
P.S. Linux Mint 21 Cinnamon

**Comment by ThePademelon** [comment] 2023-04-10 02:35
Same issue on Void Linux and was fixed by https://github.com/Facepunch/garrysmod-issues/issues/5092#issuecomment-1054453220
Didn't have to do anything else.

**Closed** 2024-03-26 18:21 UTC
Labels: Platform: Linux

**Comment by BubbaFrog** [comment] 2025-05-02 01:37
linux already has 22.1 and it still ain't fixed it crashes right on startup when it says initialing server
