### ISSUE TITLE
BuildBonePositions callback doesn't work for prop_ragdoll

### ISSUE THREAD

**Issue by Ramalayha** [Facepunch/garrysmod-issues#3787] opened 2019-03-11 23:42 UTC
Pretty straight forward, Entity:AddCallback("BuildBonePositions",...) doesn't seem to do anything when used on a prop_ragdoll entity.

**Comment by Kefta** [comment] 2019-03-15 08:57
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/207.

**Closed** 2019-03-15 18:46 UTC
