### ISSUE TITLE
Crash on Linux 

### ISSUE THREAD

**Issue by ThePierrezou** [Facepunch/garrysmod-issues#1869] opened 2015-03-11 19:15 UTC
I'm using archlinux with the radeon driver, i have a amd radeon HD6450
When i try to launch it with steam, the game have a blue backround, it say loading and it crash.
When i try to launch with the shell it does this : https://gist.github.com/ThePierrezou/4604abeb2819f27735e2

At the installation of steam i have used this trick, but i think it's not that : https://wiki.archlinux.org/index.php/steam#Using_native_runtime

**Comment by robotboy655** [comment] 2015-03-11 19:16
Duplicate of #1833

**Closed by robotboy655** 2015-03-11 19:16 UTC

**Comment by ThePierrezou** [comment] 2015-03-11 20:27
I don't uderstand, the error is not the same, but anyway if you think it's the same bug and you will resolve it, it's not a problem.

**Comment by Bo98** [comment] 2015-03-11 21:04
Verify your game. Also check if client.so exists in the bin folder.

**Comment by Bo98** [comment] 2015-03-11 21:05
Verify your game. Also check if client.so exists in your GarrysMod/garrysmod/bin folder.

**Comment by ThePierrezou** [comment] 2015-03-11 22:54
I have tried to re-install the game and it's the same.
Yeah, i have client.so but the game don't work anyway.

**Comment by G7Nation** [comment] 2015-06-29 17:10
I have the same issue with Ubuntu 14.04 64-bit and a Radeon HD 7750 GPU.  I tried the dev branch and that's busted too.  It seems like this problem has been around for a while with various workarounds along the way, however, the old workarounds aren't working for me.  client.so is in the correct location.  I know no software is without bugs, but for non-free game, this really needs to be fixed.  I'm happy to volunteer my time if it will lead to a proper fix, so please let me know what other information you need and I will give it to you ASAP.  Thanks.

$ cat garrysmod.ver 
150628
0059
ECHO is on.
513
$ cat steam.inf 
PatchVersion=15.06.04
ProductName=garrysmod
appID=4000
$ ll garrysmod/bin/
total 37860
-rwxrwxr-x 1 boom boom 13436671 Jun 29 12:49 client.so
-rwxrwxr-x 1 boom boom   265349 Jun 26 18:08 game_shader_generic_garrysmod.so
-rwxrwxr-x 1 boom boom   212675 Jun 26 18:07 gmhtml.so
-rwxrwxr-x 1 boom boom   538043 Jun 26 18:08 lua_shared.so
-rwxrwxr-x 1 boom boom  3360902 Jun 29 12:49 menusystem.so
-rwxrwxr-x 1 boom boom  1376787 Jun 26 18:08 resources.so
-rwxrwxr-x 1 boom boom 19562682 Jun 29 12:49 server.so
$ ./hl2.sh
SDL video target is 'x11'
SDL video target is 'x11'
This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system DOES NOT support the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system supports the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system supports the OpenGL extension GL_ARB_debug_output.
This system supports the OpenGL extension GL_EXT_direct_state_access.
This system DOES NOT support the OpenGL extension GL_NV_bindless_texture.
This system supports the OpenGL extension GL_AMD_pinned_memory.
This system DOES NOT support the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system DOES NOT support the OpenGL extension GL_NVX_gpu_memory_info.
This system supports the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system DOES NOT support the OpenGL extension GL_EXT_texture_compression_dxt1.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt3.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt5.
This system DOES NOT support the OpenGL extension GLX_EXT_swap_control_tear.
GL_NV_bindless_texture: DISABLED
GL_AMD_pinned_memory: DISABLED
GL_EXT_texture_sRGB_decode: AVAILABLE
Setting breakpad minidump AppID = 4000
dlopen failed trying to load:
/home/boom/.local/share/Steam/linux32/libsteam.so
with error:
/home/boom/.local/share/Steam/linux32/libsteam.so: cannot open shared object file: No such file or directory
dlopen failed trying to load:
libsteam.so
with error:
libsteam.so: cannot open shared object file: No such file or directory
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198090623523 [API loaded no]
Found joystick 'Logitech Logitech Extreme 3D' (030000006d04000015c2000010010000), but no recognized controller configuration for it.
GL_NVX_gpu_memory_info: UNAVAILABLE
GL_ATI_meminfo: AVAILABLE
GL_ATI_meminfo: GL_TEXTURE_FREE_MEMORY_ATI: Total Free: 1883835, Largest Avail: 1752676, Total Aux: 2019243, Largest Aux Avail: 2332
GL_MAX_SAMPLES_EXT: 8
IDirect3DDevice9::Create: BackBufWidth: 1680, BackBufHeight: 1050, D3DFMT: 3, BackBufCount: 1, MultisampleType: 0, MultisampleQuality: 0
GL sampler object usage: ENABLED
GL prefer MapBufferRange: NO
Could not load program cache file glbaseshaders.cfg
Could not find base GL shader cache file
Could not load program cache file glshaders.cfg
Could not find user GL shader cache file
Precache: Took 0 ms, Vertex 0, Pixel 0
Couldn't load: \home\boom\.local\share\Steam\SteamApps\common\GarrysMod\garrysmod\bin\client.so
Reason: \home\boom\.local\share\Steam\SteamApps\common\GarrysMod\garrysmod\bin\client.so: cannot open shared object file: No such file or directory

**Comment by mcd1992** [comment] 2015-07-01 15:25
Make sure you guys have the 32 bit shared libraries for your nvidia/radeon drivers. For arch linux you'll need to enable the multilib repository.

**Comment by G7Nation** [comment] 2015-07-03 15:01
Thanks for the quick response.  I'll give it a try and get back to you.
