### ISSUE TITLE
[x86-x64] Small constraint distances are crashing the game

### ISSUE THREAD

**Issue by adamnejm** [Facepunch/garrysmod-issues#4631] opened 2020-08-10 15:00 UTC
### Description
Small distances between `rope` and `slider` constraints are causing crashes.
Distance of `0.00001` is fine and works as expected.
Distance of `0.000001` or lower will cause the issue described here.
When constraint is created on frozen entities, attempting to move them will cause the crash.

### Testing
**This does NOT affect the `default` branch of Garry's Mod, the prop(s) are being safely removed!**
- `x86-x64 - Chromium + 64-bit binaries` branch.
- `Peer-to-peer` & `Local server`
- `prop_physics` & `gmod_light` (any models)  

### Reproducing
Assume that `ent1` and `ent2` are in the same position.
Note that that doesn't have to be the case, only the relative origin and target positions of the constraint matter.
  
Any of the following lines will cause the game to crash:
```lua
constraint.Rope(ent1, ent2, 0, 0, Vector(), Vector(), 0, 0, 0, 1, "cable/rope", false)
constraint.Rope(ent1, ent2, 0, 0, Vector(0, 0, 0.000001), Vector(), 0, 0, 0, 1, "cable/rope", false)

constraint.Slider(ent1, ent2, 0, 0, Vector(), Vector(), 1, "cable/cable")
constraint.Slider(ent1, ent2, 0, 0, Vector(0, 0, 0.000001), Vector(), 1, "cable/cable")
```
Any of the following lines will **NOT** crash (`0.000001` vs `0.00001`):
```lua
constraint.Rope(ent1, ent2, 0, 0, Vector(0, 0, 0.00001), Vector(), 0, 0, 0, 1, "cable/rope", false)
constraint.Slider(ent1, ent2, 0, 0, Vector(0, 0, 0.00001), Vector(), 1, "cable/cable")
```
Testing code & proof that entities don't have to be at the same position:
```lua

local function spawnEnt(pos)
	local ent = ents.Create("prop_physics")
	ent:SetModel("models/hunter/blocks/cube025x025x025.mdl")
	ent:SetPos(pos)
	ent:SetAngles(Angle())
	ent:Spawn()
	
	return ent
end

local ent1 = spawnEnt(Vector(0,0,0))
local ent2 = spawnEnt(Vector(10,20,30))
local pos = ent1:WorldToLocal(ent2:GetPos())

constraint.Rope(ent1, ent2, 0, 0, pos, Vector(), 0, 0, 0, 1, "cable/rope", false)
```

**Comment by GitSparTV** [comment] 2020-08-10 15:02
Have you tried 0?
Because I have a feeling it just clamps to 0 due to double to float conversion

**Comment by adamnejm** [comment] 2020-08-10 15:26
>Have you tried 0?

What do you mean?
Distance of `0` is in the first line of code I've posted:
```lua
constraint.Rope(ent1, ent2, 0, 0, Vector(), Vector(), 0, 0, 0, 1, "cable/rope", false)
```
As `Vector()` will return a vector with all three components equal to `0`.
If any of the vector components equal or lower than `0.000001` gets reliably rounded to `0` then yes, I'd assume it only crashes on `0`.

**Comment by thegrb93** [comment] 2020-08-11 00:47
It's not self induced. Vanilla duplicator can be rigged with these black holes

**Comment by Kefta** [comment] 2020-08-11 04:06
Self-induced by options. It will still be taken care of.

**Comment by robotboy655** [comment] 2020-08-11 14:59
Yeah it crashes in vphysics, probably due to x64's vphysics being newer. There's not much we can really do here, besides limiting the rope constraint length to be above a certain threshold, which I think is reasonable. I could not reproduce a crash with Sliders though.

**Comment by robotboy655** [comment] 2020-08-11 16:15
I have put out a fix for the rope issue. If you can't/won't provide a way to reproduce the crash issue with sliders, I will be considering this issue solved completely after some time.

**Comment by adamnejm** [comment] 2020-08-11 16:27
Will test the sliders as soon as I get home.

**Comment by adamnejm** [comment] 2020-08-11 18:43
I've only limited this testing to the `slider` constraint on a P2P server, hope it's enough.

From what I can gather it's not happening for all models.
The models that are crashing don't necessarily have to concave, but I think the distance between vertices matters.
Let's take `hunter` cube models as an example:

`models/hunter/blocks/cube025x025x025.mdl` *(source units: `12.3125 x 12.3125 x 12.3125`)* - will not cause any crashes
`models/hunter/plates/plate.mdl` *(source units: `3.5 x 3.5 x 3.5`)* - will crash the game

I couldn't often crash my game when combining safe models with the models that are causing crashes.
For example if I spawned the two previously mentioned models and link them with a constraint, the game will not crash and the constraint will be created as usual.
There is one case that I know of, but it includes model from an addon, so I'm gonna skip that.

[Crash dump <sub>*(dropbox)*</sub>](https://www.dropbox.com/s/v1zgwbsoexg1sxy/00c32c7a-89e3-41d7-aa16-33a9a882fa65.dmp?dl=1) caused by constraining two props with second model mentioned earlier (`plate.mdl`).

Below is the code I've used for testing. It includes a small list of models - both safe and the crashing ones.
I've also decided to test for validity of the bones so not to mislead the cause of the crashes.

```lua

local mdl

-- SAFE MODELS
mdl = "models/hunter/blocks/cube025x025x025.mdl"
mdl = "models/hunter/blocks/cube05x05x05.mdl"
mdl = "models/hunter/blocks/cube2x2x2.mdl"
mdl = "models/hunter/plates/plate3x3.mdl"
mdl = "models/hunter/triangles/075x075.mdl"

-- CRASHING MODELS
mdl = "models/hunter/plates/plate.mdl"
mdl = "models/hunter/triangles/025x025.mdl"
mdl = "models/hunter/triangles/05x05.mdl"
mdl = "models/props_phx/construct/metal_angle90.mdl"
mdl = "models/props_c17/FurnitureFridge001a.mdl"

local function spawnEnt(pos, mdl)
	local ent = ents.Create("prop_physics")
	ent:SetModel(mdl)
	ent:SetPos(pos)
	ent:SetAngles(Angle())
	
	if ent:GetBoneName(0) == "__INVALIDBONE__" then
		print("invalid root bone!")
		ent:Remove()
	else
		ent:Spawn()
	end
	
	return ent
end

local ent1 = spawnEnt(Vector(), mdl)
local ent2 = spawnEnt(Vector(), mdl)

if ent1 and ent1:IsValid() and ent2 and ent2:IsValid() then
	constraint.Slider(ent1, ent2, 0, 0, Vector(), Vector(), 1, "cable/cable")
end
```

If you are able to reproduce it this time, I think it's enough proof to also limit the `slider` constraint just like you did with `rope`.
If I'm not getting into the specifics of the crashes enough or missing a point somewhere in my testing, please let me know.

**Comment by robotboy655** [comment] 2020-08-12 15:29
Thanks, should be fixed.

**Closed by robotboy655** 2020-08-12 15:29 UTC
Labels: Complexity: Low, Crash, Dependency: IVP, Self-induced crash
