### ISSUE TITLE
Entity:EmitSound on server not calling EntityEmitSound hook on client

### ISSUE THREAD

**Issue by darkjacky** [Facepunch/garrysmod-issues#2514] opened 2016-03-17 20:07 UTC
If I call Entity:EmitSound on the server the EntityEmitSound hook is called on the server but not on the client.
I am not sure if this is a bug or intentional.
The only way around this at the moment seems to be to net.Start() net.SendPAS() the sound and call Entity:EmitSound on the client.

**Comment by darkjacky** [comment] 2016-03-17 20:11
I will add that the reason for doing this is because I am doing Entity:EmitSound on the server. And I was expecting Entity:SetPreventTransmit to also stop any sound from broadcasting. But it does not. < That might be a separate bug.

**Comment by robotboy655** [comment] 2016-03-17 20:39
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/198

**Closed by robotboy655** 2016-03-17 20:39 UTC

**Comment by darkjacky** [comment] 2016-03-17 20:41
I see. I did search it did not come up.
