### ISSUE TITLE
Map cleanup removes weapon_bugbait from players weapons

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3816] opened 2019-04-19 15:07 UTC
### Details
Yeah, that's basically it.
game.CleanUpMap() removes bugbait weapons.

### Steps to reproduce
Equip a bugbait.
Clear map.

**Comment by ZehMatt** [comment] 2019-04-19 16:10
Pretty sure thats supposed to happen and is not a bug, game.CleanUpMap(), the purpose is it will remove everything and basically reverts the map to its original load state.

**Comment by mcNuggets1** [comment] 2019-04-19 16:11
Yeah, but it removes the bugbait weapon from players which doesn't make sense to me.

**Comment by ZehMatt** [comment] 2019-04-19 16:14
Thats what it does and always did and what is expected, every weapon should disappear not just the bugbait if I recall correctly.

**Comment by mcNuggets1** [comment] 2019-04-19 16:14
No, just the bugbait.

**Comment by ZehMatt** [comment] 2019-04-19 16:21
Oh thats actually indeed strange, never noticed it as my gamemode just respawns players at the beginning of the map.

**Comment by robotboy655** [comment] 2019-04-23 16:09
Bugbait wasn't the only weapon affected - all HL:S weapons and the NPC only HL2 weapons were affected too, but fixed now.

**Closed by robotboy655** 2019-04-23 16:09 UTC
