### ISSUE TITLE
Left 4 Dead 2 Map c12m4_barn  crashes the game

### ISSUE THREAD

**Issue by TheBillinator3000** [Facepunch/garrysmod-issues#4808] opened 2021-01-25 02:23 UTC
The title says it all.

I don't know if its on my end or not. The problem might exist on Left 4 Dead but I have yet to check.

I was using the dev branch, no addons, and I made sure Left 4 dead 2 had all of its files. 

Steps to reproduce:
Mount Left 4 Dead 2
Load up c12m4_barn.

I sent you the .mdmp file via email.

Notes: This isn't _that_ big of an issue for me, I was just going through games in GMod to see how they worked. If you don't intend to fix it, that's ok. I'm just reporting it.

🙃

**Comment by robotboy655** [comment] 2021-01-25 13:36
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/4798

**Closed by robotboy655** 2021-01-25 13:36 UTC
