### ISSUE TITLE
Issues regarding December 2017 update

### ISSUE THREAD

**Issue by roboderpy** [Facepunch/garrysmod-issues#3349] opened 2017-12-22 00:55 UTC
This update needs to be hotfixed, because:
* BASS Library update now randomly plays OGGs
* If BASS failed to play OGG one time because file is missing, it will produce warning in console as "missing sound from disk". However, if (re-)mount GMA using game.MountGMA with this sound, playing this sound will actually do nothing (no warnings and no sound)
* (Still not fixed but got worse) Mounting a GMA using game.MountGMA before full-packet update is fully received and applied crashes the game
* Creating a render targets on various machines producing issues, including
  * Creating a render target before ANYTHING is drawn (before RenderScene is called) produce de-facto 1x1 render targets
  * These render targets can not be used for rendering (drawing inside them produces no result, only  :Download() and render.Clear works, sometimes if player is lucky, rendering in them after RenderScene has been called will produce expected result), but they still act as 512x512 (or whatever you specified) render targets (memory consumption, :Width(), :Height() returns actual sizes)
   * Intel HD Graphics users now are completely fuckedup
  * [Steam screenshots](http://steamcommunity.com/workshop/filedetails/discussion/933203381/2906376154327562580/) [Steam memory command report](http://steamcommunity.com/workshop/filedetails/discussion/933203381/1291817208498628320/?ctp=32) (memory report because Willox told me on Steam about fixing render targets memory overflow)
* **ALL** VGUI elements with Close/Move/Resize buttons from DFrame has weird padding and buttons has weird size
![25c99e5ca1_hl2_2017-12-21_10-45-32](https://user-images.githubusercontent.com/6339511/34280803-f6c1f576-e6ec-11e7-8ba9-c3cbd4728de9.png)
![lol](https://i.dbot.serealia.ca/2017/12/8b30f71f0f_hl2_2017-12-22_08-07-41.png)
* Randomly BASS crashes without crashing the game. No errors in console or something, just all sounds stop from playing which should play through BASS
* @CapsAdmin
![caps](https://i.dbot.serealia.ca/2017/12/3fecaa71da_DiscordCanary_2017-12-22_07-55-28.png)

**Comment by roboderpy** [comment] 2017-12-22 00:58
I could miss something, because there is really many issues

**Comment by robotboy655** [comment] 2017-12-22 02:12
There was no BASS.DLL update since 2016. The vgui elements weirdness will have to be fixed by the mod authors.

**Comment by RenTec** [comment] 2017-12-22 07:25
Then whats up with all the BASS issues coming up from various people across the forums? I can't get even the basic wiki example to work for sound.PlayFile() and other peoples code examples that worked when they posted it don't work. All this on vanilla code with no addons. Seems like there is a bug but it's only affecting a small percentage of people.

**Comment by robotboy655** [comment] 2017-12-22 18:38
Also please do not post multiple different problems in one issue. if you are going to post a problem with Lua functionality like the rendertargets or w/e, post code to reproduce.

**Closed by robotboy655** 2017-12-22 18:38 UTC

**Comment by roboderpy** [comment] 2017-12-22 23:56
@robotboy655 the problem is - i can't reproduce rendertargets problem by myself.  Please explain clearly what exactly got changed in them.

**Comment by roboderpy** [comment] 2017-12-23 00:02
I'm getting spammed at Discord, Steam, Github. And i can't even do anything to solve it because it basically doesn't happen to me, but happens for plenty of users.

**Comment by robotboy655** [comment] 2017-12-23 00:42
The only change to rendertargets judging from the commit messages was that they no longer allowed to have TEXTUREFLAGS_ENVMAP in Lua. That's it. 

Perhaps it is related to multicore rendering?

**Comment by roboderpy** [comment] 2017-12-23 00:43
I don't know, which multicore rendering? `gmod_mcore_test` or Multicore rendering in video settings? I already told all to disable `gmod_mcore_test`, but it has no effect.

**Comment by robotboy655** [comment] 2017-12-23 01:04
There's only one mcore rendering.

To Enable:
```
gmod_mcore_test 1
mat_queue_mode -1
```
To disable:
```
gmod_mcore_test 0
mat_queue_mode 0
```

Keep in mind autoexec's and launch parameters.

**Comment by roboderpy** [comment] 2017-12-23 13:34
Pardon about rendertargets, seems like Discord update issue.

**Comment by robotboy655** [comment] 2017-12-23 14:46
Yeah overlays are known to cause problems with the game.
