### ISSUE TITLE
.ogg files have a SoundDuration of 0 on Linux

### ISSUE THREAD

**Issue by Sampleeeee** [Facepunch/garrysmod-issues#4814] opened 2021-01-29 20:22 UTC
### Details
When running `SoundDuration` on the server, it shows my `.ogg` file as 0 seconds. Server is running Ubuntu 20.04
I would assume this is the same issue with wav files. The wiki says that on Linux and MacOS .wav files always return 0

### Steps to reproduce
```lua
-- server
concommand.Add("gettime", function()
    print(SoundDuration(Sound("music.ogg")))
    -- prints 0
end)```

**Comment by robotboy655** [comment] 2021-01-29 21:07
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/936

**Closed by robotboy655** 2021-01-29 21:07 UTC
