### ISSUE TITLE
do_constraint_system: Couldn't invert rot matrix!

### ISSUE THREAD

**Issue by nutellabrot2** [Facepunch/garrysmod-issues#5374] opened 2022-12-23 21:57 UTC
Hi,

do_constraint_system: Couldn't invert rot matrix!

This error is spammend in my Console when i spawn a car or anything, The props also just freeze in the air

**Comment by robotboy655** [comment] 2022-12-24 01:04
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5274

**Closed by robotboy655** 2022-12-24 01:04 UTC

**Comment by nutellabrot2** [comment] 2022-12-24 18:24
so i cant fix it or what?!

**Comment by Kefta** [comment] 2022-12-25 01:30
Read my comment on the duplicate issue.
