### ISSUE TITLE
Gmod crash in Half Life 2 

### ISSUE THREAD

**Issue by kem008** [Facepunch/garrysmod-issues#2384] opened 2016-01-14 12:11 UTC
I just wanted to play some Hl2 in gmod and here I found somekind of interesting bug
Maps
``` d3_c17_04 ``` -- Sometimes supply box can crash the server if you throw it with gravity gun and brake it and somekind of interesting unknown stuff can crash it after you see the first striders
``` d3_c17_05 ``` -- If you go through the first building and then climb the stairs to the big building with much of metrocops you will crash on the next down floor :(
``` Maybe others ```

I don't know if other ``` d3_c17_* ``` are crashing too, but these maps not crashing:
``` d3_c17_01-02-03 ```

**Comment by Jvs34** [comment] 2016-01-14 12:50
Crash dumps of the issue would be pretty nice for the developers, you can find them in your gmod folder near the .exe, and then post the link of the uploaded files here.

And don't post crash dumps made with older versions of gmod please.

**Comment by kem008** [comment] 2016-01-14 13:09
Okay they will be the current versions because happened yesterday and today :D

**Comment by robotboy655** [comment] 2016-01-14 13:22
```d3_c17_04``` I am assuming you are talking about the Combine Mines, the crash with them was fixed.

**Comment by kem008** [comment] 2016-01-14 13:24
Here 
[dropbox](https://www.dropbox.com/sh/iox549b9tg0hltd/AACYjSe6_pw_kTgXdxZBNGBra?dl=0)
No I tested it today and it crash. Sometimes npc_headcrab can crash the combine_mine or player if contact weird.

**Comment by robotboy655** [comment] 2016-01-14 13:28
I am going to assume that both are caused by the Combine Mine crash that was fixed in Dev branch.

**Closed by robotboy655** 2016-01-14 13:28 UTC
