### ISSUE TITLE
Recent update causing a game crash due to Physics Interactions.

### ISSUE THREAD

**Issue by MagentaIris** [Facepunch/garrysmod-issues#5703] opened 2024-01-21 18:01 UTC
A recent update to Gmod seems to be causing the game to crash during a specific part of depot_01.bsp

This never used to happen before the most recent update.

You can find depot_01 here [Depot_01 files](https://www.moddb.com/mods/depot)

Heres the dmp 
[03c14a86-1b30-4188-bac5-45e52b0bd53b.dmp](https://github.com/Facepunch/garrysmod-issues/files/14002251/03c14a86-1b30-4188-bac5-45e52b0bd53b.dmp)

When entering the second rusted ship with the antlion grubs, an antlion guard digs up from the ground and breaks the wall behind you, When the physics objects of this wall hit the edges of the boat/collision the game crashes.

Again to mention this has never happened before the 2 most recent updates.

**Comment by robotboy655** [comment] 2024-01-22 13:59
I cannot reproduce this. No matter how many times I throw those created props at any wall, nothing happens.

The crash dump you attached is also not physics related, but has something to do with AI nodes.

I am assuming this is the spot you are talking about:
![image](https://github.com/Facepunch/garrysmod-issues/assets/3299036/c83e7477-4d12-432c-979a-6f0db781eecb)

**Comment by MagentaIris** [comment] 2024-01-22 14:06
That's right yeah, that's weird.

I'm unsure how a crash can happen related to AI nodes since they're just reference data, unless it's the antlion guard itself in the dmp?

This one has me confused.

**Comment by robotboy655** [comment] 2024-01-22 14:28
How often/consistent is the crash for you? What gamemode are you playing the map in? Does it happen if you just noclip to that spot?

**Comment by MagentaIris** [comment] 2024-01-22 14:32
I have noclipped there yes, it happens on and off. Sometimes it does crash, sometimes it doesnt.

I've tried it in Sandbox a bunch which only crashed one time out of 20 attempts (I restarted the game per try)

However in Temporal Assassin it happened about 11-12 times out of 20, I will admit I do a little bit of NPC "funny" in Temporal Assassin such a some soft speed modifications but I don't actively mess with AI Nodes or the Antlion Guards actual AI.

The physics environment in TA is changed though, which is why I thought it may have been the cause, but after changing the physics environment on map load in Sandbox to be the same as TA it doesn't crash so it being linked to AI checks out.

**Comment by robotboy655** [comment] 2024-01-22 14:37
What is "Temporal Assassin"? Is that a gamemode? Can you it link for me?

**Comment by MagentaIris** [comment] 2024-01-22 14:40
> What is "Temporal Assassin"? Is that a gamemode? Can you it link for me?

It is yes.

Developed by myself, you can find it here: https://docs.google.com/document/d/1CoPKXJG31M5VLLoqdZ9yS9xov0OT_ud1hM5Bf-fEfak

Or here: https://www.moddb.com/mods/temporal-assassin

Can't put it on the workshop due to limited file hierarchy/types.

**Comment by MagentaIris** [comment] 2024-01-23 14:00
Found another crash, unsure if its related to the same thing. Noclipping on d1_canals_01a above the trains and going forward to a specific point causes the game to crash. Possibly a trigger in the map failing to do something?

MDMP: [8f305240-a51d-4ba8-ad3a-e9756f5571f9.dmp](https://github.com/Facepunch/garrysmod-issues/files/14024920/8f305240-a51d-4ba8-ad3a-e9756f5571f9.dmp)

Exact position the game froze and died: 
![image](https://github.com/Facepunch/garrysmod-issues/assets/4176672/a749c576-7a20-4866-a63b-e51dcffa5188)

Tried this multiple times too, sometimes it doesnt crash, sometimes it crashes shortly after reaching that position, sometimes it crashes when a certain npc gets killed.

**_This never, EVER used to happen before the recent updates._**

**Comment by robotboy655** [comment] 2024-01-23 16:19
Okay, thanks for this info, I was able to reproduce the issue more consistently with your gamemode + `d1_canals_01a`, I think I know what is happening, so it should be fixed on `dev` and `x86-64` soon.

**Closed by robotboy655** 2024-01-23 16:19 UTC
Labels: Crash, Regression

**Comment by MagentaIris** [comment] 2024-01-23 17:13
> Okay, thanks for this info, I was able to reproduce the issue more consistently with your gamemode + `d1_canals_01a`, I think I know what is happening, so it should be fixed on `dev` and `x86-64` soon.

Nice, May I get more insight/info into what the issue was?

**Comment by robotboy655** [comment] 2024-01-23 17:31
It's due to changes to `game.CleanUpMap` removing entities at tick end.
