### ISSUE TITLE
Using camera data from view models (VM:GetAttachment(X)) inside calc view causing VM particles to screw up

### ISSUE THREAD

**Issue by MagentaIris** [Facepunch/garrysmod-issues#1421] opened 2014-08-13 22:24 UTC
For some reason using get attachment inside a calc view hook and using that data for view origins/angles causes view model particles on attachments to be rendered at a completely different FOV than what the view models FOV actually is.

**Comment by Kefta** [comment] 2020-05-06 04:18
Basically a duplicate of https://github.com/Facepunch/garrysmod-issues/issues/1255.

**Comment by Kefta** [comment] 2020-05-06 06:33
A fix was posted here for correctly translating view model attachment data, see the bottom example: https://wiki.facepunch.com/gmod/Entity:GetAttachment

This can be closed.

**Comment by robotboy655** [comment] 2020-05-06 13:40
https://github.com/Facepunch/garrysmod-issues/issues/4481

**Closed by robotboy655** 2020-05-06 13:40 UTC
