### ISSUE TITLE
SoundDuration returns 0 in server side.

### ISSUE THREAD

**Issue by hanm13** [Facepunch/garrysmod-issues#3306] opened 2017-09-24 20:00 UTC
Bug : SoundDuration will return 0 in the server side

Example : 
`print(SoundDuration("vo/Breencast/br_collaboration02.wav"))`

**Comment by Kefta** [comment] 2017-09-24 20:16
Related https://github.com/Facepunch/garrysmod-issues/issues/936

**Comment by hanm13** [comment] 2017-09-24 20:25
It does give the right value in the client side but not in the server side.

**Comment by hanm13** [comment] 2017-09-25 15:20
@robotboy655 can you confirm it ?

**Comment by robotboy655** [comment] 2017-09-26 08:54
No I can't, really:
![image](https://user-images.githubusercontent.com/3299036/30851471-6c54e1ac-a2b1-11e7-992d-83096fe5f488.png)

Probably duplicate of #936

**Closed by robotboy655** 2017-09-26 08:54 UTC

**Comment by hanm13** [comment] 2017-09-26 09:06
```
lua_run print(SoundDuration("msuic/hl1_song10.mp3"))
> print(SoundDuration("msuic/hl1_song10.mp3"))...
0
lua_run print(SoundDuration("msuic/hl1_song10.mp3")/2)
> print(SoundDuration("msuic/hl1_song10.mp3")/2)...
0

```


I am using Linux Centos.

**Comment by TIMONz1535** [comment] 2020-03-10 19:38
Does not work on Linux dedicated server properly, always return 0. Everything works on Windows.
