### ISSUE TITLE
Unintended interaction between Entity:FireBullets and ShouldCollide hook.

### ISSUE THREAD

**Issue by TomatoCo** [Facepunch/garrysmod-issues#5210] opened 2022-04-28 23:07 UTC
### Details

If a player and an entity do not collide as a result of the ShouldCollide hook, the player will be unable to hit the entity with bullets if the bullets are fired by the player.

Protocol version 24  
Exe version 2021.12.15 (garrysmod)  
Exe build: 17:57:22 Mar 10 2022 (8524) (4000)  
GMod version 2022.03.17, branch: unknown, multicore: 0  
Windows 32bit  

### Steps to reproduce

Hook ShouldCollide like (although this also happens if only one entity involved is a player):

```lua
hook.Add("ShouldCollide", "DisableCollisions", function(ent1, ent2)
    if ent1:IsPlayer() and ent2:IsPlayer then return false end 
end)
```

and create a weapon that fires bullets like

```lua
self:GetOwner():FireBullets(bullet)
```

The bullets will not hit the other entity. If the `if` statement is commented out, or the weapon is changed to `self:FireBullets(bullet)` then the bullets will hit.

I would expect the bullets to actually hit the other entity even if they're not colliding. It seems incorrect that ShouldCollide affects things other than physics colliding. Maybe the ShouldCollide hook could get another parameter? Or the bullet trace could have its filter not populated?

**Comment by Kefta** [comment] 2022-04-29 03:58
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/3324.

**Closed** 2022-04-29 08:40 UTC
