### ISSUE TITLE
OBBMaxs not correcting itself for Crouch hull

### ISSUE THREAD

**Issue by MagentaIris** [Facepunch/garrysmod-issues#1521] opened 2014-09-28 11:52 UTC
http://puu.sh/bR7ew/15c3ddc904.png

For some awkward reason, Crouch hulls are actually 36 on the Z scalar for vectors.

But the server AND the client return OBBMaxs 60 for crouching, and not 36 like it should be doing.

Also crouch hulls aren't networked properly so when crouching through a vent the clients movement will spaz around slightly because the client thinks the player shouldn't even be able to move around in there

**Comment by robotboy655** [comment] 2015-04-05 15:05
Duplicate of #336 apparently.

**Closed by robotboy655** 2015-04-05 15:05 UTC
Labels: bug
