### ISSUE TITLE
Linux server : quit command makes segmentation fault

### ISSUE THREAD

**Issue by UltimateByte** [Facepunch/garrysmod-issues#2342] opened 2015-12-21 01:31 UTC
As seen there : https://github.com/dgibbs64/linuxgsm/issues/544#issuecomment-166159952

The "quit" command orders a restart and makes a segmentation fault...
http://image.noelshack.com/fichiers/2015/52/1450664450-quit.png
This, on a proper linux server (Debian 8 x64, up to date).
Not sure if this is new, but it's annoying.

Please fix.
Thanks for your attention.

**Comment by UltimateByte** [comment] 2015-12-21 13:30
More info : 

Exit does the same.
Stop doesn't exist.
I bet on somebody that messed up with srcds_run at some point.

Not to mention CSS, CSGO, and other source servers can quit as expected.
So it's a specific gmod issue.

As of now, you can't quit a gmod server properly.

**Comment by mcd1992** [comment] 2015-12-21 17:36
I've had this same issue when Wiremod was installed. Do you have any addons installed, and if so does it still crash without any installed?

**Comment by UltimateByte** [comment] 2015-12-21 18:11
OK, what was a bad news is finally a good news.
My test collection contains huge addons... And guess what ?
It seems like we can now dowload addons > 64 MB !
That actually made my day ! It's slower than before, but still faster than having to upload them from FTP.

So, back to our quit command : 
Just tested on an empty server : quit works.
Tested again with a collection containing wiremod : quit doesn't work
Tested again with the same collection without wiremod : qui doesn't work
Then tested again without that collection : quit works
Then, tested a collection with 1 addon (admin gun 158421055) : quit doesn't work.

So this problem occurs as soon as you're using a collection.

Thanks @mcd1992 for helping me to figure that out.

**Comment by mcd1992** [comment] 2015-12-21 18:25
Ah no problem. Never thought about it being the collection itself. I just presumed it was wiremod since its the only workshop addon I use. The rest are legacy based addons.

**Comment by robotboy655** [comment] 2015-12-21 19:10
I can confirm this even on Windows, looking into fixing it atm

**Comment by robotboy655** [comment] 2015-12-21 20:30
Should be fixed in Dev soon.

**Closed by robotboy655** 2015-12-21 20:30 UTC
