### ISSUE TITLE
file.Exists() and file.IsDir() return different results on server and client

### ISSUE THREAD

**Issue by Erlite** [Facepunch/garrysmod-issues#4704] opened 2020-10-18 22:48 UTC
### Details
```
Protocol version 24
Exe version 2020.10.14 (garrysmod)
Exe build: 16:54:42 Oct 14 2020 (7881) (4000)
GMod version 2020.10.16, branch: x86-64, multicore: 1
Windows 64bit
```

I'm currently working on a gamemode, and wrote a moduleloader that goes inside each subdirectory of the `gamemode/` directory and loads every file depending on their name. It allows me to set a load order for certain directories and files. 

I have the following path: `scp/gamemode/scpcr-modules/logging/meta`. It's set as first in the load order, and does so successfully on the server: 

![image](https://user-images.githubusercontent.com/25248023/96387482-80e81680-11a2-11eb-8d55-f23735b932a2.png)

Now the issue is that, that exact same path cannot be found on the client:

![image](https://user-images.githubusercontent.com/25248023/96387494-b4c33c00-11a2-11eb-89c6-7790b3fa4845.png)

It does exist, as seen on the bottom of the image above, as it is loaded afterwards. 

The following code is used to check for a file/dir at the given path:
```lua
    -- Check if the path exists.
    -- loadPath is outputted in the images above (found priority etc..)
    if !file.Exists(loadPath, "LUA") then
        ErrorNoHalt(string.format(" - Cannot find path '%s'. Ignoring.\n", loadPath))
        continue
    end
```
The `scp` folder is returned by `engine.ActiveGamemode()`
It seems like there's different behavior for the `file.Exists()` and `file.IsDir()` functions on client/server as both fail to find the directory. Manually checking for files using `file.Find(loadPath .. "/*", "LUA")` is a hacky workaround I can use for now.

### Steps to reproduce
I've made a temporary repository with the code to reproduce [here](https://github.com/Erlite/gmod-issue-repro), ready to be tested in-game as the `issue` gamemode

**Comment by Kefta** [comment] 2020-10-19 02:12
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/1038.

**Closed by Kefta** 2020-10-19 02:12 UTC

**Comment by Erlite** [comment] 2020-10-19 09:36
Is this ever going to be fixed? I see the issue I'm a duplicate of is 6 years old.

**Comment by Lexa013** [comment] 2020-10-19 11:37
**It's still not fixed for 3 years, you should fix that faster please !!**

**Comment by GitSparTV** [comment] 2020-10-19 12:29
I suggest to check the existence of a file not a folder. As a temporary solution. Or just know ahead of time you have these files

**Comment by Erlite** [comment] 2020-10-19 12:42
Temporary working hacky fix:
```lua
local files, dirs = file.Find("path/to/dir*, "LUA")
-- dirs will contain dir if it exists.
```

**Comment by Erlite** [comment] 2020-10-19 14:21
Modified the wiki entries for `file.IsDir()` and `file.Exists()` to show a warning about the bug
