### ISSUE TITLE
ambient_generic screwed up

### ISSUE THREAD

**Issue by daunknownman2010** [Facepunch/garrysmod-issues#1837] opened 2015-03-09 12:32 UTC
I don't know if it's only my client doing this but it seems ambient_generic will fail to do things it's meant to do. One of the things that I've noticed is some sounds that are meant to play everywhere won't play everywhere and only play around the entity. There is also some cases where the sound emitted by ambient_generic will be in an incorrect position and the volume is all messed up. If you play through maps that use this entity (HL2 Maps), you may notice some of the bugs.

**Comment by robotboy655** [comment] 2015-03-09 15:08
Can you give specific examples of how it should work and how it works? GIve me a map name, "getpos" ( console command ) coordinates so I can load the map in CS:S or HL2 and GMod and hear the difference?

**Comment by daunknownman2010** [comment] 2015-03-09 16:14
I encountered on the map d1_trainstation_05 had one of these bugs. The citadel alarm that plays in the level is not played everywhere and presumed to be played around the radius of the ambient_generic. Also, the level seems to be missing a few other sounds too.

**Comment by robotboy655** [comment] 2015-03-09 16:57
Ok, I can confirm this problem, but it is not because of ambient_generic. I think I know why it happens, I will see what I can do.

**Comment by cr0coDiL** [comment] 2015-03-09 18:29
I can confirm it too. I hope it will be fixed soon.

**Comment by DrVrej** [comment] 2015-03-09 20:42
This happens with my map as well. I placed a fire sound near env_fire and the sound plays in HL2 EP2 fine but not in GMod. But the weird thing is if you rapidly press Admin cleanup, it sometimes fixes it but not always.

**Comment by robotboy655** [comment] 2015-03-09 22:12
On second thoughts it may be actually caused by ambient_generic, the only question is why it happens since no changes were made to that or any other entity. I guess it is somehow related, again, to the the NWVars stuff.

**Comment by DrVrej** [comment] 2015-03-10 00:40
No this happened before the update as well, I tried reporting it multiple times but I never got response. I guess people are now finally realizing it.

**Closed** 2015-04-03 16:20 UTC
Labels: bug

**Comment by Matt2468rv** [comment] 2015-04-23 21:11
Has this bug been fixed for the next update?

Recently the ambient_generic entities in my map are all screwed up too.  I was going to open an issue but searched and found this first.

This is the main issue stopping me from releasing a new map and I'm relieved to see that it's not the fault of my mapping skills.

**Comment by robotboy655** [comment] 2015-04-24 10:23
Yes.

**Comment by Matt2468rv** [comment] 2015-04-24 16:39
Great, thank you.

**Comment by Mornedil** [comment] 2015-05-29 07:45
This but is NOT fixed.

Steps to reproduce:
- Load up any map that uses looping ambient_generics
- Teleport to position 0, 0, 0
- confirm that sounds are playing there.

This seems to occur only when ambient_generics does not have the SourceEntityName keyvalue specified.
So instead of playing the sounds from the origin of the ambient_generic, the sound is played from the map's origin.

According to the Valve Developer Community, there is a bug where sounds are played at 0, 0, 0 if the ambient_generic has defined a SourceEntityName, and that entity is destroyed.
However, this bug should not happen for ambient_generics that does not specify a source entity in the first place.

**Comment by Bo98** [comment] 2015-05-29 07:46
Are you using the dev branch?

**Comment by Mornedil** [comment] 2015-05-29 07:46
no

**Comment by Bo98** [comment] 2015-05-29 07:49
The update that fixes this bug isn't out yet. If you want to test it before it's out then try the dev branch.
