### ISSUE TITLE
player_disconnect called from CParallelProcessor crashes on CLuaGamemode::CallWithArgs with !ThreadInMainThread

### ISSUE THREAD

**Issue by Python1320** [Facepunch/garrysmod-issues#697] opened 2014-01-04 17:27 UTC
```
Billyboy17: lag
Giving Охотниk a weapon_archerbow
Bad SetLocalOrigin(-15047.433594,-3763.225586,-27608.164062) on gmod_hands (334)
Giving Охотниk a weapon_archerbow
ERROR! SendData reliabe data too big (538718)[Disconnect] 4 Player [3][Pewdiepie]        (STEAM_0:0:1691126101): ERROR! Couldn't send snapshot
ERROR! SendData reliabe data too big (539567)[GM:CallWithArgs - !ThreadInMainThread] player_disconnect
[GM:CallWithArgs - !ThreadInMainThread] player_disconnect

[GM:CallWithArgs - !ThreadInMainThread] player_disconnect



[CRASH] Not on main thread! 
Signal 11 at fault (nil), caller = 0xf618acd0 with sicode 1 (Address not mapped)

Regs> gs 63 fs: 0 es: 2b ds: 2b edi: edd9f64c esi: 1 ebp: edd9f5e8 esp: edd9f1c0 ebx: edd9f1dc edx: 67 ecx: 0
    > eax: e trap: 6 err: f618acd0 eip: 23 cs: 10246 flag: edd9f1c0 sp: 2b ss: 0 cr2: edd9f1dc

Stack trace:
> 1     [0xda92acc4,0xedd9e880] ERROR_SIGNAL_HANDLER_FUNC(int, siginfo*, void*) +0x794                  @ gmsv_segfault_linux.dll+0x4cc4.
> 2     [0xf775e410,0xedd9ee40] ? +0x794                @ linux-gate.so.1+0x410.
> 3     [0xf618acd0,0xedd9f1c0] Sys_Error_Internal(bool, char const*, char*) +0x160             @ engine_srv.so+0x1b8cd0.
> 4     [0xf618ad90,0xedd9f5f0] Sys_Error(char const*, ...) +0x20               @ engine_srv.so+0x1b8d90.
> 5     [0xf618c0f8,0xedd9f610] Sys_SpewFunc(SpewType_t, char const*) +0x2d8            @ engine_srv.so+0x1ba0f8.
Dropped Pewdiepie from server (ERROR! Couldn't send snapshot.)
> 6  [0xe985c74d,0xedda1670] newspew(SpewType_t, char const*) +0x27d                 @ gmsv_xterm_linux.dll+0x774d.
> 7     [0xf741cddf,0xedda16d0] _SpewMessage(SpewType_t, char const*, int, Color const*, char const*, char*) +0xbf              @ libtier0_srv.so+0xeddf.
> 8     [0xf741d82c,0xedda2ae0] Error +0x2c             @ libtier0_srv.so+0xf82c.
> 9     [0xee5d2fe8,0xedda2b00] CLuaGamemode::CallWithArgs(char const*) +0x78           @ server_srv.so+0x5d2fe8.
> 10    [0xee5f6fce,0xedda2b20] CLuaGameEventListener::FireGameEvent(IGameEvent*) +0x13e                @ server_srv.so+0x5f6fce.
> 11    [0xf60dcad6,0xedda2b90] CGameEventManager::FireEventIntern(IGameEvent*, bool, bool) +0xd6               @ engine_srv.so+0x10aad6.
> 12    [0xf60dce48,0xedda2be0] CGameEventManager::FireEvent(IGameEvent*, bool) +0x28           @ engine_srv.so+0x10ae48.
> 13    [0xf616387a,0xedda2c00] CGameClient::Disconnect(char const*, ...) +0x15a                @ engine_srv.so+0x19187a.
> 14    [0xf608cf18,0xedda3050] CBaseClient::SendSnapshot(CClientFrame*) +0x578                 @ engine_srv.so+0xbaf18.
> 15    [0xf6165214,0xedda30e0] CGameClient::SendSnapshot(CClientFrame*) +0x1c4                 @ engine_srv.so+0x193214.
> 16    [0xf6175c4f,0xedda3180] SV_ParallelSendSnapshot(CGameClient*&) +0x3f            @ engine_srv.so+0x1a3c4f.
> 17    [0xf617956a,0xedda31a0] CParallelProcessor<CGameClient*, CFuncJobItemProcessor<CGameClient*> >::DoExecute() +0x3a               @ engine_srv.so+0x1a756a.
> 18    [0xf732c307,0xedda31d0] CFunctorJob::DoExecute() +0x17                  @ libvstdlib_srv.so+0x12307.
> 19    [0xf732ce6f,0xedda31f0] CJob::Execute() +0x7f           @ libvstdlib_srv.so+0x12e6f.
> 20    [0xf732db08,0xedda3220] CJobThread::Run() +0x358                @ libvstdlib_srv.so+0x13b08.
> 21    [0xf741f578,0xedda3300] CThread::ThreadProc(void*) +0x88                @ libtier0_srv.so+0x11578.
> 22    [0xf760e00b,0xedda3330] start_thread +0xdb              @ libpthread.so.0+0x700b.
> 23    [0xf754899e,0xedda3430] clone +0x5e             @ libc.so.6+0xf399e.
END: Unspecified (general) error

Lua Trace:

STACK (0): .
Unloading crashhandlers... calling previous crash handler

```

**Comment by meepdarknessmeep** [comment] 2015-06-09 17:14
Bump, it still happens

http://a.pomf.se/mtxled.mdmp

**Comment by Lumixz** [comment] 2015-06-18 17:25
Can confirm this is still a problem. Happens while players are joining in after a map change, before the game even fully starts. Happens around 4 times a day. Windows machine. 

I don't have a dump, just popping in to bring attention to this.

**Comment by SnowboiTheGr8** [comment] 2015-06-19 18:49
Still an issue.
Happens when only under a high load of players ( About 50-60+ ) and seemingly random.
Linux machine, just to throw a spin on things.

>ERROR! SendData reliabe data too big (153349)[GM:CallWithArgs - !ThreadInMainThread] >PlayerDisconnected
>[GM:CallWithArgs - !ThreadInMainThread] PlayerDisconnected

>[GM:CallWithArgs - !ThreadInMainThread] PlayerDisconnected

**Comment by robotboy655** [comment] 2015-06-21 01:11
It looks like it crashes when trying to kick a player after failing to send a full snapshot update or some shit.

**Comment by robotboy655** [comment] 2015-06-21 01:16
Yeah, I am pretty sure that's what happens. The player is supposed to be kicked with the reason "ERROR! Couldn't send snapshot.".

**Comment by robotboy655** [comment] 2015-06-21 01:41
I believe you should be able to fix it for your server with ```sv_parallel_sendsnapshot 0```. I don't know what the draw backs are, but hey, it should fix this crash.

**Comment by Lumixz** [comment] 2015-06-21 01:43
I'll try it out. Thanks.

**Comment by SnowboiTheGr8** [comment] 2015-06-21 02:04
I've just done it so I'll let you know. Thanks.

**Comment by SnowboiTheGr8** [comment] 2015-06-21 17:55
Crashed.
>ERROR! SendData reliabe data too big (156742)Dropped A Sneaky Panda from server (ERROR! Couldn't send snapshot.)
rip community.

**Comment by Lumixz** [comment] 2015-06-21 17:58
Check your .cfg again. I noticed after I changed mine, it reverted for some reason.

**Comment by SnowboiTheGr8** [comment] 2015-06-21 18:04
It is in my server.cfg file. I ran it through console first, then it crashed.
Now it booted with the cvar it may make a difference - no idea with this game...

**Comment by SnowboiTheGr8** [comment] 2015-06-21 18:07
Sorry, can I clarify - did you mean it set back during the servers runtime, or after a crash it hadn't set? If the case is the former I could make a timer to check the cvar I guess...

**Comment by Lumixz** [comment] 2015-06-21 18:10
For me, it changed back while running. I'm not sure if it was that it never actually saved when I thought I had done it, if my host's managed system did it, or something else. Probably just didn't save. However i suspect your server needs to boot with it set for it to take effect.

**Comment by SnowboiTheGr8** [comment] 2015-06-21 18:20
Okay, thankyou - I'll be sure to post back with any further developments/failures!

**Comment by SnowboiTheGr8** [comment] 2015-06-21 20:49
>Inside fountain :<
>ERROR! SendData reliabe data too big (153729)Dropped TragicChicken from server (ERROR! >Couldn't send snapshot.)
>Segmentation fault

Nope. Not fixed. I hope they fix this soon - its destroying my community and really stressing me out. We are struggling to raise enough for the bills because of 4-5 crash's a day.

**Comment by robotboy655** [comment] 2015-06-21 20:56
Your crash is different, I am not seeing anything about player_disconnect or PlayerDisconnect in your supposed crash logs.

**Comment by SnowboiTheGr8** [comment] 2015-06-21 20:58
Right, is there any information you can give me on that issue as searching the internet for the string "ERROR! SendData reliabe data too big" doesn't show much more than this thread?

**Comment by robotboy655** [comment] 2015-06-21 21:00
Not without at least the stack trace.

**Comment by SnowboiTheGr8** [comment] 2015-06-21 21:01
That gets produced by the debug.log or the crash dumps?

**Comment by robotboy655** [comment] 2015-06-21 21:07
I have no idea what it is on Linux.

**Comment by SnowboiTheGr8** [comment] 2015-06-21 21:09
As far as I'm aware the debug.log ( Produced by the "-debug" command ) and Garrysmod crash dumps ( Always created upon a crash automatically ) are the same for Windows and Linux. I was asking which would contain the information most useful as I'd like to waste as little of your time as possible. Unless you'd need both? Or am I off the cliff here and the stack trace is something completely different?

**Comment by SnowboiTheGr8** [comment] 2015-06-21 21:11
Should I make a facepunch thread for this?

**Comment by Lexicality** [comment] 2015-06-21 22:28
Memory dumps are always useful for diagnosing crashes. Debug logs
sometimes. When in doubt provide all information available.

**Comment by Lumixz** [comment] 2015-06-21 23:27
His server might crash before it fully prints the error. That's what happens to mine, too. The full error I usually get is: 

>ERROR! SendData reliabe data too big (41816)>"xxxxxxxxx<230><xxxxxxxxxxx><>" disconnected (reason >"ERROR! Couldn't send snapshot.")
>Dropped xxxxxxxxxxxxxx from server (ERROR! Couldn't send snapshot.)
>Engine error: [GM:CallWithArgs - >!ThreadInMainThread] player_disconnect

Where the x's are player name or steam ID. Sometimes more than one person can get kicked, with all of those lines repeating for each kick. Then the server dies.  Sometimes it dies before it even prints the player getting kicked.

**Comment by SnowboiTheGr8** [comment] 2015-06-21 23:46
I can actually vouch, 3 crashes later - they all seem to cut off differently. What I don't get is before I set the cvar to 0 I never got the
>Dropped xxxxxxxxxxxxxx from server (ERROR! Couldn't send snapshot.)
Rather what you can see in one of my first posts. Really obscure. :(

**Comment by SnowboiTheGr8** [comment] 2015-06-27 14:54
Quick update; just had this 
>DLL_MessageEnd:  Refusing to send user message TextMsg of 256 bytes to client, user message size limit is 255 bytes

Happen at the same time as the crash? Not sure if its related.

**Comment by Lumixz** [comment] 2015-06-27 17:53
I'm not sure why, but the crashing seems to have stopped for me. Last crash was the 21st. Looking at my changelog, I haven't really done anything significant that I think could have fixed it.

**Comment by SnowboiTheGr8** [comment] 2015-06-28 15:13
After contacting Noiwex who I must thank for his information that he shared, it appears the crashing can be caused by too many entities. We've drastically reduced the amount of entities that'd be able to be on the map concurrently.

Lumixz did have you recently had less entities on your map?

**Comment by Lumixz** [comment] 2015-06-28 17:07
In fact we did make some changes to weapon spawns on some maps around the time the crashing stopped, although I'm pretty sure it has crashed on maps that we did not edit. But that does seem to line up. I'll go through and remove some.

Thanks for the information.

**Comment by SnowboiTheGr8** [comment] 2015-06-28 17:57
I've also been told that some weapon bases can cause it. I'm not sure how that even makes sense, really - what weapon base are you using?

**Comment by Lumixz** [comment] 2015-06-28 17:58
Default TTT.

**Comment by SnowboiTheGr8** [comment] 2015-06-28 18:00
I'm pretty sure TTT uses CSS by default, we use FA:S which seems stable, switched from CW 2.0.
Thanks.

**Comment by Lumixz** [comment] 2015-06-28 18:13
TTT has its own weapon base.

**Comment by Mista-Tea** [comment] 2015-06-28 20:26
I hadn't knowingly had my server crash from this for quite some time. Unfortunately, it appears to have just happened. I thought I was in the clear but I guess not.

**Comment by Lumixz** [comment] 2015-06-29 20:12
I didn't notice this before, but nearly every single time this has happened, the player with the snapshot error belongs to my ULX Mod or Admin groups.

**Comment by meepdarknessmeep** [comment] 2015-06-30 02:37
maybe it's trying to send too much data to an entity that doesn't fully exist yet?
like via net

**Comment by robotboy655** [comment] 2015-06-30 03:29
It's simply sending too much data.

**Comment by Lumixz** [comment] 2015-06-30 03:34
Do you think it would be possible to patch the method that it uses to kicks players, preferably in a way that isn't broken?

**Comment by robotboy655** [comment] 2015-06-30 03:41
It's not as simple as "patch it". We don't even have a 100% way to reproduce the crash on demand.

**Comment by Lumixz** [comment] 2015-07-01 08:22
Quick update, player got kicked for the snapshot error but it DID NOT crash the server this time. Again, in this case were in a ulx group other than user.

**Comment by SnowboiTheGr8** [comment] 2015-07-05 08:31
I don't think its related to the usergroup personally, for us at-least as I've had an admin kicked for the error and it not crash. We've luckily not crashed for about a week from the issue since we dropped our proplimit and max ents by more than half.

We've just started adding cars back and we'll see.

**Comment by SnowboiTheGr8** [comment] 2015-08-04 18:49
Still an issue.

**Comment by SnowboiTheGr8** [comment] 2015-08-05 19:14
Still an issue.......

**Comment by robotboy655** [comment] 2015-08-06 09:48
Of course it still a fucking issue less than 24 ago since your last post. No need to repost the same message every day unless you want to get banned.

**Comment by Lumixz** [comment] 2015-08-06 17:59
Still an issue.......

JK.

Last time I had a crash dump with the error was July 13th. I haven't had any crashes known to be caused by this issue since then. To compare, we were having crashes from this particular problem at least once per day. Interestingly it seemed to slow in frequency to the point where it doesn't even happen anymore. I've gone over all my dumps and logs and cannot find any correlation.

The only thing that I have changed (or at least that I logged in my changelog) in between now and July 13th was the removal of a weapon model I though was being troublesome. However we had this weapon on our other server which never experiences these crashes. 

I wish I could be more helpful but this whole thing is seemingly random.

**Comment by SnowboiTheGr8** [comment] 2015-08-16 10:09
We currently send a bunch of Lua to the player upon join which is then RunStringEx'd, to the point where while in game, it'll kick you for "Disconnect: SnowBoi overflowed reliable buffer", while when we do it on join, it doesn't kick you. I'm assuming that if we made a system to send the data in managed chunks. We where crashing when hitting about 30 players. We send 19 items, totalling 167.2 kB.

I'm not sure what the actual trigger is, though - though I've got some strange feeling its when someone leaves while the data is being sent. We'll look into seeing if we can reproduce this tomorrow but just thought I'd post it to see if there is any correlation with you guys doing similar things?

**Comment by meepdarknessmeep** [comment] 2015-08-16 17:01
how about not runstringex and sending raw lua over net

**Comment by SnowboiTheGr8** [comment] 2015-08-16 19:21
We have made a "cloud"-esk system. It allows us to essentially at any point while the server is running change to a different pool, which is essentially another set of client/server/shared lua. Everything old will automatically be unhooked and discarded of, while the new lua is sent and executed live. It allows easier bug fixing, and its a more controlled version of live lua refresh. It's like a ghetto git system.
It also prevents skids from stealing basic shit like our HUD, also - which is nice :smile:

**Comment by thegrb93** [comment] 2015-08-16 22:28
Is this related to the "Player left the game (Disconnect by user.)" message not showing sometimes?

**Comment by SnowboiTheGr8** [comment] 2015-08-17 00:32
After chasing up some players who where loading in just before the respective crash, I found them to explain their games freeze, to which they would force close it - at around the same time of the crash.
This also just happened with a member of staff, who also froze, force closed his game - and it crashed.
>CreateFragmentsFromFile: 'user_custom/7e/7e1b44a2.dat' doesn't exist.
>CreateFragmentsFromFile: 'user_custom/82/82bd2daa.dat' doesn't exist.
>Player [11][El Torito]'s max rank: 7 [ This message is printed before the player fully loads in. ] 
> [ This is where their game locks up, and they eventually force close it. ]
>ERROR! SendData reliabe data too big (44295)[GM:CallWithArgs - !ThreadInMainThread] player_disconnect
>[GM:CallWithArgs - !ThreadInMainThread] player_disconnect
>[GM:CallWithArgs - !ThreadInMainThread] player_disconnect

That message is there 9/10 times before the server crash's, in which has happened at least 100 times for us.

**Comment by Lumixz** [comment] 2015-08-17 00:45
Maybe try disabling sv_allowupload and sv_allowdownload?

**Comment by SnowboiTheGr8** [comment] 2015-08-17 00:54
Already tried that, thanks though

**Comment by robotboy655** [comment] 2015-08-17 04:50
```Disconnect: SnowBoi overflowed reliable buffer``` Is not related to this crash.

```ERROR! SendData reliabe data too big ``` Is.

**Comment by SnowboiTheGr8** [comment] 2015-08-17 04:53
Can I ask, do you know if this can be caused by sending a large amount of data to the client upon join, though?
You say "its simply sending too much data", but is that from the server to the client, from the client to the server, or both ways?

**Comment by SnowboiTheGr8** [comment] 2015-08-18 12:04
Could you please let me know what the maximum amount of data I should be sending at one time should be? We're almost done with the chunking system but without knowing how much data we should be sending at one time its just a case of guessing which isn't ideal.

**Comment by SnowboiTheGr8** [comment] 2015-08-18 14:23
Not sure if this is of any value, but its happened twice now to an admin. He said he is kicked with the message "[3:21:34 AM] El Torito: something like that Client:snapshot couldnt be retrieved/loaded." and both times the server went down.

**Comment by Lumixz** [comment] 2015-08-29 02:39
Well, it was good while it lasted. We didn't have the error for almost 2 months, but it just came back. 4 crashes in the span of an hour caused by the snapshot kicking.

**Comment by SnowboiTheGr8** [comment] 2015-08-29 18:26
We've had no crashing since we started chunking data, add me on steam /id/snowboi

**Comment by Lumixz** [comment] 2015-08-29 18:34
Your friends list is full

**Comment by SnowboiTheGr8** [comment] 2015-08-29 18:41
I'm out right now - Try again in like 3 hours, sorry mate

**Comment by ertug2** [comment] 2016-01-01 21:46
One of my clients just randomly experienced this and is now having the issue every couple of hours. Any updates?

```
ServerLog: GingerPopper (STEAM_0:1:46113397) is Authed

ServerLog: GingerPopper (STEAM_0:1:46113397) Spawned for the first time

[Connections | 12:47:59]GingerPopper(STEAM_0:1:46113397) has connected

ServerLog: GingerPopper (STEAM_0:1:46113397) Spawned

ERROR! SendData reliabe data too big (105191)[GM:CallWithArgs - !ThreadInMainThread] player_disconnect

[GM:CallWithArgs - !ThreadInMainThread] player_disconnect
```

**Comment by SnowboiTheGr8** [comment] 2016-02-19 15:19
Just posting an update to help anyone getting this issue or the devs debug it.

From my knowledge I think meep is on the money when he said:
> maybe it's trying to send too much data to an entity that doesn't fully exist yet?

I can reproduce this issue by sending a large amount of data on the PlayerInitialSpawn ~50% of the time, doing so at any point after that hook is called doesn't crash the server.

Anyone with this issue can add me on Steam; http://steamcommunity.com/id/SNOWBOI/

**Comment by willox** [comment] 2016-02-19 15:21
Set sv_parallel_sendsnapshot to 0 to avoid this problem for now

**Comment by SnowboiTheGr8** [comment] 2016-02-19 15:22
That doesn't stop it Willox, we tried that a while back unless you guys changed what the command does.

**Comment by willox** [comment] 2016-02-19 15:23
If your stack trace does not match the one in the first post of this issue, you're in the wrong issue.

**Closed** 2016-02-26 16:31 UTC
Labels: bug, crash
