### ISSUE TITLE
Font problem.

### ISSUE THREAD

**Issue by xpuska513** [Facepunch/garrysmod-issues#2833] opened 2016-09-25 13:27 UTC
Hi!
First of all, i'm using linux distro called Elementary OS 0.4 Loki.
And i have a problem with russian language it's not showing up russian leters in console or chat.
P.s i installed ttf-mscorefonts but it doesn't help.

**Comment by robotboy655** [comment] 2016-09-25 13:34
Duplicate of #842

**Closed by robotboy655** 2016-09-25 13:34 UTC
