### ISSUE TITLE
GetColor seems bugged with tables

### ISSUE THREAD

**Issue by robotdogs** [Facepunch/garrysmod-issues#4868] opened 2021-03-14 01:46 UTC
Hello
I'm having an issue where I cannot get the color for entities listed in a table.

Here's a snippet of the code:
`if(tbl[i]:GetClass()=="boiguh_pat" or tbl[i]:GetClass()=="boiguh_bac") then 
				print(tbl[i]:GetClass()) PrintTable(tbl[i]:GetColor())`

and when printed in-game:
`boiguh_pat
a = 0
b = 0
g = 0
r = 0`

It works fine when calling GetClass() as you can see, it'll print boiguh_pat, but GetColor() will always return 0s, which I don't understand since it'll get the class without a problem. Am I doing something wrong, or is GetColor bugged?

Thank you

**Comment by robotboy655** [comment] 2021-03-15 02:53
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/2407 (Same core issue)

**Closed by robotboy655** 2021-03-15 02:53 UTC
