### ISSUE TITLE
Player plays a running sequence(?) when standing on a moving func_door

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3067] opened 2017-02-27 22:09 UTC
### Details
When standing on a func_door which is currently moving the player plays a walk animation, even while standing on ground.

(Only works when func_door moves horizontal.)

**Comment by willox** [comment] 2017-02-27 22:29
It's probably not very hard to pass a fixed up velocity to CalcMainActivity for this

**Comment by Kefta** [comment] 2017-02-27 22:30
@willox Not sure which velocity is currently passed, but maybe it should be local velocity only as to not account for moving objects affecting the player

**Comment by willox** [comment] 2017-02-27 22:31
I thought that but I'll have to make sure it makes sense to do it that way

**Comment by robotboy655** [comment] 2021-05-25 18:03
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/3322

**Closed by robotboy655** 2021-05-25 18:03 UTC
