### ISSUE TITLE
Halos cause screen blurring on Mac

### ISSUE THREAD

**Issue by wannaseeanalien** [Facepunch/garrysmod-issues#3680] opened 2018-12-13 02:57 UTC
### Details
Whenever a "halo" is rendered via stencil operations or halo.Add, the entire screen will go blurry. It gets worse with every halo, and causes severe fps drops.
I see this is not an issue in l4d2 or csgo on mac so I do not think this is an OS limitation, and I dont remember this happening with the l4d2 player glow script in gmod 12 on mac. so it must be a gmod 13 thing...

### Steps to reproduce
cause any halo to render on anything you will notice it right away.

**Comment by robotboy655** [comment] 2018-12-13 12:42
duplicate of https://github.com/Facepunch/garrysmod-issues/issues/1158

**Closed by robotboy655** 2018-12-13 12:42 UTC
Labels: osx
