### ISSUE TITLE
Sandbox Spawnmenu bugs

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3076] opened 2017-03-09 12:30 UTC
### Details
You can hold the items outside of the spawnmenu and sometimes the tooltip does not get removed on heavy lag.

### Steps to reproduce
1. Hold mouse1 on a icon, then hold mouse 2 and close the interface. Now you got a bugged out icon.
https://puu.sh/uB84F/ff2024cc3e.png

2. Hover over an weapon for example and have a heavy lag while closing the menu.
I don't have a screenshot of this, unfortunately.

**Comment by robotboy655** [comment] 2017-03-09 14:09
I will fix the problem with pressing Mouse 1 and Mouse 2 and having the icon stuck, but I cannot reproduce any kind of "lag" when closing the menu.

As for the tool tip, there's already a ticket for it open. And it was opened by fucking you too. https://github.com/Facepunch/garrysmod-issues/issues/2869

**Closed by robotboy655** 2017-03-09 14:09 UTC

**Comment by mcNuggets1** [comment] 2017-03-09 14:16
Oh sorry, it must have been old, because I already forgot about it. 🗡
