### ISSUE TITLE
Compile errors with new brush limit

### ISSUE THREAD

**Issue by waffles187** [Facepunch/garrysmod-issues#3751] opened 2019-02-14 05:56 UTC
### Details
When compiling a map with over 8192 brushes, other limits pop up like "MAX_MAP_BRUSHSIDES" or "MAX_MAP_VERTS" and probably some others.

### Steps to reproduce
Compile a map with more than 8192 brushes.
[example vmf](https://drive.google.com/open?id=1YsHUBV9oKL-1fWcS8plwwVt0k9iaxVT4)

**Comment by robotboy655** [comment] 2019-02-14 20:31
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1269

**Closed by robotboy655** 2019-02-14 20:31 UTC

**Comment by waffles187** [comment] 2019-02-14 21:41
didnt see that. whoops
