### ISSUE TITLE
render.RenderView does not handle area portals correctly

### ISSUE THREAD

**Issue by WilliamVenner** [Facepunch/garrysmod-issues#4951] opened 2021-05-20 23:25 UTC
### Details
Area portals will continue to clip despite render.RenderView's origin.

### r_portalsopenall 0

![image](https://user-images.githubusercontent.com/14863743/119060846-ed422700-b9ca-11eb-945e-227dec63d23e.png)

### r_portalsopenall 1

![image](https://user-images.githubusercontent.com/14863743/119060867-f92de900-b9ca-11eb-8736-34b361535108.png)

### Steps to reproduce
Find a map with area portals, hook RenderScene, render.RenderView to an RT and observe.

**Comment by thegrb93** [comment] 2021-05-21 00:28
The PVS is tied to the view-entity view position rather than the camera position. Same thing happens with CalcView.

**Comment by WilliamVenner** [comment] 2021-05-21 00:49
Oh, I forgot to mention that in those pictures I am also added to the PVS of that position via SetupPlayerVisibility and AddOriginToPVS.

**Comment by robotboy655** [comment] 2021-05-21 10:17
Basically duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1861

**Closed by robotboy655** 2021-05-21 10:17 UTC
