### ISSUE TITLE
CreateMaterial Purple Texture Glitch

### ISSUE THREAD

**Issue by buk2** [Facepunch/garrysmod-issues#3341] opened 2017-12-04 07:17 UTC
I am very sorry that if this is not the right place to report this and I am not asking specifically for help to fix my code on here if it is broken. I am new to Lua and was recommended to post an issue on here as it might be a 'glitch'.

If you set a create a material with a .png image from the data directory with CreateMaterial like so below-
`CreateMaterial("whatthef", "VertexLitGeneric", {
    ["$basetexture"] = Material("data/picture.png"):GetName(),
    ["$model"] = 1, 
})`
It will work perfectly until you rejoin the server. Once you rejoin the server and try to use the EXACT same code without changing anything, it will produce a missing texture instead of the actual texture. You would have to restart your game in order to see the texture properly again. I included a video of it happening in a facepunch thread here - https://gmod.facepunch.com/f/gmoddev/otee/Use-a-jpg-png-file-that-is-located-in-the-data-folde-as-a-material-for-entities/1/

**Comment by buk2** [comment] 2017-12-08 00:06
I believe the issue I posted relates to https://github.com/Facepunch/garrysmod-issues/issues/3103

**Comment by Tripperful** [comment] 2017-12-08 20:40
It's strange that setting a texture from data folder like this works at all, since the root of all materials/textures in this case is materials folder. It means "data/picture.png" should be interpreted like "materials/data/picture.png", and if your picture is placed in data/ but not materials/data it should fail

**Comment by sannysc** [comment] 2017-12-08 20:48
It isn't strange, because it was intentionally changed to be that way.

**Comment by Kefta** [comment] 2017-12-08 21:20
@sannysc What was changed?

**Comment by sannysc** [comment] 2017-12-08 21:27
You used to need to leave the materials folder when working with the data folder like this ```Material("../data/picture.png")``` but now you can just write ```Material("data/picture.png")```

That was changed earlier this year, I believe.

**Comment by buk2** [comment] 2017-12-08 21:33
I made a hacky way of making it work properly, I guess? - 
`local a = CreateMaterial('mymaterial', "VertexLitGeneric", { ["$model"] = 1 })
a:SetTexture("$basetexture", Material('data/myimage.png'):GetName())`

**Comment by Tripperful** [comment] 2017-12-13 19:16
@sannysc 
> It isn't strange, because it was intentionally changed to be that way.

If it was really changed to work this way - that's not a good idea. When I see `Material( "data/picture.png" )`, I interpret it as `"materials/data/picture.png"`, the same should be applied to the game. 

What if I have both `"DATA/picture.png"` and `"materials/data/picture.png"`? 
Which one should be preferred by the game? How do I know this? 

When it's `"../data/picture.png"`, it's obvious what you mean. When it's `"data/picture.png"` and it works this way - it's not

**Comment by Benn20002** [comment] 2019-04-21 00:53
I found a workaround for it:
Just use file.Write to create a new file with the same content (get it by file.Read) and a unique name right before creating the material and use that to create it and then just delete it right after creating the material.

**Comment by robotboy655** [comment] 2020-11-06 17:45
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/1531 ?

**Comment by robotboy655** [comment] 2020-11-06 17:46
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/3103

**Closed by robotboy655** 2020-11-06 17:46 UTC
