### ISSUE TITLE
DColorMixer:GetColor returns table and not color object

### ISSUE THREAD

**Issue by xaviergmail** [Facepunch/garrysmod-issues#4098] opened 2019-12-20 20:02 UTC
### Details
DColorMixer:GetColor doesn't set color metatable on the returned table

**Comment by robotboy655** [comment] 2019-12-20 20:13
Essentially duplicate of https://github.com/Facepunch/garrysmod-issues/issues/2407

This affects most functions out there, especially all C bindings.

**Comment by xaviergmail** [comment] 2019-12-20 20:13
But this isn't a C binding?

https://github.com/Facepunch/garrysmod/blob/master/garrysmod/lua/vgui/dcolormixer.lua#L13

**Closed by robotboy655** 2019-12-20 20:13 UTC

**Comment by robotboy655** [comment] 2019-12-20 20:15
It must be getting color set from a color object returned by a C binding somewhere, possibly in your code. The solution here is definitely not to alter DColorMixer. Check your SetColor calls.

**Comment by xaviergmail** [comment] 2019-12-20 20:28
```lua

local frame = vgui.Create("DFrame")
frame:SetSize(300, 250)
frame:Center()
frame:MakePopup()

local mixer = frame:Add("DColorMixer")
mixer:Dock(FILL)
mixer.ValueChanged = function(self, col)
	print("Color:", col, IsColor(col))
end
```
Without calling SetColor once: Editing the SV/Alpha/Hue or RGB numberwangs returns a bare table.
The only time a Color is returned is through the preset color palette

**Comment by robotboy655** [comment] 2019-12-21 02:03
https://wiki.garrysmod.com/page/ITexture/GetColor

Fairly certain it's coming from here.
https://github.com/Facepunch/garrysmod/blob/394ae745df8f8f353ea33c8780f012fc000f4f56/garrysmod/lua/vgui/drgbpicker.lua#L25
