### ISSUE TITLE
Missing chrome textures on x86-64 branch

### ISSUE THREAD

**Issue by TheBillinator3000** [Facepunch/garrysmod-issues#4926] opened 2021-04-25 12:54 UTC
On the x86-64 branch on Garry's Mod, when going through the Half-Life: Source campaign, some world surfaces didn't have a chrome texture. 
![20210425082822_1](https://user-images.githubusercontent.com/71604944/115993499-0361f080-a5a1-11eb-9367-32ff4d9837da.jpg)

Now I'm aware the main and the dev branches also don't have chrome textures, but those branches are telling the game the chrome isn't supposed to exist, so missing textures don't appear. 

I can understand why this is done. The floors in HL:S are a bit too shiny in my opinion.

Here's the error that comes up in the developer console:
** Encountered stale cubemap! Please rebuild the following vtf:
Error reading material data "materials/environment maps/nameoftexture.vtf"

I had no addons.

Steps to reproduce:
1, Use the x86-64 branch
2, Look at 'shiny' surfaces on the maps that have them. (You don't need to look at all of them.)
_The maps that I know for sure that have shiny surfaces:_
c1a0a
c1a1a
c1a2c
c2a3a
c2a3b

**Comment by Comminux** [comment] 2021-04-25 16:30
I have the same problem but with Quake mod for Gmod.
![2021-04-25-185533_scrot](https://user-images.githubusercontent.com/14937307/116001326-9e3be880-a5fc-11eb-895e-46958b83740d.png)

**Comment by MARK2580** [comment] 2021-04-25 23:43
I confirm. On x64 assembly, there is such a problem. There is no dev build.

**Comment by robotboy655** [comment] 2021-04-26 08:56
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/4146

**Closed by robotboy655** 2021-04-26 08:56 UTC
