### ISSUE TITLE
ENT:ManipulateBonePosition and ENT:ManipulateBoneAngles break RenderBounds

### ISSUE THREAD

**Issue by js1251** [Facepunch/garrysmod-issues#5007] opened 2021-07-10 21:14 UTC
### Details
When using either of the two functions the renderbounds of the entities will mess up. Im not sure if its offset or doesnt update anymore when the ent moves but...
### the model pops out of view even if the mesh is still onscreen!

![ezgif com-gif-maker (9)](https://user-images.githubusercontent.com/57368720/125176522-6f351c00-e1d4-11eb-994f-0779652944bd.gif)

### Steps to reproduce

1.  Copy this code into "RenderBoundsTest.lua" in gmod/addons/whatever/lua/entities/
2. enable "developer 1"
3. white box is RenderBounds BEFORE bonemod messed them up
4. green box is after
5. look up to see the model disappear

```lua
AddCSLuaFile()
DEFINE_BASECLASS("base_anim")
ENT.PrintName = "RenderBounds Test Entity"
ENT.Author = "Jakob Sailer"
ENT.Information = ""
ENT.Category = "RenderBounds Bug"
ENT.Editable = true
ENT.Spawnable = true
ENT.AdminOnly = false
ENT.RenderGroup = RENDERGROUP_TRANSLUCENT

function ENT:SpawnFunction(ply, tr, ClassName)
	if (not tr.Hit) then return end
	local ent = ents.Create(ClassName)
	ent:SetPos(tr.HitPos + tr.HitNormal)
	ent:Spawn()
	ent:Activate()

	return ent
end

if SERVER then
	function ENT:Initialize()
		self:SetModel("models/cranes/crane_docks.mdl")
		self:PhysicsInit(SOLID_VPHYSICS)
		self:SetMoveType(MOVETYPE_VPHYSICS)
		self:SetSolid(SOLID_VPHYSICS)
	end
end

if CLIENT then
	function ENT:Initialize()
		local min, max = self:GetRenderBounds()
		debugoverlay.Box(self:GetPos(), min, max, 10, Color(255, 255, 255, 10))
	end

	function ENT:Think()
		local bone = self:LookupBone("arm")
		local angle = Angle(0, 0, 30 * math.sin(CurTime()))

		self:ManipulateBoneAngles(bone, angle) --comment out to see how it no longer breaks

        --renderbounds AFTER bonemod messed them up
		local min, max = self:GetRenderBounds()
		debugoverlay.BoxAngles(self:GetPos(), min, max, self:GetAngles(), FrameTime() * 2, Color(0, 207, 28, 10))
	end
end
```

**Comment by robotboy655** [comment] 2021-07-11 10:53
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/2697

**Closed by robotboy655** 2021-07-11 10:53 UTC

**Comment by robotboy655** [comment] 2021-07-12 15:37
Should be fixed on Dev. It will not be perfect, as it doesn't take into account rotation, scale or the visual mesh, but it will be not shit.

**Comment by js1251** [comment] 2021-07-12 15:45
Good stuff. Thank you
