### ISSUE TITLE
cam.Start gives up if the viewport x/y is negative on windows but not on linux

### ISSUE THREAD

**Issue by CakeKing64** [Facepunch/garrysmod-issues#6070] opened 2024-11-13 14:25 UTC
### Details
Trying to place the viewport x/y at a negative value using cam.Start works as expected under linux but just doesn't show anything under windows

### Version 
![Image](https://github.com/user-attachments/assets/60297e46-e1ae-4432-98d5-33c677559c7f)
also tested under
![Image](https://github.com/user-attachments/assets/98f08c75-c8ea-4658-a933-974de86e6a87)

### Steps to reproduce
0. Doesn't matter if `-noworkshop` is on or not or if the addons folder is empty (except for the test code)

1. Slap this sick code down into a mod/lua/vgui folder
```
local PANEL = {}

function PANEL:Paint()
    local model = ClientsideModel("models/maxofs2d/logo_gmod_b.mdl")

    cam.Start({
        x=-1, -- Works fine if this is 0 but not a negative value
        y=0,
        w=ScrW(),
        h=ScrH(),
        type="3D",
        angles = Angle(0, 0, 0),
        origin = Vector(-100,0,0),
        fov=70,
        aspect=ScrW()/ScrH()
    })

    model:DrawModel()
    model:Remove()
    cam.End3D()
end


vgui.Register("CoolPanel", PANEL, "DFrame")

function ShowPanel()
    local window = vgui.Create("CoolPanel")
    window:Center()
    window:SetSize(640, 480)
    window:MakePopup()

    local button = vgui.Create("DButton", window)
    button:SetText("Close")
    button.DoClick = function()
        window:Close()
    end
end


concommand.Add("funny3d", ShowPanel)
```

2. Open up the menu with the funny3d command and utilize the power of your eyeballs to observe the lack of/presence of the large G

Shows up like this under linux
![Image](https://github.com/user-attachments/assets/3618a903-3e77-428f-ab1f-d854ea529b42)

And this under windows (proton used here because i was too lazy to reboot back into windows but it's the same thing on both)
![Image](https://github.com/user-attachments/assets/973e968c-e201-473e-b4e8-14dc337489a8)

I think it would be very cool if it didn't vanish under windows so I don't have to change the (bad) code for my mod that is all 🥺

**Comment by robotboy655** [comment] 2024-11-13 14:51
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5665

**Closed by robotboy655** 2024-11-13 14:51 UTC
