### ISSUE TITLE
[BUG] Ladders that allow you to fly into the sky.

### ISSUE THREAD

**Issue by Satton2** [Facepunch/garrysmod-issues#3595] opened 2018-09-07 17:15 UTC
### Details
Well, everything already said in title.
Here is a small demonstration of it:
https://youtu.be/MXOATSp5CXY
### Steps to reproduce
1) Any ladder.
2) Anything that you can take and rotate with Physics gun.
3) Go up the ladder while holding anything with Physics gun.
4) While going up press and hold «Alt+E» (rotate keys).
5) That's all.

**Comment by sannysc** [comment] 2018-09-07 17:30
That's a ladder, not a staircase.

**Comment by Satton2** [comment] 2018-09-07 17:34
@sannysc Oh, yeah. I forgot about that because on Russian it's the same word.

**Comment by robotboy655** [comment] 2018-09-12 13:59
Cannot reproduce with no addons in Sandbox Singleplayer.

As soon as you press E, you fall off of the ladder and even if you manage to rotate the held prop while on a ladder, you cannot move on the ladder because the WASD keys are used to move the prop, not the player.

Alt is not bound by default to anything, so I don't know what you mean by ALT + E

**Comment by Satton2** [comment] 2018-09-12 17:53
@robotboy655 My «ALT» key is bound to «+walk»: 
![image](https://user-images.githubusercontent.com/23385240/45442095-b7046380-b6c9-11e8-9422-ee43073de18e.png)
I have disabled all my addons (excluding map) and tried to do this again. It still works. But I have found a mistake in my «steps to reproduce» — you don't need the «ALT» key. Here is another demonstration video (with disabled addons and no «ALT» key): https://youtu.be/SoRd6UdGgCY

**Comment by robotboy655** [comment] 2018-09-12 21:03
Is it a CS:S ladder? You cannot do that on HL2 ladders.

**Comment by Satton2** [comment] 2018-09-12 21:33
Are you talking about ladder function (I don't know how it's called correctly), then yeah. It's probably a CS:S ladder, because this bug doesn't work on ladders that are on HL2 maps, but it works on ladders that are on CS:S maps.

**Comment by joeyjumper94** [comment] 2018-10-28 10:42
do you mean brush based ladders?( a brush with the tools/ladder texture)

**Comment by robotboy655** [comment] 2019-09-19 17:54
Fixed in Dev,

**Closed by robotboy655** 2019-09-19 17:54 UTC
