### ISSUE TITLE
macOS Catalina probabale bug

### ISSUE THREAD

**Issue by faceofmars** [Facepunch/garrysmod-issues#3894] opened 2019-07-01 05:03 UTC
### Details
After updating to the Catalina Beta program, Garry's Mod, along with other games, will not launch. They claim they're running, though they don't boot up at all; is this normal in past years with the beta programs?

### Steps to reproduce
Just click "play" and it doesn't start.

**Comment by Bo98** [comment] 2019-07-01 08:39
Catalina drops support for 32-bit and GMod is yet to update to 64-bit.

**Comment by zac-garby** [comment] 2019-10-08 20:45
Any updates regarding this?

**Comment by meepen** [comment] 2019-10-08 21:06
Use the x64 branch

**Comment by Tataki-Guritchi** [comment] 2019-10-18 03:09
isn't the 64x branch broken on MacOS as well?

**Comment by Woet** [comment] 2019-10-20 00:33
The x86-64 branch worked great until the Garry's Mod update 2 days ago. Now it just shows the blue loading screen and crashes after "Finished!".

**Comment by ArbyAndy** [comment] 2019-10-22 08:16
(I posted this on the newer MacOS Catalina thread, but might as well re-post)
TEMPORARY FIX FOR MACOS CATALINA x64 GMOD USERS (that I've found works, i am not offering advice, just saying what I personally did to fix):
Delete the html_chromium.dylib from /Contents/MacOS/html_chromium.dylib which is inside the actual package of the game, GarrysMod.

This will disable the main menu's buttons, but at least you can still load in **without it instantly crashing** & you can use console to direct connect to servers, servers like DarkRP with radios & chromium etc do not seem to cause errors, the 64 bit GMod on MacOS is actually pretty O.K.

**Comment by Kefta** [comment] 2019-10-22 08:36
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/4029 (I know this one's older but that one has more info)

**Comment by ChocolateCircus445** [comment] 2019-10-23 03:20
As @ArbyAndy said, the menu buttons do not appear. Fortunately, you can use the console to open a singleplayer world.

Open the console by pressing the tilde (\~) on the main menu

First, type `map <map you want to load.>`

For example, if I wanted to load gm_flatgrass, I would put in `map gm_flatgrass`

The console will automatically give you a list of maps.

Please note that the gamemode will default to sandbox mode, and it will not show a loading screen.

To quit, hit the Esc key and type `quit`

**Comment by ChocolateCircus445** [comment] 2019-10-23 03:21
Saves and dupes don't work from the UI, but the spawnmenu and context menu work!

**Comment by willox** [comment] 2019-11-07 19:41
Should be fixed on the x86-64 branch

**Closed by willox** 2019-11-07 19:41 UTC
Labels: osx
