### ISSUE TITLE
phys_swap bug

### ISSUE THREAD

**Issue by weaponcubemap** [Facepunch/garrysmod-issues#4569] opened 2020-07-05 07:36 UTC
phys_swap causes FCVAR_SERVER_CAN_EXECUTE prevented server running command: escape in console, on client-side 
you can't reproduce it on server you host, it works on other servers where are you just player

**Comment by robotboy655** [comment] 2020-07-06 14:08
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/3151

**Closed by robotboy655** 2020-07-06 14:08 UTC

**Comment by weaponcubemap** [comment] 2022-08-10 10:50
> Duplicate of #3151

Even if it's duplicate, I explained better how to reproduce this bug in game, it's caused by ConCommand executing on client command "cancelselect".

https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/client.cpp#L1032

Also, I checked his issue, nobody explained why it happens. This bug can be fixed by removing this line I listed above or making it to stop selecting weapons on client.
