### ISSUE TITLE
Chromium textboxes show numbers when typing text into them

### ISSUE THREAD

**Issue by EntityinArray** [Facepunch/garrysmod-issues#4810] opened 2021-01-25 11:54 UTC
### Details
When typing into Chromium textboxes, they receive malformed input and display numbers instead of text.
Non-chromium textboxes, like game chat, console, derma textboxes are working fine.

OS: Linux Kubuntu 20.10
Garry's Mod 2020.10.23 chromium

Video demonstrating the issue:
https://streamable.com/twx99g

### Steps to reproduce

- Have Kubuntu 20.10 running on your computer
- Start Garry's Mod from Steam
- Try typing text into chromium text boxes (server list search box, addon search box etc.)

**Comment by adamnejm** [comment] 2021-01-25 16:50
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/4464?

**Closed** 2021-01-25 16:54 UTC
Labels: Bug, Dependency: CEF, Platform: Linux
