### ISSUE TITLE
Regression: sv_parallel_* commands seems to have no effect on the 64 bit branch

### ISSUE THREAD

**Issue by FredyH** [Facepunch/garrysmod-issues#5998] opened 2024-09-07 10:24 UTC
The bug from #5310 is back and the two sv_parallel_* commands have no effect on the 64 bit branch anymore.

**Comment by robotboy655** [comment] 2024-09-09 16:24
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5310

**Closed by robotboy655** 2024-09-09 16:24 UTC
