### ISSUE TITLE
gm_video (video.Record) does not save files on Mac and Linux

### ISSUE THREAD

**Issue by Bo98** [Facepunch/garrysmod-issues#464] opened 2013-09-11 17:32 UTC
The videos folder remains empty. Not heavily tested on Linux but is definitely the case on Mac.

**Comment by robotboy655** [comment] 2017-07-31 12:00
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/4

**Closed by robotboy655** 2017-07-31 12:00 UTC
Labels: linux, osx
