### ISSUE TITLE
NPC Killfeed Strings Broken

### ISSUE THREAD

**Issue by linkjay1** [Facepunch/garrysmod-issues#3249] opened 2017-07-22 18:38 UTC
If you are killed by, kill, or have NPCs kill each other, their strings are broken in the killfeed. 

I am currently running the latest version of GMod on the latest version of XUbuntu (Ubuntu 16.04).

![IMG](https://i.linkjay1.com/2fb4eb9823.png)

**Comment by robotboy655** [comment] 2017-07-22 19:08
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/44

**Closed by robotboy655** 2017-07-22 19:08 UTC
Labels: duplicate, linux
