### ISSUE TITLE
Malformed JSON generated with 0/0 as a value

### ISSUE THREAD

**Issue by TrixterTheTux** [Facepunch/garrysmod-issues#3629] opened 2018-10-09 11:26 UTC
### Details
util.TableToJSON produces malformed JSON if you pass 0/0 as a value into it.

### Steps to reproduce
Run ``lua_run print(util.TableToJSON({test = 0/0}))`` in the console.
![hi](https://maho.is-a-good-waifu.com/83f07e.png)

**Comment by Kefta** [comment] 2018-10-09 21:34
Both nan and inf are ignored by util.TableToJSON now.

**Comment by robotboy655** [comment] 2018-10-10 02:18
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/3561

**Closed by robotboy655** 2018-10-10 02:18 UTC
