### ISSUE TITLE
self:GetOwner() returns NULL Entity on SWEP:Deploy()

### ISSUE THREAD

**Issue by TheMostUpset** [Facepunch/garrysmod-issues#2179] opened 2015-08-07 15:26 UTC
When player has no weapons, self:GetOwner() (or self.Owner) of the first weapon you pickup returns NULL Entity on deploy. Happens on SWEPs with SWEP.Primary.ClipSize set to -1 and SWEP.Primary.DefaultClip higher than -1. SWEP.Primary.Ammo shouldn't be "none"

How to reproduce:
1. Do ply:StripWeapons()
2. Take any SWEP with these:

``` lua
SWEP.Primary.ClipSize = -1
SWEP.Primary.DefaultClip = 1
SWEP.Primary.Ammo = "smg1"

function SWEP:Deploy()
    print(self:GetOwner())
    return true
end
```

Done. It returns NULL Entity and may break some scripts that do something on owner in deploy hook.

**Comment by Exho1** [comment] 2015-08-07 17:15
Does it still occur if you add a small timer delay in SWEP:Deploy and then check the owner? I know that you had to do that for another function

**Comment by TheMostUpset** [comment] 2015-08-07 17:48
Seems like timer (even with zero delay) fixes the issue, but I don't think that's a good solution

**Comment by robotboy655** [comment] 2018-01-24 10:29
I cannot reproduce this using the code given. Marking as solved unless you can come up with a way to reproduce this, if it's still unfixed.

**Closed by robotboy655** 2018-01-24 10:29 UTC

**Comment by WolfKann** [comment] 2024-01-12 04:50
Was a fix for this behavior ever found. It started happened via server side on a server I play and I'm having the exact same issues, down to the "timer" fixing it partly.

**Comment by robotboy655** [comment] 2024-01-12 11:10
As I have already said in 2018 - if I cannot reproduce it I cannot look into it. If it started "recently", it must be a race condition of sorts?

Either way, I can't help without information.

**Comment by Kefta** [comment] 2024-01-12 12:16
I have had trouble replicating it but I have experienced the issue within the past year once I started logging owner validity in Deploy. The only thing I can say is that it happens on both client and server so it cannot be a prediction issue.

**Comment by WolfKann** [comment] 2024-01-12 13:40
The only thing consistently different I can find is that this bug is only active when for some reason the hook "PlayerButtonDown" is not called on the server by any means.

I can test this by adding a print("I'm here!") into the hook and nothing will appear server side regardless if I specify it or not, but it will appear client side just fine.

**Comment by WolfKann** [comment] 2024-01-12 16:17
changing the name of the hook (the unique name, not the actual hook itself) however fixed the stated bug, I'm wondering if there's a chance for hook initiation errors to cause the issue?

> The only thing consistently different I can find is that this bug is only active when for some reason the hook "PlayerButtonDown" is not called on the server by any means.
> 
> I can test this by adding a print("I'm here!") into the hook and nothing will appear server side regardless if I specify it or not, but it will appear client side just fine.

**Comment by robotboy655** [comment] 2024-01-15 14:38
Print out other `PlayerButtonDown` hooks and see what they are doing?

`lua_findhooks PlayerButtonDown` in server console. (`lua_findhooks_cl` is needed clientside)

**Comment by WolfKann** [comment] 2024-01-18 18:52
Other hooks worked, it seems to be an inconsistency issue, I couldn't find anything specific but renaming the hook fixed the issue, I'm guessing it just wasn't caching?

**Comment by robotboy655** [comment] 2024-01-18 19:31
What I meant is - check what `PlayerButtonDown` hooks from other addons do on your server, maybe one of them does something that causes the issue for you.

Also, please clarify whether the problem happens to you on the server, or on the client.

**Comment by WolfKann** [comment] 2024-01-18 22:22
> What I meant is - check what `PlayerButtonDown` hooks from other addons do on your server, maybe one of them does something that causes the issue for you.
> 
> Also, please clarify whether the problem happens to you on the server, or on the client.

No other hooks cause any issues, the problem happens to me on the client. it's as if my client is not sending the the inputs to the server, my client will "visually" attempt to load client side button presses, but the server won't register them.
