### ISSUE TITLE
net.BytesLeft padding is inconsistent

### ISSUE THREAD

**Issue by Nitestokeh** [Facepunch/garrysmod-issues#5951] opened 2024-07-29 12:30 UTC
### Tested on:
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 16:41:33 Jul 24 2024 (9385) (4000)
GMod version 2024.07.26, branch: dev, multicore: 1
Windows 32bit

### Details
I'm trying to send arguments of fluctuating amount to player in a network message. Wiki claims that this function includes 6 extra bits when no arguments are present, however I'm getting 24 and using an end marker returns 0, further adding to confusion

### Code to reproduce
```
if SERVER then
	util.AddNetworkString("Test")


	net.Start("Test")
	net.WriteUInt(1, 2)
	net.WriteUInt(1, 14)
	net.WriteUInt(1, 12)
	local a,b,c
	if a != nil then
		net.WriteType(a)
		if b != nil then
			net.WriteType(b)
			if c != nil then
				net.WriteType(c)
			end
		end
	end
	net.Broadcast()


end

print("case 1")
net.Receive("Test", function()
	local a = net.ReadUInt(2)
	local b = net.ReadUInt(14)
	local c = net.ReadUInt(12)
 
	while (true) do
		local _, left = net.BytesLeft()

		if left > 0 then
			net.ReadType()
		else
			break
		end

	end 
end)
```

**Comment by robotboy655** [comment] 2024-07-29 12:46
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/4079

**Closed by robotboy655** 2024-07-29 12:46 UTC
