### ISSUE TITLE
Sweps unable to switch weapons using keyboard.

### ISSUE THREAD

**Issue by azarus** [Facepunch/garrysmod-issues#1951] opened 2015-04-02 15:29 UTC
**So here is the issue:**
I installed M9K weapons, then some of my players told me that they are unable to switch weapons. I noticed the same thing when tried to use the keyboard. The hud is not showing up, neither switching to the desired slot / weapon. 

**I made a video showcasing the problem:**
https://www.youtube.com/watch?v=kRut2gjN0kU
As you can see when using the keyboard i can't switch between weapons.
I am only able to switch between weapons when i am using the mouse scroll. 
I am able to switch to a slot if it has at least one swep with **SWEP.SlotPos = 1** settings.

**How to reproduce?**
- Set **sbox_weapons** to  **0**.
- Install M9K or other Swep pack.
- Pickup any sweps.
- Try using the keyboard to switch between the weapons.

I started to investigate what causes this. I made a simple swep based on the chair thrower example.

**The problematic code?**
```
	SWEP.Slot = 1
	SWEP.SlotPos = 1
```

Then i noticed that setting the Slot and SlotPos values to 1 works fine. But when i change the SlotPos to a greater value, i am no longer able to switch between weapons.

I am still not sure if i am right but it is a very annoying bug. And there is no better solution than forcing the clients to set the **hud_fastswitch** cvar to 1

**Comment by wiox** [comment] 2015-04-02 15:34
This is true for any SWEP made in Lua.

**Comment by robotboy655** [comment] 2015-04-02 17:02
Duplicate of #1582

**Closed by robotboy655** 2015-04-02 17:02 UTC
