### ISSUE TITLE
Left 4 Dead/Left 4 Dead 2 Maps broken or crashing.

### ISSUE THREAD

**Issue by TyrakatheDragonFan** [Facepunch/garrysmod-issues#4798] opened 2021-01-20 00:30 UTC
### Details:
More than half of the maps for Left 4 Dead and Left 4 Dead 2's campaigns have been experiencing broken textures and models ever since the August 2020 update, with whiteline background/skybox render breaks, yellow, glassy water, glowing metal effects, blinding bloom effects, etc.

Here's a few screenshots of but a few of the maps that have such bugs.

c2m1_highway
![c2m1_highway0001](https://user-images.githubusercontent.com/77705209/105110164-a1ff2280-5a83-11eb-96ee-98819758fffd.jpg)
c3m3_shantytown
![c3m3_shantytown0000](https://user-images.githubusercontent.com/77705209/105110166-a4617c80-5a83-11eb-8054-e00cac2f7a4f.jpg)
c6m2_bedlam
![c6m2_bedlam0002](https://user-images.githubusercontent.com/77705209/105110511-5bf68e80-5a84-11eb-84ca-02bd85b0c884.jpg)
![c6m2_bedlam0003](https://user-images.githubusercontent.com/77705209/105110517-5e58e880-5a84-11eb-9909-5cf39a33b3ce.jpg)

And some of these maps outright crash the game when you try to enter them.

Game Version: 2021.1.19 Pre-Release Branch. And yes, I have tested this on all available branches, outcome is always the same.

### Steps to reproduce:
Simply open the maps in Gmod.

Before the update during early 2020), the maps were working just fine (probably for the first time in Gmod history, whatever updates it had gotten having fixed them), but now this is all too common an occurance. Please find a fix, so I can return to my scenebuilding projects within these maps.

**Comment by robotboy655** [comment] 2021-01-20 03:21
Please at least add one map name for each issue.

**Comment by TyrakatheDragonFan** [comment] 2021-01-20 03:29
> Please at least add one map name for each issue.

Done, though bugs like these are found throughout every map of the Dark Carnival and Swamp Fever campaigns.

**Comment by robotboy655** [comment] 2021-01-20 15:32
What maps crash for you?

**Comment by robotboy655** [comment] 2021-01-20 17:50
Fixed the wireframes and tried to make water not be shit (it's either that, or black skyboxes)

For proper water look this needs to be fulfilled: https://github.com/Facepunch/garrysmod-requests/issues/1162

**Comment by TyrakatheDragonFan** [comment] 2021-01-20 19:32
> Fixed the wireframes and tried to make water not be shit (it's either that, or black skyboxes)
> 
> For proper water look this needs to be fulfilled: [Facepunch/garrysmod-requests#1162](https://github.com/Facepunch/garrysmod-requests/issues/1162)

Glad to hear the problems are being fixed:

I'm slowly but surely testing each map and making a list of which crash and which have bugs; should be done soon. In the meantime, any fixes you guys do...will they be available in the upcoming Jan 2021 update?

**Comment by TyrakatheDragonFan** [comment] 2021-01-20 19:38
Also, there's a bug on numerous L4D/L4D2 that makes the swaying trees stretch weird and even break branches textures. I'll show you once the list is done,

**Comment by robotboy655** [comment] 2021-01-20 20:02
The tree's are like that even in the game itself, they just sway less because their tree sway stuff is hardcoded and ours isnt

**Comment by TyrakatheDragonFan** [comment] 2021-01-20 20:23
> What maps crash for you?:

_**MAPS THAT CRASH/FREEZE THE GAME:
Left 4 Dead:**_
l4d_airport01_greenhouse
l4d_airport02_offices
l4d_airport03_garage
l4d_airport04_terminal
l4d_airport05_runaway
l4d_farm04_barn
l4d_garage01_alleys
l4d_hospital02_subway
l4d_hospital03_sewers
l4d_hospital04_interior
l4d_river02_barge
l4d_smalltown01_caves
l4d_smalltown04_mainstreet
Most L4D2 versions of these campaigns crash as well.

**_Left 4 Dead 2:_**
c10m4_mainstreet
c10m5_houseboat
c12m4_barn

_**MAPS THAT RUN, BUT HAVE BUGS/GLITCHES:
Left 4 Dead:**_
l4d_hospital01_apartments
![l4d_hospital01_apartment0000](https://user-images.githubusercontent.com/77705209/105228027-abda6180-5b27-11eb-8b0a-60b1bf49b370.jpg)
l4d_river01_docks
![l4d_river01_docks0000](https://user-images.githubusercontent.com/77705209/105228036-b09f1580-5b27-11eb-8c03-e7cfa3e90ec7.jpg)
l4d_smalltown05_houseboat
![l4d_smalltown05_houseboat0000](https://user-images.githubusercontent.com/77705209/105228139-d0363e00-5b27-11eb-8894-f4fb5c1a5fee.jpg)
l4d_sv_lighthouse
![l4d_sv_lighthouse0001](https://user-images.githubusercontent.com/77705209/105228153-d5938880-5b27-11eb-85c7-2c98262985ff.jpg)
![l4d_sv_lighthouse0002](https://user-images.githubusercontent.com/77705209/105228160-d75d4c00-5b27-11eb-9230-c1d6dc270db0.jpg)

**_Left 4 Dead 2:_**
c10m1_caves
![c10m1_caves0003](https://user-images.githubusercontent.com/77705209/105228274-0378cd00-5b28-11eb-978e-4341e1ec027e.jpg)
c10m2_drainage
![c10m1_caves0004](https://user-images.githubusercontent.com/77705209/105228284-0673bd80-5b28-11eb-9281-26d2cc2ad5ca.jpg)
c10m3_ranchhouse
![c10m3_ranchhouse0005](https://user-images.githubusercontent.com/77705209/105228292-083d8100-5b28-11eb-9b43-c750083e3ad9.jpg)
c11m1_greenhouse
![c11m1_greenhouse0000](https://user-images.githubusercontent.com/77705209/105228360-1db2ab00-5b28-11eb-97b9-64e1a1c14fa8.jpg)
c11m2_offices
![c11m2_offices0001](https://user-images.githubusercontent.com/77705209/105228356-1b505100-5b28-11eb-9fc1-b425890477f1.jpg)
c11m3_garage
![c11m3_garage0002](https://user-images.githubusercontent.com/77705209/105228349-18edf700-5b28-11eb-80bc-a5c6b2356a00.jpg)
c11m5_runway
![c11m5_runway0003](https://user-images.githubusercontent.com/77705209/105228337-168b9d00-5b28-11eb-8640-f70bf7acc6f6.jpg)
c12m1_hilltop
![c12m1_hilltop0004](https://user-images.githubusercontent.com/77705209/105228330-14294300-5b28-11eb-9cef-808539c536f3.jpg)
c12m2_traintunnel
![c12m2_traintunnel0006](https://user-images.githubusercontent.com/77705209/105228308-0d9acb80-5b28-11eb-9c17-04be2708452a.jpg)
c12m3_bridge
![c12m3_bridge0007](https://user-images.githubusercontent.com/77705209/105228300-0bd10800-5b28-11eb-8fd8-b9357915dc10.jpg)

And you already know the Passing, Dark Carnival, Swamp Fever, and Hard Rain bugs/issues.

If I find anymore, I will imform you.

**Comment by robotboy655** [comment] 2021-01-21 16:30
You can avoid the tree stuff with these 2 commands: `ent_fire env_wind kill; cl_tree_sway_dir 0 0`

I have no plans "fixing" this.

**Comment by robotboy655** [comment] 2021-01-21 18:08
Do you know when the freezing/crashing issues started? It definitely didn't use to happen, but it's not caused by this upcoming update as far as I can tell.

**Comment by TyrakatheDragonFan** [comment] 2021-01-21 18:10
> You can avoid the tree stuff with these 2 commands: `ent_fire env_wind kill; cl_tree_sway_dir 0 0`
> 
> I have no plans "fixing" this.

Okay, since we can fix it command wise, that'll do.

> Do you know when the freezing/crashing issues started? It definitely didn't use to happen, but it's not caused by this upcoming update as far as I can tell.

After either the June 2020 Update or the August 2020 Update went live. The second half of 2020 was when it all started happening. The first half of 2020, they all work perfectly fine.

**Comment by robotboy655** [comment] 2021-01-25 17:27
Aw crap, its due to r_flushlod calls.

**Comment by robotboy655** [comment] 2021-01-25 18:39
Ok it should be fixed on Dev beta, but I will not be fixing it for the normal version of the game just yet as it probably causes issues elsewhere and it all needs looking into. It will be put into x86-64 soon after the update for testing.

**Closed by robotboy655** 2021-01-25 18:39 UTC
