### ISSUE TITLE
x86_64 Chromium causing crashes on startup or several seconds into loading, Mac Monterey 12.6

### ISSUE THREAD

**Issue by bedrockperson** [Facepunch/garrysmod-issues#5338] opened 2022-10-09 16:31 UTC
### Details
Since the March update, Garry's Mod has refused to run on my M1 MacBook. Each time, it would load to menu, and then as it began to load addons, it would crash. After disabling all addons and loading the game, it would crash after the moment in time that the addons would have began loading.

There was a workaround – when the crash window dialog opened, I'd just choose "reopen" and a _signed GMod app would open and work flawlessly.

However, after sending in my MacBook for a repair, all data was lost and its OS was updated to Monterey 12.6. Reinstalled GMod – this time, it would crash at the blue loading screen.

Problem Reporter spat out [this](https://pastebin.com/aDEbmx61) (pastebin)

I found a thread here which suggested adding the -nochromium parameter to the launch. When I did this, it cleared the blue loading screen... and then, the old bug re-emerged – as soon as addons began being loaded, it crashed.

Problem Reporter now coughed up [this](https://pastebin.com/kQAcF9jh).

Honestly not sure where to go from here. My livelihood depends on this and the fact this continues to get worse without any real progress is incredibly disheartening.

[Here](https://drive.google.com/file/d/1JX0MkZAhO-abv4eeQiA-JBJcKA2xOIQk/view?usp=sharing) is a .dmp file from March, when I began having this problem in the first place. 

If it helps, also, [here](https://pastebin.com/XFci2ULQ) is what shows up in Terminal.

**I've confirmed this is exclusive to x86_64 and Chromium builds** I just pulled out an old, shitty Mac laptop and ran the regular 32-bit GMOD on it. Absolutely no problems. What the fuck.

### Steps to reproduce

Install x86_64 beta of G-Mod, load it, get the crash log.

Then, add a -nochromium property, launch G-Mod, get the crash log.

**Comment by robotboy655** [comment] 2022-10-13 11:58
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5001

**Closed** 2022-10-13 11:58 UTC
Labels: Platform: MacOS, Crash
