### ISSUE TITLE
VMatrix:SetScale doesn't work properly

### ISSUE THREAD

**Issue by Jcw87** [Facepunch/garrysmod-issues#2222] opened 2015-09-01 13:14 UTC
if you run this:

```
local m = Matrix()
m:SetScale(Vector(10, 1, 1))
PrintTable(m:ToTable())
```

you get this:

> 1:
>       1   =   9.9999990463257
>       2   =   0
>       3   =   0
>       4   =   0
> 2:
>       1   =   0
>       2   =   0.99999994039536
>       3   =   0.99999994039536
>       4   =   0
> 3:
>       1   =   0
>       2   =   0
>       3   =   0
>       4   =   0
> 4:
>       1   =   0
>       2   =   0
>       3   =   0
>       4   =   1

clearly not correct. If you use VMatrix:Scale() instead:

```
local m = Matrix()
m:Scale(Vector(10, 1, 1))
PrintTable(m:ToTable())
```

you get this

> 1:
>       1   =   10
>       2   =   0
>       3   =   0
>       4   =   0
> 2:
>       1   =   0
>       2   =   1
>       3   =   0
>       4   =   0
> 3:
>       1   =   0
>       2   =   0
>       3   =   1
>       4   =   0
> 4:
>       1   =   0
>       2   =   0
>       3   =   0
>       4   =   1

looks much better.

**Comment by willox** [comment] 2016-01-20 09:02
Are you reporting the loss of precision or that the 2nd/3rd rows are being calculated wrong?

**Comment by thegrb93** [comment] 2016-01-20 10:44
Both it seems.

**Comment by Jcw87** [comment] 2016-01-22 03:48
Both, with a greater emphasis on the wrong calculation. The precision issue is important too though, because I wouldn't expect a precision issue while trying to SET the scale of an identity matrix.

**Comment by robotboy655** [comment] 2016-01-22 10:10
The 2nd/3rd row bug should be fixed in the January update FYI.

**Comment by thegrb93** [comment] 2016-01-22 17:31
Looks good. The precision problem seems to come from the VMatrix.ToTable method because the __tostring method don't show any precision loss.

**Comment by robotboy655** [comment] 2016-01-22 21:34
No, the problem is not ToTable. __tostring rounds the numbers down.

**Comment by xaviergmail** [comment] 2016-03-03 02:17
SetScale doesn't appear to work after being set to Vector(0, 0, 0), no matter what you try to set it to.

I am on the dev branch.

Code:
```
function ENT:Initialize()
	self.StartTime = RealTime()
	self.FadeTime = 5

	self.VecMin = Vector()
	self.VecMax = Vector(10, 10, 10)

	self.DrawMatrix = Matrix()
	self:EnableMatrix("RenderMultiply", self.DrawMatrix)
end

function ENT:Draw()
	local v = LerpVector((RealTime() - self.StartTime) / self.FadeTime, self.VecMin, self.VecMax)
	self.DrawMatrix:SetScale(v)
	print("V:", v, "M:", self.DrawMatrix:GetScale())
	PrintTable(self.DrawMatrix:ToTable())
	self:DrawModel()
end
```

Results:
>
V:	4.564844 4.564844 4.564844	M:	0.000000 0.000000 0.000000
1:
		1	=	0
		2	=	0
		3	=	0
		4	=	0
2:
		1	=	0
		2	=	0
		3	=	0
		4	=	0
3:
		1	=	0
		2	=	0
		3	=	0
		4	=	0
4:
		1	=	0
		2	=	0
		3	=	0
		4	=	1

Expected:
>
V:	4.564844 4.564844 4.564844	M:	4.564844 4.564844 4.564844
[...]

**Comment by robotboy655** [comment] 2016-03-03 10:36
Are you implying you expect multiplication by 0 be anything else but 0?

After you have set the matrix elements to 0, how do you expect them to change by applying multiplication to them.

To fix your problem, use self.DrawMatrix:Identity() to set the diagonal elements to 1 before applying SetScale:
```
function ENT:Initialize()
    self.StartTime = RealTime()
    self.FadeTime = 5

    self.VecMin = Vector()
    self.VecMax = Vector(10, 10, 10)

    self.DrawMatrix = Matrix()
end

function ENT:Draw()
    local v = LerpVector((RealTime() - self.StartTime) / self.FadeTime, self.VecMin, self.VecMax)
    self.DrawMatrix:Identity()
    self.DrawMatrix:SetScale(v)
    self:EnableMatrix("RenderMultiply", self.DrawMatrix)
    print("V:", v, "M:", self.DrawMatrix:GetScale())
    PrintTable(self.DrawMatrix:ToTable())
    self:DrawModel()
end
```

**Comment by thegrb93** [comment] 2016-03-03 10:49
SetScale implies that the scaling of the matrix is set. Not scaled i.e. multiplied.

**Comment by thegrb93** [comment] 2016-03-03 10:52
Maybe this is a case of a bad function name?

**Comment by robotboy655** [comment] 2016-03-03 11:22
Just how do you think the scale of a matrix is stored in the matrix?

```
local m = Matrix()
print("Initial matrix:")
print(m)
m:SetScale( Vector(1,1,1) )
print("Scale set to 1")
print(m)
m:SetScale( Vector(2,2,2) )
print("Scale set to 2")
print(m)
m:Scale(Vector(2,2,2))
print("Scale multiplied by 2")
print(m)
m:Scale(Vector(10,10,10))
print("Scale multiplied by 10")
print(m)
m:SetScale(Vector(10,10,10))
print("Scale set to 10")
print(m)
```

```
Initial matrix:
[1.00000,	0.00000,	0.00000,	0.00000]
[0.00000,	1.00000,	0.00000,	0.00000]
[0.00000,	0.00000,	1.00000,	0.00000]
[0.00000,	0.00000,	0.00000,	1.00000]
Scale set to 1
[1.00000,	0.00000,	0.00000,	0.00000]
[0.00000,	1.00000,	0.00000,	0.00000]
[0.00000,	0.00000,	1.00000,	0.00000]
[0.00000,	0.00000,	0.00000,	1.00000]
Scale set to 2
[2.00000,	0.00000,	0.00000,	0.00000]
[0.00000,	2.00000,	0.00000,	0.00000]
[0.00000,	0.00000,	2.00000,	0.00000]
[0.00000,	0.00000,	0.00000,	1.00000]
Scale multiplied by 2
[4.00000,	0.00000,	0.00000,	0.00000]
[0.00000,	4.00000,	0.00000,	0.00000]
[0.00000,	0.00000,	4.00000,	0.00000]
[0.00000,	0.00000,	0.00000,	1.00000]
Scale multiplied by 10
[40.00000,	0.00000,	0.00000,	0.00000]
[0.00000,	40.00000,	0.00000,	0.00000]
[0.00000,	0.00000,	40.00000,	0.00000]
[0.00000,	0.00000,	0.00000,	1.00000]
Scale set to 10
[10.00000,	0.00000,	0.00000,	0.00000]
[0.00000,	10.00000,	0.00000,	0.00000]
[0.00000,	0.00000,	10.00000,	0.00000]
[0.00000,	0.00000,	0.00000,	1.00000]
```

**Comment by robotboy655** [comment] 2016-03-03 11:30
Think of a normal number. If you set it to 0, you cannot change it to non zero with multiplication unless you SET the number to a non zero value.

The only way you set a scale of a matrix is with multiplication.

See https://en.wikipedia.org/wiki/Scaling_(geometry) ( The matrix stuff )

**Comment by thegrb93** [comment] 2016-03-03 20:15
The real reason is SetScale fails if a null vector is in the column since there's no direction to scale to.

**Comment by xaviergmail** [comment] 2016-03-03 21:04
I expected `**Set**Scale` to straight up set it, with no multiplication since that's what `Scale` does
Calling `Identity` just seems like a waste of a call

**Comment by thegrb93** [comment] 2016-03-04 00:13
The problem is that the basis of your matrix contains null vectors of which it is impossible to set the scale. What's weird is that your matrix isn't Identity to begin with. Matrix() should return an identity matrix. Make sure you're not setting the scale to 0 by accident.

**Comment by thegrb93** [comment] 2016-03-04 00:17
I recommend keeping your matrix as it is and each frame make a copy and do your scaling on the copy and then use the copy.

**Comment by xaviergmail** [comment] 2016-03-04 00:51
It is. The issue is that it can't recover from SetScale(Vector(0, 0, 0))
which is the case in the first frame because of LerpVector.

Basically, initial settings:
matrix:SetScale(Vector(0, 0, 0))

matrix:Scale(Vector(1, 1, 1))  -- Should be 0, 0, 0, is 0, 0, 0
matrix:SetScale(Vector(1, 1, 1))  -- Should be 1, 1, 1 but stays at 0, 0, 0

I simply countered that by setting my minimum vector to lerp from to
Vector(1, 1, 1) / 1000 instead of Vector(0, 0, 0) (PS Vector() isn't a
"null" vector. It's the same as Vector(0, 0, 0))

**Comment by thegrb93** [comment] 2016-03-04 03:12
http://mathworld.wolfram.com/NullVector.html

**Comment by thegrb93** [comment] 2021-04-10 22:21
@robotboy655 this can be closed

**Closed** 2021-04-12 08:09 UTC
