### ISSUE TITLE
Terrortown (TTT) Crash on CleanUpMap()

### ISSUE THREAD

**Issue by Drizzy-1** [Facepunch/garrysmod-issues#4959] opened 2021-05-30 00:20 UTC
I have managed a TTT server for over a year now and I have not been able to figure out this crashing issue. I have taken all addons of any sort and everything and completely stripped it off of my server and the crashes still occurred. I have fully reinstalled the server and left it untouched other than adding a map to the files. I have also tried using different hosts and much more. The crashes are completely random and I am not sure how to fix this issue. 

I have tried many "fixes" such as this one `game.CleanUpMap( false, { "env_fire", "entityflame", "_firesmoke" } )`

I have added some crash dumps/logs below.
If anyone can help, I would greatly appreciate it.

![D0LvZR3](https://user-images.githubusercontent.com/84890626/120088041-f6ae4c00-c0ba-11eb-91a2-5702b10313d6.png)
![jPr9Psb](https://user-images.githubusercontent.com/84890626/120088042-f6ae4c00-c0ba-11eb-90ee-f394fa22efa5.png)

Steps to reproduce: Wait till the round restarts. (Crashes are random)

**Comment by robotboy655** [comment] 2021-05-31 13:29
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/4960

**Closed by robotboy655** 2021-05-31 13:29 UTC
Labels: Crash, Dependency: IVP
