### ISSUE TITLE
Blendmeasure materials on brushes are shown incorrectly in Hammer

### ISSUE THREAD

**Issue by osiris-plus** [Facepunch/garrysmod-issues#4847] opened 2021-02-25 16:40 UTC
### Details
Have blendmeasure material applied both to brush and displacement. Displacement shows correctly in hammer, but brushes are not.

![](https://cdn.discordapp.com/attachments/589120351238225940/814534816804372510/unknown.png)
![](https://cdn.discordapp.com/attachments/589120351238225940/814534747437924412/unknown.png)

Source SDK 2013's hammer doesn't have this issue, but it has other issue: blending being shown incorrectly and rough.

### Steps to reproduce

Here is vmf and bsp files:

https://cdn.discordapp.com/attachments/589120351238225940/814534689627832330/blendmeasure_bug.vmf
https://cdn.discordapp.com/attachments/589120351238225940/814534692409835541/blendmeasure_bug.bsp

**Comment by robotboy655** [comment] 2021-02-25 17:41
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/3247

**Closed by robotboy655** 2021-02-25 17:41 UTC
Labels: Shaders, Tools

**Comment by osiris-plus** [comment] 2021-02-25 17:47
![](https://cdn.discordapp.com/emojis/745733891398303847.png?v=1)
