### ISSUE TITLE
$treeSway 1 Flickerin` shadows

### ISSUE THREAD

**Issue by MalevichLD** [Facepunch/garrysmod-issues#5960] opened 2024-07-31 22:51 UTC
### Details
 Since 2018 I saw a report here on the topic $treeSway 1 applied in GMOD and there is still no solution to the problem
If earlier it was possible to do at least something using $halflambert, now even this does not help
Dear developers, do not abandon GMOD, we believe that you can solve this problem
We believe

### Steps to reproduce
 

1. Apply $treeSway 1 to a texture with a VertexLitGeneric shader of a specific model on any editable map
2. Go to the map and turn on the flashlight while looking at this model

**Comment by robotboy655** [comment] 2024-07-31 22:59
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/3504

**Closed by robotboy655** 2024-07-31 22:59 UTC
Labels: Shaders
