### ISSUE TITLE
SWEP:GetNPCBurstSettings() does not work on Combine soldiers

### ISSUE THREAD

**Issue by TheOnly8Z** [Facepunch/garrysmod-issues#4553] opened 2020-06-24 22:28 UTC
### Details
If a SWEP uses `GetNPCBurstSettings()` to set the length and duration of a burst for NPCs, it will be functional on citizens and metropolice, but not combine soldiers (and any variant of them, like elites and prison guards). 

On Combine soldiers, they will only fire the first bullet per burst, and for the rest of the burst emit shell and muzzle flashes (but not actually bullets).

### Steps to reproduce
Use the following SWEP file.
```
AddCSLuaFile()

SWEP.PrintName = "test weapon"

SWEP.Slot = 1
SWEP.SlotPos = 5

SWEP.Spawnable = true
SWEP.WorldModel = "models/weapons/w_smg1.mdl"
SWEP.ViewModel = "models/weapons/c_smg1.mdl"

SWEP.Primary.ClipSize = -1
SWEP.Primary.DefaultClip = -1
SWEP.Primary.Automatic = true
SWEP.Primary.Ammo = "none"

SWEP.Secondary.ClipSize = -1
SWEP.Secondary.DefaultClip = -1
SWEP.Secondary.Automatic = true
SWEP.Secondary.Ammo = "none"

function SWEP:Initialize()
    self:SetHoldType("smg")
end

function SWEP:PrimaryAttack()
    if self:GetNextPrimaryFire() > CurTime() then return end

    self:EmitSound("Weapon_AR2.Single")
    self:ShootBullet(10, 1, 0.01)

    self:SetNextPrimaryFire(CurTime() + 0.1)
end

function SWEP:CanBePickedUpByNPCs()
    return true
end

function SWEP:GetNPCBulletSpread()
    return 15
end

function SWEP:GetNPCBurstSettings()
    return 10, 20, 0.1
end

function SWEP:GetNPCRestTimes()
    return 0.2, 0.3
end
```

1. Give any random NPC that isn't a combine soldier this SWEP. Make it fire to confirm the burst is working as normal.
2. Give any Combine soldier this SWEP. Make it fire - it would only shoot the first bullet.
3. Modify the SWEP's `GetNPCBurstSettings()` return value to 1, 1 and 0.1. The Combine soldier should fire single shots normally.

**Comment by robotboy655** [comment] 2020-06-30 18:56
Should be fixed. The issue is that combine NPC do not use the shot regulator like all other NPCs do, sigh..

Also fixed combine soldiers not using GetNPCRestTimes at all.

**Closed by robotboy655** 2020-06-30 18:56 UTC
