### ISSUE TITLE
Client workshop addons no longer download

### ISSUE THREAD

**Issue by crosscoder1** [Facepunch/garrysmod-issues#5646] opened 2023-12-18 02:45 UTC
### Details
Since the update on Dec 13th, the Linux x86-64 client will no longer download addons from the Workshop when connecting to a dedicated server.  I can provide a full console log on request, however, I have included some relevant parts of the log displaying the errors below.   Also despite content being cached locally, that appears to be ignored as it attempts to re-download all workshop content on each load.  Rolling the binaries back from the Steam Depot to 2023.06.28 resolves the issue.  I can confirm that this issue occurs with multiple Linux users.  I have not tested the 32bit Linux client.

### Steps to reproduce
1) Update to the latest Linux x86-64 Garry's Mod client.
2) Connect to any server relying on workshop downloads for addon content.
3) Map, textures, models are all missing.

Log Portions:
`...WorkshopDL: Took too long to get item info for 935754808!
WorkshopDL: There is no file to mount for '935754808'!
WorkshopDL: Took too long to get item info for 1626509911!
WorkshopDL: There is no file to mount for '1626509911'!
WorkshopDL: Took too long to get item info for 2062531235!
WorkshopDL: There is no file to mount for '2062531235'!
WorkshopDL: Took too long to get item info for 246873784!
WorkshopDL: There is no file to mount for '246873784'!
WorkshopDL: Took too long to get item info for 1741741175!
WorkshopDL: There is no file to mount for '1741741175'!
WorkshopDL: Took too long to get item info for 1228585060!
WorkshopDL: There is no file to mount for '1228585060'!
WorkshopDL: Took too long to get item info for 2007086325!
WorkshopDL: There is no file to mount for '2007086325'!...`

`...Error downloading 'sound/fishingrod/reel.wav' (denied by server)
Error downloading 'materials/mediaplayer/ui/spritesheet2015-10-7.png' (denied by server)
Error downloading 'resource/fonts/ClearSans-Medium.ttf' (denied by server)
Error downloading 'materials/vgui/entities/carbomb.vtf' (denied by server)
Error downloading 'materials/vgui/entities/carbomb.vmt' (denied by server)
Error downloading 'materials/vgui/hud/carbomb_hud_icon.vtf' (denied by server)
Error downloading 'materials/vgui/hud/carbomb_hud_icon.vmt' (denied by server)
Error downloading 'materials/vgui/entities/carbomb-defusekit.vtf' (denied by server)
Error downloading 'materials/vgui/entities/carbomb-defusekit.vmt' (denied by server)
Error downloading 'materials/vgui/hud/carbomb_defuse_hud_icon.vtf' (denied by server)
Error downloading 'materials/vgui/hud/carbomb_defuse_hud_icon.vmt' (denied by server)
Error downloading 'materials/vgui/entities/carbomb-scanner.vtf' (denied by server)
Error downloading 'materials/vgui/entities/carbomb-scanner.vmt' (denied by server)
Error downloading 'materials/vgui/hud/carbomb_scanner_hud_icon.vtf' (denied by server)
Error downloading 'materials/vgui/hud/carbomb_scanner_hud_icon.vmt' (denied by server)...`

**Comment by robotboy655** [comment] 2023-12-18 18:09
Cannot confirm this. Both WorkshopDL and the other system work correctly on `x86-64 ` beta in my testing joining random Sandbox servers on Windows client.

The workshop error you are getting suggests there's a network issue on your end, between you and Steam. Perhaps it was a simple Steam outage. Maybe try checking https://steamstat.us when this happens.

The other errors you are getting are likely the fact that the server you were testing does not allow downloads through that system, as it probably expects workshop downloads to be successful and contain those files.

**Comment by crosscoder1** [comment] 2023-12-18 18:15
This is with the Linux client, not Windows.  I have confirmed with 3 other Linux users on the x86-64 build that they are experiencing the same issue and with multiple servers.  This issue first appeared for me after the update on the 13th and I tested it again yesterday before posting this bug report.  Additionally, as mentioned, rolling back to a previous build's binary does solve the issue.

**Comment by Lamrr** [comment] 2023-12-19 05:09
I can also confirm this issue on my system. I can join servers and their addons will be downloaded successfully, so it seems like  the problem doesn't seem to (just) be in the downloading but the mounting of addons. Persists after completely reinstalling the game. I'm happy to try an earlier binary to see if this is a regression issue, if someone is willing to walk through the steps of doing so.

Fedora 39, Nvidia drivers 545.29.06, GNOME 45.2, X11
Patched with GModCEFCodecFix.

When joining a server which has already successfully downloaded its workshop addons I get the following;
```
WorkshopDL: Querying 10 addons for info..
Not loading addon '/home/USERNAME/.local/share/steam/steamapps/workshop/content/4000/1505634134/sunrust_content.gma' - file doesn't exist
Couldn't mount file [/home/USERNAME/.local/share/steam/steamapps/workshop/content/4000/1505634134/sunrust_content.gma]
WorkshopDL: Failed to mount /home/USERNAME/.local/share/Steam/steamapps/workshop/content/4000/1505634134/sunrust_content.gma
Not loading addon '/home/USERNAME/.local/share/steam/steamapps/workshop/content/4000/1924496353/temp.gma' - file doesn't exist
Couldn't mount file [/home/USERNAME/.local/share/steam/steamapps/workshop/content/4000/1924496353/temp.gma]
WorkshopDL: Failed to mount /home/USERNAME/.local/share/Steam/steamapps/workshop/content/4000/1924496353/temp.gma
Not loading addon '/home/USERNAME/.local/share/steam/steamapps/workshop/content/4000/2566097537/sparkwerk.gma' - file doesn't exist
Couldn't mount file [/home/USERNAME/.local/share/steam/steamapps/workshop/content/4000/2566097537/sparkwerk.gma]
WorkshopDL: Failed to mount /home/USERNAME/.local/share/Steam/steamapps/workshop/content/4000/2566097537/sparkwerk.gma
Not loading addon '/home/USERNAME/.local/share/steam/steamapps/workshop/content/4000/1940258759/temp.gma' - file doesn't exist
Couldn't mount file [/home/USERNAME/.local/share/steam/steamapps/workshop/content/4000/1940258759/temp.gma]
WorkshopDL: Failed to mount /home/USERNAME/.local/share/Steam/steamapps/workshop/content/4000/1940258759/temp.gma
Not loading addon '/home/USERNAME/.local/share/steam/steamapps/workshop/content/4000/2966488461/gmpublisher.gma' - file doesn't exist
Couldn't mount file [/home/USERNAME/.local/share/steam/steamapps/workshop/content/4000/2966488461/gmpublisher.gma]
WorkshopDL: Failed to mount /home/USERNAME/.local/share/Steam/steamapps/workshop/content/4000/2966488461/gmpublisher.gma
Not loading addon '/home/USERNAME/.local/share/steam/steamapps/workshop/content/4000/2986186449/temp.gma' - file doesn't exist
Couldn't mount file [/home/USERNAME/.local/share/steam/steamapps/workshop/content/4000/2986186449/temp.gma]
WorkshopDL: Failed to mount /home/USERNAME/.local/share/Steam/steamapps/workshop/content/4000/2986186449/temp.gma
Not loading addon '/home/USERNAME/.local/share/steam/steamapps/workshop/content/4000/1940240985/temp.gma' - file doesn't exist
Couldn't mount file [/home/USERNAME/.local/share/steam/steamapps/workshop/content/4000/1940240985/temp.gma]
WorkshopDL: Failed to mount /home/USERNAME/.local/share/Steam/steamapps/workshop/content/4000/1940240985/temp.gma
Not loading addon '/home/USERNAME/.local/share/steam/steamapps/workshop/content/4000/1949295500/gmpublisher.gma' - file doesn't exist
Couldn't mount file [/home/USERNAME/.local/share/steam/steamapps/workshop/content/4000/1949295500/gmpublisher.gma]
WorkshopDL: Failed to mount /home/USERNAME/.local/share/Steam/steamapps/workshop/content/4000/1949295500/gmpublisher.gma
Not loading addon '/home/USERNAME/.local/share/steam/steamapps/workshop/content/4000/1836233427/zs.gma' - file doesn't exist
Couldn't mount file [/home/USERNAME/.local/share/steam/steamapps/workshop/content/4000/1836233427/zs.gma]
WorkshopDL: Failed to mount /home/USERNAME/.local/share/Steam/steamapps/workshop/content/4000/1836233427/zs.gma
Not loading addon '/home/USERNAME/.local/share/steam/steamapps/workshop/content/4000/1729777418/temp.gma' - file doesn't exist
Couldn't mount file [/home/USERNAME/.local/share/steam/steamapps/workshop/content/4000/1729777418/temp.gma]
WorkshopDL: Failed to mount /home/USERNAME/.local/share/Steam/steamapps/workshop/content/4000/1729777418/temp.gma
```
The aforementioned files do exist and were successfully downloaded, using `ls -R` in workshop/content/4000;

```
.:
1505634134  1924496353  1949295500  2904941963  3001181000
1729777418  1940240985  2566097537  2966488461  3015580234
1836233427  1940258759  2868502388  2986186449  3098427828

./1505634134:
sunrust_content.gma

./1729777418:
temp.gma

./1836233427:
zs.gma

./1924496353:
temp.gma

./1940240985:
temp.gma

./1940258759:
temp.gma

./1949295500:
gmpublisher.gma

./2566097537:
sparkwerk.gma

./2868502388:
gmpublisher.gma

./2904941963:
zs_bankbarn.gma

./2966488461:
gmpublisher.gma

./2986186449:
temp.gma

./3001181000:
gmpublisher.gma

./3015580234:
zs_obj_horizons_a3.gma

./3098427828:
gmpublisher.gma
```

**Comment by crosscoder1** [comment] 2023-12-20 15:30
As an update.  This issue still persists on the version released on the 19th.  The only workaround found was using a previous binary from the 13th.

As a further note, as the previous commenter noted, the issues does appear to include a mounting issue too.  Even if all workshop items are manually subscribed to, errors still appear on the map.

**Comment by mlysle** [comment] 2023-12-21 22:46
I can also confirm this issue.

**Comment by Dolphin2Point1** [comment] 2023-12-22 00:22
The issue with mounting appears to be that all the paths become lowercase in the second and third line of each error.
The format typically looks like this:
```WorkshopDL: Failed to mount /home/<username>/.local/share/Steam/steamapps/common/GarrysMod/garrysmod/cache/workshop/<addonid>.gma
Not loading addon '/home/<username>/.local/share/steam/steamapps/common/garrysmod/garrysmod/cache/workshop/<addonid>.gma' - file doesn't exist
Couldn't mount file [/home/<username>/.local/share/steam/steamapps/common/garrysmod/garrysmod/cache/workshop/<addonid>.gma]```
as you can see in the first "Failed to mount" line, the directories are properly capitalized, but when you get to the second or third ones "Steam" and "GarrysMod" lose their capitalization.
This also applies for the ones formatted like `[/home/<username>/.local/share/Steam/steamapps/workshop/content/4000/<addonid>/<addonfilename>.gma]`

**Comment by chev2** [comment] 2023-12-23 00:11
Experiencing the same issue as well, Linux x86-64 branch.

As a temporary workaround, I created symbolic links for `steam/` -> `Steam/` and `garrysmod/` -> `GarrysMod/` which does appear to work.

**Comment by Dolphin2Point1** [comment] 2023-12-23 22:18
i never even thought of doing that chev, that's genius!

**Comment by Exotic0015** [comment] 2023-12-31 19:06
I am experiencing this as well and can confirm that chev's workaround fixes the issue.

**Comment by robotboy655** [comment] 2024-01-04 13:13
Thanks for the investigation and sorry for the delayed fix, should be fixed within the day.

**Closed by robotboy655** 2024-01-04 13:13 UTC
Labels: Platform: Linux, Cannot confirm
