### ISSUE TITLE
Entity:GetAttachment() returns incorrect position data for viewmodels

### ISSUE THREAD

**Issue by TiberiumFusion** [Facepunch/garrysmod-issues#4481] opened 2020-05-02 01:11 UTC
### Details
The worldspace position returned by `Entity:GetAttachment()` is simply wrong when called on viewmodels.

The worldspace translation seems to include some perspective calculations (how odd) that incorrectly factors in the player's FOV and the viewmodel's FOV.

#### Quick demo screenshot (which you can reproduce with the code below)
The red cube is positioned via `GetBoneMatrix():GetTranslation()`, which returns a _correct_ translation. The green cube is positioned via `GetAttachment().Pos`, which returns an _incorrect_ translation.
![getattachment is broken 1](https://user-images.githubusercontent.com/6332277/80851423-cd896680-8bef-11ea-8659-7ef173aaee62.png)
If the player's FOV (as set by the game settings) and the SWEP's `ViewModelFOV` property do not match (which is the case for 99.99% of all SWEPs), then `GetAttachment()` gives bogus data. If the player's FOV and the SWEP's `ViewModelFOV` property are equal, then the translation given by `GetAttachment()` is correct.

This makes `GetAttachment()` unusable on viewmodels, meaning that the QC `$attachment` system is pretty much useless in gmod when dealing with viewmodels.

**!!! Here is a short, 7 second video which better visualizes the issue:** [https://drive.google.com/open?id=1i4JWdoo8sTN9RrI2aS5nvBaXiAhDSbiL](https://drive.google.com/open?id=1i4JWdoo8sTN9RrI2aS5nvBaXiAhDSbiL)

### Steps to reproduce
- In the game's settings, set your FOV to the default value of `82.5`.
- Create a SWEP with a `SWEP.ViewModelFOV` of `70`.
- Pick a viewmodel that has a QC `$attachment` with zero offset from a bone
- Use the code below to visualize the issue
```
SWEP.ViewModelFOV = 70
SWEP.BobScale = 0
SWEP.SwayScale = 0

if CLIENT then
	SWEP.CSEntViewBone = nil
	SWEP.CSEntViewAttachment = nil
	
	function SWEP:Initialize()
		-- Two CSEnts that will help visualize this problem
		self.CSEntViewBone = ClientsideModel("models/hunter/blocks/cube025x025x025.mdl", RENDERGROUP_VIEWMODEL)
		self.CSEntViewBone:SetNoDraw(true)
		self.CSEntViewAttachment = ClientsideModel("models/hunter/blocks/cube025x025x025.mdl", RENDERGROUP_VIEWMODEL)
		self.CSEntViewAttachment:SetNoDraw(true)
		
		local scaleCompositeMatrix = Matrix() -- Shrink them a bit so they dont obscure the whole viewmodel
		scaleCompositeMatrix:Scale(Vector(0.1, 0.1, 0.1))
		self.CSEntViewBone:EnableMatrix("RenderMultiply", scaleCompositeMatrix)
		self.CSEntViewAttachment:EnableMatrix("RenderMultiply", scaleCompositeMatrix)
	end
	
	function SWEP:GetViewModelPosition(pos, ang)
		local newPos = pos * 1
		newPos = newPos + (Vector(4, 0, 0) * math.sin(SysTime() / 180 * math.pi * 50)) -- Oscillating offset to demonstrate the failure of GetAttachment()
		return newPos, ang
	end
	
	function SWEP:ViewModelDrawn()
		local vm = self.Owner:GetViewModel()
		vm:SetupBones()
		local b = vm:GetBoneMatrix(vm:LookupBone("z_scope")):GetTranslation() -- Pick a bone
		local e = vm:GetAttachment(2).Pos -- Pick an attachment that has zero offset from the above bone
		print(b, e, (b - e)) -- Prints the worldspace bone translation (which is correct), the worldspace attachment translation (which is wrong), and their difference
		
		-- Red csent cube. Uses the translation from GetBoneMatrix (which is correct data)
		render.SetColorModulation(1, 0, 0)
		self.CSEntViewBone:SetPos(b)
		self.CSEntViewBone:DrawModel()
		
		-- Green csent cube. Uses the translation from GetAttachment (which is invalid data)
		render.SetColorModulation(0, 1, 0)
		self.CSEntViewAttachment:SetPos(e)
		self.CSEntViewAttachment:DrawModel()
		
		render.SetColorModulation(1, 1, 1)
	end
end
```

This code demonstrates the issue by using `GetViewModelPosition` to translate the viewmodel away from the origin (so that the perspective miscalculations are revealed). This is NOT the only time the issue presents itself, however. Any time a QC $attachment is transformed away from the viewmodel entity's position (i.e. what I presume is the local origin for `GetAttachment()`'s calculations), the issue will become very apparent.

### Environment
x64 2020.04.30

**Comment by robotboy655** [comment] 2020-05-04 15:22
Potentially duplicate of #1421

**Comment by TiberiumFusion** [comment] 2020-05-04 22:11
@robotboy655 For what it's worth, I suspect this issue has existed since at least 2013, perhaps introduced by Gmod 13. There are a few insanely popular SWEP-related addons which _should_ use `GetAttachment()` by all means, but instead use `GetBoneMatrix()`, and have been that way since the day they released in 2013 or earlier. In other words, the precedent for `GetBoneMatrix()` might be a 7+ year workaround to a 7+ year old bug. Getting this fixed would be wonderful.

**Comment by TankNut** [comment] 2020-05-05 18:40
So I might've accidentally found a fix for this. While working on a custom weapon model thing some time ago I figured out my own implementation of GetAttachment was missing a call to [FormatViewModelAttachment](https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/game/client/c_baseviewmodel.cpp#L45) or a lua equivalent similar to this:
```lua
local function translatefov(fov, pos, inverse)
	local worldx = math.tan(LocalPlayer():GetFOV() * (math.pi / 360))
	local viewx = math.tan(fov * (math.pi / 360))

	local factor = Vector(worldx / viewx, worldx / viewx, 0)
	local tmp = pos - EyePos()

	local eye = EyeAngles()
	local transformed = Vector(eye:Right():Dot(tmp), eye:Up():Dot(tmp), eye:Forward():Dot(tmp))

	if inverse then
		transformed.x = transformed.x / factor.x
		transformed.y = transformed.y / factor.y
	else
		transformed.x = transformed.x * factor.x
		transformed.y = transformed.y * factor.y
	end

	local out = (eye:Right() * transformed.x) + (eye:Up() * transformed.y) + (eye:Forward() * transformed.z)

	return EyePos() + out
end
```

After adding the above function and swapping out the ViewModelDrawn portion with the following code, the issue is fixed.

```lua
function SWEP:ViewModelDrawn()
	local vm = self.Owner:GetViewModel()
	vm:SetupBones()
	local e = vm:GetAttachment(2)

	render.SetColorModulation(0, 1, 0)

	self.CSEntViewAttachment:SetPos(translatefov(self.ViewModelFOV, e.Pos, true))
	self.CSEntViewAttachment:SetAngles(e.Ang)
	self.CSEntViewAttachment:DrawModel()

	render.SetColorModulation(1, 1, 1)
end
```

![2020-05-05_20-34-41](https://user-images.githubusercontent.com/1381265/81102418-e5265f00-8f0f-11ea-8097-67ff5ae07b94.png)
![2020-05-05_20-34-44](https://user-images.githubusercontent.com/1381265/81102429-e8b9e600-8f0f-11ea-9a1b-060c1bc9fc82.png)

**Comment by TiberiumFusion** [comment] 2020-05-06 01:01
@TankNut Great info, thanks much. Your explanation checks out with all I can tell and the transformation by `FormatViewModelAttachment` does indeed fix the issue in my limited testing.

If the speculation above is indeed correctly, then this seems like a done deal to me.
@robotboy655 Hopefully this speeds up this ticket?

**Comment by willox** [comment] 2020-05-06 03:09
Yup this is entirely expected and, as you said, caused by the difference between perspectives when rendering the world and the view model. The code above is the correct solution if you need to match between world and viewmodel coordinates.

**Comment by willox** [comment] 2020-05-06 03:11
I mean... GetAttachment could probably have some sort of hack to work with ViewModels but I think that's just asking for the alternate issue to happen (where you're rendering in the other perspective.)

**Comment by TiberiumFusion** [comment] 2020-05-06 04:00
@willox So why was this closed...? Neither **A)** The issue was fixed in gmod, or **B)** The wiki was updated to inform us that wrong data is a feature and not a bug, has happened. You can't say the issue is resolved because it's not. And, considering how dead simple, yet undocumented, the fix is, what good reason is there to skip fixing this?

If returning incorrect data is considered intended behavior for some unholy reason, then at the very least, the wiki page for [`GetAttachment()`](https://wiki.facepunch.com/gmod/Entity:GetAttachment) should be updated to state that `GetAttachment()` is purposefully designed to return bad data for viewmodels. Elsewise, the next poor soul to come across this undocumented "feature" might lose a day of manhours re-diagnosing this same issue, only to get the same "wont fix" answer.

**Comment by willox** [comment] 2020-05-06 04:08
I was under the impression that `SWEP:PreDrawViewModel` and `SWEP:PostDrawViewModel` was called with the same projection matrix as the viewmodel itself, apparently they're not - this behaviour would be sound if they were.

I can't tell for sure right now if something is actually wrong with the game here but I can open the issue anyway.

**Comment by Kefta** [comment] 2020-05-06 04:08
I think [FormatViewModelAttachment](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/client/c_baseviewmodel.cpp#L95) should just be binded for viewmodel ents (and maybe a viewmodel metatable should be added at this point). It's a lot of math ops so it's gonna be slow in Lua.

**Comment by TankNut** [comment] 2020-05-06 04:23
If a fix for `GetAttachment()` isn't feasible there's always the option of just adding a direct binding to FormatViewModelAttachment (Either in C or failing that, lua) and mentioning it on the wiki. At least that way there's a simple enough solution for people to work with instead of going through the same method of digging through the SDK to find out what they're missing.

**Comment by Kefta** [comment] 2020-05-06 04:26
This is a duplicate of https://github.com/Facepunch/garrysmod-issues/issues/1255 essentially. I have updated the wiki page for GetAttachment to include the proper attachment translation code, but it's not entirely accurate. We need https://github.com/Facepunch/garrysmod-requests/issues/1014 and ``ViewModelFOV()`` binded.

**Comment by TiberiumFusion** [comment] 2020-05-06 06:20
If [`EyeFOV()`](https://github.com/Facepunch/garrysmod-requests/issues/1014) isn't up for consideration, then some new method `GetAttachmentViewmodel()` could be introduced that mirrors `GetAttachment()` and tailcalls `FormatViewModelAttachment`. It's ugly, but this pattern is already established in GLua, e.g. we have things like `Entity:SendViewModelMatchingSequence()` for viewmodels only and `Entity:ResetSequence()` for everything else. This would also have the benefit of not breaking up to 7+ year old code that relies on the busted `GetAttachment()` behavior.

**Comment by Kefta** [comment] 2020-05-06 06:32
GetAttachment isn't broken here, it just returns the untranslated attachment data. View model rendering just happens in a different projection space, and there's fully working Lua code to correctly translate the attachment data: https://wiki.facepunch.com/gmod/Entity:GetAttachment

This should be closed. https://github.com/Facepunch/garrysmod-issues/issues/1255 and https://github.com/Facepunch/garrysmod-requests/issues/1588 should be fulfilled.

**Comment by Volantarius** [comment] 2020-06-05 09:00
I use `cam.Start3D(EyePos(), EyeAngles(), nil, 0, 0, ScrW(), ScrH(), nil, nil)` for drawing anything that needs viewmodel positions. Works well and doesn't need translations for each position, everything in the cam call works fine!

**Comment by Kefta** [comment] 2020-06-05 11:33
No it doesn't:
https://youtube.com/embed/GDGW0G4qkcU

The green cube uses transformation while the red cube is drawn inside the 3D cam. Not only will clipping occur from drawing in the incorrect projection space, objects will appear smaller (the cubes are drawn with the same size vectors).

**Comment by Kefta** [comment] 2020-07-29 15:18
See https://wiki.facepunch.com/gmod/Entity:GetAttachment for the fix.

**Closed by Kefta** 2020-07-29 15:18 UTC
Labels: Can't/Won't fix, Complexity: Easy
