### ISSUE TITLE
npc_vortigaunt dispel effect leaves behind permanent visual bug on x86-64 branch only

### ISSUE THREAD

**Issue by NO-LOAFING** [Facepunch/garrysmod-issues#4952] opened 2021-05-21 18:03 UTC
### Details
On the x86-64 branch only, when an npc_vortigaunt performs its dispel attack (either by entering `ent_fire !picker dispel` in console, or triggered by its AI when several antlions are nearby), it leaves behind a large flashing yellow-blue effect that persists indefinitely.

![20210521105926_1](https://user-images.githubusercontent.com/12566919/119179373-af252180-ba23-11eb-8980-ee910a657883.jpg)

Looking at the [code](https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/game/server/hl2/npc_vortigaunt_episodic.cpp#L2461), this looks like a malformed "beam ring" effect, but I can't reproduce it with anything else that uses the same function ([combine ball](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/hl2/prop_combine_ball.cpp#L1042), [combine mortar](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/hl2/func_tank.cpp#L3644), [strider bullets](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/hl2/npc_strider.cpp#L2759), [gunship ground attack](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/hl2/npc_combinegunship.cpp#L1111), or either of the examples on the effects.BeamRingPoint [wiki page](https://wiki.facepunch.com/gmod/effects.BeamRingPoint))

**Comment by robotboy655** [comment] 2023-11-24 17:14
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5552

Also fixed.

**Closed by robotboy655** 2023-11-24 17:14 UTC
