### ISSUE TITLE
Nextbots fail to compute a path seemingly at random

### ISSUE THREAD

**Issue by Dragoteryx** [Facepunch/garrysmod-issues#5782] opened 2024-03-04 00:23 UTC
### Details
Me and other nextbot creators have noticed a bug in the dev branch that still isn't fixed as of the time I am writing this issue.
This seems unrelated to the #5757 issue although both bugs seem to have appeared at the same time.

Nextbots will randomly fail to compute a path to their target if it's in a different nav area. There doesn't seem to be any discernible pattern to the bug, but I have noticed that once you've entered the nextbot's nav area the issue seems to disappear.

I've made a video of the issue:
https://www.youtube.com/watch?v=fQT5O2TW7EQ
(notice the nextbot spamming the console trying to compute a path in vain)

### Steps to reproduce
In the video I am using the [DrGBase test nextbot](https://steamcommunity.com/workshop/filedetails/?id=1560118657), but I've managed to reproduce the issue with a non DrGBase nextbot as well ([this one](https://steamcommunity.com/sharedfiles/filedetails/?id=779759026)).
You should be able to reproduce this issue using any nextbot.

**Comment by robotboy655** [comment] 2024-03-04 15:42
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5771

**Closed by robotboy655** 2024-03-04 15:42 UTC
