### ISSUE TITLE
CUserCmd Client input not working with gui.EnableScreenClicker( true )

### ISSUE THREAD

**Issue by Hoffa1337** [Facepunch/garrysmod-issues#982] opened 2014-04-11 07:58 UTC
It appears that CUserCmd functions used for getting key input breaks when using gui.EnableScreenClicker( true ) on the client.
Example:
hook.Add("CreateMove", "TestCreateMove"; function( cmd ) 

 gui.EnableScreenClicker( true )
print( cmd:GetMouseWheel() )

end )

**Comment by Neeve01** [comment] 2019-06-23 03:32
Will this ever get fixed?

**Comment by robotboy655** [comment] 2019-06-26 00:33
i mean, probably not, the user input is getting overtaken by the vgui system so you can't look around, etc. 

I'd say this is very much expected behavior.

(`gui.EnableScreenClicker( true )` makes a popup panel off screen with mouse input enabled)

**Comment by redsigma** [comment] 2021-02-06 21:27
> (gui.EnableScreenClicker( true ) makes a popup panel off screen with mouse input enabled)

This also happens when changing resolution while having `gui.EnableScreenClicker` on true. Is there any other way to enable mouse clicking without using `gui.EnableScreenClicker` ?

**Comment by robotboy655** [comment] 2021-02-06 21:41
> This also happens 

What is "this"?

What is the problem you are having/trying to solve?

**Comment by redsigma** [comment] 2021-02-11 07:05
Sorry if i missed any details (pretty sure i quoted the previous message) but what i want is to make a panel which can be shown if i press a button, **press** the button not **hold** it. Similar to how the scoreboard works but instead of holding the button you only press it once to show the panel and press it again to hide it.

I'm doing this by using gui.EnableScreenClicker but after i use it and change the resolution of my game, a small panel appears at the left of the screen.
To replicate the issue i did it like this:
1. gui.EnableScreenClicker(true)
2. Change resolution => panel shows
3. gui.EnableScreenClicker(false) => panel disapppears

If i only use gui.EnableScreenClicker true and false without changing the resolution tthen everything is ok.

**Comment by robotboy655** [comment] 2021-02-11 12:45
Ah.
 I don't see how this is related to the original issue though.

**Comment by robotboy655** [comment] 2021-02-11 14:37
@redsigma's issue should be fixed on Dev. 

The original issues is not a bug.

**Closed by robotboy655** 2021-02-11 14:37 UTC
Labels: Can't/Won't fix

**Comment by redsigma** [comment] 2021-02-12 19:18
> 
> 
> @redsigma's issue should be fixed on Dev.
> 
> The original issue is not a bug.

Thanks a lot. Will wait unti it hits the main x86-64 branch
