### ISSUE TITLE
SetModelScale and GetCollisionBounds/OBBMins/OBBMaxs

### ISSUE THREAD

**Issue by shadowscion** [Facepunch/garrysmod-issues#2231] opened 2015-09-09 21:51 UTC
When setting a model's scale _and_ activating it, the collision bounds are not set to the correct values. 

```
    local function SetTestScale( entity, scale, activate )
        entity:SetModelScale( scale, 0 )
        if activate then entity:Activate() end

        local min, max = entity:GetCollisionBounds()

        print( string.format( "Scale: %f\nMin: %f, %f, %f\nMax: %f, %f, %f\n\n", scale, min.x, min.y, min.z, max.x, max.y, max.z ) )
    end

    hook.Add( "PlayerSpawnedProp", "SetScaleTest", function( ply, model, entity )

        local activate = true

        SetTestScale( entity, 1,   activate )
        SetTestScale( entity, 0.5, activate )
        SetTestScale( entity, 1,   activate )

    end )
```

Output:
```
    when activated:

    Scale: 1.000000
    Min: -6.250000, -6.250010, -6.250000
    Max: 6.250000, 6.250010, 6.250000

    Scale: 0.500000
    Min: -1.562500, -1.562502, -1.562500
    Max: 1.562500, 1.562502, 1.562500

    Scale: 1.000000
    Min: -3.125000, -3.125005, -3.125000
    Max: 3.125000, 3.125005, 3.125000


    when not activated:

    Scale: 1.000000
    Min: -6.250000, -6.250010, -6.250000
    Max: 6.250000, 6.250010, 6.250000

    Scale: 0.500000
    Min: -3.125000, -3.125005, -3.125000
    Max: 3.125000, 3.125005, 3.125000

    Scale: 1.000000
    Min: -6.250000, -6.250010, -6.250000
    Max: 6.250000, 6.250010, 6.250000
```

**Comment by robotboy655** [comment] 2016-01-15 11:15
Duplicate of #2193

**Closed by robotboy655** 2016-01-15 11:15 UTC
