### ISSUE TITLE
Cannot write .gma file into the data directory

### ISSUE THREAD

**Issue by Dr4iv3rNope** [Facepunch/garrysmod-issues#5613] opened 2023-11-19 23:08 UTC
### Details
```
] version
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 16:34:46 Sep  4 2023 (9040) (4000)
GMod version 2023.09.06, branch: unknown, multicore: 0
Windows 32bit
```

Beta: none

### Steps to reproduce
1. Join singleplayer
2. Turn on `sv_cheats 1`
3. Execute `file.Write("sample.gma", "")` (using `lua_run` or `lua_run_cl` command)
4. Function will silently fail

**Comment by MaslovKK** [comment] 2023-11-19 23:39
.gma is not allowed to use it as filename extension.

**Comment by Dr4iv3rNope** [comment] 2023-11-19 23:46
> .gma is not allowed to use it as filename extension.

Check out [file.Write on Wiki](https://wiki.facepunch.com/gmod/file.Write)

**Comment by MaslovKK** [comment] 2023-11-19 23:49
> > .gma is not allowed to use it as filename extension.
> 
> Check out [file.Write on Wiki](https://wiki.facepunch.com/gmod/file.Write)

as i see, .gma added by not a developer 
![image](https://github.com/Facepunch/garrysmod-issues/assets/45038542/4eb2c49e-45a9-4231-873a-4a50d3e3eb22)

**Comment by Kefta** [comment] 2023-11-19 23:59
Test on the dev branch.

**Comment by Dr4iv3rNope** [comment] 2023-11-20 00:03
> Test on the dev branch (not x86_64).

Yes, it's working. It works on x86_64/chromium branches as well

**Comment by Kefta** [comment] 2023-11-20 00:17
Wait for next update then.

**Comment by robotboy655** [comment] 2023-11-20 13:24
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/2173

**Closed** 2023-11-20 13:24 UTC
