### ISSUE TITLE
MacOS missing binaries

### ISSUE THREAD

**Issue by BullyHunter32** [Facepunch/garrysmod-issues#5313] opened 2022-08-24 21:10 UTC
### Details
MacOS is failing to launch as all of the `.dylib`s are missing
Tried both x86-64 versions.
Files were also validated.

Dumps emailed.

### Steps to reproduce
N/A

**Comment by robotboy655** [comment] 2022-08-25 12:27
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5001

**Closed by robotboy655** 2022-08-25 12:27 UTC

**Comment by BullyHunter32** [comment] 2022-08-25 18:05
Would I be wrong to say that their issue is different to mine?

As far as I can see the people with the issue you linked are able to launch the game, but crash while it's open. In my case I do not download the `dylib`s and the game will not launch, it will silently crash.

**Comment by robotboy655** [comment] 2022-08-26 13:00
What makes you say "I do not download the dylibs". The console errors mentioned in the above linked issue (They are normal)? Or the fact that they do not appear in the same place as they do on Windows on the x86-64 beta branch, which is also normal?

**Comment by BullyHunter32** [comment] 2022-08-26 14:15
Before dylibs would download into `Garry's Mod/bin` and `Garry's Mod/garrysmod/bin`. Now I cannot find any.

**Comment by robotboy655** [comment] 2022-08-26 14:20
Yes that is normal, they should be stored somewhere in `GarrysMod.app` folder for the `x86-64` versions.
