### ISSUE TITLE
Garry's Mod crashes on macOS Sierra Public Beta 1

### ISSUE THREAD

**Issue by justin97530** [Facepunch/garrysmod-issues#2710] opened 2016-07-09 09:38 UTC
Garry's Mod crashes on macOS Sierra Public Beta 1 on both the "Stable" and "Dev" branch.

This is not an isolated incident as my friend has also experienced similar issues on the same OS version.

EDIT: I researched a bit into the issue, and it requires Awesomium to update to a newer version of Chromium, so I don't think Garry's Mod devs can do anything about it until that happens.

-- Bug Information --
- Launch Garry's Mod (hl2_osx) on Steam.
- Startup UI is shown.
- Startup finishes, shows "Finished"
- Game crashes in thread "AwesomiumBrowserMain"

-- Logs --
macOS crash logs are attached in "[crash.txt](https://github.com/Facepunch/garrysmod-issues/files/355500/crash.txt)"

-- Information --
Garry's Mod version: 2016 July Update (and Dev release as of post)
System: Macmini6,1
RAM: DDR3-1600 10GB
CPU: Intel Core i7 3615-QM
GPU: Integrated Intel HD 4000 (1356MB)
Version: macOS 10.12 Build 16A238m (Development Beta 2 / Public Beta 1)
System Integrity Protection: OFF

**Comment by Bo98** [comment] 2016-07-09 10:25
Try launching it through terminal and see if anything interesting is outputted when it crashes. Stack trace doesn't seem to have anything to do with Awesomium (thread 0 name is always named as AwesomiumBrowserMain so that doesn't say much).

**Comment by Bo98** [comment] 2016-07-09 10:30
Looks like PlayOnMac (wine wrapper thing) has similar issues so it's possible it could be an OS bug. I guess we'll see what they conclude. If it's a bug then someone will need to report it.

**Comment by GRANTSWIM4** [comment] 2016-07-12 00:03
I have the same issue. My crash logs matches @justin97530 to a T. I'm also running the beta as well.

**Comment by justin97530** [comment] 2016-07-12 02:28
@Bo98 Sorry for the late reply, but I'm not aware as to how to run Garry's Mod through terminal, just calling hl2_osx does not work.

**Comment by Jake3231** [comment] 2016-07-12 21:27
I thought that I'd report that I am having the same, or similar issue with the Awesomium thread crashing on El Capitan (10.11.5).  I am using a very recent Mac with the stable branch, along with the recommended method of multicore rendering enabled.  Almost every crash is caused by the Awesomium thread.

**Comment by Bo98** [comment] 2016-07-12 22:56
That's the standard OS X memory crashes GMod has had for years. This issue specifically is for GMod crashing _on startup_ on macOS Sierra which is not caused by hitting the 32-bit memory limit.

As a side note, the "Awesomium thread" is actually just the main thread but Awesomium renames it for some reason.

**Comment by Jake3231** [comment] 2016-07-12 23:53
Thanks for clearing that up.  That's good to know, as I am planning to test Sierra also.  As for the 32-bit memory limit, I assume that that's system RAM and not VRAM.  If the Windows version is 64-bit, I don't see why the Mac version wouldn't be. It has so many advantages in my view. Anyway, it's good to know that the bug originally listed only affects Sierra.

**Comment by willox** [comment] 2016-07-13 02:20
Garry's Mod is using a pretty old set of code that interfaces directly with Cocoa rather than using SDL. It's needed changing for quite a while and this would probably be solved by that. It'd also let us update TOGL for both OSX and Linux.

Can you launch TF2?

**Comment by Jake3231** [comment] 2016-07-13 04:54
Okay.  It also seems that development of a Garry's Mod sequel is in the works.  I'm hoping that it solves all of these problems..

**Comment by Kefta** [comment] 2016-07-13 05:23
It won't be for years

**Comment by Bo98** [comment] 2016-07-13 07:44
> If the Windows version is 64-bit

With the exception of CS:GO's OS X and Linux versions, no other version of Source 1 is 64-bit.

**Comment by DanDaDominator** [comment] 2016-07-13 08:37
I am also experiencing this issue on macOS Sierra Beta 2.
(Didn't think a new thread was required for my crash)

I also experience the same crash on startup, but I got a different log stating Chrome_Launcher is the culprit:
[crash.txt](https://github.com/Facepunch/garrysmod-issues/files/361022/crash.txt)

Hope that helps.

**Comment by Bo98** [comment] 2016-07-13 09:16
That one looks like Awesomium which is worrying.

**Comment by justin97530** [comment] 2016-07-13 11:25
I just checked, TF2 indeed works.

**Comment by GRANTSWIM4** [comment] 2016-07-13 12:35
Can confirm TF2 does work.

**Comment by TimCook** [comment] 2016-07-13 22:55
I also confirm TF2 works, as well as most of other Source based games (e.g. CS:S, CS:GO, L4D2)

**Comment by Bo98** [comment] 2016-07-14 21:02
@justin97530 @GRANTSWIM4 Does being in fullscreen or not have any affect on the issue?

**Comment by GRANTSWIM4** [comment] 2016-07-14 21:45
@Bo98 will try now, by chace what is the startup arg not to lanuch in full screen?

**Comment by justin97530** [comment] 2016-07-15 02:48
My Garry's Mod defaults to launching in windowed, still crashes.

**Comment by TimCook** [comment] 2016-07-19 02:22
I'll try to see if Sierra Beta 3 changes anything.

**Comment by TimCook** [comment] 2016-07-19 05:40
Updating to Sierra Dev Beta 3 fixed this issue.

**Comment by justin97530** [comment] 2016-07-19 11:17
Is the Dev beta 3 available for public?

**Comment by Bo98** [comment] 2016-07-19 12:17
Not yet. Probably will in a few days.

**Comment by Bo98** [comment] 2016-07-20 21:05
Public Beta 2 is out.

**Comment by TimCook** [comment] 2016-07-21 03:40
I don't know when the public beta 3 will be released, but I'm fairly certain this issue will be addressed in the public beta as well.

**Comment by Bo98** [comment] 2016-07-21 07:53
Public beta 2 == Dev beta 3.

The first dev beta didn't get a corresponding public beta.

**Comment by TimCook** [comment] 2016-07-22 00:06
Ah.

Did the new public beta fix the Awesomium issue for you?

**Comment by willox** [comment] 2016-07-25 21:08
Don't expect any OSX updates to improve Garry's Mod compared to how it is now (because it isn't OSX's fault). I'll assume that this specific issue is solved though.

**Closed by willox** 2016-07-25 21:08 UTC
Labels: awesomium, crash, osx
