### ISSUE TITLE
Errors in pcall and xpcall are counted towards sv_kickerrornum

### ISSUE THREAD

**Issue by ZKShao** [Facepunch/garrysmod-issues#1041] opened 2014-04-24 11:40 UTC
Errors raised in pcall's and xpcall's during client-side LUA execution are being reported to the server. The server counts this as a LUA error that can get the client kicked if too many errors occur. I believe that since pcall and xpcall are used for proper error handling, these should not count as errors that can get a player kicked.

Example:

```
LoadModuleButton.DoClick = function()
    local status, error = pcall( require( "mymodule" ) )
    if not status then
        print( "Please download the module from ___ and try again." )
    end
end
```

**Comment by robotboy655** [comment] 2023-11-10 14:02
This is basically duplicate of https://github.com/Facepunch/garrysmod-issues/issues/2498

Only `ErrorNoHalt` errors are counted towards `sv_kickerrornum` in `pcall` because they are not blocked.

**Closed by robotboy655** 2023-11-10 14:02 UTC
