### ISSUE TITLE
After new september update, a workshop bug appeared

### ISSUE THREAD

**Issue by Alf21** [Facepunch/garrysmod-issues#3974] opened 2019-09-03 19:53 UTC
### Details
Previously (before this update), everything works fine.
After this update, many things broke. Maybe this is caused by a new loading order of the add-ons?
In addition to that, a new error appeared in the console:

![Screenshot (449)](https://user-images.githubusercontent.com/11843790/64203960-eee55780-ce94-11e9-80f3-8e4bd63f4316.png)

Additionally: Try to deinstall some add-ons and visit the last page of the add-ons manager (the last pagination point). There are some strange things too.

### Steps to reproduce
Just update the game, maybe with some deactivated add-ons (via the gmod add-on manager).

**Comment by robotboy655** [comment] 2019-09-03 20:01
What is exactly is broken? Be as descriptive as possible. "Many things" is not helpful.

There were no changes to the addon system or any "loading orders", the addons menu was changed however which added just 2 new filters.

**Comment by Alf21** [comment] 2019-09-03 21:43
New occurred bugs:

1. The last side of the gmod add-on manager lists an empty entry for every (previously) deleted add-on. Deleting this entity again fixes the buggy displaying.

2. As visible in the picture above, the green error appears if you deactivate add-ons via the gmod add-on manager

3. It seems that the hook loading order broke/got changed. Our mod needed to receive a hotfix (ref.: https://github.com/TTT-2/TTT2/commit/7c270c0a281817cf47244b3701a069719bc180ad).

**Comment by robotboy655** [comment] 2019-09-03 22:20
I will get the first 2 looked at, but there no hook order changes. `PlayerInitialSpawn` hook got got an extra argument, perhaps one or more if your addons are doing something stupid like returning a non nil value from a `PlayerInitialSpawn` hook?

**Comment by robotboy655** [comment] 2019-09-04 15:02
Are you sure you are running unmodified menu? Have you tried verifying game cache integrity? I cannot reproduce either one of the 2 first issues.

**Comment by Alf21** [comment] 2019-09-04 15:29
Yea I'm sure, as you can see here: https://youtu.be/0QO-iyKq8Z0 (after trying to reproduce it the third time, it doesn't work. Strange anyway, but not as critical as the described hook issue).

I'm sure that we didn't used an undefined nil var before or returned nil in `PlayerInitialSpawn`. All in all, this issue just happens after this update. Maybe something with https://wiki.garrysmod.com/page/GM/InitPostEntity or ConVar/Config related things?

**Comment by robotboy655** [comment] 2019-09-04 15:40
Ok I looked at your screenshot again and its because of the .gma files you have inside addons. Its not a new problem.

**Comment by Alf21** [comment] 2019-09-04 15:57
okay. If it's known, then it's just the strange appearance bug and the hook issue. Never noticed this green WS bug :O

**Comment by robotboy655** [comment] 2019-09-04 16:51
The bug that gamemode was experiencing is probably related to the now fixed https://github.com/Facepunch/garrysmod-issues/issues/3977

**Closed by robotboy655** 2019-09-04 16:51 UTC

**Comment by robotboy655** [comment] 2019-09-04 19:02
I fixed the workshop issues as well, for reference this is what it looks now:
![image](https://user-images.githubusercontent.com/3299036/64283207-a777cd80-cf5f-11e9-8e93-729fae89cdf2.png)

**Comment by TimGoll** [comment] 2019-09-05 15:38
You can see now localyy installed addons in the mod menu? A dream come true. THANKS!

**Comment by Alf21** [comment] 2019-09-05 15:47
Moving the ConVar initialization from `PlayerInitialSpawn` (TTT is doing this by default) into `InitPostEntity` seems to fix this. Maybe related to your reference, but in theory, this doesn't make sense based on this change. Switching to dev branch works **without** this hotfix (moving the ConVar initialization). 

In any case, many thanks for the fast processing!
