### ISSUE TITLE
monster_scientist gets frozen when another one asks something

### ISSUE THREAD

**Issue by TheMostUpset** [Facepunch/garrysmod-issues#3781] opened 2019-03-03 16:19 UTC
After the latest update scientists can talk with each other, but it's pretty buggy.
If one scientist acts something and another one talks to him, the first one stays frozen.
Video: https://puu.sh/CUvYJ/b68784e9c6.webm

**Comment by robotboy655** [comment] 2019-03-07 20:09
Should be fixed.

**Closed by robotboy655** 2019-03-07 20:09 UTC

**Comment by TheMostUpset** [comment] 2019-05-03 17:50
Happened again. They both were following the player, the running guy was about to use the retinal scanner, and suddenly another one asked him something, so he got frozen in running animation.

![20190503224355_1](https://user-images.githubusercontent.com/7527872/57155654-76429180-6df5-11e9-9c88-e757bf215d73.jpg)

**Comment by robotboy655** [comment] 2019-05-03 20:11
Map? Steps to reproduce?

**Comment by TheMostUpset** [comment] 2019-05-03 20:32
c2a4e
Take at least two scientists to the retinal scanner. If you somehow manage to force one to ask something the another one, which is acting retinal scanner map script, he will stay frozen.

**Comment by TheMostUpset** [comment] 2019-05-03 20:37
Or that server was running the old version of the game (is it possible?)

**Comment by robotboy655** [comment] 2019-05-03 21:18
Yes, it is possible server is not updated, since the fix was in the April update.
