### ISSUE TITLE
Projected Texture shadows not properly shadowing decals

### ISSUE THREAD

**Issue by Kidnation** [Facepunch/garrysmod-issues#4003] opened 2019-09-20 23:37 UTC
![bugreport_1](https://user-images.githubusercontent.com/14626164/65361975-8992a580-dbba-11e9-889d-ef972cb7c3c4.png)

Simply said, shadows from projected textures that cast onto decals appear lit from the projected texture, ignoring any shadows casting onto the decal.  Making the decal appear as if it's being full brighted by the projected texture.

As a result of this odd behavior, decals behind walls or really anything will appear lit when a projected texture is pointed in their direction.  It's especially noticeable inside gm_construct's secret room:

![gm_construct0002](https://user-images.githubusercontent.com/14626164/65362928-24d94a00-dbbe-11e9-8a06-01ccf62988cd.jpg)
![gm_construct0003](https://user-images.githubusercontent.com/14626164/65362931-273ba400-dbbe-11e9-9780-14def033aabc.jpg)

Despite the lamp being above the secret room, the decals in the secret room still get lit up.  This happens on any map no matter the compile or version of game it comes from, or even which entity is used to create the decals (infodecal, info_overlay, etc.).  I've also tested this with the env_projectedtexture entity, the player's flashlight, and ProjectedTexture(), all which have the same issue with decals.  Interestingly, decals like blood that use the DecalModulate shader don't seem to be affected by this issue, only ones that use LightmappedGeneric and such get affected by this glitch.

I've tested this both on the main and developer branch of Gmod, it happens on both.  I've also tested this without any games/addons mounted in my Gmod as well, and still had the issue.

### Steps to reproduce
To reproduce the glitch easily, you can simply do what I did in the last 2 screenshots.

1. Load up gm_construct.
2. Spawn a lamp and position it so that it's above the secret room, pointing down at it.
3. Go into the room, and all the decals in it will be lit as if the light is shining on them.

**Comment by robotboy655** [comment] 2019-09-20 23:51
Basically duplicate of or similar https://github.com/Facepunch/garrysmod-issues/issues/2954

**Comment by robotboy655** [comment] 2019-10-10 18:43
I was wrong and now it is fixed!

**Closed by robotboy655** 2019-10-10 18:43 UTC

**Comment by Kidnation** [comment] 2019-10-17 07:14
Thanks mate! ^_^
