### ISSUE TITLE
Source entity names left unlocalized in MacOS x86_64 branch

### ISSUE THREAD

**Issue by SuperStik** [Facepunch/garrysmod-issues#4789] opened 2021-01-05 20:20 UTC
### Details
All base Source entity names (fire, NPCs, etc.) are left unlocalized. This does not include any Lua-created entities. This has been going on for about a year, and hasn't been reported yet to my knowledge. Also, I tested it on my PC, and it appears the localizations are there, but I couldn't get a screenshot from the PC.
![gm_haus0025](https://user-images.githubusercontent.com/51009602/103695116-db4a7500-4f50-11eb-8d6a-e7b67d34b6b5.jpg)
![gm_haus0026](https://user-images.githubusercontent.com/51009602/103695120-dc7ba200-4f50-11eb-9a59-3bf4e46c5280.jpg)

### Steps to reproduce
Get a base NPC to kill something, or die of fall damage, and it will be unlocalized since there is a "#" symbol in front of the name.

**Comment by SuperStik** [comment] 2021-01-05 20:35
It seems to be the same or similar issue as #4781

**Comment by robotboy655** [comment] 2021-01-05 21:42
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/44

**Closed by robotboy655** 2021-01-05 21:42 UTC
Labels: Bug, Platform: OSX
