### ISSUE TITLE
DFrame Crashes Since April 2017 Update

### ISSUE THREAD

**Issue by stickz** [Facepunch/garrysmod-issues#3156] opened 2017-04-22 01:52 UTC
### Details
Every time I try to render a DFrame on my game client it crashes. 

This has been happening constantly since the latest game update. 

Tons of clients have reported the same issue.
[Crash_Dumps.zip](https://github.com/Facepunch/garrysmod-issues/files/948658/Crash_Dumps.zip)

### Steps to reproduce
To reproduce this bug, I'm calling the CreateUpgradesMenu() function [here](https://github.com/Remscar/Morbus/blob/master/MorbusGamemode/gamemodes/morbusgame/gamemode/client/vgui/cl_upgrademenu.lua).

**Comment by robotboy655** [comment] 2017-04-22 02:28
Duplicate of #3150 related to Material function fucking up.

**Closed by robotboy655** 2017-04-22 02:28 UTC
Labels: crash, duplicate

**Comment by willox** [comment] 2017-04-22 12:32
@stickz how often are you able to reproduce this?

**Comment by willox** [comment] 2017-04-22 12:40
Never-mind, I've managed to reproduce it. Thanks for the info.
