### ISSUE TITLE
sv_netspike broken on 32x and causes crash

### ISSUE THREAD

**Issue by RaphaelIT7** [Facepunch/garrysmod-issues#5492] opened 2023-06-25 01:19 UTC
### Details
If you enable sv_netspike while you're on the dev or main branch, it seems like it doesn't work, but then after enabling it and noclipping around, it will crash the game.
Affected are the main, prerelease and dev branch. x86-64 and Linux all versions works fine.
Crash dump (rename it to .mdmp):
[hl2_230623_crash_2023_6_25T1_13_30C0.txt](https://github.com/Facepunch/garrysmod-issues/files/11858514/hl2_230623_crash_2023_6_25T1_13_30C0.txt)

### Steps to reproduce
1. Enable sv_netspike → Run `sv_netspike 1`
You will see that nothing is printed, while it should print stuff.
2. do anything like noclipping opening the spawn menu etc.

**Comment by robotboy655** [comment] 2023-06-26 15:06
I followed your steps on `dev` beta, but everything worked as intended?
![image](https://github.com/Facepunch/garrysmod-issues/assets/3299036/80cd910e-42fe-4989-b4f6-75665b63a05a)

It does spam messages and there are no crashes.

**Comment by robotboy655** [comment] 2023-06-26 15:45
Hmm, looking further into it, the console messages are put into the logging file outside of singleplayer `log 1`. The crash could be related to the recently fixed threaded networking convars?

**Comment by RaphaelIT7** [comment] 2023-06-26 19:38
I tested a bit and found out it works fine in singleplayer.
I created a Video to show how It crashes: https://www.youtube.com/watch?v=7W3BrgDhXLk

**Comment by RaphaelIT7** [comment] 2023-06-30 19:28
> The crash could be related to the recently fixed threaded networking convars?

I don't think so because it also crashes when `sv_parallel_sendsnapshot` is set to `0`

**Comment by robotboy655** [comment] 2023-06-30 19:31
Yeah I cannot reproduce any crashes, singleplayer or not.

**Comment by robotboy655** [comment] 2024-03-26 21:07
I am closing this as I simply cannot reproduce the issue. I have tried using the command on srcds and in local multiplayer, and it will not crash.

I suspect if there is a crash, it has to do with other convars being set on your client beforehand. I have noticed in your video you have `log 1` enabled automatically before you enter the command. I have tried enabling it before entering the command as well, but no crash still.

**Closed by robotboy655** 2024-03-26 21:07 UTC
Labels: Crash, Cannot confirm

**Comment by RaphaelIT7** [comment] 2024-04-21 03:03
I finally took a bit of time to find what causes it to crash, only on my end.
After checking everything again and going through all ConVars `differences` said had a different value than the default and could have something to do with it,
I found out that `sv_logecho` was set to `1` and setting it to `0` solved it.

So the steps to reproduce it now are these:
1. Run `sv_netspike 1`
2. Run `log 1`
3. Set `sv_logecho` to `1`
4. Spawn a prop to cause a networking spike
5. Crash

Maybe you can now reproduce it with this.

**Comment by robotboy655** [comment] 2024-04-22 12:20
Still no dice on my end. `sv_logecho` defaults to `1` anyway, so I have already tried it at the time I closed the issue.

The crash is definitely related to printing messages to console, but I don't see how. It might be related to multicore rendering, but I am not sure.

**Comment by robotboy655** [comment] 2024-04-26 13:35
OK, that seems to be it. I think I found a fix for this, it will be on `dev` soon.

**Comment by RaphaelIT7** [comment] 2024-04-27 00:56
It seems to now work perfectly fine. Thanks for the fix :D
