### ISSUE TITLE
Workshop related crash (Related to large number of downloads)

### ISSUE THREAD

**Issue by Shigbeard** [Facepunch/garrysmod-issues#1918] opened 2015-03-22 10:50 UTC
Hi, I've been experiencing a crash for a while, and have finally decided that it needs addressing.

This crash is related to workshop subscriptions. When downloading a large number of addons, or you have been downloading for quite some time, something occurs that I have nicknamed; "The Timeout". When The Timeout occurs, the following scenario will begin to take place:
1. All remaining addons that require downloading after The Timeout will begin downloading "Instantly". When I say this, I mean the workshop progress bar that appears center in the bottom of the screen will cycle through each addon, showing them instantly hit 100% complete, before proceeding to the next download and repeating. It will cycle all addons on loop, for some time. In the console at the time, there is a message in red, that is repeated for each addon, claiming that it was "unable to extract [addon], Uh Oh!"
2. After this cycle continues for some time (I've ranged this period to be between 5 to 20 seconds, or about 20-40 addons), Garry's Mod will begin to hang, before quickly crashing. However, this isn't where it ends.
3. Almost as soon as Garry's Mod has crashed, the Steam Client will freeze, and remain unresponsive until forcefully terminated by the user. _EDIT: Correction, after some time, ~~Windows~~ Something (probably the Steam Client itself) will automatically terminate Steam._

These symptoms are near identical each time, especially the Steam Crash that always coincides with this scenario.

From my brief search through other issues, I assume that because I'm reporting a crash, you would like my 'dxdiag' output. You can find a pastebin of it here: [DxDiag.txt - Pastebin.com](http://pastebin.com/R67idhYi)

**Comment by whyisthisnotworking** [comment] 2015-03-22 20:08
i have the same problem

**Comment by robotboy655** [comment] 2015-11-23 22:25
Possible duplicate of #352

**Comment by robotboy655** [comment] 2016-11-09 18:05
One of the known causes was fixed in latest update ( October #2 )

if you can still reproduce this problem, let me know.

**Closed by robotboy655** 2016-11-09 18:05 UTC
Labels: crash
