### ISSUE TITLE
Garry's Mod x86-64 chromium + 64-bit binaries beta doesn't work

### ISSUE THREAD

**Issue by zielony12** [Facepunch/garrysmod-issues#5437] opened 2023-04-10 09:54 UTC
OS: ArchLinux x86_64 6.2.10-arch-1
CPU: Intel i5-10200H (8) @ 4.100GHz
GPU: Intel Comet Lake-H GT1 [UHD Graphics 610]
Memory: 16GB

My steam library is on a usb stick mounted on /mnt with chmod 755 and I'm the ownership of all the files. 
Once I click run, I see vulkan shaders processing and when they finish, steam crashes.
The stdout:
```
(steam:11238): Gtk-WARNING **: 11:35:24.487: gtk_disable_setlocale() must be called before gtk_init()
local (potentially out of sync) copy of roaming config loaded - 351 bytes.
sh: line 1: xdg-user-dir: command not found
Installing breakpad exception handler for appid(steam)/version(1679680416)/tid(11463)
vkCreateInstance failed with error -1
BInit - Unable to initialize Vulkan!
Installing breakpad exception handler for appid(steam)/version(1679680416)/tid(11465)
sh: line 1: xdg-user-dir: command not found
BRefreshApplicationsInLibrary 1: 1ms
roaming config store loaded successfully - 351 bytes.
migrating temporary roaming config store
sh: line 1: xdg-user-dir: command not found
sh: line 1: xdg-user-dir: command not found
sh: line 1: xdg-user-dir: command not found
GetWin32Stats: restoring previous glx context
ExecCommandLine: "'/home/karol/.local/share/Steam/ubuntu12_32/steam'"
System startup time: 3.72 seconds
sh: line 1: xdg-user-dir: command not found

(steam:11238): LIBDBUSMENU-GLIB-WARNING **: 11:35:27.178: Trying to remove a child that doesn't believe we're it's parent.

(steam:11238): LIBDBUSMENU-GLIB-WARNING **: 11:35:27.178: Trying to remove a child that doesn't believe we're it's parent.

(steam:11238): LIBDBUSMENU-GLIB-WARNING **: 11:35:27.178: Trying to remove a child that doesn't believe we're it's parent.

(steam:11238): LIBDBUSMENU-GLIB-WARNING **: 11:35:27.178: Trying to remove a child that doesn't believe we're it's parent.

(steam:11238): LIBDBUSMENU-GLIB-WARNING **: 11:35:27.178: Trying to remove a child that doesn't believe we're it's parent.

(steam:11238): LIBDBUSMENU-GLIB-WARNING **: 11:35:27.178: Trying to remove a child that doesn't believe we're it's parent.

(steam:11238): LIBDBUSMENU-GLIB-WARNING **: 11:35:27.178: Trying to remove a child that doesn't believe we're it's parent.

(steam:11238): LIBDBUSMENU-GLIB-WARNING **: 11:35:27.178: Trying to remove a child that doesn't believe we're it's parent.

(steam:11238): LIBDBUSMENU-GLIB-WARNING **: 11:35:27.178: Trying to remove a child that doesn't believe we're it's parent.

(steam:11238): LIBDBUSMENU-GLIB-WARNING **: 11:35:27.178: Trying to remove a child that doesn't believe we're it's parent.

(steam:11238): LIBDBUSMENU-GLIB-WARNING **: 11:35:27.178: Trying to remove a child that doesn't believe we're it's parent.

(steam:11238): LIBDBUSMENU-GLIB-WARNING **: 11:35:27.178: Trying to remove a child that doesn't believe we're it's parent.

(steam:11238): LIBDBUSMENU-GLIB-WARNING **: 11:35:27.178: Trying to remove a child that doesn't believe we're it's parent.

(steam:11238): LIBDBUSMENU-GLIB-WARNING **: 11:35:27.178: Trying to remove a child that doesn't believe we're it's parent.

(steam:11238): LIBDBUSMENU-GLIB-WARNING **: 11:35:27.178: Trying to remove a child that doesn't believe we're it's parent.

(steam:11238): LIBDBUSMENU-GLIB-WARNING **: 11:35:27.178: Trying to remove a child that doesn't believe we're it's parent.
BuildCompleteAppOverviewChange: 304 apps
RegisterForAppOverview 1: 1ms
RegisterForAppOverview 2: 2ms
sh: line 1: xdg-user-dir: command not found
GameAction [AppID 4000, ActionID 1] : LaunchApp changed task to ProcessingInstallScript with ""
GameAction [AppID 4000, ActionID 1] : LaunchApp changed task to SynchronizingCloud with ""
sh: line 1: xdg-user-dir: command not found
sh: line 1: xdg-user-dir: command not found
GameAction [AppID 4000, ActionID 1] : LaunchApp changed task to ProcessingShaderCache with ""
Fossilize INFO: Setting autogroup scheduling.
Installing breakpad exception handler for appid(steam)/version(1679680416)/tid(11638)
Installing breakpad exception handler for appid(steam)/version(1679680416)/tid(11640)
Installing breakpad exception handler for appid(steam)/version(1679680416)/tid(11680)
Installing breakpad exception handler for appid(steam)/version(1679680416)/tid(11681)
[2023-04-10 11:37:23] Background update loop checking for update. . .
[2023-04-10 11:37:23] Checking for available updates...
[2023-04-10 11:37:23] Downloading manifest: https://client-update.akamai.steamstatic.com/steam_client_ubuntu12
[2023-04-10 11:37:24] Manifest download: send request
[2023-04-10 11:37:24] Manifest download: waiting for download to finish
[2023-04-10 11:37:25] Manifest download: finished
[2023-04-10 11:37:25] Download skipped by HTTP 304 Not Modified
[2023-04-10 11:37:25] Nothing to do
***** OUT OF MEMORY! attempted allocation size: 1714696766 ****
src/tier0/memstd.cpp (3026) : OUT OF MEMORY
src/tier0/memstd.cpp (3026) : OUT OF MEMORY
src/tier0/memstd.cpp (3026) : Fatal assert; application exiting
src/tier0/memstd.cpp (3026) : Fatal assert; application exiting
Installing breakpad exception handler for appid(steam)/version(1679680416)/tid(11309)
assert_20230410114123_32.dmp[12232]: Uploading dump (out-of-process)
/tmp/dumps/assert_20230410114123_32.dmp
_ExitOnFatalAssert
[karol@archlinux ~]$ assert_20230410114123_32.dmp[12232]: Finished uploading minidump (out-of-process): success = yes
assert_20230410114123_32.dmp[12232]: response: CrashID=bp-7e7bda28-8efc-4314-a568-da5d12230410
assert_20230410114123_32.dmp[12232]: file ''/tmp/dumps/assert_20230410114123_32.dmp'', upload yes: ''CrashID=bp-7e7bda28-8efc-4314-a568-da5d12230410''
```
I have also tried to run the game by hand:
```
LD_PRELOAD=filesystem_stdio_client.so LD_LIBRARY_PATH="/mnt/steam/steamapps/common/GarrysMod/bin/linux64/;/home/karol/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/" gmod
```
But nothing happens, I can interrupt the process by ^C and it quits immediately like it was just in a loop? I tried debugging it and I know that it creates a new thread and then a new process, then just "freezes" or anything. I don't get any message, but when I don't set the LD_PRELOAD, then the program says its unable to load the filesystem_stdio_client.so which is in a directory in LD_LIBRARY_PATH.
`ldd filesystem_stdio_client.so` with LD_LIBRARY_PATH set as above: 
```
linux-vdso.so.1 (0x00007ffcb9568000)
libtier0_client.so => /mnt/steam/steamapps/common/GarrysMod/bin/linux64/libtier0_client.so (0x00007f8189e00000)
libvstdlib_client.so => /mnt/steam/steamapps/common/GarrysMod/bin/linux64/libvstdlib_client.so (0x00007f8189a00000)
libsteam_api.so => /mnt/steam/steamapps/common/GarrysMod/bin/linux64/libsteam_api.so (0x00007f8189600000)
libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f818a611000)
libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f8189200000)
/usr/lib64/ld-linux-x86-64.so.2 (0x00007f818a646000)
libm.so.6 => /usr/lib/libm.so.6 (0x00007f818a527000)
libgcc_s.so.1 => /home/karol/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f8188e00000)
libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f818a522000)
libc.so.6 => /usr/lib/libc.so.6 (0x00007f8189019000)
```
I don't see any libraries missing when I run ldd for „*”.
Stdout when I don't preload the filesystem_stdio_client.so library first:
```
Failed to load /mnt/steam/steamapps/common/GarrysMod/filesystem_stdio_client.so: (null)
AppFramework : Unable to load module /mnt/steam/steamapps/common/GarrysMod/filesystem_stdio_client.so!
```
PS. The regular 32-bit Garry's Mod release worked without problems. The only reason is that 32-bit programs have some limitations I want to avoid with using the 64-bit beta.

**Comment by robertkirkman** [comment] 2024-01-20 17:25
Hi I got it to work for me
```bash
cd /mnt/ATOM/SteamLibrary/steamapps/common/GarrysMod/
ldd bin/linux64/engine_client.so 
```
that command shows whether you have all the dependencies of gmod installed or not, if it says "not found" for anything other than `libtier0_client.so` , `libvstdlib_client.so` and `libsteam_api.so` then you need to install a compatible system library now. I had to install this
```bash
sudo emerge =openssl-compat-1.0.2u-r2
ln -s /usr/lib64/ bin/linux64/swiftshader
```
64-bit Gmod wasn't able to detect my graphics driver. the `ln` command connected Gmod to the graphics driver `libGLESv2.so`, `libEGL.so` etc.

The main menu is invisible for me. But I was able to load `gm_construct` by pressing the     \`          key which opened the Game Console and i was able to type `map gm_construct` to get in-game.
![image](https://github.com/Facepunch/garrysmod-issues/assets/31490854/29e1edaf-0f43-4068-a292-1a28f5134d0a)

Maybe the main menu being invisible has to do with some of these errors
```
Failed to load /mnt/ATOM/SteamLibrary/steamapps/common/GarrysMod/bin/linux64/stdshader_dx6_client.so: (null)
Failed to load stdshader_dx6_client.so: (null)
Failed to load /mnt/ATOM/SteamLibrary/steamapps/common/GarrysMod/bin/linux64/stdshader_dx7_client.so: (null)
Failed to load stdshader_dx7_client.so: (null)
Failed to load /mnt/ATOM/SteamLibrary/steamapps/common/GarrysMod/bin/linux64/stdshader_dx8_client.so: (null)
Failed to load stdshader_dx8_client.so: (null)
Convar mat_monitorgamma has conflicting FCVAR_ARCHIVE flags (child: has FCVAR_ARCHIVE, parent: no FCVAR_ARCHIVE, parent wins)
Failed to load /mnt/ATOM/SteamLibrary/steamapps/common/GarrysMod/bin/linux64/game_shader_dx6_client.so: (null)
Failed to load /mnt/ATOM/SteamLibrary/steamapps/common/GarrysMod/garrysmod/bin/game_shader_dx6_client.so: (null)
Failed to load game_shader_dx6_client.so: (null)
Failed to load /mnt/ATOM/SteamLibrary/steamapps/common/GarrysMod/bin/linux64/game_shader_dx7_client.so: (null)
Failed to load /mnt/ATOM/SteamLibrary/steamapps/common/GarrysMod/garrysmod/bin/game_shader_dx7_client.so: (null)
Failed to load game_shader_dx7_client.so: (null)
Failed to load /mnt/ATOM/SteamLibrary/steamapps/common/GarrysMod/bin/linux64/game_shader_dx8_client.so: (null)
Failed to load /mnt/ATOM/SteamLibrary/steamapps/common/GarrysMod/garrysmod/bin/game_shader_dx8_client.so: (null)
Failed to load game_shader_dx8_client.so: (null)
Failed to load /mnt/ATOM/SteamLibrary/steamapps/common/GarrysMod/bin/linux64/game_shader_dx9_client.so: (null)
Failed to load /mnt/ATOM/SteamLibrary/steamapps/common/GarrysMod/garrysmod/bin/game_shader_dx9_client.so: (null)
Failed to load game_shader_dx9_client.so: (null)
```

**Comment by robotboy655** [comment] 2024-03-26 20:10
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5166

**Closed by robotboy655** 2024-03-26 20:10 UTC
Labels: Platform: Linux
