### ISSUE TITLE
Weapons can't be reloaded unless ammo was available at the point   the weapon was last switched-to.

### ISSUE THREAD

**Issue by philxyz** [Facepunch/garrysmod-issues#2595] opened 2016-05-06 01:50 UTC
If you switch to a weapon while no ammo is available for that weapon - then you call ply:GiveAmmo(), it is not possible to reload that weapon's clip until the weapon is reselected by the player.

Here is the workaround I am using:

```
function meta:GiveAmmo_ReloadFix(amount, typ, hidePopup)

	local wep = self:GetActiveWeapon()

	local paType = wep:GetPrimaryAmmoType()
	local paName = game.GetAmmoName(paType)

	local saType = wep:GetSecondaryAmmoType()
	local saName = game.GetAmmoName(saType)

	-- Determine whether we need to switch the player's weapon away and back
	-- so as to re-enable reloads of the weapon.
	local switchRequired = (paName ~= nil and paName:lower() == typ:lower() and self:GetAmmoCount(paType) == 0) or (saName ~= nil and saName:lower() == typ:lower() and self:GetAmmoCount(saType) == 0)

	-- Call the original GiveAmmo implementation
	self:GiveAmmo(amount, typ, hidePopup)

	if switchRequired then
		self:SelectWeapon("hands") -- Gamemode specific. This can be anything that all players have by default.
		self:SelectWeapon(wep:GetClass())
	end
end
```

**Comment by robotboy655** [comment] 2016-05-06 22:01
Fun fact: When this happens, ItemPostFrame is not called, so things like SWEP:Tick and SWEP:Think arent.

**Comment by philxyz** [comment] 2016-05-06 22:16
Oh - I thought that it _could_ have been intentional that it worked that way (since it makes sense that with no ammo available, why should you be able to reload) - but the above code probably shouldn't be necessary to work around it, either, ideally.

**Comment by robotboy655** [comment] 2016-05-06 22:32
I think this was unintentionally caused by the fix for multiplayer when you try to throw a prop picked up with E and it would try to shoot clientside.

**Comment by robotboy655** [comment] 2016-05-06 22:57
Should be fixed in Dev when it updates.

**Closed by robotboy655** 2016-05-06 22:57 UTC
