### ISSUE TITLE
No longer any way to interact with GMAs without/before mounting

### ISSUE THREAD

**Issue by NanoAi** [Facepunch/garrysmod-issues#4417] opened 2020-03-16 22:20 UTC
After the updates it seems that there's no longer a way to `file.Open` or even interact with GMA files outside of just blindly mounting them.

For example the following code...
```
local new = 2018382604
steamworks.DownloadUGC( new, function( result )
	print( "NEW: UGC: ", result )
	print( "IS NIL", file.Open( result, "rb", "GAME" ) == nil )
end)
```
Ouputs the following...
```
NEW: UGC: C:\Steam\steamapps\workshop\content\4000\2018382604/temp.gma
IS NIL: true
```

**Comment by bigdogmat** [comment] 2020-03-17 00:29
I dunno if this is in yet but if so https://github.com/Facepunch/garrysmod-requests/issues/1507#issuecomment-585284298

**Comment by NanoAi** [comment] 2020-03-17 00:51
I might be misunderstanding Robotboy's reply in there however he did say...

> Lets try this then:
> 
> The callback of steamworks.DownloadUGC will not have a second argument - a read only File object pointing to the ,gma. The file is closed after the hook is ran, so you gotta do everything you need to inside the callback.

And as you can see above I am doing everything inside the callback, just trying to read the actual contents of the GMA before mounting it. However it seems that this isn't currently possible.

**Comment by bigdogmat** [comment] 2020-03-17 01:49
What I got from it is there's a second argument to the callback in `steamworks.DownloadUGC`.  The second argument is a file handle to the downloaded gma. After the callback though it's closed and you can no longer access the file.

**Comment by robotboy655** [comment] 2020-03-17 07:25
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1507

**Closed by robotboy655** 2020-03-17 07:25 UTC

**Comment by NanoAi** [comment] 2020-03-17 17:31
> What I got from it is there's a second argument to the callback in `steamworks.DownloadUGC`. The second argument is a file handle to the downloaded gma. After the callback though it's closed and you can no longer access the file.

Robotboy said there wasn't though, on the wiki ( https://wiki.facepunch.com/gmod/steamworks.DownloadUGC ) it says... 

> The first and only argument is a string, containing path to the saved file, or nil if the download failed to any reason.

But I will try using a second argument, and post here just to clear things up for people.

**Comment by robotboy655** [comment] 2020-03-17 18:32
Sorry, I have documented this, this change was applied in todays update.
