### ISSUE TITLE
Non-Existant Materials On Client Cause Lag/Freezing

### ISSUE THREAD

**Issue by shadowscion** [Facepunch/garrysmod-issues#511] opened 2013-10-07 20:16 UTC
If someone spawns a prop (via a duplicator or something), and that prop has a material that the client doesn't have, the client will freeze, sometimes up to a minute, depending on how many props were spawned with the material.

Its very common for this to happen if you don't own some source games, or don't have them installed/mounted.

I thought I read that this was fixed, but I guess not.

**Comment by Mista-Tea** [comment] 2017-01-25 16:04
Can anything be done about this issue? This is an absolute game-killer on Sandbox.

E.g., upon a client entering a visleaf with multi-hundred prop contraptions that has missing materials (to the client), the client will lag out and keeping moving forward until they hit a wall or leave the visleaf, basically making it impossible for them to play.

**Comment by thegrb93** [comment] 2017-01-25 17:49
Yeah it sucks. I've had to mod everything that uses custom materials to abide by the server's material list.

**Comment by thegrb93** [comment] 2017-07-09 00:52
30 second lagspikes on some servers. It hurts.

**Comment by shadowscion** [comment] 2017-07-12 22:24
@thegrb93 can't believe this hasn't even been acknowledged in the 4 years since I opened it

eventually I got fed up and made a .bat file to create .vmts for every material from games I don't have, haven't had any issues since

**Comment by Noiwex** [comment] 2017-11-04 18:17
This still happens and it still hurts a lot, it may freeze game for good 10 seconds.

**Comment by Noiwex** [comment] 2018-08-17 15:50
If user machine isn't so fast and/or there's some considerable amount of addons, the lag can grow in time drastically.

**Comment by Mista-Tea** [comment] 2018-08-18 02:31
I had someone on my server grab a TF2 material and apply it to a PHX prop. I've stacked the plate several times to make the effect more noticeable. Essentially, the prop will look completely normal as if no material has been applied to it. However, trying to load the dupe(s) or walking into the dupe's visleaf should lag you out for a good while.

As noted in the FP Next Update thread, you may want to try this on a dedicated server that has all of the source games mounted.

I'm attaching both an AdvDupe2 dupe and a regular Duplicator dupe. Both should have the same effect of lagging you out, assuming you don't have TF2 mounted.

**AdvDupe2**
[MissingMaterialsTest.txt](https://github.com/Facepunch/garrysmod-issues/files/2299076/MissingMaterialsTest.txt)

**Duplicator**
You'll need to change the extension of the 2fcb0fbde52c6d3652ad904df4a6fb0f.txt file to .dupe

[2fcb0fbde52c6d3652ad904df4a6fb0f.txt](https://github.com/Facepunch/garrysmod-issues/files/2299085/2fcb0fbde52c6d3652ad904df4a6fb0f.txt)
![2fcb0fbde52c6d3652ad904df4a6fb0f](https://user-images.githubusercontent.com/5177393/44294877-87de0c00-a25b-11e8-933d-5da65896aa83.jpg)

I have all of these mounted on the server, and none of them mounted on my client.
```
"gamedepotsystem"
{
	"hl2"		"1"
	"episodic"	"1"
	"ep2"		"1"
	"lostcoast"	"1"
	"csgo"      "1"
	"cstrike"	"1"
	"l4d"       "1"
	"l4d2"      "1"
	"portal"    "1"
	"portal2"   "1"
	"tf"        "1"
	"dod"       "1"
}
```

**Comment by besenyei** [comment] 2018-08-18 04:01
fs_tellmeyoursecrets 1

Why does the game have to search every possible directory, and for each of those plates?

**Comment by Noiwex** [comment] 2018-08-18 08:28
Because it doesn't keep directory contents cached and that's how mounting works.

**Comment by Mista-Tea** [comment] 2020-05-04 01:25
This is still a terrible issue, so here are some more details to replicate it.

**The amount of lag experienced seems directly related to the number of paths mounted on the filesystem, as evidenced by `fs_tellmeyoursecrets 1` shown above.** 

## Setup:
- **Vanilla sandbox server** (dedicated)
- **SProps** (legacy addon) mounted on **server** https://github.com/shadowscion/sprops
- **Vanilla client** with as many source games mounted as possible
This is my `cfg/mountdepots.txt`:
```"gamedepotsystem"
{
	"hl2"		"1"
	"cstrike"		"1"
	"tf"		"1"
	"dod"		"1"
	"ep2"		"1"
	"episodic"		"1"
	"lostcoast"		"1"
	"hl1mp"		"1"
	"portal"		"1"
	"left4dead2"		"1"
	"left4dead"		"1"
	"portal2"		"1"
	"csgo"		"1"
	"thestanleyparable"		"1"
}
```

## Steps:
1. Join the server on gm_flatgrass
2. Go to the hidden area underneath spawn
3. Spawn any default prop you have (e.g. `models/hunter/blocks/cube025x025x025.mdl`)
4. Run `material_override sprops/textures/sprops_metal2` (a material included in SProps that the server will have but you will not)
5. Use the material tool to apply the material on the prop
6. Duplicate the prop and spawn it **dozens of time** (do not skimp on this, it will vary so literally spam it if you have to)
7. Try noclipping in and out of the hidden area multiple times

## Demo Video
https://i.gyazo.com/3dab82ca155330f7336e98b58ca027db.mp4

### With literally only a SINGLE prop spawned out, this is how many paths it searches when re-entering the PVS.
### Duplicate the prop multiple times and you start to get maybe why this lags so much.
### This is all without **ANY WORKSHOP OR LEGACY ADDONS**, which would only make the lag even worse with the increased search paths

```
Addon[GetFile]: [t:\programs\steam\steamapps\common\garrysmod\garrysmod\workshop\gamemodes\sandbox\content\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\garrysmod\garrysmod\workshop\gamemodes\base\content\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\garrysmod\garrysmod\workshop\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\garrysmod\garrysmod\overrides\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\garrysmod\garrysmod\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\garrysmod\sourceengine\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\garrysmod\platform\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\half-life 2\hl2\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\counter-strike source\cstrike\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\team fortress 2\tf\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\day of defeat source\dod\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\half-life 2\ep2\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\half-life 2\episodic\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\half-life 2\lostcoast\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\half-life 1 source deathmatch\hl1\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\half-life 1 source deathmatch\hl1mp\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\portal\portal\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\steam\steamapps\common\left 4 dead 2\left4dead2_dlc1\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\steam\steamapps\common\left 4 dead 2\left4dead2_dlc2\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\steam\steamapps\common\left 4 dead 2\left4dead2_dlc3\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\steam\steamapps\common\left 4 dead 2\left4dead2\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\steam\steamapps\common\left 4 dead\left4dead_dlc3\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\steam\steamapps\common\left 4 dead\left4dead\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\portal 2\portal2\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\counter-strike global offensive\csgo\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\the stanley parable\thestanleyparable\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\garrysmod\garrysmod\download\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\garrysmod\garrysmod\fallbacks\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\garrysmod\garrysmod\workshop\gamemodes\sandbox\content\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\garrysmod\garrysmod\workshop\gamemodes\base\content\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\garrysmod\garrysmod\workshop\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\garrysmod\garrysmod\overrides\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\garrysmod\garrysmod\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\garrysmod\sourceengine\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\garrysmod\platform\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\half-life 2\hl2\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\counter-strike source\cstrike\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\team fortress 2\tf\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\day of defeat source\dod\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\half-life 2\ep2\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\half-life 2\episodic\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\half-life 2\lostcoast\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\half-life 1 source deathmatch\hl1\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\half-life 1 source deathmatch\hl1mp\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\portal\portal\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\steam\steamapps\common\left 4 dead 2\left4dead2_dlc1\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\steam\steamapps\common\left 4 dead 2\left4dead2_dlc2\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\steam\steamapps\common\left 4 dead 2\left4dead2_dlc3\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\steam\steamapps\common\left 4 dead 2\left4dead2\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\steam\steamapps\common\left 4 dead\left4dead_dlc3\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\steam\steamapps\common\left 4 dead\left4dead\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\portal 2\portal2\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\counter-strike global offensive\csgo\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\the stanley parable\thestanleyparable\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\garrysmod\garrysmod\download\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\garrysmod\garrysmod\fallbacks\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\garrysmod\garrysmod\workshop\gamemodes\sandbox\content\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\garrysmod\garrysmod\workshop\gamemodes\base\content\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\garrysmod\garrysmod\workshop\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\garrysmod\garrysmod\overrides\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\garrysmod\garrysmod\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\garrysmod\sourceengine\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\garrysmod\platform\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\half-life 2\hl2\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\counter-strike source\cstrike\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\team fortress 2\tf\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\day of defeat source\dod\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\half-life 2\ep2\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\half-life 2\episodic\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\half-life 2\lostcoast\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\half-life 1 source deathmatch\hl1\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\half-life 1 source deathmatch\hl1mp\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\portal\portal\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\steam\steamapps\common\left 4 dead 2\left4dead2_dlc1\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\steam\steamapps\common\left 4 dead 2\left4dead2_dlc2\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\steam\steamapps\common\left 4 dead 2\left4dead2_dlc3\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\steam\steamapps\common\left 4 dead 2\left4dead2\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\steam\steamapps\common\left 4 dead\left4dead_dlc3\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\steam\steamapps\common\left 4 dead\left4dead\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\portal 2\portal2\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\counter-strike global offensive\csgo\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\the stanley parable\thestanleyparable\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\garrysmod\garrysmod\download\materials\sprops\textures\sprops_metal2.vmt]
Addon[GetFile]: [t:\programs\steam\steamapps\common\garrysmod\garrysmod\fallbacks\materials\sprops\textures\sprops_metal2.vmt]

```

**Comment by willox** [comment] 2020-05-04 01:49
Note: It won't increase in the same way with GMA addons. They don't have this sort of access pattern.

**Comment by robotboy655** [comment] 2020-05-06 16:50
Ok, the gm_flatgrass example was easy to reproduce, thanks.

This should be fixed on Dev. Unfortunately the fix has a side effect - if the material(s) become valid and existing after they are applied to a prop, they will still not load, even if you reapply the material. 

Previously it would load the material when you re enter the PVS or reapply the texture.
Now calling `mat_reloadmaterial` on the material will make the above tricks work.

I feel like this is a decent trade off - at least it doesn't lag insanely anymore and you should have all the materials ready when joining a server anyway.

**Closed by robotboy655** 2020-05-06 16:50 UTC

**Comment by thegrb93** [comment] 2020-05-06 17:31
Fuck yea. This was the worst bug

**Comment by Mista-Tea** [comment] 2020-05-06 18:46
This seems to work as intended. Thank you so much for addressing this -- it's practically a game-changer for sandbox and related gamemodes for clients that don't have optional content.

**Comment by shadowscion** [comment] 2020-05-15 16:53
Thank you

**Comment by shadowscion** [comment] 2020-08-11 16:21
Is this fixed on the x84-64 branch? Still having the issue.

**Comment by robotboy655** [comment] 2020-08-11 16:32
You are not having this issue, or your client is out of date, such as running Chromium branch.

**Comment by shadowscion** [comment] 2020-08-11 17:10
I am and I can reproduce it using the flatgrass example above. I've factory reset and I have also opted out of all the beta branches.

**Comment by robotboy655** [comment] 2020-08-12 15:56
Good catch, should be fixed on Dev and other branches by the end of the week.
