### ISSUE TITLE
Models got reflected by using cam.Start3D()

### ISSUE THREAD

**Issue by markusmarkusz** [Facepunch/garrysmod-issues#2719] opened 2016-07-12 15:34 UTC
If I use cam.Start3D() to render something then it cause problems if I have "Water details" set to "Reflect world" or "Reflect all".
I don't know if there are relationships with this #2682.

Here is a example:
Code:
```lua
hook.Add("RenderScreenspaceEffects", "Test", function()
    local color_effect = {
	["$pp_colour_addr"] = 0,
	["$pp_colour_addg" ] = 0,
	["$pp_colour_addb" ] = 0,
	["$pp_colour_brightness" ] = 0,
	["$pp_colour_contrast" ] = 1,
	["$pp_colour_colour" ] = 0,
	["$pp_colour_mulr" ] = 0.,
	["$pp_colour_mulg" ] = 0,
	["$pp_colour_mulb" ] = 0
    }

    DrawColorModify(color_effect)
    cam.Start3D(EyePos(), EyeAngles())
        for k,v in pairs(player.GetAll()) do
            render.SuppressEngineLighting( true )
            render.SetColorModulation(1,1,1)
            v:DrawModel()
            render.SuppressEngineLighting( false )
        end
    cam.End3D()
end)
```

Map example 1 (with many water and with "Water detail" set to "Reflect world"):
![image](https://cloud.githubusercontent.com/assets/7966992/16696417/11a51742-4545-11e6-91f4-6c737313211c.png)

With "Water detail" set to "Simple reflections":
![image](https://cloud.githubusercontent.com/assets/7966992/16696471/4e9983ae-4545-11e6-8de7-5fb0cc058903.png)

Map example 2 (with no water):
![image](https://cloud.githubusercontent.com/assets/7966992/16696585/ed8804d6-4545-11e6-98a3-c3d0328092a6.png)

Already opend a thread at the Facepunch-Forum.
(Link: https://facepunch.com/showthread.php?t=1525331)
But nobody answers and I'm 100% sure that this is a GMod bug.

This bug is already longer present.

**Comment by robotboy655** [comment] 2016-08-29 10:26
I am pretty sure the root cause of this was fixed in the Dev branch some weeks ago. At the very least I could not reproduce it on gm_construct with your code and a bot above water with reflections set to reflect all.

**Closed by robotboy655** 2016-08-29 10:26 UTC
