### ISSUE TITLE
Marlett font ignores symbol argument on linux

### ISSUE THREAD

**Issue by CGDoctor8** [Facepunch/garrysmod-issues#4089] opened 2019-12-09 18:51 UTC
### Details
on the x86-64 bratch (it may also effect main branch) the font Marlett is not rendered the same on windows client vs linux client and on the linux client symbol argument is just strait up ignored this can cause problems where current add-ons will be completely unusable on Linux 

### Steps to reproduce
Place lua in GarrysMod/garrysmod/lua/autorun/client/cl_test.lua
```lua
// GarrysMod/garrysmod/lua/autorun/client/cl_test.lua

surface.CreateFont( "test", {
    font = "Marlett",
    size = 50,
    weight = 500,
    symbol = false,
})

hook.Add( "HUDPaint", "HelloThere", function()
    draw.DrawText( "Hello there!", "test", ScrW() * 0.5, ScrH() * 0.25, Color( 255, 0, 0, 255 ), TEXT_ALIGN_CENTER )
end )
```

### Screen Shots
unusable add-on
![image](https://user-images.githubusercontent.com/39572468/70463389-ba48f380-1ab4-11ea-99d0-7af95cafeb78.png)

Linux -- symbol = false
![image](https://user-images.githubusercontent.com/39572468/70462765-7dc8c800-1ab3-11ea-88dc-9f65b1fbe158.png)

Windows -- symbol = false
![image](https://user-images.githubusercontent.com/39572468/70462719-64c01700-1ab3-11ea-909d-d859c05ac356.png)

Linux -- symbol = true
![image](https://user-images.githubusercontent.com/39572468/70462781-83bea900-1ab3-11ea-92a8-5685b5775ac2.png)

Windows -- symbol = true
![image](https://user-images.githubusercontent.com/39572468/70462673-4d812980-1ab3-11ea-9e94-0dbde5089821.png)

**Comment by robotboy655** [comment] 2019-12-09 19:21
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/842

**Closed by robotboy655** 2019-12-09 19:21 UTC

**Comment by CGDoctor8** [comment] 2019-12-09 19:23
Is it indented for symbol = false to do nothing? the other issue dosnt mention it and its the main reason this issue was created
