### ISSUE TITLE
Crash while playing gmod

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#2916] opened 2016-11-12 19:37 UTC
### Details
https://www.dropbox.com/s/359f4gl694monhi/hl2_161029_crash_2016_11_12T19_34_54C0.mdmp?dl=0

### Steps to reproduce
Happened when I died.
hl2. exe stopped working.

**Comment by Kefta** [comment] 2016-11-12 19:49
http://dumps.metastruct.uk.to/ you can upload and read the dump here. This is not a place to report every crash you have

**Comment by robotboy655** [comment] 2016-11-12 20:08
Duplicate of the decals crash already reported.

**Closed by robotboy655** 2016-11-12 20:08 UTC
Labels: crash
