### ISSUE TITLE
WEAPON:DoImpactEffect() doesn't remove water impacts on returning true

### ISSUE THREAD

**Issue by Nitestokeh** [Facepunch/garrysmod-issues#5676] opened 2023-12-31 21:37 UTC
### Details
Returning true for function SWEP:DoImpactEffect(tr) doesn't remove water effects nor its sounds

### Steps to reproduce
Return true for the function

**Comment by robotboy655** [comment] 2024-04-30 18:27
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/2970

**Closed by robotboy655** 2024-04-30 18:27 UTC
