### ISSUE TITLE
Filesystem GMAs suddenly do not load

### ISSUE THREAD

**Issue by yogwoggf** [Facepunch/garrysmod-issues#6024] opened 2024-10-10 03:31 UTC
### Details
Lots of my users are complaining about my addon going completely missing upon updating to `Exe build: 18:45:32 Oct  9 2024 (9452) (4000)`.
I package my addon as a GMA to ease deployment on user computers (its a niche addon which uses binary modules).

### File structure which previously worked

```
GarrysMod/
    - addon/
        - addon.gma (loads!)
- ...
```

This no longer works as of the update I mentioned.
```
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 18:45:32 Oct  9 2024 (9452) (4000)
GMod version 2024.10.09, branch: x86-64, multicore: 1
Windows 64bit
```

**Comment by robotboy655** [comment] 2024-10-10 11:35
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5974#issuecomment-2402907288

It will be fixed soon.

**Closed by robotboy655** 2024-10-10 11:35 UTC
