### ISSUE TITLE
Clientside GetEyeTrace in Entity:Think crash

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#3309] opened 2017-09-29 23:20 UTC
I've been seeing this a lot on my server and can't figure out what is doing it.

Stable branch dump that was just generated today.
https://www.dropbox.com/s/vbr6f9kj18xb3rh/hl2_170801_crash_2017_9_29T23_5_7C0.mdmp?raw=1

**Comment by Kefta** [comment] 2017-09-30 01:14
GetEyeTrace is implemented in Lua (https://github.com/Facepunch/garrysmod/blob/784cd57576d85712fa13a7cea3a9523b4df966b0/garrysmod/gamemodes/base/gamemode/obj_player_extend.lua#L183). Can you replicate it with TraceLine?

**Comment by thegrb93** [comment] 2017-09-30 02:50
Yea traceline is at the top of the stacktrace.

**Comment by robotboy655** [comment] 2017-09-30 11:55
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/2145

**Closed by robotboy655** 2017-09-30 11:55 UTC
Labels: crash, duplicate

**Comment by thegrb93** [comment] 2017-09-30 17:09
How does a clientside trace crash relate to server.dll crash?

**Comment by robotboy655** [comment] 2017-09-30 17:46
It's a TraceLine crash that happens on both.
