### ISSUE TITLE
mounting of deinstalled addons

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3601] opened 2018-09-13 06:09 UTC
### Details
I today subscribed to some addons.
I deinstalled them already, but in offline mode they appear again and are getting mounted in game.
The gma files are still there.

### Steps to reproduce
unknown

**Comment by Kefta** [comment] 2018-09-13 06:14
I'm pretty sure there's no way to verify which addons you are subscribed to in offline mode resulting in everything being enabled.

**Comment by mcNuggets1** [comment] 2018-09-13 06:14
I should still be able to deinstall those and if I unsubscribe to something it actually should get deleted.

**Comment by Jpofin** [comment] 2018-09-20 13:42
^ what robotboy says.

Uninstall them ingame. There is an "uninstall-all" extension somewhere on the internet aswell.

**Comment by mcNuggets1** [comment] 2018-09-20 13:44
Gosh, I did.

But when deinstalling via the "Internet", the gma file still remains in the gmod folder and when in offline mode, you can't deinstall at all.

**Comment by Jpofin** [comment] 2018-09-20 14:12
If you mean uninstalling via the steam browser I think gmod thinks that you still have them.
You can un-subscribe in gmod in the home menu.

It works for me, so I don't think it's a problem of the game itself.

**Comment by Jpofin** [comment] 2018-09-20 14:27
I never tried that before. I don't think I ever will need this.
Well I've not seen someone playing in offline mode and wanting to remove addons.
Could be an issue, I can try this sometimes.
So you can't start the game in offline-mode (without an ethernet/wireless connection) and then go into "addons" in the home-menu and remove them?

Probably can't fetch them then, I don't know.

There is still an addon uninstaller on the internet, I can't remember where I found it but I still have it and it works good.

**Comment by mcNuggets1** [comment] 2018-09-20 14:29
It's not a top priority issue of course, so stop texting :P

**Comment by robotboy655** [comment] 2018-09-21 04:42
>  In offline mode you can't do anything to delete files from your computer, even tho you aren't subscribed to them anymore.

Except that you can go to your addons folder and just delete the files like you can any file on your computer.

As I said, it will only delete the .gma from addons/ if the game is open when you unsub. How you unsub is not important:
https://my.mixtape.moe/rpubqm.webm

The reason we don't delete .gma files of unsubbed addons automatically on start up is because people made a big fuss about it when I proposed that in the Next Update thread. Otherwise I'd be already done.

As I've also said, the problem will no longer exist in the future, when we no longer manually compress/decompress the addons meaning addon files will be handled entirely by Steam.

**Comment by siasur** [comment] 2018-11-12 09:50
Will the .gma file still exist then as it is now?
And will it still be mounted to the game if found in the addons/ dir?

**Comment by robotboy655** [comment] 2020-01-24 16:50
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/2178

**Closed by robotboy655** 2020-01-24 16:50 UTC
