### ISSUE TITLE
surface.PlaySound does not work with sound scripts (sound.Add)

### ISSUE THREAD

**Issue by NforceSSP** [Facepunch/garrysmod-issues#5341] opened 2022-10-17 21:16 UTC
As the title says, surface.PlaySound() does not work with sound scripts. This was tested with a sample addon on Windows, the normal branch, dev branch, and x86-64 branch were tested. It returns an error stating that "big_explosion" (see below) is not on the disk/repository.

Code used:
```
sound.Add({
	name = "big_explosion",
	channel = CHAN_STATIC,
	volume = 1.0,
	level = 80,
	pitch = {95, 110},
	sound = "phx/explode03.wav"
})

surface.PlaySound( "big_explosion" )
```

### Steps to reproduce
Paste code above in a sample addon.

**Comment by robotboy655** [comment] 2022-10-18 10:33
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/4504

**Closed by robotboy655** 2022-10-18 10:33 UTC
