### ISSUE TITLE
Bodygroup limit for viewmodel

### ISSUE THREAD

**Issue by arkayden** [Facepunch/garrysmod-issues#5369] opened 2022-12-15 15:17 UTC
The problem with the bodygroups limit on viewmodel. Our weapons have a large number of bodygroups, and when we set bodygroups on viewmodel such as we have set on worldmodel, they are displayed incorrectly, because the limit for bodygroups on viewmodel is only 8 bits.

We need to change the value from 8 to 32 be so that we can use the same bodygroups on viewmodel that we use on worldmodel. By default, CBaseAnimating supports 4,294,967,296 combinations (32 bits)

https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/shared/baseviewmodel_shared.cpp#L561

**Comment by robotboy655** [comment] 2022-12-15 15:25
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/830

**Closed by robotboy655** 2022-12-15 15:25 UTC
Labels: Duplicate, Net compat
