### ISSUE TITLE
Arch Linux Chrome Beta Issue

### ISSUE THREAD

**Issue by djpiper28** [Facepunch/garrysmod-issues#5202] opened 2022-03-31 20:34 UTC
### Details
Tell us exactly what happens here, every single detail that you can think of.
Please include information such as which Beta Branch your game is on, the console log (opened in-game by pressing SHIFT+ESC) and the version of the game you are running, which can be retrieved via the `version` console command.
Please try running a different(dev)/none beta branch and verifying your game cache integrity before reporting an issue. 

If you are going to post crash dumps (.mdmp or .dmp files), please either send them to robotboy655@facepunchstudios.com or create a **permanent** link.

System:
 - Arch
 - x86_64 build for gmod
 - Google Chrome

Error in chromium_log. This can be solved with `--no-sandbox` but I do not know how to give this to
my chrome. When gmod is started, how do I give it this flag?
```
The display compositor is frequently crashing. Goodbye.
```

**Comment by djpiper28** [comment] 2022-03-31 20:39
Edit: my options menu and, all that use chromium do not render. but with some arcane magic I got the game to launch

**Comment by rileysu** [comment] 2022-04-01 07:34
https://github.com/solsticegamestudios/GModCEFCodecFix

Does this fix the issue?

**Comment by Mr0maks** [comment] 2022-04-24 21:51
> https://github.com/solsticegamestudios/GModCEFCodecFix
> 
> Does this fix the issue?

Fixed issue for me

**Comment by EntityinArray** [comment] 2022-06-29 17:44
Experiencing the same issue, on Arch Linux with x86_64 branch of GMod
````[0629/204009.882426:ERROR:gl_implementation.cc(277)] Failed to load /mnt/Windows/SteamLibrary/steamapps/common/GarrysMod/bin/linux64/swiftshader/libGLESv2.so: /mnt/Windows/SteamLibrary/steamapps/common/GarrysMod/bin/linux64/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0629/204009.882689:VERBOSE1:gpu_init.cc(308)] gl::init::InitializeStaticGLBindingsOneOff failed
[0629/204009.887435:ERROR:viz_main_impl.cc(161)] Exiting GPU process due to errors during initialization
[0629/204009.956493:VERBOSE1:sandbox_linux.cc(69)] Activated seccomp-bpf sandbox for process type: gpu-process.
[0629/204010.673012:WARNING:gpu_process_host.cc(1165)] The GPU process has crashed 1 time(s)
[0629/204010.722336:VERBOSE1:sandbox_linux.cc(69)] Activated seccomp-bpf sandbox for process type: gpu-process.
[0629/204010.995954:WARNING:gpu_process_host.cc(1165)] The GPU process has crashed 2 time(s)
[0629/204011.046874:VERBOSE1:sandbox_linux.cc(69)] Activated seccomp-bpf sandbox for process type: gpu-process.
[0629/204012.120290:WARNING:gpu_process_host.cc(1165)] The GPU process has crashed 3 time(s)
[0629/204012.120413:FATAL:gpu_data_manager_impl_private.cc(1034)] The display compositor is frequently crashing. Goodbye.
Game process removed: AppID 4000 "/home/entityinarray/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=4000 -- '/mnt/Windows/SteamLibrary/steamapps/common/GarrysMod/hl2.sh' -steam -game garrysmod", ProcID 51393

**Comment by robotboy655** [comment] 2024-03-26 20:11
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5166

**Closed by robotboy655** 2024-03-26 20:11 UTC
Labels: Platform: Linux
