### ISSUE TITLE
The file function `file.Open()` does not find AddCSLuaFile'ed files in LUA path.

### ISSUE THREAD

**Issue by Grocel** [Facepunch/garrysmod-issues#5719] opened 2024-01-29 20:41 UTC
# Details
The file function `file.Open()` does not find AddCSLuaFile files in `LUA` path. This also affects `file.Read()`. The functions `file.Exists()` and `file.IsDir()` work fine, especially after https://github.com/Facepunch/garrysmod-issues/issues/5674 has been fixed.

This issue happens on the clientside if the Lua file has been AddCSLuaFile'ed from the server, but is not physically present on the client. One such case is server exclusive Lua content.

The issue has been confirmed to exist by Rubat on Discord.
<img width="428" alt="Discord_2024-01-29_21-47-49" src="https://github.com/Facepunch/garrysmod-issues/assets/2457653/1b8650bc-afb9-4958-a3bf-ee19d642b895">

# Steps to reproduce
The issue is best reproduced on a dedicated server, using the test scripts as shown below as an addon.

## Test scripts
```lua
-- autorun/_test_addcslua.lua

AddCSLuaFile()
AddCSLuaFile("_test_addcslua/testfile.lua")

-- include("_test_addcslua/testfile.lua") -- Optional

local function fileOpenTest( path, dir )
    local f = file.Open( path, "r", dir )

    if f then
        f:Close()

        return true
    end

    return false
end

local function fileReadTest( path, dir )
    return tobool( file.Read( path, dir ) )
end

local function TestFunction(name, func, path, searchPath)
    print( name .. " " .. searchPath )

    print( "  path: ", path )
    print( "  searchPath: ", searchPath )
    print( "  finds: ", func( path, searchPath ) )
end


local function Test()
    print("\n============================\n")

    print( "REALM: ", SERVER and "SERVER" or "CLIENT")
    print( "VERSION: ", VERSION)
    print( "BRANCH: ", BRANCH)

    print("\n----------------------------\n")

    TestFunction("file.Exists()", file.Exists, "_test_addcslua/testfile.lua", "LUA")

    print("")

    TestFunction("file.Exists()", file.Exists, "lua/_test_addcslua/testfile.lua", "GAME")


    print("\n----------------------------\n")


    TestFunction("file.IsDir()", file.IsDir, "_test_addcslua", "LUA")

    print("")

    TestFunction("file.IsDir()", file.IsDir, "lua/_test_addcslua", "GAME")


    print("\n----------------------------\n")

    TestFunction("file.Read()", fileReadTest, "_test_addcslua/testfile.lua", "LUA")

    print("")

    TestFunction("file.Read()", fileReadTest, "lua/_test_addcslua/testfile.lua", "GAME")


    print("\n----------------------------\n")


    TestFunction("file.Open()", fileOpenTest, "_test_addcslua/testfile.lua", "LUA")

    print("")

    TestFunction("file.Open()", fileOpenTest, "lua/_test_addcslua/testfile.lua", "GAME")

    print("\n============================\n")
end

timer.Simple(1, Test)
```

```lua
-- _test_addcslua/testfile.lua
print("_test_addcslua/testfile.lua loaded")
-- whatever...
```

## Test Result
| **Function**                    | **Search Path** | **supports AddCSLuaFile** |
|---------------------------------|-----------------|----------------------------------|
| `file.Exists`                   | `LUA`           | Yes                              |
| `file.Exists`                   | `GAME`          | No                               |
| `file.IsDir`                    | `LUA`           | Yes                              |
| `file.IsDir`                    | `GAME`          | No                               |
| `file.Read()`                   | `LUA`           | No <- ERROR                      |
| `file.Read()`                   | `GAME`          | No                               |
| `file.Open()`                   | `LUA`           | No <- ERROR                      |
| `file.Open()`                   | `GAME`          | No                               |

## Raw Test Result
```
============================

REALM: 	CLIENT
VERSION: 	240129
BRANCH: 	dev

----------------------------

file.Exists() LUA
  path: 	_test_addcslua/testfile.lua
  searchPath: 	LUA
  finds: 	true

file.Exists() GAME
  path: 	lua/_test_addcslua/testfile.lua
  searchPath: 	GAME
  finds: 	false

----------------------------

file.IsDir() LUA
  path: 	_test_addcslua
  searchPath: 	LUA
  finds: 	true

file.IsDir() GAME
  path: 	lua/_test_addcslua
  searchPath: 	GAME
  finds: 	false

----------------------------

file.Read() LUA
  path: 	_test_addcslua/testfile.lua
  searchPath: 	LUA
  finds: 	false

file.Read() GAME
  path: 	lua/_test_addcslua/testfile.lua
  searchPath: 	GAME
  finds: 	false

----------------------------

file.Open() LUA
  path: 	_test_addcslua/testfile.lua
  searchPath: 	LUA
  finds: 	false

file.Open() GAME
  path: 	lua/_test_addcslua/testfile.lua
  searchPath: 	GAME
  finds: 	false

============================
```

# Why is this an issue?
1. It is inconstant with the rest of the API making it harder to learn.
2. This behavior has not been documented as intended, therefor it can be considered as a bug in the given context.
3. Make file reading of affected files impossible and could cause unexpected behavior on more advanced Lua setups.

# My proposed resolution
1. Please add AddCSLuaFile support to the affected function
2. Or please document the missing AddCSLuaFile support as intentional with a reason why it is so otherwise.

**Comment by robotboy655** [comment] 2024-04-30 17:56
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/1798

**Closed by robotboy655** 2024-04-30 17:56 UTC

**Comment by Grocel** [comment] 2024-08-17 17:50
> Duplicate of #1798

Bad issue management. Especially after you said no one would have asked for that in the past 10 years. 👎
