### ISSUE TITLE
GMod freezes render after some time 

### ISSUE THREAD

**Issue by GitSparTV** [Facepunch/garrysmod-issues#4415] opened 2020-03-13 17:02 UTC
GMod rendering stops at random time. It doesn't crash so no crash logs.
I can use keyboard and mouse, even retry connection and use main menu but the frame is not changing.
This is happening to me last month.
Multicore rendering setting doesn't matter .

All branches, Windows 10, x64, BootCamp, AMD Radeon R9 M380.

https://imgur.com/3m6CWb0 (Apparently the video is useless because it didn't capture my mouse)

**Comment by GitSparTV** [comment] 2020-03-13 17:09
It can freeze even in main menu (i didn't start the game yet)

**Comment by GitSparTV** [comment] 2020-03-15 14:54
I suspect Alt+Tab for this issue but if I spam it it doesn't freeze.
Autorefresh also is out of suspicion since the freeze can happen in the main menu

**Comment by GitSparTV** [comment] 2020-03-15 15:16
I managed to record the cursor interaction.
https://imgur.com/Nkcbh7G

**Comment by GitSparTV** [comment] 2020-03-15 17:07
Attaching the debugger didn't show anything. Both in hl2.exe and awesomium_renderer.exe

**Comment by GitSparTV** [comment] 2020-03-16 17:12
Note: Even a steam overlay freezes with the game.
Here on the picture the image of the latest update is not loaded fully and the steam overlay popped out. At this moment the game freezes the render
![image](https://user-images.githubusercontent.com/5685050/76783090-4ceae400-67c2-11ea-87c5-04a20410bed5.png)

**Comment by GitSparTV** [comment] 2020-03-16 17:14
Note: My screen resolution is 5120x2880 with 200% scale. The size of the gmod window doesn't matter, it freezes on any of them

**Comment by robotboy655** [comment] 2020-03-16 17:53
I have only seen this reported with AMD graphics card, so its not out of question it is a problem with drivers.

**Comment by GitSparTV** [comment] 2020-03-16 18:04
I will try to reinstall drivers

**Comment by GitSparTV** [comment] 2020-03-17 23:13
Damn, installing the latest GPU driver and windows update didn't fix the problem.

**Comment by GitSparTV** [comment] 2020-03-17 23:14
Interesting this that Radeon Software is telling me that VRAM is almost 100%

**Comment by GitSparTV** [comment] 2020-03-21 00:02
I tried to lower all settings to minimal because someone had problem because of higher shader details.
This didn't solve my problem. Still trying

**Comment by thegrb93** [comment] 2020-03-21 00:28
Maybe a clean windows install would help :v

**Comment by GitSparTV** [comment] 2020-03-21 12:05
Ok what, here my GPU values when GMod is opened with 2048x1152 in-game resolution with ultra-high settings. Windows settings: 2560x1440:
![image](https://user-images.githubusercontent.com/5685050/77225975-59d25380-6b85-11ea-9e99-af9a091a0acb.png)

![image](https://user-images.githubusercontent.com/5685050/77225801-c2b8cc00-6b83-11ea-93af-f3875ed6ad56.png)

This is the same GMod settings but now the Windows screen resolution is native: 5120x2880
![image](https://user-images.githubusercontent.com/5685050/77225898-b6813e80-6b84-11ea-9704-858ead2b5b10.png)
![image](https://user-images.githubusercontent.com/5685050/77225903-c13bd380-6b84-11ea-918e-5b28d798d6fe.png)

**Comment by GitSparTV** [comment] 2020-03-22 09:50
So I'm sitting on 2560x1440 for more than 24 hours and the game didn't freeze all this time.
I need to test who sucks in rendering in 5K.

**Comment by Gmod4phun** [comment] 2020-04-06 21:22
This might not be related at all, but this happened to me after a clean install of Windows on my other PC. At first I tought it was a driver issue, or a Windows Update problem. Every game would just freeze after a few seconds, I could hear it running in the background, I could walk, shoot etc, but the rendering was frozen. Turned out one of my ram sticks somehow got wiggled (presumably), as everything went back to normal after I re-seated the ram (after 2 windows reinstalls :P). Give that a shot, you never know.

**Comment by robotboy655** [comment] 2020-05-25 18:33
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/4415

**Closed by robotboy655** 2020-05-25 18:33 UTC
