### ISSUE TITLE
64 bit vbsp has broken instancing

### ISSUE THREAD

**Issue by Aarik1** [Facepunch/garrysmod-issues#5724] opened 2024-01-31 15:35 UTC
### Details

I am running x86-64 branch

Version Info
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 13:53:47 Jan 31 2024 (9196) (4000)
GMod version 2024.01.31, branch: x86-64, multicore: 1
Windows 64bit

When a map is compiled using the 64 bit vbsp.exe, the instances located within that map will have all their entities sent to 0 0 0.
The entities retain their offsets from the instance so its like the instance is stuck at 0 0 0. Static geometry such as brushes are unaffected by this bug. If 0 0 0 is out in the void vbsp will say its leaking.

This is most likely a problem with a broken attempt at porting over instancing code from later engine branches.

### Steps to reproduce
1. Create an instance and place it in the maps/instances folder, make sure there are entities in it.
2. Place down a func_instance in a map set it to the instance you just created.
3. Compile the map

Once you spawn into the map any entities that were in the instances should be at 0 0 0.

**Comment by robotboy655** [comment] 2024-01-31 15:53
Does this happen on NONE beta?

**Comment by robotboy655** [comment] 2024-01-31 16:00
Sounds like a duplicate of https://github.com/Facepunch/garrysmod-issues/issues/4848

**Comment by Aarik1** [comment] 2024-01-31 16:05
> Does this happen on NONE beta?

This does not happen on the main branch I forgot to add. That branch's vbsp also has some issues, ill write up an issue ticket later with the details on that.

**Comment by robotboy655** [comment] 2024-01-31 17:59
I cannot reproduce this. I have a func_instance in my test map, added some props to it and compiled using x86-64 tools, it still functions.

![image](https://github.com/Facepunch/garrysmod-issues/assets/3299036/0708171a-943b-4854-bde1-a40e98586f0b)

**Comment by Aarik1** [comment] 2024-01-31 19:24
After a complete reinstall of the game and a reboot, the issue is still here. Ill zip up the vmf and instance im using.
[maps.zip](https://github.com/Facepunch/garrysmod-issues/files/14116189/maps.zip)

**Comment by robotboy655** [comment] 2024-02-01 13:19
Still nada. I have tried running vbsp only, and all 3 compilers on Fast, nothing.

![image](https://github.com/Facepunch/garrysmod-issues/assets/3299036/5338179b-7aea-4587-9dc6-eff557dbae97)

Are you absolutely certain you are running the game's VBSP, not some custom one? What are your EXACT settings you use to compile the map?

**Comment by Aarik1** [comment] 2024-02-01 16:22
Using a fresh build downloaded from steam after uninstalling and reinstalling, i used the bin/win64/vbsp.exe executable.
If i compile via command line by just doing 
```
vbsp.exe -game "D:\SteamLibrary\steamapps\common\GarrysMod\garrysmod" D:\SteamLibrary\steamapps\common\GarrysMod\garrysmod\maps\vmf.vmf 
```

it will output a bsp that looks like this
![20240201081353_1](https://github.com/Facepunch/garrysmod-issues/assets/36469582/f4aaea7d-149c-4fc4-af2b-fb3ef6c7796f)

Heres the bsp itself if you want to look at it
[instance_test.zip](https://github.com/Facepunch/garrysmod-issues/files/14127972/instance_test.zip)

**Comment by robotboy655** [comment] 2024-02-02 17:16
Thanks for the details. The issue appears to be specifically with the 64bit build of `vbsp.exe`, which is not used by Hammer on `x86-64` beta, which is where the discrepancy was.

I am able to reproduce the issue.

Closing this as a duplicate of https://github.com/Facepunch/garrysmod-issues/issues/4848

**Closed by robotboy655** 2024-02-02 17:16 UTC
Labels: Tools
