### ISSUE TITLE
NextBot locomotion breaks on interaction with ladders

### ISSUE THREAD

**Issue by 3Pills** [Facepunch/garrysmod-issues#3726] opened 2019-01-26 09:07 UTC
### Details
A specific interaction with ladders / cliffs causes nextbots to enter a broken T-Pose physics state where they freeze mid-air and their CLuaLocomotion object returns true for IsUsingLadder (something that never usually happens in my experience). 

[Image Example](https://i.imgur.com/4SiKFj5.jpg)

### Steps to reproduce
I've provided a test addon which contains a map zh_laddertest to replicate this [nextbot_ladder_bug.zip](https://github.com/Facepunch/garrysmod-issues/files/2798800/nextbot_ladder_bug.zip). Stick that in the addons folder. (Excuse the hacky autorun lua, it is gutted from my zombie gamemode)

The bug should automatically happen to at least one of the zombies that spawns and runs at you, provided you stay still. It seems that you need a cliff, with a connection to a lower navmesh, and a ladder also connecting to a lower navmesh. When the bot tries to jump down the cliff while in contact with the ladder, this issue occurs.

**Comment by robotboy655** [comment] 2019-01-26 10:55
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/663

**Closed by robotboy655** 2019-01-26 10:55 UTC
