### ISSUE TITLE
Scrolling doesnt work right on mac!

### ISSUE THREAD

**Issue by wannaseeanalien** [Facepunch/garrysmod-issues#3679] opened 2018-12-13 02:55 UTC
### Details
Scrolling of any sort does not work right at all. Physgun use, using any menu, scrolling thru console, weapons etc it all is broken and busted. Eespecially the physgun, sandbox is basically unplayable like this... Sometimes i cant even move my prop at all :/

(Windows: If you are going to post crash logs, post the .mdmp files themselves, download links)

### Steps to reproduce
Literally try to use your physgun in any activity or try to navigate a menu/gui that supports scrolling and see the anomalous behaviour.

I see this is not a problem in other source engine ports for macos and I certainly don't remember it being a problem in gmod 12, I dont know how long this has been an issue but can we PLEASE get it fixed? sandbox is like the core of gmod and i cant play it like this....... thank you

**Comment by robotboy655** [comment] 2018-12-13 12:44
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/2772

**Closed by robotboy655** 2018-12-13 12:44 UTC
Labels: osx

**Comment by wannaseeanalien** [comment] 2018-12-14 04:18
Soooo its been reported multiple times over the years, and instead of fixing it you are just closing ppls threads.... why??  we want to play gmod too :(

**Comment by UAVXP** [comment] 2018-12-24 18:17
The thing is not to report the same thing over and over again. This wont help developers much, instead this will just increase amount of open issues. Just wait, that's the best option. Developers are people too, just like you are
