### ISSUE TITLE
pcall doesn't stop include errors

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3112] opened 2017-04-03 04:59 UTC
It will print the file error to console but not halt the function, causing pcall to return true.

Semi-related: https://github.com/Facepunch/garrysmod-issues/issues/1976

**Comment by TASSIA710** [comment] 2020-10-16 17:18
This workaround worked for me:
```lua
local exec = CompileFile("your_file.lua")
local status, err = pcall(exec)
```

**Comment by Kefta** [comment] 2020-10-16 21:48
That doesn't work with autorefresh though.

**Comment by robotboy655** [comment] 2023-10-13 15:29
This is ultimately a duplicate of https://github.com/Facepunch/garrysmod-issues/issues/3112 - same cause.

**Closed by robotboy655** 2023-10-13 15:29 UTC
Labels: Complexity: Low, Intentional
