### ISSUE TITLE
Invisible Barrier on Ladders

### ISSUE THREAD

**Issue by ThatGmodZServer** [Facepunch/garrysmod-issues#2980] opened 2016-12-21 23:34 UTC
### Details
With the recent update of Garry's Mod, Ladders on my server are having this weird occurring bug where an invisible barrier or box forms around the ladder or outside of it preventing players from going up or down the ladder itself.
I assume it has to do with the recent fix labeled: Fixed buggy behavior when a player dies whilst climbing a ladder.

Here are 2 Videos of the invisible barrier: 
https://my.mixtape.moe/jjfvnw.mp4
https://my.mixtape.moe/jdasop.mp4

The only way I found to fix it temporarily is to do a restart but that isn't something I would find convenient for myself or my players.  

### Steps to reproduce
Not exactly sure how to reproduce it just yet, I can only assume it's when a player dies on the ladder.

**Comment by Kefta** [comment] 2016-12-21 23:43
Can reproduce this with some HL2 ladders. CS:S ladders are unaffected.

**Comment by robotboy655** [comment] 2016-12-21 23:47
Post steps to reproduce then??

**Comment by ThatGmodZServer** [comment] 2016-12-22 02:06
Glad to hear someone was able to reproduce it, I wasn't able to.

**Comment by kem008** [comment] 2016-12-23 11:19
I remember this bug from hl2dm. Valve fixed it im sure.

**Comment by ThatGmodZServer** [comment] 2016-12-27 01:15
Is this something that is currently being looked at to fix soon? This is a troublesome of an issue to deal with.

**Comment by Kefta** [comment] 2016-12-27 01:19
I can't reproduce it even close to consistently; it's definitely an issue, but I only notice it on highly populated RP servers. I got it once on a listen Sandbox, but it was seemingly random.

**Comment by ThatGmodZServer** [comment] 2016-12-27 02:32
I just seem to grasp why this is happening or what truly provoked this in the latest update. I found a few days ago that it wasn't just myself who had this issue on their server as well. So the quicker the fix is found and released that would be excellent.

**Comment by robotboy655** [comment] 2016-12-27 03:49
Should be fixed in Dev.

**Closed by robotboy655** 2016-12-27 03:49 UTC

**Comment by ThatGmodZServer** [comment] 2016-12-27 04:42
I understand it might be fixed in the Dev Branch, but when will that fix be released as that affects multiple servers that use HL2 ladders, the sooner that it's fixed the better.

**Comment by Kefta** [comment] 2016-12-27 04:42
What was the issue?

**Comment by xaviergmail** [comment] 2016-12-29 22:39
Is there anything we can do in Lua to help this issue in the meantime?

**Comment by robotboy655** [comment] 2016-12-29 23:17
No. It will be on prerelease in ~1 hour so you can get it.

**Comment by ThatGmodZServer** [comment] 2017-01-25 23:28
When will the next update be released? Or could this just come out sooner as a hotfix?
