### ISSUE TITLE
Crash when reusing IMesh in mesh.begin

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#4634] opened 2020-08-13 00:17 UTC
Something under the hood is getting corrupted/crashing when you re-use an IMesh in mesh.begin. Would be great to not have to destroy/create new IMesh each time, but seems not an option for now.

Attached some mdmps
[crashes.zip](https://github.com/Facepunch/garrysmod-issues/files/5066502/crashes.zip)

**Comment by robotboy655** [comment] 2020-09-02 09:19
Code to reproduce is always appreciated. None of those attached crashes appear anything to do with meshes at all.

**Comment by thegrb93** [comment] 2020-09-04 06:02
Pretty sure it was as simple as this, but I'll test again soon.

```lua
local m = Mesh()
hook.Add("HUDPaint","",function()
	mesh.Begin(m, MATERIAL_TRIANGLES, 1)
	mesh.Position(Vector(1, 1, 1))
	mesh.AdvanceVertex()
	mesh.Position(Vector(1, 0, 1))
	mesh.AdvanceVertex()
	mesh.Position(Vector(0, 0, 1))
	mesh.AdvanceVertex()
	mesh.End()

	m:Draw()
end)
```

**Comment by robotboy655** [comment] 2024-03-26 00:09
Sounds like duplicate of https://github.com/Facepunch/garrysmod-issues/issues/4592 but I am also fairly certain this was fixed.

**Closed by robotboy655** 2024-03-26 00:09 UTC
Labels: Bug, Crash
