### ISSUE TITLE
Entity:GetColor() not setting color metatable

### ISSUE THREAD

**Issue by ajloveslily14** [Facepunch/garrysmod-issues#3643] opened 2018-10-21 06:18 UTC
### Details
if you use entity:GetColor() the returned color does not have it's metatble set to the same one that Color() returns

This can be annoying if you add metamethods to the Color metatable and want to use them after using entity:GetColor()

### Steps to reproduce

- Run `PrintTable(getmetatable(Color(255,255,255)))`
- Notice metatable
- Spawn a prop
- Use color tool to change color of prop
- Run `PrintTable(getmetatable(LocalPlayer():GetEyeTrace().Entity:GetColor()))`
- Notice nothing gets printed because there is no metatable

**Comment by robotboy655** [comment] 2018-10-23 13:52
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/2407

**Closed by robotboy655** 2018-10-23 13:52 UTC
