### ISSUE TITLE
Vehicle Bug

### ISSUE THREAD

**Issue by djtb2924** [Facepunch/garrysmod-issues#3765] opened 2019-02-20 20:22 UTC
### Details
Tell us exactly what happens, every single detail that you can think of

Sometimes, in several servers, the vehicle's driver & the passengers are not in the vehicle, this is for all clients
![image](https://user-images.githubusercontent.com/26027040/53121764-3e95ae80-3555-11e9-8d18-b73c06fbb58a.png)

### Steps to reproduce
Be in a Vehicle, not related to VCMod or NovaCars

**Comment by thegrb93** [comment] 2019-02-20 20:49
I haven't seen this bug in ages. Maybe addon related (unless it is a result of the new update that I haven't seen yet)

**Comment by djtb2924** [comment] 2019-02-20 20:57
This isn't addon related, or its for all car's addon

**Comment by Kefta** [comment] 2019-02-20 21:08
Might be related to this: https://forum.facepunch.com/gmoddev/btvju/Next-Update-v9-October-2018-Update-is-live/8/#postcwqrvh

**Comment by djtb2924** [comment] 2019-02-20 21:47
Yes I think too, I didn't see that post

**Comment by robotboy655** [comment] 2019-02-22 13:43
So the issue here really is the weapons you use on your server, they are not ending lag compensation properly.

**Comment by ZehMatt** [comment] 2019-02-22 13:53
This happened to some people during streaming when they found themselves way behind their airboat. And players had no scripted weapons on them, so this might be not necessarily that. I believe this is happening during PVS transitioning where you have a lot of momentum and the update does something strange to your player.

**Comment by robotboy655** [comment] 2019-02-22 15:13
The player in the vehicle doesn't need to have a weapon, I just tested it and if anyone on the server using a weapon broken in this way, the players in a vehicle will get this problem.

**Comment by thegrb93** [comment] 2019-02-22 15:19
That screenshot is amazing btw

**Comment by ZehMatt** [comment] 2019-02-22 15:47
Like I stated previously in the comment, no scripted weapons were used during the gameplay, every weapon was the vanilla builtin one. I have scripted entities parented to players but I'm not sure they would relate to lag compensation.

**Comment by thegrb93** [comment] 2019-02-22 15:51
Anything that uses https://wiki.garrysmod.com/page/Player/LagCompensation

**Comment by thegrb93** [comment] 2019-02-22 15:54
Maybe
```lua
lua_run local p = FindMetaTable("Player") local f=p.LagCompensation p.LagCompensation=function(...) debug.Trace() return f(...) end
```
To see what's calling it.

**Comment by robotboy655** [comment] 2019-02-22 16:19
Whoever is affected, please try the Dev branch and see if it is fixed.

**Comment by ZehMatt** [comment] 2019-02-22 17:44
Always had a tough time reproducing it, I'll try to do it.

**Comment by VigiFyre** [comment] 2019-02-23 16:13
I've made a trap that would have caught a situation where LagCompensation(true) would have been called without LagCompensation(false) being called afterwards.
There wasn't a single catch, meanwhile players were sliding out of their seats right before my eyes.
I believe this has started happening after recent game update.

**Comment by ZehMatt** [comment] 2019-02-23 17:31
This happened for as long I can think, its nothing that was introduced recently. The first time this happened was about 2 years back when I first started my gamemode.

**Comment by VigiFyre** [comment] 2019-02-23 20:55
This is how the issue looks like: https://streamable.com/g8cf2
Couldn't pinpoint yet what exact combination causes this to happen.


> This happened for as long I can think, its nothing that was introduced recently. The first time this happened was about 2 years back when I first started my gamemode.

Mine has had players driving cars for several years now, and recently has been the first time i have ever seen players drifting out of their seats.


> Whoever is affected, please try the Dev branch and see if it is fixed.

Issue still happens on `-beta dev`, `VERSION 190222`.

**Comment by thegrb93** [comment] 2019-02-24 02:04
I just started playing on my server and I've noticed the bug too after never seeing it beforehand.

**Comment by mcNuggets1** [comment] 2019-02-25 22:59
I am getting a ton of reports lately either :s

**Comment by robotboy655** [comment] 2019-02-27 14:17
Well there's not much we can do without being able to reproduce it.

The only way to reproduce this (not ending the lag comp) was fixed on Dev, there must be some other cause for this which we are unaware of.

**Comment by Marxon1134** [comment] 2019-03-02 19:33
I can confirm that this happens independent of addons, simply moving fast in a laggy server desyncs the player position visually from the seat, and this is visible serverside by all players.

**Comment by djtb2924** [comment] 2019-03-08 13:23
@robotboy655 if you fixed it on the dev branch can you push that into the master branch, and make an hotfix please ? It's very embarrassing for roleplay.

Thanks

**Comment by robotboy655** [comment] 2019-03-08 15:30
According to people who tested it, it doesn't fix the problem.

Either way you can update your server to use the Dev branch and test yourself.

**Comment by djtb2924** [comment] 2019-03-08 15:33
> According to people who tested it, it doesn't fix the problem.
> 
> Either way you can update your server to use the Dev branch and test yourself.

It is retro-compatible ?

**Comment by robotboy655** [comment] 2019-03-08 16:26
Yes

**Comment by ZehMatt** [comment] 2019-03-20 19:53
Its still present. The problem lies on how lag compensation works and that players inside a vehicle will be moved back in time but the vehicle still moves forward so the stored position is no longer correct. There are two possible ways to fix this.
1. Move the player back into the vehicles seat after lag compensation is done.
2. Move the entire vehicle back in time instead of just the player.

**Comment by VigiFyre** [comment] 2019-03-21 07:45
Feels like something about lag compensation got changed in the Feb 18/19 update. Except this vehicle bug, we've also suddenly started seeing player complaints about bullets not hitting their targets

**Comment by ZehMatt** [comment] 2019-03-21 07:58
Bullets not hitting the targets has been always an issue since the client runs its own animation cycles and is not in sync with the server. Only CS:GO right now actually keeps every animation in sync with the server, we might see something good once x64 is done since its derived from the CS:GO branch now.

**Comment by VigiFyre** [comment] 2019-03-21 08:13
I mean, a lot of reports of the same thing came in right after the update was released. Like hit registration got worse. Not saying it's serious evidence, just giving all the info I have.

**Comment by ZehMatt** [comment] 2019-03-21 08:30
Well its hardly helping anyone reporting on an already broken thing, theres also an issue for this: #3683

**Comment by VigiFyre** [comment] 2019-03-21 08:40
I know it has been like that since forever. I'm saying it might have gotten worse. Now it's not just poses, now it's also player's origin position. I don't think you are reading my comments properly. Can we stop?

**Comment by thegrb93** [comment] 2019-03-23 22:54
Is there a lua fix for this meanwhile

**Comment by mcNuggets1** [comment] 2019-03-23 22:55
If we would have some reproduction code or footage to show the devs, we wouldn't need a lua fix...

**Comment by Kefta** [comment] 2019-03-23 22:55
You can apply a ``GetRenderOrigin`` hack to the players that are too far back in the vehicle. Getting an accurate seat position is the tricky part and differs between different vehicle addons already.

**Comment by thegrb93** [comment] 2019-03-23 22:59
It's probably CW2.0 then.

**Comment by thegrb93** [comment] 2019-03-23 23:02
Looks like it's turning on and off correctly though.

**Comment by thegrb93** [comment] 2019-03-23 23:02
However, it's doing it serverside and not clientside

**Comment by thegrb93** [comment] 2019-03-23 23:02
```lua
if CLIENT then
	function PLAYER:cw20LagCompensation(state)
		-- do nothing, since according to the wiki "Despite being defined shared, it (:LagCompensation) can only be used server side in a Predicted Hook." and we don't want to set up different code on client and server
	end
else
	PLAYER.cw20LagCompensation = PLAYER.LagCompensation -- use the LagCompensation code instead
end
```

**Comment by mcNuggets1** [comment] 2019-03-23 23:03
On my server this problem occured once, but then never again.
Right after the update released.

Please don't spam, I receive e-mails for all of your messages.

**Comment by thegrb93** [comment] 2019-03-23 23:05
There's a setting for that you know

**Comment by thegrb93** [comment] 2019-03-23 23:05
It happens so badly on my server that people can't tank battle

**Comment by mcNuggets1** [comment] 2019-03-23 23:06
Just EDIT your last message.
I wanna get notified for new answers, but not for a monologue.

**Comment by thegrb93** [comment] 2019-03-23 23:31
Seems to happen most commonly when players paste stuff with Advdupe2

**Comment by mcNuggets1** [comment] 2019-03-23 23:32
If you reconnect is the position still invalid?
Is the bug clientside or serverside only?

**Comment by thegrb93** [comment] 2019-03-23 23:35
[spidermans_swep.zip](https://github.com/Facepunch/garrysmod-issues/files/2999875/spidermans_swep.zip)
99% sure its this swep causing it

**Comment by mcNuggets1** [comment] 2019-03-23 23:36
3 minutes before it was Advdupe2.
This doesn't add up.

**Comment by thegrb93** [comment] 2019-03-23 23:36
Because it's chaos on my server. But we've pinpointed it now.

**Comment by mcNuggets1** [comment] 2019-03-23 23:37
Find the code which is causing it, so the devs can take a closer look.
Otherwise they might waste their time.

**Comment by thegrb93** [comment] 2019-03-23 23:38
I did. It's in that .zip I posted

**Comment by thegrb93** [comment] 2019-03-23 23:38
Didn't happen before the update btw

**Comment by mcNuggets1** [comment] 2019-03-23 23:40
This calls lag compensation as far as I can see every tick/frame.

**Comment by mcNuggets1** [comment] 2019-03-23 23:40
Wait, did you test on the DEV branch?

**Comment by thegrb93** [comment] 2019-03-23 23:42
The current release

**Comment by mcNuggets1** [comment] 2019-03-23 23:43
That's not the dev branch.
Your pinpointing was worth nothing.

**Comment by thegrb93** [comment] 2019-03-23 23:45
Uh no. They have reproduction now. Not worth nothing.

**Comment by thegrb93** [comment] 2019-03-23 23:45
[spidermans_swep.zip](https://github.com/Facepunch/garrysmod-issues/files/2999885/spidermans_swep.zip)

**Comment by mcNuggets1** [comment] 2019-03-23 23:46
They already fixed the problems with LagCompensation!
The fix is on the dev branch!!!

**Comment by thegrb93** [comment] 2019-03-23 23:47
Must be in dedicated server btw

**Comment by thegrb93** [comment] 2019-03-23 23:47
Release it already then

**Comment by mcNuggets1** [comment] 2019-03-23 23:48
I'm not a GMod-Dev, please.
Just put your server on the dev branch, it should be compatible, but I can't know.

**Comment by Kefta** [comment] 2019-03-23 23:52
55 comments for a fixed bug 🙏

**Comment by thegrb93** [comment] 2019-03-23 23:58
Doubt it's actually fixed but I'm not risking putting my server on dev to find out.

**Comment by mcNuggets1** [comment] 2019-03-24 00:00
There is no real risk.

**Comment by thegrb93** [comment] 2019-03-24 01:12
Still happens, but not nearly as much. That swep just makes it happen a shitton more when someone is using it.

Guessing it's a global bug with SetCompensation

**Comment by thegrb93** [comment] 2019-03-31 21:37
hook.Add("Think","fixchairs",function() for k, v in ipairs(player.GetAll()) do if v:GetParent():IsValid() then v:SetPos(Vector()) end end end)

if anyone needs a temperary fix

**Comment by djtb2924** [comment] 2019-04-18 15:29
Something new ?

**Comment by robotboy655** [comment] 2019-05-14 11:31
I am unable to reproduce the problem with the steps from #3835 

Do you get prediction errors with m_vecNetworkOrigin when this happens? (```cl_showerror 2```)

**Comment by ZehMatt** [comment] 2019-05-14 15:52
Have you ever considered just handling players in vehicles during prediction? When a player is inside a vehicle the position saved/restored must be relative to the vehicle/seat or whatever object the player is attached to, this probably also happens with parenting. The easiest would be to just ignore prediction when they are in such state as vehicles and any other non player entity is not predicted.

**Comment by djtb2924** [comment] 2019-05-17 15:42
> I am unable to reproduce the problem with the steps from #3835
> 
> Do you get prediction errors with `m_vecNetworkOrigin` when this happens? (`cl_showerror 2`)

Nope I didn't get any `m_vecNetworkOrigin`

**Comment by VigiFyre** [comment] 2019-05-22 06:41
The bug has ceased to happen after Apr update.

At least the one that appeared after Feb update, the one i believe this issue is about, judging by the date it was created (right after Feb update).

**Comment by djtb2924** [comment] 2019-05-22 08:22
Yes I think too

**Closed** 2019-05-22 08:22 UTC
