### ISSUE TITLE
Garry's Mod totally F*cked on MacBook Pro 2022 (M2, 12.5.1)

### ISSUE THREAD

**Issue by jadenquinn** [Facepunch/garrysmod-issues#5315] opened 2022-08-26 07:07 UTC
### Details
I tried using every beta Steam offers for Garry's mod, the only one that seemed to do anything is Chromium+64. The main menu does not show up at all, and I know I have no addons installed as I manually delete the workshops folder every time I try to launch, yes it's annoying :/ -  I've tried the CEF codec fix tool thing someone made - I tried -nochromium every time I tried anything new - I tried changing the resolution manually - I turned off "retina" on my MacBook and set the res to what is now native to the MacBook display - The CEF fix seemed to make everything worse though, I never even got to the title screen after using the fix tool. Heard about the tool here: https://github.com/Facepunch/garrysmod-issues/issues/5111
I also tried downloading Garry's Mod on my other MacBook that can natively run Gmod without F*ckery and copy the files gmod said it was missing in Terminal when I tried to manually launch it that way, and that aleived SOME of the errors in Terminal, but not all, and the game would STLL not get to the title screen.
Whenever it did get to the title screen though, there would not be an actual title screen, just the background images and the workshop progress indicator thing at the bottom.

I don't know what a permanent link is and I don't care right now frankly. You get my crashes via Google Drive as I've been trying to fix this all day: https://drive.google.com/drive/folders/1a85jPKUogs5OIj4n_Jpy7Pmq7fazrC1W?usp=sharing
Yes, I'm mad. That's just how life is sometimes.

### Steps to reproduce
Buy an M2 MacBook Pro - Download Steam - Download Garry's Mod - Launch the game.

**Comment by robotboy655** [comment] 2022-08-26 13:40
Apple Silicon macs are not officially supported, that being said, duplicate of #5001

**Closed by robotboy655** 2022-08-26 13:40 UTC
