### ISSUE TITLE
Missing Main Menu (OSX)

### ISSUE THREAD

**Issue by Ari-Memer** [Facepunch/garrysmod-issues#5470] opened 2023-05-31 16:40 UTC
Its in the tittle, the main menu is missing and I have no clue what to do. Verified integrity of files, reinstalled. Nothing has worked. I'm also on the x86 chromium version of the game (nochromeium launch options)

**Comment by robotboy655** [comment] 2023-05-31 17:29
`-nochromium` launch options is why its missing.

Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5001

**Closed by robotboy655** 2023-05-31 17:29 UTC
Labels: Platform: MacOS

**Comment by Ari-Memer** [comment] 2023-05-31 17:45
> `-nochromium` launch options is why its missing.
> 
> Duplicate of #5001

My game won't launch without `-nochromium`
Any other advice?
