### ISSUE TITLE
Clientside Ragdolls don't support flex (face posing)

### ISSUE THREAD

**Issue by NeatNit** [Facepunch/garrysmod-issues#2500] opened 2016-03-04 22:21 UTC
I'm posting this here in the blind hope that it would be an easy fix. Clientside Ragdolls, created with _Entity:BecomeRagdollOnClient_ or with _ClientsideRagdoll_, do not support flex. _Entity:HasFlexManipulatior_ returns **false**, and none of the flex functions do anything.

**Comment by robotboy655** [comment] 2016-03-04 22:37
Possible duplicate of #1779

**Comment by Kefta** [comment] 2018-07-30 15:57
Definitely a duplicate of #1779

**Closed** 2018-07-30 17:10 UTC
