### ISSUE TITLE
Switching to Grav Gun (whoops)

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3122] opened 2017-04-08 19:57 UTC
### Details
Switching to gravity gun is serverside called, but should be shared.
Prints a error in the console too.

### Steps to reproduce
Press phys_swap key.

**Comment by robotboy655** [comment] 2020-07-06 14:08
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/3151

**Closed by robotboy655** 2020-07-06 14:08 UTC
