### ISSUE TITLE
Custom / Appended ACTs do not regenerate on CLIENT when r_flushlod is called

### ISSUE THREAD

**Issue by KingDavidW** [Facepunch/garrysmod-issues#5759] opened 2024-02-29 00:18 UTC
### Details
If I mount animations onto a player with one of the animation bases that exist and I r_flushlod to refresh the models, the ACT list will update perfectly fine on the server, but it will be unchanged on the client.

If I'm on a locally hosted server this isn't an issue because that ACT list is one in the same, but once I go to a dedicated server I lose all my ACTs.

I have a strong belief that his is due to this little if statement in the activity list generation: https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/shared/animation.cpp#L140

There have been previous requests to add the ability to simply define ACTs ourselves (which would be cool and allow us to ensure activities are matched between server and client, though that may require the activities to be cleaned up after disconnect), but this is an immediate problem, and the last limitation imposed by the engine on this

### Steps to reproduce
Since there's no official way of doing animation mounting, here's what you can do:

1) Get an animation base: https://steamcommunity.com/workshop/filedetails/?id=2916561591
2) Get an animation extension: https://steamcommunity.com/sharedfiles/filedetails/?id=848953359
3) Print sequence info for one of the custom animations on server, then try the same on client

**Comment by KingDavidW** [comment] 2024-03-16 22:48
The March 14th update did not solve this issue:

## Client Output
```
] lua_run_cl PrintTable( Entity(1):GetSequenceInfo( Entity(1):LookupSequence( "b_idle" ) ) )
["activity"]	=	-1
["activityname"]	=	ACT_BB_B_IDLE
["actweight"]	=	1
["anims"]:
		[1]	=	1711
["bbmax"]	=	15.271691 11.668678 64.087021
["bbmin"]	=	-24.167732 -9.877677 0.483948
["cycleposeindex"]	=	0
["fadeintime"]	=	0.20000000298023
["fadeouttime"]	=	0.20000000298023
["flags"]	=	8193
["label"]	=	b_idle
["lastframe"]	=	0
["localentrynode"]	=	0
["localexitnode"]	=	0
["nextseq"]	=	0
["nodeflags"]	=	0
["numblends"]	=	1
["numevents"]	=	0
["pose"]	=	0
```

## Server Output
```
] lua_run PrintTable( Entity(1):GetSequenceInfo( Entity(1):LookupSequence( "b_idle" ) ) )
["activity"]    =       2081
["activityname"]        =       ACT_BB_B_IDLE
["actweight"]   =       1
["anims"]:
                [1]     =       1711
["bbmax"]       =       15.271691 11.668678 64.087021
["bbmin"]       =       -24.167732 -9.877677 0.483948
["cycleposeindex"]      =       0
["fadeintime"]  =       0.20000000298023
["fadeouttime"] =       0.20000000298023
["flags"]       =       12289
["label"]       =       b_idle
["lastframe"]   =       0
["localentrynode"]      =       0
["localexitnode"]       =       0
["nextseq"]     =       0
["nodeflags"]   =       0
["numblends"]   =       1
["numevents"]   =       0
["pose"]        =       0
```

Looking at a few older tickets, this seems to basically be the same issue as this, 10 years ago: https://github.com/Facepunch/garrysmod-issues/issues/1085#issuecomment-42175689

The specific line of code that needs to be addressed is: https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/shared/animation.cpp#L160

You can see the STUDIO_ACTIVITY flag being removed even if you look at the sequence info prints above.

**Comment by Yautja** [comment] 2024-03-27 02:54
It'd be great if this got fixed! Will solve a lot of issues I have on my own server.

**Comment by robotboy655** [comment] 2024-03-27 05:45
Can you provide a model that I can use to replicate the issue with?

**Comment by KingDavidW** [comment] 2024-03-27 07:22
I appreciate you taking a look at this. I'll do you one better, I've prepared something that should simulate what is happening. There are two console commands.

Because it uses model file manipulation to demonstrate it easier, you'll have an ADDONS folder and a DATA folder. Just drop them at your garrysmod folder. Incase anything goes wrong with the .MDL file, I've included a backup so you can just copy and rename back to robo.mdl

[wos_debuganim_for_robotboy.zip](https://github.com/Facepunch/garrysmod-issues/files/14769465/wos_debuganim_for_robotboy.zip)

Now you'll have two commands:
**execute_robo_patch_sv** for the serverside 
**execute_robo_patch_cl** for the clientside

You can run these on a dedicated server and you'll immediately see the behavior. Here's some pics from my run.

![image](https://github.com/Facepunch/garrysmod-issues/assets/40400837/165fb0e4-50e1-425c-a85c-23be09ae5125)
![image](https://github.com/Facepunch/garrysmod-issues/assets/40400837/a29acd48-5d59-42fa-a64f-3e051cb8dbeb)

If you need one for the listen server just add a RunLua print of the same sequence information after the flushlod. I doubt you need me to whip that up for you, but if you do just let me know.

**Comment by robotboy655** [comment] 2024-03-28 07:07
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/1085

Also it should now be fixed, but keep in mind that the generated IDs will not be identical between client and server, which is why I imagine this was made specifically to not work. We shall see if fixing this has any negative impact on the game.

**Closed by robotboy655** 2024-03-28 07:07 UTC

**Comment by KingDavidW** [comment] 2024-03-30 00:50
> Also it should now be fixed, but keep in mind that the generated IDs will not be identical between client and server, which is why I imagine this was made specifically to not work. We shall see if fixing this has any negative impact on the game.

Well it did fix the issue, and I can see exactly what you're mentioning. I was able to fill the BASE offset from server to client with some garbage ACTs and everything gets resync'd properly going forward, so that's great news.

My question is why does it desync? Are there client only ACTs being defined (like viewmodel ACTs maybe?). Just want to know if there's anything you can see easily on your end

**Comment by robotboy655** [comment] 2024-04-01 06:37
There's no networking done to sync it, so it obviously desyncs, as different amounts of models (different versions of models even) are loaded on different clients and the server itself, and in different order.
