### ISSUE TITLE
Error and ErrorNoHalt has very limited char count

### ISSUE THREAD

**Issue by roboderpy** [Facepunch/garrysmod-issues#2247] opened 2015-09-22 03:31 UTC
E.g. 
![2015-09-22_10-26_garry s mod](https://cloud.githubusercontent.com/assets/6339511/10010340/595d6924-6114-11e5-8e63-4964d5e34455.jpg)
Will result into 
![2015-09-22_10-26_garry s mod 2](https://cloud.githubusercontent.com/assets/6339511/10010343/64360cca-6114-11e5-80f4-d4d48e07250e.jpg)
![2015-09-22_10-32_ponyrp r 1 0 10 5 pred](https://cloud.githubusercontent.com/assets/6339511/10010409/4fe0c142-6115-11e5-9e9f-39b5d6f8602a.jpg)
That's forced me to replace this functions with mine, what have no this issue.
Replaced ErrorNoHalt by me:
![2015-09-22_10-28_garry s mod](https://cloud.githubusercontent.com/assets/6339511/10010364/acda211e-6114-11e5-8b67-506312cb12d5.jpg)
Will result into:
![2015-09-22_10-28_garry s mod 2](https://cloud.githubusercontent.com/assets/6339511/10010369/b88333b6-6114-11e5-8ab0-2aafe0d96ec0.jpg)
![2015-09-22_10-28_ponyrp r 1 0 10 5 -string](https://cloud.githubusercontent.com/assets/6339511/10010376/bd5decb4-6114-11e5-8ab7-6512d04dd1a9.jpg)
Default Lua 'error' have no issues
![2015-09-22_10-29_garry s mod](https://cloud.githubusercontent.com/assets/6339511/10010382/e1220ae0-6114-11e5-8b89-73d385b98876.jpg)
![2015-09-22_10-29_garry s mod 2](https://cloud.githubusercontent.com/assets/6339511/10010395/06ab4c22-6115-11e5-9244-77764b4f1f55.jpg)
![2015-09-22_10-29_ponyrp r 1 0 10 5 t](https://cloud.githubusercontent.com/assets/6339511/10010383/e1244b84-6114-11e5-8cb1-8f8285607a7a.jpg)

**Comment by Kefta** [comment] 2018-06-20 17:13
Semi-duplicate of https://github.com/Facepunch/garrysmod-requests/issues/668 - this is documented behaviour on the wiki

**Comment by thegrb93** [comment] 2018-06-20 17:14
Was wondering why stack trace was getting cut off in some cases

**Comment by robotboy655** [comment] 2019-04-03 13:38
Limit has been increased drastically.

**Closed by robotboy655** 2019-04-03 13:38 UTC
