### ISSUE TITLE
C_PhysPropClientside::Initialize: PhysModelParseSolid failed for entity -3.

### ISSUE THREAD

**Issue by WilliamVenner** [Facepunch/garrysmod-issues#4793] opened 2021-01-09 21:43 UTC
### Details
Sometimes, randomly, `ents.CreateClientProp` fails with the message:

```
C_PhysPropClientside::Initialize: PhysModelParseSolid failed for entity -3.
```

It will do this every time it's called with the same model until it's fixed by calling `util.PrecacheModel` to precache the model.

I am calling it using the model argument and not using SetModel.

Apparently this is not expected behaviour.

x86_64 branch

**Comment by robotboy655** [comment] 2021-01-09 22:41
Maybe post the actual models you are trying to use.

**Comment by Kefta** [comment] 2021-01-09 22:42
This is expected behaviour. The real request here is to separate the clientside and serverside model caches so that the model doesn't have to be cached on the server to use it on the client.

**Comment by WilliamVenner** [comment] 2021-01-09 22:43
Here's the model

```
models/hunter/plates/plate05x05.mdl
```

**Comment by robotboy655** [comment] 2021-01-11 16:37
Cannot reproduce this with that model. I can only reproduce this with a model that doesn't have a physics mesh, such as `models/Items/item_item_crate_dynamic.mdl`, which makes perfect sense.

Adjusted the message you reference to include the model name for debugging purposes.
```
] testent 
C_PhysPropClientside::Initialize: PhysModelParseSolid failed for model 'models/Items/item_item_crate_dynamic.mdl' @ index -3.
] testent 
] testent 
C_PhysPropClientside::Initialize: PhysModelParseSolid failed for model '<no model>' @ index -1.
```

Command I used to spawn models:
```
concommand.Add( "testent", function( ply )
	local plyTr = ply:GetEyeTrace()

	csEnt = ents.CreateClientProp( "models/hunter/plates/plate05x05.mdl" )
	csEnt:SetPos( plyTr.HitPos + plyTr.HitNormal * 24 )
	csEnt:Spawn()
end )
```

**Comment by WilliamVenner** [comment] 2021-01-11 18:47
Yes, it's quite random with no obvious cause. I cannot reproduce it myself, as it happens randomly.

However, since when it does happen, it happens every single time the prop is spawned, I was able to find that using `util.PrecacheModel` fixes it.

**Comment by robotboy655** [comment] 2021-01-11 18:50
Well if you could try to make it happen on Dev beta, maybe it will shed some light. Maybe there's a limit on dynamic model indices...?

**Comment by robotboy655** [comment] 2024-04-01 09:21
I think this should be fixed as of the March 2024 Patch.

**Closed by robotboy655** 2024-04-01 09:21 UTC
Labels: Cannot confirm
