### ISSUE TITLE
VPhysics entities fall through displacements

### ISSUE THREAD

**Issue by evilpigeonlol** [Facepunch/garrysmod-issues#4939] opened 2021-05-06 19:27 UTC
### Details
https://developer.valvesoftware.com/wiki/Entities_fall_through_displacements

This is basically what has been happening to me lately. I normally play on the 64-bit branch of the game, but switching to the dev branch or no branch doesn't make a difference. Verifying the cache does nothing. I've tried to run the game with -noaddons and -noworkshop without any difference. Altering gmod_physiterations does nothing. Regular Half-Life 2 doesn't have this problem at all. Just recently I reinstalled GMOD and it still hasn't fixed the issue.

### Steps to reproduce
Load up a map with displacements like d1_canals_03, on that map go to the first civil protection encounter in it. The ragdolls of the npcs, the falling floor grate and any other prop will have no collision with the displacement right below them. gm_construct_3 also has this problem.

**Comment by evilpigeonlol** [comment] 2021-05-06 20:57
![20210506225347_1](https://user-images.githubusercontent.com/83785196/117364471-3a4bd680-aebe-11eb-9620-4cd50050dee5.jpg)
![20210506225406_1](https://user-images.githubusercontent.com/83785196/117364478-3ae46d00-aebe-11eb-915f-1ddf2fc47a2f.jpg)
example on gm_construct_3 with -noaddons and -noworkshop

**Comment by MARK2580** [comment] 2021-05-06 22:12
Most likely this is a very old map that was compiled when such an error still existed. It was fixed sometime in 2012.

**Comment by evilpigeonlol** [comment] 2021-05-06 22:18
> Most likely this is a very old map that was compiled when such an error still existed. It was fixed sometime in 2012.

It happens on all maps with displacements

**Comment by MARK2580** [comment] 2021-05-06 22:37
> > Most likely this is a very old map that was compiled when such an error still existed. It was fixed sometime in 2012.
> 
> It happens on all maps with displacements.
> On that note I should mention that it used to be fine about a week ago, on this map and others.

This was my guess. I just went and checked out a few games. For starters, I checked canals_03, it really does fall through, just like canals_04.
Then I loaded one of the Epidose One maps and there the ragdolls fall through the displacement as well.
I also loaded the l4d2 and ep2 maps - there is no such problem.
Let's see what Rubat answers.

**Comment by evilpigeonlol** [comment] 2021-05-06 22:39
> > > Most likely this is a very old map that was compiled when such an error still existed. It was fixed sometime in 2012.
> > 
> > 
> > It happens on all maps with displacements.
> > On that note I should mention that it used to be fine about a week ago, on this map and others.
> 
> This was my guess. I just went and checked out a few games. For starters, I checked canals_03, it really does fall through, just like canals_04.
> Then I loaded one of the Epidose One maps and there the ragdolls fall through the displacement as well.
> I also loaded the l4d2 and ep2 maps - there is no such problem.
> Let's see what Rubat answers.

Thank you, I was worried it was just on my own end. By the way, I am absolutely certain it used to be fine last month because I played on the canals maps among others with displacements and I didn't notice this issue then.

**Comment by MARK2580** [comment] 2021-05-06 22:41
Here are screenshots from my side. Half-Life 2 and Episode Two.
![Half Life  Source Screenshot 2021 05 07 - 01 20 50 57](https://user-images.githubusercontent.com/11617079/117374178-5c9d1e80-aed5-11eb-9037-6dfadd57378e.jpg)
![Half Life  Source Screenshot 2021 05 07 - 01 20 55 53](https://user-images.githubusercontent.com/11617079/117374190-5f980f00-aed5-11eb-8b9a-28da0e2e1bbd.jpg)
![Half Life  Source Screenshot 2021 05 07 - 01 40 35 88](https://user-images.githubusercontent.com/11617079/117374198-6161d280-aed5-11eb-8050-f38a4bc44258.jpg)

**Comment by TW1STaL1CKY** [comment] 2021-05-07 08:19
I've been starting to have this happen on cs_office too, though strangely _only_ cs_office from the other CSS maps I've tested.
For example, de_nuke and de_inferno's displacements handle VPhysics objects fine.

**Comment by robotboy655** [comment] 2021-05-07 13:55
Specifically the problem is that the affected maps do not have the collision data for the displacements in them. (Lump 28)

**Comment by robotboy655** [comment] 2021-05-07 15:02
Should be fixed once it updates.

**Closed by robotboy655** 2021-05-07 15:02 UTC
