### ISSUE TITLE
Entity:FollowBone strangeness

### ISSUE THREAD

**Issue by LeQuackers** [Facepunch/garrysmod-issues#4821] opened 2021-02-05 05:40 UTC
Basically ```Entity:FollowBone``` causes the child model to jitter when the child model has attachments and the boneid is greater than zero.

Notes:
- ```Entity:SetPredictable``` doesn't appear to help
- models without attachments don't jitter
- setting the boneid to zero prevents jittering
- you can stack as many "good" models as you want with no jittering, but a single "bad" model will cause all of them to jitter

Setup 1:
- call ```StartGithubTest()```
- call ```GithubTest(i)``` as needed, where i is between 1 and 9 (1 through 5 do not jitter, 6 through 9 cause jitter)
- move spawned combine mine around

Setup 2:
- swtich to weapon_pistol
- call ```GithubWeaponTest(i)``` as needed, where i is between 1 and 9 (1 through 5 do not jitter, 6 through 9 cause jitter)
- move around

```
if SERVER then
	local testEnt = NULL
	function StartGithubTest()
		if IsValid(testEnt) then
			testEnt:Remove()
			for i, ent in ipairs(ents.FindByClass("github_test")) do ent:Remove() end
		end
		testEnt = ents.Create("prop_physics")
		testEnt:SetPos(Entity(1):EyePos())
		testEnt:SetModel("models/props_combine/combine_mine01.mdl")
		testEnt:Spawn()
	end
	


	local models = {
		-- these don't jitter
		"models/props_junk/watermelon01.mdl",
		"models/Roller.mdl",
		"models/props_combine/combine_mine01.mdl",
		"models/headcrabclassic.mdl",
		"models/humans/charple01.mdl",
		
		-- these do jitter
		"models/manhack.mdl",
		"models/Combine_turrets/Floor_turret.mdl",
		"models/player/monk.mdl",
		"models/props_combine/combinethumper001a.mdl"
	}
	
	
	
	function GithubTest(i)
		if not IsValid(testEnt) then return end
		
		local model = models[i] or models[1]
	
		local ent = ents.Create("github_test")
		ent:SetModel(model)
		ent:FollowBone(testEnt, 1)
		ent:SetLocalPos(vector_origin)
		ent:SetLocalAngles(angle_zero)
		ent:Spawn()
	end
	
	
	
	function GithubWeaponTest(i)
		local parent = Entity(1):GetViewModel()
		
		local model = models[i] or models[1]
	
		local ent = ents.Create("github_test")
		ent:SetModel(model)
		ent:SetModelScale(0.3)
		ent:FollowBone(parent, parent:LookupBone("ValveBiped.square"))
		ent:SetLocalPos(vector_origin)
		ent:SetLocalAngles(angle_zero)
		ent:Spawn()
	end
end



local ENT = {}

ENT.Type = "anim"

function ENT:Initialize()
	-- Entity:SetPredictable will cause jittering for models that work unless you cl_fullupdate
	-- as for models that do jitter it doesn't appear to do anything
	-- if CLIENT then self:SetPredictable(true) end
	self:SetNotSolid(true)
	self:SetMoveType(MOVETYPE_NONE)
	self:PhysicsDestroy()
end

scripted_ents.Register(ENT, "github_test")
```

**Comment by LeQuackers** [comment] 2021-02-06 01:25
After doing some more testing found out that removing the EFL_USE_PARTITION_WHEN_NOT_SOLID flag prevents jittering.
```
-- not sure if it has to be in a think function but this fixes it
function ENT:Think()
	self:RemoveEFlags(EFL_USE_PARTITION_WHEN_NOT_SOLID)
end
```

**Comment by LeQuackers** [comment] 2021-02-06 01:40
More testing/digging. I'm Very certain it is related to this:
https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/shared/collisionproperty.cpp#L1327-L1332
When the child model is solid or FSOLID_TRIGGER is set or EFL_USE_PARTITION_WHEN_NOT_SOLID is set, it jitters.

**Comment by LeQuackers** [comment] 2021-04-01 20:33
After doing some more testing it seems like ```Entity:FollowBone``` uses ```BaseAnimating::GetBonePosition``` internally, which is very likely the cause of all the issues. Using ```Entity:GetBoneMatrix``` (```BaseAnimating::GetBoneTransform```?) instead seems to fix the issues.

Setup:
- switch to pistol
- ```github_test``` in console
- move around

Notes:
- the red turret uses ```Entity:FollowBone``` (always jitters)
- the green turret alternates every one second between using ```Entity:GetBonePosition``` (matches ```Entity:FollowBone``` jitter perfectly) and ```Entity:GetBoneMatrix``` (works fine)

```
if SERVER then
	concommand.Add("github_test", function(ply, cmd, args)
		local parent = ply:GetViewModel()
		
		local model = "models/Combine_turrets/Floor_turret.mdl"
		local bone = parent:LookupBone("ValveBiped.square")
		
		local ent = ents.Create("github_test")
		ent:SetModel(model)
		ent:SetModelScale(0.3)
		ent:FollowBone(parent, bone)
		ent:SetLocalPos(vector_origin)
		ent:SetLocalAngles(angle_zero)
		ent:SetColor(Color(255, 0, 0))
		ent:Spawn()
		
		local ent = ents.Create("github_test")
		ent:SetModel(model)
		ent:SetModelScale(0.3)
		ent:TestFollowBone(parent, bone)
		ent:SetLocalPos(vector_origin)
		ent:SetLocalAngles(angle_zero)
		ent:SetColor(Color(0, 255, 0))
		ent:Spawn()
	end)
end



local ENT = {}

ENT.Type = "anim"

function ENT:Initialize()
	self:SetNotSolid(false)
	self:SetMoveType(MOVETYPE_NONE)
	self:PhysicsDestroy()
end


function ENT:GetBoneID() return self:GetDTInt(0) - 1 end
function ENT:SetBoneID(v) self:SetDTInt(0, v + 1) end
local function followBone(self, pos, ang)
	local parent = self:GetParent()
	
	if math.floor(CurTime()) % 2 == 1 then
		if CLIENT then parent:SetupBones() end
		local mat = parent:GetBoneMatrix(self:GetBoneID())
		return mat:GetTranslation(), mat:GetAngles() -- works great
	else
		if CLIENT then parent:SetupBones() end -- does nothing for Entity:GetBonePosition?
		return parent:GetBonePosition(self:GetBoneID()) -- jitters
	end
end
function ENT:TestFollowBone(parent, boneid)
	if parent and parent:IsValid() then
		self:SetParent(parent)
		self:SetBoneID(boneid)
	else
		self:SetParent(NULL)
		self:SetBoneID(-1)
	end
end
function ENT:Think()
	self.CalcAbsolutePosition = self:GetBoneID() > -1 and followBone or nil
end


scripted_ents.Register(ENT, "github_test")
```

**Comment by robotboy655** [comment] 2021-04-02 09:26
Possibly related or duplicate of https://github.com/Facepunch/garrysmod-issues/issues/4586

FollowBone uses `BaseAnimating::GetBoneTransform` internally.

**Comment by LeQuackers** [comment] 2021-04-02 16:44
Interesting, so what is ```Entity:GetBoneMatrix``` bound to?

Also quick fix if anyone needs it (doesn't work with the current github test because it overrides ```ENTITY:CalcAbsolutePosition```)
```
local meta = FindMetaTable("Entity")

local function followBone(self, pos, ang)
	local parent = self:GetParent()
	if CLIENT then parent:SetupBones() end
	local mat = parent:GetBoneMatrix(self:GetNW2Int("issue-4821.BoneID"))
	mat:Translate(self:GetLocalPos())
	mat:Rotate(self:GetLocalAngles())
	return mat:GetTranslation(), mat:GetAngles()
end

function meta:FollowBone(parent, boneid)
	if parent and parent:IsValid() then
		self:SetParent(parent)
		self:SetNW2Int("issue-4821.BoneID", boneid)
		self.CalcAbsolutePosition = followBone
	else
		self:SetParent(NULL)
		self:SetNW2Int("issue-4821.BoneID", -1)
		self.CalcAbsolutePosition = nil
	end
end

hook.Add("EntityNetworkedVarChanged", "issue-4821", function(self, name, old, new)
	if name == "issue-4821.BoneID" then
		self.CalcAbsolutePosition = new != -1 and followBone or nil
	end
end)
```

**Comment by robotboy655** [comment] 2021-04-05 11:38
The exact same thing on the server - `CBaseAnimating::GetBoneTransform`. On the client it uses `C_BaseAnimating::GetBone`

**Comment by LeQuackers** [comment] 2021-04-05 18:11
So how does ```Entity:FollowBone``` work internally then? Is the bulk of it in [```C_BaseEntity::GetParentToWorldTransform```](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/client/c_baseentity.cpp#L4297-L4306) with a check for ```EF_FOLLOWBONE``` or am I missing something?

**Comment by thegrb93** [comment] 2021-04-05 18:50
Probably related https://github.com/CapsAdmin/pac3/issues/894

**Comment by LeQuackers** [comment] 2021-04-06 13:18
The bone cache is FUBARed by ```Entity:FollowBone``` if it isn't set to 0.

github_test_1: control (works fine)
github_test_2: follow bone 0 (works fine)
github_test_3: follow attachment 1 (works fine)
github_test_4: follow bone 1 (spam from check)

```
if SERVER then
	local model = "models/combine_turrets/floor_turret.mdl"
	local function spawnParent()
		local ent = ents.Create("github_test")
		ent:SetModel(model)
		ent:PhysicsInit(SOLID_VPHYSICS)
		ent:Spawn()
		ent:PhysWake()
		return ent
	end
	
	concommand.Add("github_test_1", function(ply, cmd, args)
		spawnParent()
	end)
	
	concommand.Add("github_test_2", function(ply, cmd, args)
		local parent = spawnParent()
		
		local ent = ents.Create("github_test")
		ent:SetModel(model)
		ent:SetModelScale(0.3)
		ent:SetNotSolid(true)
		ent:SetMoveType(MOVETYPE_NONE)
		ent:FollowBone(parent, 0)
		ent:SetLocalPos(vector_origin)
		ent:SetLocalAngles(angle_zero)
		ent:SetColor(Color(255, 0, 0))
		ent:Spawn()
		
	end)
	
	concommand.Add("github_test_3", function(ply, cmd, args)
		local parent = spawnParent()
		
		local ent = ents.Create("github_test")
		ent:SetModel(model)
		ent:SetModelScale(0.3)
		ent:SetNotSolid(true)
		ent:SetMoveType(MOVETYPE_NONE)
		ent:SetParent(parent, 1)
		ent:SetLocalPos(vector_origin)
		ent:SetLocalAngles(angle_zero)
		ent:SetColor(Color(255, 0, 0))
		ent:Spawn()
	end)
	
	concommand.Add("github_test_4", function(ply, cmd, args)
		local parent = spawnParent()
		
		local ent = ents.Create("github_test")
		ent:SetModel(model)
		ent:SetModelScale(0.3)
		ent:SetNotSolid(true)
		ent:SetMoveType(MOVETYPE_NONE)
		ent:FollowBone(parent, 1)
		ent:SetLocalPos(vector_origin)
		ent:SetLocalAngles(angle_zero)
		ent:SetColor(Color(255, 0, 0))
		ent:Spawn()
	end)
end



local ENT = {}

ENT.Type = "anim"

function ENT:Think()
	for i = 0, self:GetBoneCount() - 1 do
		if CLIENT then self:SetupBones() end
		local pos, ang = self:GetBonePosition(i)
		local mat = self:GetBoneMatrix(i)
		
		if pos != mat:GetTranslation() or ang != mat:GetAngles() then
			print(self, self:GetParent(), "pos/ang different for bone " .. i)
			--print(pos, ang)
			--print(mat:GetTranslation(), mat:GetAngles())
		end
	end
end

scripted_ents.Register(ENT, "github_test")
```

**Comment by LeQuackers** [comment] 2021-04-10 05:14
I looked at this some more and I don't think ```C_BaseAnimating::GetBoneTransform``` is the right choice for ```Entity:FollowBone```/```Entity:GetBonePosition``` clientside because of all caching issues and should probably use ```C_BaseAnimating::GetBone``` instead. Attachments use ```C_BaseAnimating::GetBone``` in [```C_BaseAnimating::SetupBones_AttachmentHelper```](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/client/c_baseanimating.cpp#L2041-L2072) clientside, which was probably a conscious decision by Valve.

This is the only way I found to get ```Entity:FollowBone```/```Entity:GetBonePosition``` to work properly (probably because it [destroys the bone cache](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/client/c_baseanimating.cpp#L1071-L1091)):

```
if SERVER then
	concommand.Add("github_test", function(ply, cmd, args)
		local model = "models/Combine_turrets/Floor_turret.mdl"
		local bone = 2
		
		local parent = ents.Create("github_test")
		parent:SetModel(model)
		parent:PhysicsInit(SOLID_VPHYSICS)
		parent:Spawn()
		parent:PhysWake()
		
		local ent = ents.Create("github_test")
		ent:SetModel(model)
		ent:SetModelScale(0.3)
		ent:FollowBone(parent, bone)
		ent:SetLocalPos(vector_origin)
		ent:SetLocalAngles(angle_zero)
		ent:SetNotSolid(false)
		ent:SetMoveType(MOVETYPE_NONE)
		ent:Spawn()
		ent:PhysicsDestroy()
	end)
end



local ENT = {}

ENT.Type = "anim"

function ENT:Think()
	if CLIENT then
		local parent = self:GetParent()
		if parent:IsValid() then
			-- this does nothing?
			-- parent:InvalidateBoneCache()
			-- parent:SetupBones()
			
			local model = parent:GetModel()
			parent:SetModel("models/manhack.mdl")
			parent:SetModel(model)
		end
	end
end

scripted_ents.Register(ENT, "github_test")
```

**Comment by robotboy655** [comment] 2021-04-12 12:30
Unfortunately from my tests simply using `C_BaseAnimating::GetBone` on client makes it even worse, with the test above it is now "jittering"/lags behind at all times, but for all models in the original test.

**Comment by LeQuackers** [comment] 2021-04-12 15:09
Did you call ```SetupBones( NULL, -1, -1, gpGlobals->curtime );``` before ```C_BaseAnimating::GetBone```? lagging behind the parent sounds like my initial tests before I started using ```Entity:SetupBones``` before ```Entity:GetBoneMatrix```.

**Comment by LeQuackers** [comment] 2021-04-13 04:33
Okay, so in my tests the code below works and uses ```Entity:GetBoneMatrix``` (```C_BaseAnimating::GetBone```) without jittering or lagging. When you tested to see if ```C_BaseAnimating::GetBone``` would work, how did it differ from ```ENT:CalcAbsolutePosition``` below? Why does ```Entity:GetBoneMatrix``` (```C_BaseAnimating::GetBone```) work for the lua fix but not the c++ one?

```
if SERVER then
	concommand.Add("github_test", function(ply, cmd, args)
		local model = "models/Combine_turrets/Floor_turret.mdl"
		
		local parent = ents.Create("github_test")
		parent:SetModel(model)
		parent:PhysicsInit(SOLID_VPHYSICS)
		parent:Spawn()
		parent:PhysWake()
		
		local ent = ents.Create("github_test")
		ent:FollowBone(parent, 2)
		ent:SetLocalPos(vector_origin)
		ent:SetLocalAngles(angle_zero)
		ent:SetModel(model)
		ent:SetModelScale(0.3)
		ent:SetNotSolid(false)
		ent:SetMoveType(MOVETYPE_NONE)
		ent:Spawn()
		ent:PhysicsDestroy()
	end)
end



local ENT = {}

ENT.Type = "anim"

function ENT:CalcAbsolutePosition(pos, ang)
	if self:IsEffectActive(EF_FOLLOWBONE) then
		local parent = self:GetParent()
		if parent:IsValid() then
			if CLIENT then parent:SetupBones() end
			local mat = parent:GetBoneMatrix(self:GetParentAttachment())
			if mat then
				mat:Translate(self:GetLocalPos())
				mat:Rotate(self:GetLocalAngles())
				return mat:GetTranslation(), mat:GetAngles()
			end
		end
	end
	return pos, ang
end

scripted_ents.Register(ENT, "github_test")
```

**Comment by LeQuackers** [comment] 2021-04-13 04:45
This might not help but shouldn't [```CBoneCache::IsValid```](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/public/bone_setup.cpp#L193) check ```abs(curtime - m_timeValid) <= dt``` because prediction can rewind curtime?

**Comment by robotboy655** [comment] 2021-04-13 10:02
`SetupBones` does make it work (and so does forcing CBoneCache to be invalid at all times), but it's strange that the Lua binding doesn't use it and still works properly.

 I have applied the fix on Dev.

**Closed by robotboy655** 2021-04-13 10:02 UTC
