### ISSUE TITLE
Linux x86_64 build still fails

### ISSUE THREAD

**Issue by grepwood** [Facepunch/garrysmod-issues#5225] opened 2022-05-20 13:47 UTC
I had to create 2 symlinks in my games library, `/usr/local/games`, to get the game running:
```
/usr/local/games/steamapps/common/GarrysMod/bin/linux64/swiftshader/libGLESv2.so -> /usr/lib64/libGLESv2.so
/usr/local/games/steamapps/common/GarrysMod/bin/linux64/swiftshader/libEGL.so -> /usr/lib64/libEGL.so
```
Also that `swiftshader` directory is entirely missing so I had to create it too.

Afterwards, the game starts, but the menu isn't even there.

**Comment by robotboy655** [comment] 2022-05-30 12:48
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5096

**Closed by robotboy655** 2022-05-30 12:48 UTC
Labels: Duplicate
