### ISSUE TITLE
debugoverlay.* seems to be broken + debugoverlay.Sphere crashes, a dedicated server

### ISSUE THREAD

**Issue by RaphaelIT7** [Facepunch/garrysmod-issues#5483] opened 2023-06-20 19:11 UTC
### Details
If you join a dedicated server and try to use any of the debugoverlay functions, you will start to notice that they seem to do nothing.
If you use debugoverlay.Sphere it will crash the server.

#### debugoverlay.*
Run `developer 1` and then try to use any function, and you will notice that it seems like they do nothing / are broken.

#### debugoverlay.Sphere Crash
Run `developer 1`
and then run `lua_run debugoverlay.Sphere(Vector(0, 0, 0), 10, 5)`

**Comment by robotboy655** [comment] 2023-06-20 19:30
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5359

If I remember right, `debugoverlay` is not supported for networked clients, it's only supported for the listen server host.

**Closed by robotboy655** 2023-06-20 19:30 UTC
