### ISSUE TITLE
CSoundPatch/CreateSound crash

### ISSUE THREAD

**Issue by anyome** [Facepunch/garrysmod-issues#5120] opened 2021-12-23 17:14 UTC
Players tend to timeout when they Play on my server for no apparent reason.

They play, and they just "timeout" for no reason after 30-60 minutes of playing

https://i.imgur.com/jRj3BPY.png

here is the mdmp file: 
https://teamfrench.net/crash/hl2_211214_crash_2021_12_21T19_0_59C0.mdmp
&
https://teamfrench.net/crash/hl2_211214_crash_2021_12_23T18_22_10C0.mdmp

please can you help me, i'm running a big community and I never had this problem before !
Can anyone help me please?!

**Comment by anyome** [comment] 2021-12-23 17:40
here is the mdmp file: https://teamfrench.net/crash/hl2_211214_crash_2021_12_21T19_0_59C0.mdmp

**Comment by anyome** [comment] 2021-12-25 15:30
@robotboy655 Can you help please here is the most recent mdmp file: https://teamfrench.net/crash/hl2_211214_crash_2021_12_23T18_22_10C0.mdmp

**Comment by GitSparTV** [comment] 2021-12-25 15:44
Rubat is not your personal help service, and GitHub is not used for throwing crash dumps without any context.

Use Discord or email dumps to Rubat's email

**Comment by robotboy655** [comment] 2022-01-03 17:49
The crash is related to CSoundPatch/CreateSound sounds, I have seen a few reports of this since the update, any way to reproduce it on demand or any other info would be helpful.

**Comment by Andrew-Eathan** [comment] 2022-05-29 13:11
i think this has been happening on my server too, players would inexplicably simultaneously crash at random times, seems to have gone away at some point but i haven't ever been able to debug it because i never got the crashes myself

**Comment by robotboy655** [comment] 2024-03-22 17:15
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5809

**Closed by robotboy655** 2024-03-22 17:15 UTC
Labels: Crash
