### ISSUE TITLE
Garry's Mod doesn't clean lua scripts from other servers

### ISSUE THREAD

**Issue by GitSparTV** [Facepunch/garrysmod-issues#3854] opened 2019-05-17 23:33 UTC
Garry's Mod doesn't clean client settings, included lua scripts, addons, etc when user starts new singleplayer/2 player game if he played before on some multiplayer server.

Steps:
1. Join multiplayer server
2. Disconnect
3. Start new game (will do 2 step automatically)
4. All clients lua files will run while the user doesn't have their .gma / folder in **addons/** / subscription

This could throw lots of errors, especially for some exclusive anticheats.
Most critical effect happens when you connect to darkrp server, then move to singleplayer: (DarkRP is not installed on user's GMod):
![hl2_2019-05-18_02-22-54](https://user-images.githubusercontent.com/5685050/57961036-02d07200-7915-11e9-82ed-08501e4b87b0.png)

Version: 190430. Windows 64x

**Comment by biorisk2** [comment] 2019-05-19 10:01
this issue is soooooo annoying

**Comment by robotboy655** [comment] 2019-05-21 12:00
The engine error was fixed better this time, thanks for the specific steps to reproduce, the rest is duplicate of #3123 or #3465

**Closed by robotboy655** 2019-05-21 12:00 UTC
