### ISSUE TITLE
file.Exists is super slow when used with "LUA" path

### ISSUE THREAD

**Issue by wrefgtzweve** [Facepunch/garrysmod-issues#5674] opened 2023-12-31 17:30 UTC
After investigating long lua startup times when joining a server i've noticed that file.Exists( file, "LUA" ) seems to be incredibly slow
This was tested on 64x cl, seems to be the same on 32x servers though.

## My test:
```lua
print( "file.Exists LUA" )
print( file.Exists( "entities/sent_ball.lua", "LUA" ) )
local start = SysTime()
for i = 1, 100 do
    file.Exists( "entities/sent_ball.lua", "LUA" )
end
print( SysTime() - start )

print( "file.Exists GAME" )
print( tobool( file.Read( "lua/entities/sent_ball.lua", "GAME" ) ) )
local start = SysTime()
for i = 1, 100 do
    tobool( file.Read( "lua/entities/sent_ball.lua", "GAME" ) )
end
print( SysTime() - start )

print( "file.Read LUA" )
print( tobool( file.Read( "entities/sent_ball.lua", "LUA" ) ) )
local start = SysTime()
for i = 1, 100 do
    tobool( file.Read( "entities/sent_ball.lua", "LUA" ) )
end
print( SysTime() - start )

print( "file.Read GAME" )
print( tobool( file.Read( "lua/entities/sent_ball.lua", "GAME" ) ) )
local start = SysTime()
for i = 1, 100 do
    tobool( file.Read( "lua/entities/sent_ball.lua", "GAME" ) )
end
print( SysTime() - start )

local function fileExists( path, dir )
    local f = file.Open( path, "r", dir )
    if f then
        f:Close()
        return true
    end
    return false
end

print( "Custom file exist GAME" )
print( fileExists( "lua/entities/sent_ball.lua", "GAME" ) )
local start = SysTime()
for i = 1, 100 do
    fileExists( "lua/entities/sent_ball.lua", "GAME" )
end
print( SysTime() - start )

print( "Custom file exist LUA" )
print( fileExists( "entities/sent_ball.lua", "LUA" ) )
local start = SysTime()
for i = 1, 100 do
    fileExists( "entities/sent_ball.lua", "LUA" )
end
print( SysTime() - start )
```

### Small amount of addons, local dev server, clientside:
```
file.Exists LUA
true
0.69640199999998
file.Exists GAME
true
0.33176890000004
file.Read LUA
true
0.2955905
file.Read GAME
true
0.32984709999999
Custom file exist GAME
true
0.2006068
Custom file exist LUA
true
0.18350279999999
```

### Public dedicated prod server with addons, clientside:
```
file.Exists LUA
true
6.9172338000001
file.Exists GAME
true
0.35067989999993
file.Read LUA
true
0.31082429999992
file.Read GAME
true
0.33976000000007
Custom file exist GAME
true
0.2093010000001
Custom file exist LUA
true
0.18773499999998
```

Both tests were carried out on the same PC, do note that my `fileExists` likely cant be used as a drop in replacement for file.Exists as file.Read doesn't play nicely with lua files sometimes.

**Comment by Grocel** [comment] 2023-12-31 17:37
I can conform this with a similar but a quite faster result.

## Result
### Server
```
----------------------------

REALM:	SERVER
file.Exists LUA
true
0.069304200000033
file.Exists GAME
true
0.093234999999936
file.Read LUA
true
0.064957800000002
file.Read GAME
true
0.092480499999965
Custom file exist GAME
true
0.063004299999989
Custom file exist LUA
true
0.045790199999942

----------------------------
```

### Client

```
----------------------------

REALM:	CLIENT
file.Exists LUA
true
0.31779099999994
file.Exists GAME
true
0.092465199999992
file.Read LUA
true
0.065484999999967
file.Read GAME
true
0.092128900000034
Custom file exist GAME
true
0.064726500000006
Custom file exist LUA
true
0.045994599999972

----------------------------

PrintTable( debug.getinfo( file.Exists ) ):

currentline	=	-1
func	=	function: 0xdb993faa
isvararg	=	true
lastlinedefined	=	-1
linedefined	=	-1
namewhat	=	
nparams	=	0
nups	=	0
short_src	=	[C]
source	=	=[C]
what	=	C


PrintTable( debug.getinfo( file.Read ) ):

currentline	=	-1
func	=	function: 0xdded4a2a
isvararg	=	false
lastlinedefined	=	19
linedefined	=	4
namewhat	=	
nparams	=	2
nups	=	0
short_src	=	lua/includes/extensions/file.lua
source	=	@lua/includes/extensions/file.lua
what	=	Lua

----------------------------
```

## Test script
```lua
print("\n----------------------------\n")

print( "REALM:", SERVER and "SERVER" or "CLIENT")

print( "file.Exists LUA" )
print( file.Exists( "entities/sent_ball.lua", "LUA" ) )
local start = SysTime()
for i = 1, 100 do
    file.Exists( "entities/sent_ball.lua", "LUA" )
end
print( SysTime() - start )

print( "file.Exists GAME" )
print( tobool( file.Read( "lua/entities/sent_ball.lua", "GAME" ) ) )
local start = SysTime()
for i = 1, 100 do
    tobool( file.Read( "lua/entities/sent_ball.lua", "GAME" ) )
end
print( SysTime() - start )

print( "file.Read LUA" )
print( tobool( file.Read( "entities/sent_ball.lua", "LUA" ) ) )
local start = SysTime()
for i = 1, 100 do
    tobool( file.Read( "entities/sent_ball.lua", "LUA" ) )
end
print( SysTime() - start )

print( "file.Read GAME" )
print( tobool( file.Read( "lua/entities/sent_ball.lua", "GAME" ) ) )
local start = SysTime()
for i = 1, 100 do
    tobool( file.Read( "lua/entities/sent_ball.lua", "GAME" ) )
end
print( SysTime() - start )

local function fileExists( path, dir )
    local f = file.Open( path, "r", dir )
    if f then
        f:Close()
        return true
    end
    return false
end

print( "Custom file exist GAME" )
print( fileExists( "lua/entities/sent_ball.lua", "GAME" ) )
local start = SysTime()
for i = 1, 100 do
    fileExists( "lua/entities/sent_ball.lua", "GAME" )
end
print( SysTime() - start )

print( "Custom file exist LUA" )
print( fileExists( "entities/sent_ball.lua", "LUA" ) )
local start = SysTime()
for i = 1, 100 do
    fileExists( "entities/sent_ball.lua", "LUA" )
end
print( SysTime() - start )

print("\n----------------------------\n")

print("PrintTable( debug.getinfo( file.Exists ) ):\n")
PrintTable( debug.getinfo( file.Exists ) )

print("\n")

print("PrintTable( debug.getinfo( file.Read ) ):\n")
PrintTable( debug.getinfo( file.Read ) )

print("\n----------------------------")
```

**Comment by Grocel** [comment] 2024-01-03 01:31
Today I did a bit more research on that issue and oh boy I did not expect this result.

Apparently the performance slows down when you have many addon's installed in general. But it is at worst if the addon contain Lua files.

# Summery

This is what I found:
- The count of addons containing Lua files matter the most. On my system the effect start getting noticeable at around 150-200 addons.
- The total count of Lua files matter somewhat, but it's not that bad.
- A single addon with many Lua files, doesn't have much impact. I have tested an addon with 5000 valid unique shared Lua files.
- Many non-Lua addon (only containing a single sound file in this test) does not impact the performance.
- A non-Lua addon with many files 500k (30 GB) does not impact the performance.

The weirdest part I have found:
A server side only addon containing a Lua file still affects the clients performance, even though the client never downloads or runs the Lua file. The Lua files doesn't need to be run on the server to affect the performance. It just need to exist on the server.

## Setup

### Benchmark
See the scripts in above posts. I run them in a 1 sec `timer.Simple` delay to avoid hiccups after start ups and for a more consistent reading.

### addon generator scripts
To reproduce the issue I use a custom written batch script to generate and regenerate hundreds of addons with each containing a single unique Lua script and a sound file for testing the "non-lua cases".

Put this script below in the addons folder you want to test in as a `*.bat`-file and run it. It will tell you what it does. You may want to adjust script internal configs to test different cases. It should be safe to use, as I user error proved it quite a bit, but I still recommend to be careful on where you run it. I recommend to review and analyze the script before using.

```batch
@echo off

set basedir=%~dp0

rem Make sure you are in the addons directory
cd %basedir%

setlocal ENABLEDELAYEDEXPANSION


rem How many addons do you need?
set /A addonCount=500

echo This will create %addonCount% dummy addons.
set /P continueScript=Do you want to continue (Y/[N])?

IF /I "%continueScript%" NEQ "Y" GOTO FINISH


rem Insert the dummy script as serverside only script (1 = On, 0 = Off)
set /A serversideOnlyLua=1

rem Insert the dummy script as clientside only script (1 = On, 0 = Off)
set /A clientsideOnlyLua=0

rem Path of the dummy files to create, unwanted files can be removed by commenting them out
set luaPath=lua\autorun
set luaPathServerOnly=lua\autorun\server
set luaPathClientOnly=lua\autorun\client
set soundPath=sound\_test_addon_dummies


rem Prefix for addon folders
set addonPrefix=_test_addon_dummy_

rem Temporary file name for the sound file
set dummySoundFile=_dummy_sound.wav

rem copy of sound/synth/sine_1760.wav from wiremod
set dummySoundFileData= ^
52 49 46 46 B6 00 00 00 57 41 56 45 66 6D 74 20 ^
10 00 00 00 01 00 01 00 44 AC 00 00 88 58 01 00 ^
02 00 10 00 64 61 74 61 32 00 00 00 8E F5 10 E0 ^
91 CC 49 BC 3F B0 31 A9 92 A7 79 AB AC B4 94 C2 ^
54 D4 CF E8 BD FE BF 14 76 29 94 3B F9 49 BD 53 ^
44 58 46 57 D2 50 50 45 78 35 48 22 F2 0C 63 75 ^
65 20 1C 00 00 00 01 00 00 00 01 00 00 00 00 00 ^
00 00 64 61 74 61 00 00 00 00 00 00 00 00 00 00 ^
00 00 4C 49 53 54 34 00 00 00 61 64 74 6C 6C 74 ^
78 74 14 00 00 00 01 00 00 00 19 00 00 00 72 67 ^
6E 20 00 00 00 00 00 00 00 00 6C 61 62 6C 0C 00 ^
00 00 01 00 00 00 4C 6F 6F 70 20 30 31 00

rem Clean up old addons starting with _test_addon_dummy_ (%addonPrefix%)
echo.
echo Deleteing old dummy addons starting with %addonPrefix%* ...
for /d %%G in (%addonPrefix%*) do (
   rd /S /Q "%%~G" 2> nul
   echo Deleted addon %%~G
)

rem Config validation
set /A addLuaFile=1
set /A addSoundFile=1
set /A addCSLuaFile=1

if %serversideOnlyLua% EQU 1 (
   set luaPath=%luaPathServerOnly%
)

if %clientsideOnlyLua% EQU 1 (
   set luaPath=%luaPathClientOnly%
)

if "%luaPath%"=="" (
   set addLuaFile=0
)

if %addonCount% LEQ 0 (
   set addLuaFile=0
)

if "%soundPath%"=="" (
   set addSoundFile=0
)

if "%dummySoundFile%"=="" (
   set addSoundFile=0
)

if "%dummySoundFileData%"=="" (
   set addSoundFile=0
)

if %addonCount% LEQ 0 (
   set addSoundFile=0
)

if %serversideOnlyLua% EQU 1 (
   set addCSLuaFile=0
)

if %clientsideOnlyLua% EQU 1 (
   set addCSLuaFile=0
)

rem create dummy sound dummy file from hex
if %addSoundFile% EQU 1 (

   echo.
   echo Creating dummy sound file: !dummySoundFile!

   del /F /Q %dummySoundFile% 2> nul

   echo %dummySoundFileData%> %dummySoundFile%.tmp
   certutil -f -decodehex %dummySoundFile%.tmp %dummySoundFile% >nul
   del /F /Q %dummySoundFile%.tmp 2> nul
)

if %addLuaFile% NEQ 1 (
   if %addSoundFile% NEQ 1 (
      goto FINISH
   )
)

echo.
set /A addonsCreated=0

for /l %%x in (1, 1, %addonCount%) do (
   set fx=000000%%x
   set fx=!fx:~-5!

   set addonName=%addonPrefix%!fx!
   mkdir !addonName! 2> nul

   set /A addonsCreated=addonsCreated+1

   rem create the lua dummy file

   if %addLuaFile% EQU 1 (
      set folderAddonLua=!addonName!\%luaPath%

      mkdir !folderAddonLua! 2> nul

      set filename=!addonName!.lua
      set file=!folderAddonLua!\!filename!
      set fileOutput=!file:\=/!

      echo Creating file: !file!

      echo -- Dummyfile !fileOutput!>> !file!
      echo.>> !file!

      if %addCSLuaFile% EQU 1 (
         echo if SERVER then AddCSLuaFile^(^) end>> !file!
         echo.>> !file!
      )

      echo print^("!fileOutput!"^)>> !file!
      echo.>> !file!

      echo return true>> !file!

      echo.>> !file!
      echo.>> !file!
   )

   rem copy the sound dummy file

   if %addSoundFile% EQU 1 (
      set folderAddonSound=!addonName!\%soundPath%

      mkdir !folderAddonSound! 2> nul

      set filename=!addonName!.wav
      set file=!folderAddonSound!\!filename!

      echo Creating file: !file!

      copy /B /Y %dummySoundFile% !file! /B 1> nul
   )
)

if %addSoundFile% EQU 1 (
   del /F /Q %dummySoundFile% 2> nul

   echo.
   echo Deleted temp dummy sound file %dummySoundFile%
)

:FINISH

set /A addonsCreated=addonsCreated

cd %basedir%

echo.
echo %addonsCreated% addons created.

endlocal

echo Press any key to close.
pause > nul

@echo on
@exit /B 0
```

### Addon content
Each addon has content to ensure that the testing environment is as realistic as possible. The game can never see the addons as empty. They contain:

- A very short but valid sound file
- A short but valid Lua script that can be shared, clientside only or serverside only (default) depending on the config
- Each file is uniquely named to avoid internal conflicts
- Each Lua file has unique content to distinct operation during tests

Each lua looks similar to this. It varies a bit depending on config. Shared scripts are `AddCSLuaFile`'ed.
```lua
-- Dummyfile _test_addon_dummy_00496/lua/autorun/server/_test_addon_dummy_00496.lua

print("_test_addon_dummy_00496/lua/autorun/server/_test_addon_dummy_00496.lua")

return true
```

**Comment by Grocel** [comment] 2024-01-04 20:43
# Update

## Datapacks
After some discussion on GMod Discord I have found out that you can print out a list of networked datapacks using `datapack_paths` (cliendside only, sv_cheats).

```
] datapack_paths 
[...]
9. "addons/wire/lua/"
10. "addons/wire-extras/lua/"
11. "addons/_test_addon_dummy_00001/lua/"
12. "addons/_test_addon_dummy_00002/lua/"
13. "addons/_test_addon_dummy_00003/lua/"
14. "addons/_test_addon_dummy_00004/lua/"
15. "addons/_test_addon_dummy_00005/lua/"
16. "addons/_test_addon_dummy_00006/lua/"
17. "addons/_test_addon_dummy_00007/lua/"
18. "addons/_test_addon_dummy_00008/lua/"

[...]

494. "addons/_test_addon_dummy_00484/lua/"
495. "addons/_test_addon_dummy_00485/lua/"
496. "addons/_test_addon_dummy_00486/lua/"
497. "addons/_test_addon_dummy_00487/lua/"
498. "addons/_test_addon_dummy_00488/lua/"
499. "addons/_test_addon_dummy_00489/lua/"
500. "addons/_test_addon_dummy_00490/lua/"
501. "addons/_test_addon_dummy_00491/lua/"
502. "addons/_test_addon_dummy_00492/lua/"
503. "addons/_test_addon_dummy_00493/lua/"
504. "addons/_test_addon_dummy_00494/lua/"
505. "addons/_test_addon_dummy_00495/lua/"
506. "addons/_test_addon_dummy_00496/lua/"
507. "addons/_test_addon_dummy_00497/lua/"
508. "addons/_test_addon_dummy_00498/lua/"
509. "addons/_test_addon_dummy_00499/lua/"
510. "addons/_test_addon_dummy_00500/lua/"
511. "workshop/lua/"
512. "workshop/gamemodes/"
513. "lua/"
514. "gamemodes/"
515. "workshop/gamemodes/base/entities/"
516. "gamemodes/base/entities/"
517. "workshop/gamemodes/sandbox/entities/"
518. "gamemodes/sandbox/entities/"
```

We have found that `file.Exists` grows linearly by the size of the above list when run on a "LUA" path. If an addon has Lua files (even serverside only or not loaded/included), the server will network the path to the client and the client's `file.Exists` will iterate it on every call.

## Replacements for file.Exists
Today I noticed that `file.Exists` can't be replaced without sacrificing reliability on some cases. Using the function with the "GAME" path and using the custom function for checking a file existence will result in false negatives if the requested file is only available via `AddCSLuaFile()` on the client, e.g the file/addon not installed on said client.

So the original file.Exists can NOT be replaced: According to RaphaelIT7 on discord the function could be improved, though.
![grafik](https://github.com/Facepunch/garrysmod-issues/assets/2457653/e2ac4634-f64f-4113-8ebc-fc93fc9c81fb)
![grafik](https://github.com/Facepunch/garrysmod-issues/assets/2457653/4546781e-8181-410a-bfd4-58fdd2a317c5)

**Comment by brandonsturgeon** [comment] 2024-01-10 21:35
I know the established wisdom is to have as few addons as possible.

In our community, we opted to.. ignore this wisdom - but only in a way.
We have a standard _number_ of Lua files, but we keep our code very segmented. Each project is in its own addon directory.

This helps us with permission boundaries on the Github side of things, as well as letting us provide useful automatic update messages. It's also just a common practice in most development environments.

Doing it this way meant we paid a huge tax on startup time. I was okay with that, I thought it was a fair trade.

Now, though, it's clear that it's causing performance problems that can (in some cases) severely impact both player and server experience. That sucks a lot.

Am I supposed to automatically compile all of my addons into a single addon directory to "trick" the game into performing well?

Thanks for the thorough research and reporting @Grocel - Great work🥇

**Comment by InfHorus** [comment] 2024-01-11 00:09
What do you mean by can not be replaced by a lua function? I've made an alternative using file.Open & benched boths and the difference on LUA path is insane, when the alternative takes 0.07 seconds file.Exists takes 13 seconds

**Comment by Grocel** [comment] 2024-01-12 00:53
I have refreshed testing setup a bit and I have added 2 more cases for reproduction. In Total we have:
- [500 addons with a single Lua file each](https://gist.github.com/Grocel/add06eee1dc4f4435e9d2aa8e43b732e)
- [An addon with many non-Lua files (50k sounds)](https://gist.github.com/Grocel/7ab3bc42a129a37be62681d2db8afbbb)
- [An addon with many Lua files (5k shared scripts)](https://github.com/Facepunch/garrysmod-issues/files/13910126/_test_addon_many_luas.zip)

Both single addon cases have shown to have no or very little effect to the run times on `file.Exist` or other file IO operations.
My above post have been updated accordingly. I also updated the post to be a bit more clear.

**Comment by robotboy655** [comment] 2024-01-23 16:43
I have done some changes to address this, even though I don't even understand what scenario you'd want file.Exists for Lua path.

**Comment by Grocel** [comment] 2024-01-23 21:21
Thinks Rubat. I can confirm that the update increased the performance quite a lot, good work on that.

However I have found regression in `file.IsDir()`. It no longer finds directories added via `AddCSLuaFile()` on the client. I'm not sure if it is a trade off or an unintended mistake. `file.exists` works just fine and does not have that regression. The results has showen that the `file.Exists` was a bit slower on server after the update. Can anybody confirms this?


# Benchmark
I did the benchmark and using these scripts: https://gist.github.com/Grocel/f8eff1ba32f2ef0e46f91e0ae1a79c4f

The test were ran on a dedicated server with a locally connected client. All test were done on the main (`live`) and development (`dev`) branches. NOTE: The reported `BRANCH` in the files is `unknown` on both server versions.

## Result files
These are the raw results: [FileExistsBenchmark.zip](https://github.com/Facepunch/garrysmod-issues/files/14029732/FileExistsBenchmark.zip)


# Summary

## Supports AddCSLuaFile

| **Function**                    | **Search Path** | **supports AddCSLuaFile on main** | **supports AddCSLuaFile on dev** |
|---------------------------------|-----------------|-----------------------------------|----------------------------------|
| `file.Exists`                   | `LUA`           | Yes                               | Yes                              |
| `file.Exists`                   | `GAME`          | No                                | No                               |
| `file.IsDir`                    | `LUA`           | Yes                               | No                               |
| `file.IsDir`                    | `GAME`          | No                                | No                               |
| `tobool(file.Read())`           | `LUA`           | No                                | No                               |
| `tobool(file.Read())`           | `GAME`          | No                                | No                               |
| `Custom file exist (file.Open)` | `LUA`           | No                                | No                               |
| `Custom file exist (file.Open)` | `GAME`          | No                                | No                               |


## Timings

All timing values are given in milliseconds. They are the average runtimes of single function calls. Each function was called 100 times during the test.
All Addon cases are serverside only. The client doesn't have any addon beside some common ones. The cases with Lua files are serverside only without AddCSLuaFile().


### Case: No Addons

| **Function**                    | **Search Path** | **CLIENT on main** | **CLIENT on dev** | **SERVER on main** | **SERVER on dev** |
|---------------------------------|-----------------|--------------------|-------------------|--------------------|-------------------|
| `file.Exists`                   | `LUA`           | `1.0364`           | `0.1567`          | `0.4047`           | `0.4836`          |
| `file.Exists`                   | `GAME`          | `1.0426`           | `1.0406`          | `0.5041`           | `0.5811`          |
| `file.IsDir`                    | `LUA`           | `1.4552`           | `0.0392`          | `0.6885`           | `0.0118`          |
| `file.IsDir`                    | `GAME`          | `0.0132`           | `0.0135`          | `0.0102`           | `0.0096`          |
| `tobool(file.Read())`           | `LUA`           | `0.7416`           | `0.7423`          | `0.4327`           | `0.4890`          |
| `tobool(file.Read())`           | `GAME`          | `1.0515`           | `1.0656`          | `0.5151`           | `0.5582`          |
| `Custom file exist (file.Open)` | `LUA`           | `0.4848`           | `0.5254`          | `0.3321`           | `0.3389`          |
| `Custom file exist (file.Open)` | `GAME`          | `0.6806`           | `0.7283`          | `0.3972`           | `0.4200`          |


### Case: 500 Addons with a sound file

| **Function**                    | **Search Path** | **CLIENT on main** | **CLIENT on dev** | **SERVER on main** | **SERVER on dev** |
|---------------------------------|-----------------|--------------------|-------------------|--------------------|-------------------|
| `file.Exists`                   | `LUA`           | `1.0054`           | `0.1596`          | `0.6203`           | `0.7158`          |
| `file.Exists`                   | `GAME`          | `1.0359`           | `1.0382`          | `33.4058`          | `32.8321`         |
| `file.IsDir`                    | `LUA`           | `1.4262`           | `0.0394`          | `0.8444`           | `0.0292`          |
| `file.IsDir`                    | `GAME`          | `0.0132`           | `0.0133`          | `0.0268`           | `0.0268`          |
| `tobool(file.Read())`           | `LUA`           | `0.7317`           | `0.7412`          | `0.7017`           | `0.7473`          |
| `tobool(file.Read())`           | `GAME`          | `1.0483`           | `1.0855`          | `33.1853`          | `33.2276`         |
| `Custom file exist (file.Open)` | `LUA`           | `0.5153`           | `0.5275`          | `0.5433`           | `0.6368`          |
| `Custom file exist (file.Open)` | `GAME`          | `0.7138`           | `0.7270`          | `25.4823`          | `24.9065`         |


### Case: 500 Addons with a Lua file file and a sound file

| **Function**                    | **Search Path** | **CLIENT on main** | **CLIENT on dev** | **SERVER on main** | **SERVER on dev** |
|---------------------------------|-----------------|--------------------|-------------------|--------------------|-------------------|
| `file.Exists`                   | `LUA`           | `31.6935`          | `6.1780`          | `17.1791`          | `36.6961`         |
| `file.Exists`                   | `GAME`          | `1.0622`           | `1.0468`          | `36.7566`          | `37.0381`         |
| `file.IsDir`                    | `LUA`           | `32.1035`          | `0.5925`          | `17.7347`          | `0.0312`          |
| `file.IsDir`                    | `GAME`          | `0.0132`           | `0.0133`          | `0.0350`           | `0.0334`          |
| `tobool(file.Read())`           | `LUA`           | `0.7419`           | `0.7580`          | `36.3106`          | `36.5833`         |
| `tobool(file.Read())`           | `GAME`          | `1.0355`           | `1.0600`          | `36.1863`          | `36.7394`         |
| `Custom file exist (file.Open)` | `LUA`           | `0.5079`           | `0.5065`          | `28.2398`          | `28.2288`         |
| `Custom file exist (file.Open)` | `GAME`          | `0.7251`           | `0.7247`          | `28.5915`          | `29.0190`         |


# Conclusion

- In the slowest test `file.IsDir` was around **50x times faster** on client.
- In the slowest test `file.Exists` was around **5x times faster** on client.
- On the server `file.Exists` was about **2x times slower** on the worst case. Was that a fluctuation, or is it a regression?
- On the server `file.IsDir` was about **a whopping 550x times faster** in the slowest test. WTF?

**Comment by BullyHunter32** [comment] 2024-01-24 00:11
> Thinks Rubat. I can confirm that the update increased the performance quite a lot, good work on that.
> 
> However I have found regression in `file.IsDir()`. It no longer finds directories added via `AddCSLuaFile()` on the client. I'm not sure if it is a trade off or an unintended mistake. The function `file.exists` works just fine and does not have that regression. The results has showen that the `file.Exists` was a bit slower on server after the update. Can someone confirms this?
> 
> # Benchmark
> I did the benchmarks and tests using these scripts: https://gist.github.com/Grocel/f8eff1ba32f2ef0e46f91e0ae1a79c4f
> 
> The test were ran on a dedicated server with a locally connected client. All test were done on the main (`live`) and development (`dev`) branches. NOTE: The reported `BRANCH` in the files is `unknown` on both server versions.
> 
> ## Result files
> These are the raw results: [FileExistsBenchmark.zip](https://github.com/Facepunch/garrysmod-issues/files/14029732/FileExistsBenchmark.zip)
> 
> # Summary
> ## Supports AddCSLuaFile
> **Function**	**Search Path**	**supports AddCSLuaFile on main**	**supports AddCSLuaFile on dev**
> `file.Exists`	`LUA`	Yes	Yes
> `file.Exists`	`GAME`	No	No
> `file.IsDir`	`LUA`	Yes	No (regression or trade off)
> `file.IsDir`	`GAME`	No	No
> `tobool(file.Read())`	`LUA`	No	No
> `tobool(file.Read())`	`GAME`	No	No
> `Custom file exist (file.Open)`	`LUA`	No	No
> `Custom file exist (file.Open)`	`GAME`	No	No
> ## Timings
> All timing values are given in milliseconds. They are the average runtimes of single function calls. Each function was called 100 times during the test. All Addon cases are serverside only. The client doesn't have any addon beside some common ones. The cases with Lua files are serverside only without AddCSLuaFile().
> 
> ### Case: No addons
> **Function**	**Search Path**	**CLIENT on main**	**CLIENT on dev**	**SERVER on main**	**SERVER on dev**
> `file.Exists`	`LUA`	1.0364	0.1567	0.4047	0.4836
> `file.Exists`	`GAME`	1.0426	1.0406	0.5041	0.5811
> `file.IsDir`	`LUA`	1.4552	0.0392	0.6885	0.0118
> `file.IsDir`	`GAME`	0.0132	0.0135	0.0102	0.0096
> `tobool(file.Read())`	`LUA`	0.7416	0.7423	0.4327	0.4890
> `tobool(file.Read())`	`GAME`	1.0515	1.0656	0.5151	0.5582
> `Custom file exist (file.Open)`	`LUA`	0.4848	0.5254	0.3321	0.3389
> `Custom file exist (file.Open)`	`GAME`	0.6806	0.7283	0.3972	0.4200
> ### Case: 500 addons with a sound file
> **Function**	**Search Path**	**CLIENT on main**	**CLIENT on dev**	**SERVER on main**	**SERVER on dev**
> `file.Exists`	`LUA`	1.0054	0.1596	0.6203	0.7158
> `file.Exists`	`GAME`	1.0359	1.0382	33.4058	32.8321
> `file.IsDir`	`LUA`	1.4262	0.0394	0.8444	0.0292
> `file.IsDir`	`GAME`	0.0132	0.0133	0.0268	0.0268
> `tobool(file.Read())`	`LUA`	0.7317	0.7412	0.7017	0.7473
> `tobool(file.Read())`	`GAME`	1.0483	1.0855	33.1853	33.2276
> `Custom file exist (file.Open)`	`LUA`	0.5153	0.5275	0.5433	0.6368
> `Custom file exist (file.Open)`	`GAME`	0.7138	0.7270	25.4823	24.9065
> ### Case: 500 addons with a Lua file file and a sound file
> **Function**	**Search Path**	**CLIENT on main**	**CLIENT on dev**	**SERVER on main**	**SERVER on dev**
> `file.Exists`	`LUA`	**31.6935**	**6.1780**	**17.1791**	**36.6961** (?)
> `file.Exists`	`GAME`	1.0622	1.0468	36.7566	37.0381
> `file.IsDir`	`LUA`	**32.1035**	**0.5925**	**17.7347**	**0.0312** (?)
> `file.IsDir`	`GAME`	0.0132	0.0133	0.0350	0.0334
> `tobool(file.Read())`	`LUA`	0.7419	0.7580	36.3106	36.5833
> `tobool(file.Read())`	`GAME`	1.0355	1.0600	36.1863	36.7394
> `Custom file exist (file.Open)`	`LUA`	0.5079	0.5065	28.2398	28.2288
> `Custom file exist (file.Open)`	`GAME`	0.7251	0.7247	28.5915	29.0190
> # Conclusion
> * In the slowest test `file.Exists` was around **5x times faster** on client.
> * In the slowest test `file.IsDir` was around **50x times faster** on client.
> * On the server `file.Exists` was about **2x times slower** on the worst case. Was that a fluctuation, or is it a regression?
> * On the server `file.IsDir` was about **a whopping 550x times faster** in the slowest test. WTF, is this real?
> * Other the stuff seems to be rather unremarkable or insignificant.

file.Exists has support for `*` wildcards, your custom implementation does not however.

**Comment by robotboy655** [comment] 2024-01-24 13:42
Wildcard search for `file.Exists` in `LUA` paths was not intentional, and cannot remain if this performance improvement is desired to stay.

I am also not seeing `file.IsDir` issue reported where it does not support `AddCSLuaFile()`'d files clientside. In my tests it does.
![image](https://github.com/Facepunch/garrysmod-issues/assets/3299036/d6cccb91-45e9-4989-b094-dae130d88bb8)


I am able to reproduce slower `file.Exists` on `LUA` serverside, but only in the extreme case of 500 single file addons.

Perhaps file.Find and file.Exists scale differently with the amount of mounted paths for some reason.

**Comment by Grocel** [comment] 2024-01-24 14:20
> I am also not seeing `file.IsDir` issue reported where it does not support `AddCSLuaFile()`'d files clientside. In my tests it does.

Please make sure the file does not actually exist as a physically file on the client. A dedicated server is needed to test it properly. If tested on a local server the file would be reported to be existing, because if the actual file physically existing, not because it has been transferred via AddCSLuaFile().

**Closed** 2024-01-24 15:51 UTC
Labels: Bug, Regression
