### ISSUE TITLE
A .lua file w/ capital letters containing a tool => in multi player mode, the hooks are not called on the server side

### ISSUE THREAD

**Issue by cristian-spiescu** [Facepunch/garrysmod-issues#6078] opened 2024-11-16 21:56 UTC
### Steps to reproduce

A file name such as ...\lua\weapons\gmod_tool\stools\POITool.lua`, containing e.g.

```lua
TOOL.Category = "My categ"
TOOL.Name = "POI Tool"
TOOL.Command = nil
TOOL.ConfigName = ""

function TOOL:LeftClick(tr)
	print("poi tool: left click")
	if(CLIENT) then return true end
end
```

in multi player mode, will output this:

![Image](https://github.com/user-attachments/assets/e7524d93-75a1-40aa-b212-0efdcaef7aea)

I.e. the event handler is **NOT** invoked on server.

If I change the name of the file to `...\poitool.lua`, then the handler is also invoked on the server side. Hence the console prints orange and blue.

**Comment by NathanX-S** [comment] 2024-11-18 05:53
This is expected behavior.

**Comment by robotboy655** [comment] 2024-11-20 15:09
Will be fixed, although you really should have all your files lowercase because that's a requirement for Steam Workshop uploading anyway.

**Closed by robotboy655** 2024-11-20 15:09 UTC
