### ISSUE TITLE
GetSequenceActivity() does not see the sequence ACT id on the client ?

### ISSUE THREAD

**Issue by Feromon32** [Facepunch/garrysmod-issues#5796] opened 2024-03-15 13:51 UTC
### Details

On the local server everything works fine, client and server see the act id, but if I run a dedicated server, the client act id of the animation I want always returns "-1", although GetSequenceActivityName() returns the correct name

### Steps to reproduce

console output:
![gmod_HA5fEwQXD2](https://github.com/Facepunch/garrysmod-issues/assets/65503900/c0c614f1-dd32-4fe8-80c9-57dc8abfeea6)

code:
![gmod_8EHQFCDa1V](https://github.com/Facepunch/garrysmod-issues/assets/65503900/9b86dd7d-178a-4a66-8b41-7be638b99e05)

qc:
![sublime_text_IyLy90djKY](https://github.com/Facepunch/garrysmod-issues/assets/65503900/b24a07f0-f74a-4471-a879-563e310bdc39)

**Comment by robotboy655** [comment] 2024-03-28 07:05
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5759

**Closed by robotboy655** 2024-03-28 07:05 UTC
