### ISSUE TITLE
Unexpected crashing after July 2024 Update

### ISSUE THREAD

**Issue by Andrekan1** [Facepunch/garrysmod-issues#5964] opened 2024-08-04 12:10 UTC
### Details
I was playing on dedicated server (updated to July Update) with addon [Trolleybus System](https://steamcommunity.com/sharedfiles/filedetails/?id=1909642310), after the update game keeps crashing no matter what.
I tried every possible solution on site: https://support.facepunchstudios.com/hc/en-us/articles/213577689-Common-start-up-Problems-and-Solutions

Such as:
- Verifying Game Cache Integrity
- Uninstall or exit programs that are known to cause problems (Disabling discord overlay)
- Forcing windowed mode (Running always in Borderless windowed) 
- Turning down "Texture Detail" and "Model Detail" in the Advanced Video Options.

Also tried to change gmod to x86-64 branch, similiar result was seen (game crashed).

### Steps to reproduce
1. Add this addon [Trolleybus System](https://steamcommunity.com/sharedfiles/filedetails/?id=1909642310)
2. Disable 64bit branch version
3. Load on any map and spawn bunch of Trolleybus Entities
4. Monitor RAM usage of the game (on 32bit its limit before crash is 1.5GB)
5. Try to enable 64bit branch and repeat steps 3 and 4 (limit before crash is 2.1GB)

[GarrysMod_32bit_crashdump.zip](https://github.com/user-attachments/files/16487426/GarrysMod_32bit_crashdump.zip)
[GarrysMod_64bit_crashdump.dmp](https://github.com/user-attachments/files/16487449/49683817-5695-43b0-b184-be14d48b7182.dmp)

**Comment by robotboy655** [comment] 2024-08-05 12:26
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5959

**Comment by robotboy655** [comment] 2024-08-05 14:52
I have found a sound-related crash with your steps, simply by spawning in `trolleybus_ent_trolza5265` but it doesn't appear to be the crash you are experiencing.

I have tried spawning every single vehicle from that addon, and there's no crash nor does the memory usage go above 1GB.

I will put the fix for the crash I found to `dev` and `x86-64` betas, please let me know if that fixes the issues you are having.

**Comment by robotboy655** [comment] 2024-08-08 14:49
I am assuming the issue is solved due to the silence.

**Closed by robotboy655** 2024-08-08 14:49 UTC
Labels: Duplicate, Crash
