### ISSUE TITLE
Maps still sending over fastdl when gma is mounted

### ISSUE THREAD

**Issue by stickz** [Facepunch/garrysmod-issues#2951] opened 2016-12-06 04:27 UTC
### Details
When I mount a map pack from workshop on my gameserver, it sends to clients like normal. However, sometimes the map will also send over fastdl, even if the gma is already downloaded and mounted.

### Steps to reproduce
The best way to reproduce this issue is to setup a dedicated server with a map-pack of multiple maps mounted. Then change level to that map and disconnect after you've loaded in. It's critical to make sure the bsp file is NOT inside your game client's map folder before continuing. Afterwards use the steam://connect/ip:port handle to directly connect to said server. (same as 'join friend' via steam)

It may be useful to mention the map is inside the server's map folder. And the following command is run after initializing a gamemode, to mount the workshop add-on. `resource.AddWorkshop("811812938") `

**Comment by stickz** [comment] 2016-12-06 04:41
I wonder if this is related to #2948 or not. It's highly possible that 'Fetching Subscriptions' is still spinning up when connecting to said server, because my game loads really fast on my hardware.

**Comment by Jake3231** [comment] 2016-12-09 18:08
That's a good thought. What kind of hardware do you have that makes it load so fast?

**Comment by stickz** [comment] 2016-12-09 20:11
My loading times are mainly CPU bound due two solid state drives in a raid 0 (stripe) configuration. I don't think this information is very relevant to this problem though.

**Comment by robotboy655** [comment] 2017-04-23 21:10
Duplicate of #1660

**Closed by robotboy655** 2017-04-23 21:10 UTC
