### ISSUE TITLE
blacklist +voicerecord from being run by lua scripts

### ISSUE THREAD

**Issue by rikkaaaaaaa** [Facepunch/garrysmod-issues#5037] opened 2021-08-24 08:37 UTC
### Details
an unfortunately common and somewhat well-known practice with malicious servers is the use of the lua concommand apis to send "+voicerecord" to players in order to simulate pressing their talk bind, transmitting their voice without their consent (and potentially without their knowledge, since the voice hud could be silently hidden from the user). quite frankly, i see absolutely no legitimate use whatsoever for lua scripts being able to run this command, and i think it should be blacklisted.

this issue presently exists in all branches of the game to my knowledge, but i am currently on the x64 branch.

### Steps to reproduce
```
-- clientside
RunConsoleCommand("+voicerecord")
```
![image](https://user-images.githubusercontent.com/48163728/130584804-a0e152c9-cd45-453f-96f2-595beeb752b0.png)

**Comment by Kefta** [comment] 2021-08-24 13:18
Can't be done without breaking TTT.

**Comment by Kefta** [comment] 2021-08-24 13:19
Also duplicate of https://github.com/Facepunch/garrysmod-requests/issues/896.

**Closed** 2021-08-24 13:19 UTC
Labels: Duplicate

**Comment by rikkaaaaaaa** [comment] 2021-08-24 13:47
apologies, i didnt even think to check garrysmod-requests because i thought of this as more a bug than a feature
