### ISSUE TITLE
Crash when calling ent:Remove on an entity that is being crazy physics defused.

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#3877] opened 2019-06-11 01:09 UTC
Basically two entities got crazy physics removed together at the same time, one of them had a DeleteOnRemove on the other and the game crashed. I have a really easy reproduction method if you want to work on it.

**Comment by thegrb93** [comment] 2019-06-11 01:16
Was actually ENT:OnRemove() that led to the other entity being ent:Remove() but I doubt that matters.

**Comment by thegrb93** [comment] 2019-06-11 01:17
I should also mention the two entities were constrained together.

**Comment by thegrb93** [comment] 2019-06-11 01:17
[hl2_190430_crash_2019_6_11T1_4_7C0.zip](https://github.com/Facepunch/garrysmod-issues/files/3274366/hl2_190430_crash_2019_6_11T1_4_7C0.zip)

**Comment by thegrb93** [comment] 2019-06-11 19:39
Maybe just mark stuff being diffused for deletion so that Remove() doesn't do anything to them?

**Comment by robotboy655** [comment] 2019-06-12 12:26
What do you think ent:Remove() does? It marks an entity for deletion.

It is possible the crash is caused by the constraints, wouldn't be the first time, unfortunately the dump is useless and only points to vphysics.dll for which we do not have symbols.

It is also possible it just crashes because of crazy physics regardless of anything else, the crazy physics defusion is not flawless.

If you can reproduce this, try the x64 branch - the 64bit client specifically, it has a different vphysics build.

**Comment by thegrb93** [comment] 2019-06-12 17:23
Why would the lua stack be inside ent:Remove() when it crashes if all it does is mark for deletion? I think you're probably wrong.

**Comment by thegrb93** [comment] 2019-06-12 17:26
Didn't @willox write the crazy physics defuser? What do you think?

**Comment by robotboy655** [comment] 2019-06-12 18:25
Good question.

ent:Remove() uses a separate queue, not the Source Engine one, for reasons only Garry knows.

Unfortunately I cannot see what exactly in `Entity,Remove` is running at the moment of the crash because VS will not allow me to look at it without vphysics symbols, but its most likely the code that makes the entity non solid. How reliably can you reproduce this crash, if at all?

**Comment by willox** [comment] 2019-06-12 18:30
I came to the same conclusion. Maybe more could be found a bunch of work, but if it can be reproduced on x86-64 everything should go more smoothly.

**Comment by thegrb93** [comment] 2019-06-12 18:45
I have an easy reproduction method, I'll send it to your github e-mail when I get home.

**Comment by thegrb93** [comment] 2019-06-13 00:39
Sent to the e-mail on your profile. I don't see one for @robotboy655 but I'm assuming @willox can just forward it if he wants it.

**Comment by robotboy655** [comment] 2019-06-14 15:22
Yeah it crashes deep in vphysics (IVP) when calling `CollisionRulesChanged`, not sure if this can be fixed without killing physics objects on all crazy physics entities before removing them, and even then I am not sure it will work.

**Comment by thegrb93** [comment] 2019-06-16 23:26
Anything that would fix it would be good. This seems to be one of the only few cases where crazy physics defusal will fail.

I imagine thrusters and other entities that deleteOnRemove would have the same problem

**Comment by robotboy655** [comment] 2019-06-18 17:25
Ok I think I managed to fix this particular case.

**Comment by thegrb93** [comment] 2019-06-18 17:25
Badass

**Closed by robotboy655** 2019-06-18 17:25 UTC
Labels: Dependency:vphysics, crash
