### ISSUE TITLE
d2_prison_08 crash clients.

### ISSUE THREAD

**Issue by kem008** [Facepunch/garrysmod-issues#2904] opened 2016-11-05 18:56 UTC
### Details
I tried it manytimes when all lights get off or combine_soldier throw flare.
I cant understand which cause crash. But I know before all lights get off.

[Link mdmp](https://www.dropbox.com/s/gnr8xq5ek3ntc2m/hl2_161029_crash_2016_11_5T18_30_27C0.mdmp?dl=0)

### Steps to reproduce
select map open d2_prison_08 and go forward and u will get a huge crash.
I used srcds as a server.

**Comment by robotboy655** [comment] 2016-11-05 21:45
Duplicate of #2786

**Closed by robotboy655** 2016-11-05 21:45 UTC
Labels: crash

**Comment by kem008** [comment] 2016-11-05 21:49
ah sry. thats why it was similar.
