### ISSUE TITLE
GNU/LINUX GMOD 64 BIT BROKEN - AGAIN --- HERES A FIX

### ISSUE THREAD

**Issue by GabenCrying** [Facepunch/garrysmod-issues#5206] opened 2022-04-20 18:53 UTC
https://github.com/solsticegamestudios/GModCEFCodecFix/

ALSO UNBAN ME FROM THE COMMUNITY HUB, I HAD TO SPAM 1000 POSTS LAST TIME TO GET 64  BIT FIXED ON GNU/LINUX

https://steamcommunity.com/id/freebsd/    - Mr.Weegeeman

**Comment by GitSparTV** [comment] 2022-04-20 19:27
It won't be merged due to the license conflicts

**Comment by robotboy655** [comment] 2022-04-21 07:16
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5092

**Closed by robotboy655** 2022-04-21 07:16 UTC

**Comment by GabenCrying** [comment] 2022-07-29 19:01
> It won't be merged due to the license conflicts

can you please unban my account, i had to mass spam to get 64 bit working on gnu/linux a few years ago but i miss being albe to upload screenshots/comment on anythinbg garrrysmod
