### ISSUE TITLE
Loading CSGO map in Singleplayer Causes a Engine ERROR

### ISSUE THREAD

**Issue by Not-Anatrax** [Facepunch/garrysmod-issues#4035] opened 2019-10-23 17:00 UTC
Details:
When i join dz_sirocco ( New  Dangerzone map ) I start loading in then a error pops up while im joining my own singleplayer game.
Steps to reproduce:

Step 1: Load up gmod.
Step 2: Join a singleplayer match for the CSGO map Sirocco ( dz_sirocco )
Step 3: gmod crashes

![Engine error](https://user-images.githubusercontent.com/38396226/67416577-92482280-f623-11e9-884c-5173621872af.png)

**Comment by robotboy655** [comment] 2019-10-23 17:05
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/1257

**Closed by robotboy655** 2019-10-23 17:05 UTC
