### ISSUE TITLE
Recent update to x64 branch eliciting malware detection

### ISSUE THREAD

**Issue by B-Xerxes** [Facepunch/garrysmod-issues#4062] opened 2019-11-15 16:43 UTC
![image](https://user-images.githubusercontent.com/6752026/68959735-90a6f000-07c6-11ea-89ad-575ff89ad2a0.png)
![image](https://user-images.githubusercontent.com/6752026/68959806-b9c78080-07c6-11ea-879a-bfb85eb5c96b.png)

The first screenshot appeared after adding an exception in the antivirus software
This is only occurring with the 64 bit executable and doesn't occur with the 32 bit executable in the same branch

**Comment by robotboy655** [comment] 2019-11-15 16:57
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/4060

**Closed by robotboy655** 2019-11-15 16:57 UTC
