### ISSUE TITLE
Broken animations on models from Portal 2 engine branch

### ISSUE THREAD

**Issue by DeffOS** [Facepunch/garrysmod-issues#5928] opened 2024-07-04 14:37 UTC
### Details
Models from Portal 2 engine branch loosing or incorrectly read animation data causing error and additive tpose
This bug doesn't occur in HLMV

``Warning! 'player/ballbot/ballbot.mdl' animation requested bone 88, but model only has 64! (x10)``
![image](https://github.com/Facepunch/garrysmod-issues/assets/68462654/de6af380-7887-4b1b-b499-9e2904d5b3c5)

### Steps to reproduce
1.In spawn menu open Edit icon on `models/player/ballbot/ballbot.mdl`
2.Select any animation
3.Be amazed

**Comment by DeffOS** [comment] 2024-07-04 14:38
Looks like https://github.com/Facepunch/garrysmod-issues/issues/5114 is related

**Comment by robotboy655** [comment] 2024-07-04 16:36
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5218

**Closed by robotboy655** 2024-07-04 16:36 UTC
