### ISSUE TITLE
Driver still shifts away from their vehicle (via proppushing)

### ISSUE THREAD

**Issue by CaptainPRICE** [Facepunch/garrysmod-issues#3835] opened 2019-05-01 05:07 UTC
### Details
Version 30.04.2019 (April update)

![screenshot](https://user-images.githubusercontent.com/9789070/57006195-183c6100-6bdf-11e9-8860-a9b9d6946277.png)

I'm not sure if the following has anything to do with this issue:
"Switched Lag Compensation back to local coordinates from absolute ones to fix vehicle seat position shifting"

### Steps to reproduce
1. Have your friend enter the vehicle/seat.
2. Physgun 'prop-push' the seat, do it hard (`physgun_wheelspeed 10000`)!
3. See your friend player will start to shift away from the seat.

**Comment by thegrb93** [comment] 2019-05-01 06:56
This happens with any parented entity and has been forever.

**Comment by robotboy655** [comment] 2019-05-14 08:59
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/3765

**Closed by robotboy655** 2019-05-14 08:59 UTC

**Comment by thegrb93** [comment] 2019-05-14 14:30
It's not a duplicate. I think its a precision issue when physics go crazy, parented children get shifted.
