### ISSUE TITLE
Wrong OBBMaxs()/OBBMins() calculation on players.

### ISSUE THREAD

**Issue by LazInSpace** [Facepunch/garrysmod-issues#2387] opened 2016-01-15 10:01 UTC
When using SetModelScale on players, hull doesn't change, that's why i need to apply SetHull and SetHullDuck after this. But when i did it, i get OBB values much too small than it must be.
It seems like this thing takes the values of hull and multiply with ModelScale.
```
] rcon lua_run player.GetAll()[1]:SetHull( Vector(-0.4064,-0.4064,0), Vector(0.4064,0.4064,1.8288))
> player.GetAll ( ) [1] : SetHull ( Vector ( -0.4064,-0.4064,0 ) , Vector ( 0.4064,0.4064,1.8288 ) )...
] rcon lua_run player.GetAll()[1]:SetModelScale( 0.0254, 0)
> player.GetAll ( ) [1] : SetModelScale ( 0.0254, 0 )...
] rcon lua_run PrintTable(player.GetAll()[1]:GetPhysicsObject():GetMesh())
> PrintTable ( player.GetAll ( ) [1] : GetPhysicsObject ( ) : GetMesh ( ) )...
1:
		pos	=	-0.406400 0.406400 1.828800
...
] rcon lua_run print(player.GetAll()[1]:OBBMaxs())
> print ( player.GetAll ( ) [1] : OBBMaxs ( ) )...
0.010323 0.010323 0.046452
] rcon lua_run print(player.GetAll()[1]:OBBMins())
> print ( player.GetAll ( ) [1] : OBBMins ( ) )...
-0.010323 -0.010323 0.000000
```

**Comment by robotboy655** [comment] 2016-01-15 11:14
Duplicate of #2231

**Closed by robotboy655** 2016-01-15 11:14 UTC
