### ISSUE TITLE
Driver bone don't affect flex controller on fly

### ISSUE THREAD

**Issue by Kpyxa** [Facepunch/garrysmod-issues#5895] opened 2024-06-09 08:22 UTC
I made a custom playermodel with corrective flexes for leg bending.
Flexes Are Drived with driver bone, in HLMV they work perfectly fine, but in game they don't work, but if i strip weapons or choose fists, they start to freaking out.
If i use ManipulateBonePosition command on driver bone, the flexes actually change it's state, meaning they work, but only if i change  driver bone state myself, but in video you can see how driver bone is actually moving.

The video from game: https://youtu.be/I6ppVm9yqS0
The video from HLMV: https://youtu.be/ug2ysv18IlQ

Version of the game from 2024.03.21

**Comment by Kpyxa** [comment] 2024-07-04 09:51
> Can you link a model for testing? Does it work when it is a ragdoll? Or in the spawnmenu icon preview with the same animations?
Compiled model with QC: https://drive.google.com/file/d/18hP6OjPZ6NpZsvWkK0WLdL4bMRvlrbPw/view?usp=sharing
Nope, it doesn't work on ragdoll, and nope, doesn't work in preview.

**Comment by robotboy655** [comment] 2024-07-04 16:16
Ok, thanks, I think I got it fixed.

It's hard for me to tell whether it's doing what it's supposed to, but the flex values are now are being set to non 0 values in-game.

The changes will be live on `x86-64` beta within a few minutes, please test and let me know if it works properly or not.

I was unable to reproduce the buggy behavior of the flexes getting random values, so I don't know what's up with that.

I also fixed a few crashes with HLMV that your model exposed, so there's also that.

Apparently also duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5054

**Closed by robotboy655** 2024-07-04 16:16 UTC
Labels: Bug, Duplicate
