### ISSUE TITLE
Entity:SetNWEntity("string",nil) does not network to clients

### ISSUE THREAD

**Issue by joeyjumper94** [Facepunch/garrysmod-issues#3655] opened 2018-10-30 01:49 UTC
### Details
Tell us exactly what happens, every single detail that you can think of
calling SetNWEntity from the serverside with nil as the second argument will not network to clients
### Steps to reproduce
Tell us how to reproduce the problem, step by step
from the console run these commands
lua_run player.GetAll()[1]:SetNWEntity("test",player.GetAll()[1])
lua_run print(player.GetAll()[1]:GetNWEntity("test",NULL):IsValid())--prints true
lua_run_cl print(player.GetAll()[1]:GetNWEntity("test",NULL):IsValid())--prints true

lua_run player.GetAll()[1]:SetNWEntity("test",nil)
lua_run print(player.GetAll()[1]:GetNWEntity("test",NULL):IsValid())--prints false
lua_run_cl print(player.GetAll()[1]:GetNWEntity("test",NULL):IsValid())--prints true, oddly enough

lua_run player.GetAll()[1]:SetNWEntity("test",NULL)
lua_run print(player.GetAll()[1]:GetNWEntity("test",NULL):IsValid())--prints false
lua_run_cl print(player.GetAll()[1]:GetNWEntity("test",NULL):IsValid())--prints false
### other
i discovered this issue when i was working on the drag mechanism or a handcuff swep

**Comment by bigdogmat** [comment] 2018-10-30 02:16
Every type is like this, you can't set them to nil and have it get networked.

**Comment by Kefta** [comment] 2018-10-31 08:01
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/3397.

**Closed** 2018-10-31 14:31 UTC
