### ISSUE TITLE
BadSetLocalOrigin serverside console

### ISSUE THREAD

**Issue by matiasg90** [Facepunch/garrysmod-issues#3168] opened 2017-04-25 08:46 UTC
### Details
Bad SetLocalOrigin ( ) on gmod_hands
https://i.gyazo.com/0e246e2e24a03d8efc30315ce8059a08.png
https://i.gyazo.com/86beff9942fd2a4c4e554e925b66553e.png

### Steps to reproduce
Changing weapons (darkrp+custom map)

https://facepunch.com/showthread.php?t=1394674
https://facepunch.com/showthread.php?t=1526947
https://facepunch.com/showthread.php?t=1402400

**Comment by robotboy655** [comment] 2017-04-25 08:57
Duplicate of #1184

**Closed by robotboy655** 2017-04-25 08:57 UTC
