### ISSUE TITLE
Typo in RichText Context Menu

### ISSUE THREAD

**Issue by A1steaksa** [Facepunch/garrysmod-issues#5940] opened 2024-07-13 20:15 UTC
## The Issue
When right-clicking on a `RichText` panel,  the context menu says "C&opy" instead of "Copy".

![image](https://github.com/user-attachments/assets/19f72910-d4d1-48cd-a4f3-7fc732d68e23)

## Repro
```lua
if not CLIENT then return end

concommand.Add( "richtext_test", function()
    local frame = vgui.Create( "DFrame" )
    frame:SetSize( 400, 200 )
    frame:Center()
    frame:MakePopup()

    local richtext = vgui.Create( "RichText", frame )
    richtext:Dock( FILL )
    richtext:AppendText( "This is a RichText panel!" )
end )
```

**Comment by robotboy655** [comment] 2024-07-15 17:54
Kinda duplicate of https://github.com/Facepunch/garrysmod-issues/issues/3981

But also fixed now.

**Closed by robotboy655** 2024-07-15 17:54 UTC
