### ISSUE TITLE
Immediate Crash-to-Desktop on Launch in OSX (as of March Patches)

### ISSUE THREAD

**Issue by scnce** [Facepunch/garrysmod-issues#5193] opened 2022-03-23 00:00 UTC
As of the two recent March patches, the game crashes to desktop after being launched in OSX. It launches, gets to the Facepunch screen, finishes loading there, then crashes. I tried a full uninstall, wipe, and reinstall of the game and it still happens. I tested this after both the March 10th patch and the Match 17th patch and the results were the same. I'm a little bit tech-illiterate in this specific area, so I apologize if I can't offer more insight or be more helpful. The crash report that OSX gave me included the following:

```
Crashed Thread:        0  AwesomiumBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [0]
```

I can email the rest of the report as a txt file if you believe it to be necessary.

**Comment by Jake3231** [comment] 2022-03-29 01:46
Is this on macOS Monterey? If so, it's a possible dupe of https://github.com/Facepunch/garrysmod-issues/issues/5001.

**Comment by jadenquinn** [comment] 2022-08-26 07:27
> Is this on macOS Monterey? If so, it's a possible dupe of #5001.

Yes but there's nothing useful in #5001

**Comment by robotboy655** [comment] 2022-10-13 11:58
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5001

**Closed** 2022-10-13 11:58 UTC
Labels: Platform: MacOS, Crash
