### ISSUE TITLE
Server browser loading servers in weird order

### ISSUE THREAD

**Issue by willcurry** [Facepunch/garrysmod-issues#5411] opened 2023-02-20 11:56 UTC
### Details
Since around 2 weeks ago the server browser has been displaying/loading in servers in a weird order. I am based in the UK and before all UK servers would load in and be displayed first. Now South America, Australian and American servers load in first and UK servers don't load in for a while (1-3 minutes). Its almost loading them in alphabetical order (Argentina, Australia, Brazil, Chile). This is happening to people from all over Europe. I am on the Chromium branch. 

This coupled with servers spoofing their ping (e.g. USA servers showing 10 ping to EU clients) is creating a massively unfair advantage and harming a lot of EU servers.

I know its probably on Valves end but the issue is still persisting after 2 weeks so thought to make a report here.

### Steps to reproduce
Open the server browser from the EU and look what servers load first.

![image](https://user-images.githubusercontent.com/11460313/220099715-3cf5d058-c444-4b13-b4ea-2c0b6de849af.png)

**Comment by robotboy655** [comment] 2023-02-20 14:04
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5405

**Closed by robotboy655** 2023-02-20 14:04 UTC
