### ISSUE TITLE
x86 x64 Branch new update Crash

### ISSUE THREAD

**Issue by TheLuMasters** [Facepunch/garrysmod-issues#6088] opened 2024-11-21 21:06 UTC
Crash only in x86/x64 Branch / Tested in singleplayer and not only me its happening

### Details
Since the updated the x86/x64 branch version, my game has been crashing.

### Steps to reproduce
Shooting a weapon and then the game crash

Files Atacched Dumps and console.log

[3de996a2-a244-40df-84c8-0f1fb2212995.txt](https://github.com/user-attachments/files/17851989/3de996a2-a244-40df-84c8-0f1fb2212995.txt)
[0226dfed-f737-4580-b97c-5495718d428c.txt](https://github.com/user-attachments/files/17851993/0226dfed-f737-4580-b97c-5495718d428c.txt)
[b4e17c6a-b2be-4774-b3d7-79abe3341824.dmp](https://github.com/user-attachments/files/17851990/b4e17c6a-b2be-4774-b3d7-79abe3341824.dmp)
[0226dfed-f737-4580-b97c-5495718d428c.dmp](https://github.com/user-attachments/files/17851991/0226dfed-f737-4580-b97c-5495718d428c.dmp)
[b4e17c6a-b2be-4774-b3d7-79abe3341824.txt](https://github.com/user-attachments/files/17851995/b4e17c6a-b2be-4774-b3d7-79abe3341824.txt)
[3de996a2-a244-40df-84c8-0f1fb2212995.dmp](https://github.com/user-attachments/files/17851994/3de996a2-a244-40df-84c8-0f1fb2212995.dmp)
[console.log](https://github.com/user-attachments/files/17851992/console.log)

**Comment by TheLuMasters** [comment] 2024-11-21 21:27
Here you have in zip file [Files.zip](https://github.com/user-attachments/files/17852197/Files.zip)

**Comment by MagentaIris** [comment] 2024-11-21 22:08
This is happening to me as well.

Trying to launch Temporal Assassin, 2 Player Local Server on 64 Bit causes an out of memory error for some reason, This never used to happen before the update about an hour ago.

![Image](https://github.com/user-attachments/assets/344b6616-d77b-4dfa-97f6-95cba21e7695)

For reproduction, here's Temporal Assassin: https://steamcommunity.com/sharedfiles/filedetails/?id=3258426988&searchtext=temporal+assassin

**Comment by RandomHuman2020** [comment] 2024-11-22 03:28
after investigating this problem a bit myself it seems to be related to VRAM, as the amount of used VRAM on my GPU (it's a 3060 with 12 gigs) gets nearly to 100% until the game is closed by the error message's OK button![Image](https://github.com/user-attachments/assets/241875eb-738a-475d-9de7-ceb236aa9547)

**Closed** 2024-11-22 13:19 UTC
Labels: Crash, Regression
