### ISSUE TITLE
Garry's Mod Crashes in Sandbox whenever I or another Player dies 

### ISSUE THREAD

**Issue by Truegamer5** [Facepunch/garrysmod-issues#1718] opened 2015-01-03 04:14 UTC
So for some reason, recently, whenever I start up a Garry's Mod single player sandbox game, or when I play with my friends using Hamachi when I host the server, I join the game and my player has no skin, it's just this black figure with no hands and kinda looks like SCP 106 from SCP Containment Breach. Then if that's not bad enough, any time my character dies, or is about to die, no matter the means, either suicide, being shot, fall damage the game just freezes for a second or two then just force quits to desktop. I realize this is probably an addon issue, however I've uninstalled my most recently installed addons but still nothing, and I don't want to manually uninstall each of them one by one. Here is my most recent crash log
http://dumps.metastruct.uk.to/dumper.py?dump=hl2_140713_crash_2015_1_3T2_58_57C0.mdmp&key=bQ8SxXjuCih-TD47u36zLeTL3NqKvDKKVDjw39eqqP1eJBYX9Hc9RRZFHyxgjMX4Gu_shuKgPjTubiJhjCbgk9_2MuiQbY9R-00Q1Tv0fzwI0jb-lLwqnDmdUNaK9YNttcHrtHtdVv38K_d3-7nHfOuKvzl66Kq8bTt8MrSJ5Uc=

Any help would be appreciated and I thank you in advance

**Comment by robotboy655** [comment] 2015-01-03 04:20
Duplicate of #932

Something on your server fucks up the player models. You are getting a shitton of Lua errors in your console. ( SLV and GMod legs ). Figure it out.

**Closed by robotboy655** 2015-01-03 04:20 UTC
