### ISSUE TITLE
x86-64 update: no steam overlay on Linux

### ISSUE THREAD

**Issue by LiamDawe** [Facepunch/garrysmod-issues#4127] opened 2020-01-13 22:02 UTC
Testing out the new x86-64 branch on Steam, that has 64bit and Chromium, there's now no Steam Overlay.

Fine other than that so far.

Full system info: https://pastebin.com/vhfjTN98

Whatever other info/tests you need, let me know. Happy to help.

**Comment by robotboy655** [comment] 2020-01-14 03:44
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/3925 and https://github.com/Facepunch/garrysmod-issues/issues/4058

**Closed by robotboy655** 2020-01-14 03:44 UTC
Labels: duplicate, linux
