### ISSUE TITLE
DTextEntry Multiline Freeze

### ISSUE THREAD

**Issue by MinIsMin** [Facepunch/garrysmod-issues#3257] opened 2017-07-31 09:00 UTC
@LightPrismHD [reported an issue in a different repository](https://github.com/Tommy228/TTTDamagelogs/issues/263) which freezes GarrysMod until the end of time when typing specific text into `DTextEntry` if Multiline is enabled.

### Steps to reproduce
Create a [DTextEntry](https://wiki.garrysmod.com/page/Category:DTextEntry) which size is longer than the text (see below), set `SetMultiline(true)` and write with lua `SetText()` something like this into it (with ~20 spaces before '[any words]'):

```
"o o f                             [any words]"
"b o o                               [any words]"
"b o                                  [any words]"
```
These formats do not work:
```
"test                             [any words]"
```

Example code (**Will freeze your Gmod client!**):

```
local frame = vgui.Create( "DFrame" )
frame:SetSize( 400, 200 )
frame:Center()
frame:MakePopup()
local TextEntry = vgui.Create( "DTextEntry", frame )
TextEntry:SetPos( 25, 50 )
TextEntry:SetSize( 100, 300 )
TextEntry:SetMultiline(true)
TextEntry:SetText( "o o f                                     Freeze" )
```

Notes:
- Tested with stable and dev.
- May work on other Panels using `:SetMultiline( )`

**Credits to @LightPrismHD for finding this.**

**Comment by robotboy655** [comment] 2017-07-31 09:03
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/2690

**Closed by robotboy655** 2017-07-31 09:03 UTC
