### ISSUE TITLE
util.PrecacheModel doesnt cache model's activities on client

### ISSUE THREAD

**Issue by DeffOS** [Facepunch/garrysmod-issues#5927] opened 2024-07-04 09:06 UTC
### Details
Precaching models doesnt cache foreign acts on client leading to invalid acts or in case of entity loading model - mismatched actlist

![image](https://github.com/Facepunch/garrysmod-issues/assets/68462654/9f73ac83-2dc0-44c2-bf4f-6c791255632b)

### Steps to reproduce

-1. Get models to test (those from Dino D-Day) - [ForeignActs.zip](https://github.com/user-attachments/files/16096006/ForeignActs.zip)
<details><summary>0. Setup sh_TestCode.lua in autorun/ from this Spoiler</summary>

```lua
--SHARED FILE
local models = {
	"models/player/axis/trex_mp.mdl",
	"models/player/axis/styracosaurus_mp.mdl",
}
for _, model in ipairs(models) do
	util.PrecacheModel(model)
end

local ISSUE_actlist = {
	"ACT_DDD_TREX_ROAR_ATTACK",
	"ACT_DDD_TREX_ROAR_ATTACK_B",
	"ACT_DDD_TREX_PICKUP_BOMB",
	"ACT_DDD_TREX_THROW_BOMB",
	"ACT_DDD_TREX_PICKUP_FLAG",
	"ACT_DDD_TREX_DROP_FLAG",
	"ACT_DDD_TREX_EAT_PLAYER_A",
	"ACT_DDD_TREX_EAT_PLAYER_B",
	"ACT_DDD_TREX_PUKE",

	"ACT_SECONDARYATTACK_HEAD",
	"ACT_SECONDARYATTACK_TAIL",
	"ACT_STYRAC_RECOIL_NW",
	"ACT_STYRAC_RECOIL_W",
	"ACT_STYRAC_RECOIL_SW",
	"ACT_STYRAC_RECOIL_S",
	"ACT_STYRAC_RECOIL_SE",
	"ACT_STYRAC_RECOIL_E",
	"ACT_STYRAC_RECOIL_NE",
}

if SERVER then
	util.AddNetworkString("ISSUE.ForeignActs")
	local cl,cs,cc = Color(231,231,231),Color(100,198,255),Color(255,222,34)
	local function _spewRoutine(ply,callback)
		print("Starting Spew")
		net.Start("ISSUE.ForeignActs")
		net.Send(ply)
		local clientacts = coroutine.yield()
		for _, actname in ipairs(ISSUE_actlist) do
			MsgC(cl,actname,cs,"\t",util.GetActivityIDByName(actname),cc,"\t",clientacts[_],"\n")
		end
		callback()
	end
	local routine
	net.Receive("ISSUE.ForeignActs",function()
		local clientacts = {}
		for index, __ in ipairs(ISSUE_actlist) do
			clientacts[index] = net.ReadInt(16)
		end
		coroutine.resume(routine,clientacts)
	end)
	local function spewActlist(ply,callback)
		routine = coroutine.create(_spewRoutine)
		coroutine.resume(routine,ply,callback)
	end

	concommand.Add("ISSUE.TestForeignActs",function()
		print("Initial actlist check")
		local ply = Entity(1)
		spewActlist(ply,function()
			print("Changing playermodel to cache on client")
			ply:SetModel(models[2])
			ply:ConCommand("thirdperson")
			timer.Simple(1,function()
				spewActlist(ply,function()
					print("Not -1 client acts will not match server ones")
				end)
			end)
		end)
	end)
else
	net.Receive("ISSUE.ForeignActs",function()
		net.Start("ISSUE.ForeignActs")
		for _, actname in ipairs(ISSUE_actlist) do
			net.WriteInt(util.GetActivityIDByName(actname),16)
		end
		net.SendToServer()
	end)
end
```
</details>

1. Start new, non-Singleplayer, game
2. Run "ISSUE.TestForeignActs" command from file
3. Observe

**Comment by robotboy655** [comment] 2024-07-04 09:32
Looks to me like duplicate of https://github.com/Facepunch/garrysmod-issues/issues/1085 which should be solved on `dev`/`x86-64` betas, and in the next update.

**Closed by robotboy655** 2024-07-04 09:32 UTC

**Comment by DeffOS** [comment] 2024-07-04 09:41
Then i hope actlist desync issues will not persist

**Comment by robotboy655** [comment] 2024-07-04 10:21
There's no real reason to prevent it since models are loaded in random orders clientside and serverside, you should be using the act names either way, that's what they are for.

**Comment by DeffOS** [comment] 2024-07-04 10:53
I suspected this issue causing models in my case to not play animations but looks like its problem with how gmod loads Portal 2 branch .mdl
Also yea, thanks for fixing such old issues.
