### ISSUE TITLE
Hammer movement keys get stuck

### ISSUE THREAD

**Issue by stepa2** [Facepunch/garrysmod-issues#4768] opened 2020-12-16 12:32 UTC
I am not sure this bug is only happens with texture application tool.

### Steps to reproduce 
1. Create/open a map in Hammer.
2. Open "Face Edit Sheet" window (texture applicator)
3. Hold movement key (e.g. W) 
4. Press Alt+Right Mouse while holding movement key

**Comment by robotboy655** [comment] 2020-12-16 14:57
Cannot reproduce any bugs with given steps. It is likely this issue is already fixed on the Dev beta and in the next update.

**Closed by robotboy655** 2020-12-16 14:57 UTC
Labels: Cannot confirm, Tools
