### ISSUE TITLE
Using scripted_ents.Register more than once with same ent table that has no ClassName registers all ents with one ClassName

### ISSUE THREAD

**Issue by WinterPhoenix** [Facepunch/garrysmod-issues#5495] opened 2023-06-27 04:43 UTC
### Details
[There is/was some code in Fat Kid](https://github.com/swampservers/fatkid/blob/master/gamemodes/infection/gamemode/game/sh_spawnpoint_ents.lua#L23-L27) that utilizes the same table to register effectively the same entity under multiple names. This collides with https://github.com/Facepunch/garrysmod/pull/1299 in that `scripted_ents.Register` will set `ClassName` on the original table passed into it, if it doesn't have one already set. If you call that function multiple times in this scenario, it'll just end up re-using the same name over and over.

### Steps to reproduce
```lua
-- Not Working
local entNotWorking = {
    Base = "base_anim",
    Type = "anim"
}

for i=1, 2 do
    scripted_ents.Register(ENT, "custom_ent_" .. i)
end
print("exists", scripted_ents.Get("custom_ent_1"))
print("does not exist", scripted_ents.Get("custom_ent_2"))

-- Working
local entWorking = {
    Base = "base_anim",
    Type = "anim"
}

for i=1, 2 do
    scripted_ents.Register(table.Copy(entWorking), "custom_ent_" .. i)
end
print("exists", scripted_ents.Get("custom_ent_1"))
print("exists", scripted_ents.Get("custom_ent_2"))
```
In this example, `custom_ent_2` won't exist registering it with the `entNotWorking` table, but will with the `entWorking` table, because we copied it. Copying prevents `ClassName` from being set on the original.

### Conclusion
I'm not sure how we should handle this. Maybe devs shouldn't have expected to be able to use the same ent table for multiple entities in the first place? On the other hand, usually functions aren't expected to edit the table passed into it, unless it's explicitly outlined that that's what it does.

It seems like `scripted_ents.Alias` is the intended way to do something like what the code above does, but I can't imagine Fat Kid is the only gamemode that takes an approach like this.

**Comment by Kefta** [comment] 2023-06-27 07:36
For future reference, this was because I imported the SWEP's behaviour of setting the data table's ClassName directly. Coupled with the manual ClassName setting, this broke registering multiple SENTs with the same data table. SWEPs should have never done this, but it's too late to change it, so all that can be done is remove the newer SENT regression.

**Comment by robotboy655** [comment] 2023-06-27 19:49
I have reverted the change, so it should be fixed now.

**Closed by robotboy655** 2023-06-27 19:49 UTC
