### ISSUE TITLE
Entity:SetParent breaks clientside entity when parent go out of PVS

### ISSUE THREAD

**Issue by Be1zebub** [Facepunch/garrysmod-issues#5382] opened 2023-01-07 15:29 UTC
### Details
I use `Entity:SetParent(ply)` on clientside entity, when parent player change PVS clientside entity parent becomes NULL.
maybe its related to `Entity:AddEffects(EF_BONEMERGE)`

### Steps to reproduce
you can run code from: https://github.com/Facepunch/garrysmod-issues/issues/5381 to reproduce it
(parent clientside entity to bot, teleport bot to another PVS & CsEntity:GetParent() will return NULL, cs entity will freeze in the air instead of teleporting along with the parent).

**Comment by robotboy655** [comment] 2023-01-07 16:20
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/861

**Closed by robotboy655** 2023-01-07 16:20 UTC
