### ISSUE TITLE
x64 Gmod doesn't let me use -tools

### ISSUE THREAD

**Issue by MagentaIris** [Facepunch/garrysmod-issues#4567] opened 2020-07-04 01:03 UTC
Pretty much the title, Trying to use -tools in the 64 bit branch yields no tools, I'm assuming this will be enabled once it's released properly? If so then ignore this, i'm just making sure that -tools will still be accessible when the update comes out.

**Comment by robotboy655** [comment] 2020-07-04 01:08
You need to launch the 32bit build on the x64-86 branch.

**Comment by robotboy655** [comment] 2020-07-04 01:08
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/4459, thanks for using the Search feature.

**Closed by robotboy655** 2020-07-04 01:08 UTC

**Comment by TiberiumFusion** [comment] 2022-07-23 00:54
> Duplicate of #4459, thanks for using the Search feature.

Searching for [-tools](https://github.com/Facepunch/garrysmod-issues/issues?q=-tools) or ["-tools"](https://github.com/Facepunch/garrysmod-issues/issues?q=%22-tools%22) does not actually returns results with `-tools`. Instead it returns results with `tools`. This is a common word in conversation entirely unrelated to the -tools launch arg.

Thanks for testing the Search feature.
