### ISSUE TITLE
Adding rope with material decals/rendershadow crashes the game

### ISSUE THREAD

**Issue by xebage** [Facepunch/garrysmod-issues#5013] opened 2021-07-23 11:50 UTC
### Details
Version: 2021.07.12 (not using beta branch)
MDMP: https://files.catbox.moe/spmerv.mdmp
This particular bug crashes most of the players
### Steps to reproduce
1. Set console command "rope_material" value to "decals/rendershadow"
2. Spawn rope

### Notes
Setting rope_rendersolid by 0 fixes the problem

**Comment by robotboy655** [comment] 2021-07-23 14:55
Couldn't reproduce a crash, but disallowed the shader used by that material to be used in constraints.

The fix is in Lua, so you can apply it to your server immediately:
https://github.com/Facepunch/garrysmod/commit/49ea58682e029a482fe7d688f97a7644745f4954

**Closed by robotboy655** 2021-07-23 14:55 UTC
Labels: Crash
