### ISSUE TITLE
new parenting issue in latest update

### ISSUE THREAD

**Issue by Divran** [Facepunch/garrysmod-issues#2505] opened 2016-03-07 22:04 UTC
Reported on wiremod here https://github.com/wiremod/wire/issues/1105

Could it have something to do with the changes @willox mentioned here? https://github.com/Facepunch/garrysmod-issues/issues/1596

The problem is this:
If you make a parent circle in gmod, your game instantly crashes. This has always been the case. Wiremod has had [checks for this](https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/hologram.lua#L1006-L1016) in place since it first added parent functions, so it has never been a problem. Until now.

The problem seems to be that the GetParent function is always one tick out of date. Example:

- Make 3 props.
- Parent prop 1->2, 2->3, but leave 3->1 unparented. You now have a parent line, but not yet a circle.
- Now wait a short while, then unparent 2->3, and then re-parent 2->3 and 3->1, all in the same tick.

The GetParent function seemingly doesn't have time to update, which causes wire's check to fail, and the game to crash. If you add a timer to the SetParent function, it works (no longer crashes, since wire's check catches it in time). I would rather not do that, however, as some people's contraptions depend on being able to parent things quickly, or they will be misaligned.

**Comment by thegrb93** [comment] 2016-03-07 23:42
While you guys fix this, can make the parent cycle check internal as well so we don't have to deal with this anymore?

**Comment by willox** [comment] 2016-03-08 15:51
I'm not sure why this would have only started being an issue now. In the end I only modified some code that runs before CanPlayerEnterVehicle.

**Comment by Divran** [comment] 2016-03-08 16:47
I guess it doesn't have anything to do with those changes, then, but it definitely started happening recently.

**Comment by willox** [comment] 2016-03-09 01:59
I'm not sure why your method of reproducing this issue is so complicated compared to:
```lua
A:SetParent( B ); B:SetParent( A )
```

So it'd be nice if you could make sure the fix for this works as it should. It should be on the dev branch by tomorrow.

**Closed by willox** 2016-03-09 01:59 UTC

**Comment by Divran** [comment] 2016-03-09 09:20
Sorry i just tested what that guy posted in the wire issue, but yes any
cyclic connection crashes it so that would work as well

**Comment by thegrb93** [comment] 2016-03-09 09:36
His method was complicated because it was a way to bypass lua parent cycle detection.

**Comment by Divran** [comment] 2016-03-09 13:23
exactly
