### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by gpdgzpdn** [Facepunch/garrysmod-issues#5767] opened 2024-03-01 18:48 UTC
### Details
It seems like Zero’s lua addons (which we have on our darkrp server) somehow provoke audio-related crashes for some players.

It looks like crashes preceded by “DRASTIC MEMORY OVERFLOW: Fell out of small block heap!” and, sometimes, also with “total_channels == MAX_CHANNELS” console messages (however: 1. I’m not sure about this because I was able to get console logs only from one player; 2. crash doesn’t appear guaranteed after those warnings)

Crashes appear at 64-bit as well as at 32-bit version of Garry's Mod.

I sent all crash dumps and logs to robotboy655@facepunchstudios.com.

### Steps to reproduce
Unfortunately, I have not been able to find any patterns that could provoke this crash other than playing with Zero's addons, interacting with Zero's entities etc.

**Comment by robotboy655** [comment] 2024-03-08 15:54
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5120

Unfortunately this is not a crash I can do much about without a way to reproduce it.

How often do these crashes happen?

**Comment by robotboy655** [comment] 2024-03-22 17:14
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5809

**Closed by robotboy655** 2024-03-22 17:14 UTC
Labels: Crash
