### ISSUE TITLE
Bodygroups issue with weapons

### ISSUE THREAD

**Issue by HaodongMo** [Facepunch/garrysmod-issues#4698] opened 2020-10-14 10:38 UTC
### Details
When attempting to change the bodygroups of a weapon viewmodel in multiplayer above or equal to number 5 (Argument 1 in SetBodygroup), instead random other bodygroups will be changed if there are more than 5 bodygroup categories and at least one has more than 2 options.

### Steps to reproduce
First, create a viewmodel that has more than 5 bodygroups. As an example, the AK47 from ArcCW: Gunsmith Offensive. At least one bodygroup must have more than 2 options (Which are not blank).  Next, set up a basic SWEP to set a bodygroup on the viewmodel with vm:SetBodygroup(5, 1). Bodygroups that are not correct will be set, sometimes more than 1.

I used the code:
```SWEP.Spawnable = true

SWEP.ViewModel = "models/weapons/arccw_go/v_rif_ak47.mdl"

SWEP.UseHands = true

function SWEP:Deploy()
    local vm = self:GetOwner():GetViewModel()
    timer.Simple(0, function()
    vm:SetBodygroup(5, 1)
    end)
end
```

Bodygroup (5, 1) is no stock, and in singleplayer, this is set properly. However, in multiplayer, the AKS-74U barrel appears.

**Comment by TheOnly8Z** [comment] 2020-10-14 10:51
The workshop link for the weapon models is [here](https://steamcommunity.com/sharedfiles/filedetails/?id=2257255110). All viewmodels/worldmodels with many bodygroups seem to trigger it, even when the models themselves are properly compiled and can change bodygroups normally as a prop.

**Comment by robotboy655** [comment] 2020-10-14 13:21
Duplicate of https://github.com/Facepunch/garrysmod-requests/issues/830

**Closed by robotboy655** 2020-10-14 13:21 UTC
