### ISSUE TITLE
Issue with http.Fetch and URLs ending with "10.png"

### ISSUE THREAD

**Issue by Torbikini** [Facepunch/garrysmod-issues#5511] opened 2023-07-03 19:15 UTC
### Details

For some reason, I am getting the `invalid url` error when trying the `http.Fetch` a URL that ends in `10.png` (there could be more affected URLs, but these are the ones I have noticed the issue on.)

#### Versions tested, and the issue has been seen on:
```Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 20:27:54 Jun 27 2023 (8998) (4000)
GMod version 2023.06.30, branch: unknown, multicore: 0
Windows 32bit
```
```Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 17:00:04 Jun 28 2023 (8999) (4000)
GMod version 2023.06.30, branch: x86-64, multicore: 1
Windows 64bit
```

### Steps to reproduce
Run an `http.Fetch` with an image that ends in `10.png`, below are some example commands and the console output when running them from Garry's Mod.

```
lua_run_cl http.Fetch("https://img-cdn.sgn.gg/inventory/ttt/item_weapon_mac_1.png", function() print("success") end, function() print("fail") end)
success
lua_run_cl http.Fetch("https://img-cdn.sgn.gg/inventory/ttt/item_weapon_mac_10.png", function() print("success") end, function() print("fail") end)
fail

lua_run_cl http.Fetch("https://i.imgur.com/fIsRv10.png", function() print("success") end, function() print("fail") end)
fail
lua_run_cl http.Fetch("https://i.imgur.com/0gWZL32.png", function() print("success") end, function() print("fail") end)
success
```

**Comment by robotboy655** [comment] 2023-07-03 19:18
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/4133

**Closed by robotboy655** 2023-07-03 19:18 UTC
