### ISSUE TITLE
Game crash from dhtml panel

### ISSUE THREAD

**Issue by StarLight-Oliver** [Facepunch/garrysmod-issues#5208] opened 2022-04-26 12:15 UTC
### Details
Wiki says dhtml doesn't block mp4 (though it does say it blocks mp3) [example here](https://wiki.facepunch.com/gmod/HTML)
So I tried seeing if I could get videos to play like this.
When it failed to work I then tried to remove the panel and it proceeded to crash the game.
I have also tested this by exiting the game and it crashes it as well.

It doesn't crash if the removal happens same tick

Protocol version 24
Exe version 2021.12.15 (garrysmod)
Exe build: 17:57:22 Mar 10 2022 (8524) (4000)
GMod version 2022.03.17, branch: unknown, multicore: 0
Windows 32bit

### Steps to reproduce
`
HTMLTest = vgui.Create( "DHTML" )
HTMLTest:SetPos( 50, 50 )
HTMLTest:SetSize( ScrW() - 100, ScrH() - 100 )
HTMLTest:OpenURL( "http:/urlTo/amp4_file.mp4" )
timer.Simple(0, function()
HTMLTest:Remove()
end)
`

A simple block on mp4 would help resolve this crash

**Comment by robotboy655** [comment] 2024-03-26 18:42
Sounds like duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5139

**Closed by robotboy655** 2024-03-26 18:42 UTC
Labels: Crash
