### ISSUE TITLE
Segmentation fault, issue with constraints?

### ISSUE THREAD

**Issue by willcurry** [Facepunch/garrysmod-issues#3582] opened 2018-08-24 08:37 UTC
### Details
My server crashes randomly, always with the same debug.log. "rem_core_controller", this has been going on for a few weeks now. I run Ubuntu 14.04. When the server usually crashes the last thing used is the button tool, weld tool or keypad. But not always. I have researched this a lot online but have come to no solution. I know its vphysics crash and its hard to fix when I cannot reproduce and I am only giving little info but any help would be greatly appreciated as its really starting to stress me out. Thanks!

Here is the last lines in console and the debug log: https://pastebin.com/YXvL5X5p

### Steps to reproduce
I have not get figured out how to reproduce, but I have been trying. Its hard because I do not believe the issue is malicious. The crashes occur randomly.

**Comment by thegrb93** [comment] 2018-08-24 08:50
Looks like something to do with phys_constraintsystem used in the constraint library. I've seen crashes with it before, but not sure what all the crash cases are.

**Comment by willcurry** [comment] 2018-08-24 11:41
Yeah, its strange. My server is an RP server so the tools are very limited. I also don't have any editable entities with networked properties.

**Comment by robotboy655** [comment] 2018-08-25 00:42
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/2450

**Closed by robotboy655** 2018-08-25 00:42 UTC
Labels: crash, duplicate, vphysics

**Comment by willcurry** [comment] 2018-08-25 08:39
It that issue it looks like the issue occurs from a dodgy fishing addon, or using the rope tool. In my case the issue is coming from a tool like button or keypad using the constraint.Weld function. Could having a corrupt .so files cause this?

**Comment by Kefta** [comment] 2018-08-25 08:43
No, it's a crash in the physics module

**Comment by willcurry** [comment] 2018-08-31 20:04
After further exploration and testing I have discovered the function causing the crash is `constraint.Weld`. So I added this print to the weld function to give me some info: `print("WELD: " .. tostring(Ent1) .. "(" .. tostring(Bone1) .. ") and " .. tostring(Ent2) .. "(" .. tostring(Bone2) .. ") DOB:" .. tostring(deleteonbreak))`

When the server crashed it displayed this info on the last line `WELD: Entity [2374][prop_physics](0) and Entity [3318][prop_physics](0) DOB:nil`

Which gives no more information to me. Is there anything more I can do to get more information? This issue is really driving me crazy.

**Comment by thegrb93** [comment] 2018-08-31 22:45
It has to do with deleting a physics object attached to a phys_constraintsystem creating a new physobject and then trying to constrain it; or something along those lines.

Someone reported a sent_ball crash a while ago that involved it, but tools like makespherical or prop resizer might still suffer from it.

**Comment by thegrb93** [comment] 2018-08-31 22:46
https://github.com/Facepunch/garrysmod-issues/issues/3039

**Comment by thegrb93** [comment] 2018-08-31 22:47
https://www.youtube.com/watch?v=SJ-hhPLhdF4

**Comment by willcurry** [comment] 2018-09-01 10:32
Ah yes ive seen this before, but my server does not have any tools like that or sent_balls. My server also does not have any entities where you can edit its properties like with button (I disabled it on button).

**Comment by Kefta** [comment] 2018-09-01 10:42
That's just a way to reproduce the crash - it can happen with any constraint system.

**Comment by willcurry** [comment] 2018-09-02 19:53
`[PROP PROTECTION] DEspawn727(STEAM_0:0:175706679) used TOOL: button on prop_physics(models/hunter/blocks/cube05x4x05.mdl) at 2278.790283 -1382.015625 -149.653061 [owner: Player [44][DEspawn727]]
WELD: Entity [2221][gmod_button] at 2265.746582 -1451.679810 -147.990051 with angles 90.000 180.000 0.000(0) and Entity [824][prop_physics] at 2278.790283 -1382.015625 -149.653061 with angles 0.000 180.000 0.000(0) DOB:true
Segmentation fault (core dumped)`

Another one. What can/should I do? This is seriously harming my community now. Can you please respond @robotboy655

**Comment by thegrb93** [comment] 2018-09-02 21:58
See what model the button is. Maybe that has something to do with it.

**Comment by willcurry** [comment] 2018-09-13 15:08
> 
> 
> See what model the button is. Maybe that has something to do with it.

Good idea, I added in the model to the print but the model doesn't raise any alarms with me here is the print before the crash:

`WELD: Entity [2089][prop_physics] (models/hunter/blocks/cube4x4x025.mdl) at 3942.651611 -5759.796387 -19.543095 with angles -0.005 90.000 0.007[0] and Entity [1163][prop_physics] (models/hunter/blocks/cube4x4x025.mdl) at 3752.349854 -5759.796387 -19.543095 with angles 359.995 90.000 0.007[0] DOB:false`

**Comment by thegrb93** [comment] 2018-09-14 00:46
One of the addons on your server has to be manipulating their physics in some way that it doesn't like. I don't see crashes on my Sandbox server happen from welds. Think about what addon could be changing the entity's physics and try inducing the crash by using welds with whatever function the addon is doing. If you can find the cause, then it will be possible to add safety against it.

**Comment by willcurry** [comment] 2018-09-14 17:49
I don't think I have any addon that manipulates physics, most of my addons I wrote myself and I don't do anything with physics that I can remember. Also the crash above was caused by the weld tool. Im going to play around and look through everything again to make sure but I remember spending hours trying to reproduce his before and getting nowhere.

**Comment by thegrb93** [comment] 2018-09-14 22:30
I wonder if it's specific to Linux
