### ISSUE TITLE
Projected Textures do not show up on clientside props.

### ISSUE THREAD

**Issue by raubana** [Facepunch/garrysmod-issues#3268] opened 2017-08-13 17:04 UTC
_### Details
Tell us exactly what happens, every single detail that you can think of_

Simply, any clientside props will not have projected textures show up on them. That includes the player's flashlight. However, the prop will still produce a shadow behind it.

_### Steps to reproduce
Tell us how to reproduce the problem, step by step_

I've provided a simple addon for testing this bug out in gm_construct. A prop will spawn in the darker area directly behind the player-spawn area, as well as a projected texture which will shine down on the prop.

[cmodels_projtext_bug_testscript.zip](https://github.com/Facepunch/garrysmod-issues/files/1220602/cmodels_projtext_bug_testscript.zip)

**Comment by raubana** [comment] 2017-08-13 17:11
![20170813131043_1](https://user-images.githubusercontent.com/5302549/29251758-e6d6a920-8028-11e7-825b-077305db6c4e.jpg)

**Comment by NeatNit** [comment] 2017-08-25 01:47
I couldn't get your script to work, and I couldn't reproduce the issue myself:

![gm_construct0017](https://user-images.githubusercontent.com/2400026/29696172-bbb99e84-894f-11e7-920d-f11766167110.jpg)

Got this by running this in the console via lua_run_cl:
``` Lua
-- spawn an explosive barrel to precache the model, then ignore it or remove it

-- be in dark room
BRL = ents.CreateClientProp("models/props_c17/oildrum001_explosive.mdl")
BRL:SetPos(LocalPlayer():GetPos())

-- move back, point at barrel
PRJ = ProjectedTexture()
PRJ:SetPos(LocalPlayer():EyePos())
PRJ:SetAngles(LocalPlayer():EyeAngles())
PRJ:SetTexture("effects/flashlight/hard")
PRJ:Update()
```

**Comment by raubana** [comment] 2017-08-25 02:56
That's strange. I had FusionLord test my script with me in a server and he experienced the exact same glitch.

**Comment by thegrb93** [comment] 2017-08-25 03:08
OS

**Comment by raubana** [comment] 2017-08-25 03:30
My OS is Windows 8.1.

**Comment by FusionLord** [comment] 2017-08-25 03:31
Using Windows 10, Nvidia GTX 970. -dxlevel 110

**Comment by Kefta** [comment] 2017-08-25 03:57
@FusionLord 98 is the max supported dxlevel, just so you know.

**Comment by Kefta** [comment] 2017-08-25 04:38
I'm actually having an issue testing your code -- for some reason, clientside models are always spawned at 0, 0, 0 unless their position is set a frame later for me. Testing on dev branch single-player. However, I did figure out the discrepancy.

Lit barrel: Spawning barrel from spawnmenu first to precache it shared then running https://pastebin.com/EQqGUtgn
Unlit barrel: https://pastebin.com/756EgbWG
No barrel at all: https://pastebin.com/Hg4XdAj9

The problem seems to relate to when the model is precached and whether the model is set through the first argument of ents.CreateClientProp or SetModel.

**Comment by robotboy655** [comment] 2020-04-16 13:50
Should be fixed on Dev.

**Closed by robotboy655** 2020-04-16 13:50 UTC
