### ISSUE TITLE
Disconnecting while inside a Lua brush passes a somewhat invalid Player object

### ISSUE THREAD

**Issue by bigdogmat** [Facepunch/garrysmod-issues#3032] opened 2017-01-29 06:39 UTC
### Details
If you disconnect while inside a Lua brush, `IsValid` will return true, however the player table has been reset.

### Steps to reproduce
```lua
hook.Add("PlayerInitialSpawn", "test_1", function(ply)
  ply.somevar = true
end)

hook.Add("PlayerDisconnected", "test_1", function(ply)
  print("PlayerDisconnected", ply.somevar)
end)

function ENT:EndTouch(ent)
  if IsValid(ent) then
    print("EndTouch", ent.somevar)

    -- Just to show that variables can still be assigned to it
    ent.somevar = true
    print("EndTouch", ent.somevar)
  end
end
```

What will get printed

```
PlayerDisconnected    true
EndTouch    nil
EndTouch    true
```

**Comment by bigdogmat** [comment] 2017-09-03 18:49
Guessing this is probably related.

Running this in the hook
```lua
if not ent:IsPlayer() or ent:IsBot() then return end
```
I'll randomly get a `Player is NULL(!?)` error coming from the `IsBot` call.

**Comment by neico** [comment] 2017-09-03 20:15
Just because a player disconnected doesn't make the object vanish (or magically not getting referenced anymore), it still needs to be garbage collected, which will happen quite some time later, so being able to assign variables is totally expected behavior.

With that in mind the only place left is the actual `Entity:IsValid()` function (which `IsValid()` calls) that should be able to tell that the player behind the object is de-facto deleted by now and should return false (think of a temporary player object pool which reuses the objects instead of garbage collecting them)

If that works then we could probably modify `__newindex` to throw a error message until the object get's either collected or reused with a valid player object

PS: I don't remember well how exactly `EndTouch()` is being called, but ideally it should happen in the `OnDisconnect` phase, not the `OnDisconnected` phase (or even later), so that the trigger still has a valid object to work with

**Comment by bigdogmat** [comment] 2017-09-03 21:20
The issue at least in my first comment had nothing to do with the object still being there.

The issue is the fact that the player's table is a different table, as such not having any of the variables I had assigned to it on there. `IsValid` returns true for it, functions such as `AccountID` and printing out the object itself still show the correct information. As you've said I imagine this has to do with when `EndTouch` is being called during the disconnection process.

The second comment I imagine happens for the same reason, however it's much more sporadic and as such I don't really have an easy way of testing it. I wasn't checking `IsValid` in this case so it may have been returning false.

**Comment by robotboy655** [comment] 2019-08-14 18:18
This should be fixed in Dev. Not the `Player is NULL(!?)` stuff though, I couldn't reproduce that and it is unrelated to the original issue.

**Closed by robotboy655** 2019-08-14 18:18 UTC
