### ISSUE TITLE
Crashes on switching to camera

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3329] opened 2017-11-13 13:14 UTC
### Details
hl2.exe doesnt work anymore whenever I switch to camera in random situations.
(doesnt happen always)
it doesnt generate a crash log either.

### Steps to reproduce
Start a map.
Do some things.
Switch to camera. (Hopefully crashed)

**Comment by robotboy655** [comment] 2017-11-13 13:44
sigh...

Have you tried no addons?
No crash logs, "Happens randomly"

What do you expect us to be able to do about this?
First time I hear about anything like this for sure.

**Comment by mcNuggets1** [comment] 2017-11-13 13:45
I dont have any addons.
It happens on local multiplayer, listen server.
Crashlogs aren't there cause it is a hl.exe doesnt react anymore-crash.

**Comment by mcNuggets1** [comment] 2017-11-13 13:46
Actually on the map rp_downtown_evilmelon_fade it happens very often.
When I spam switch weapon to camera, it crashes very fast.

**Comment by mcNuggets1** [comment] 2017-11-13 13:47
It did a crash log. on the third time trying this.

https://www.dropbox.com/s/of02iwsh9rh709a/hl2_170801_crash_2017_11_13T13_47_13C0.mdmp?dl=0

**Comment by mcNuggets1** [comment] 2017-11-13 13:48
Another thing:
It only happens in a specific area of the map for some reason.

**Comment by robotboy655** [comment] 2017-11-13 13:50
Dev branch or live?

This looks like that material crash, nothing to do with cameras.

**Comment by mcNuggets1** [comment] 2017-11-13 13:51
I am heading to the dev branch, just to test for you.
This is how much I love you.

**Comment by mcNuggets1** [comment] 2017-11-13 13:55
Do you need a devbranch crash dump?

If you need one:
https://www.dropbox.com/s/i6choy6n4j5pozq/hl2_171108_crash_2017_11_13T13_54_42C0.mdmp?dl=0

**Comment by robotboy655** [comment] 2017-11-13 14:15
I am fairly certain this is related or duplicate of https://github.com/Facepunch/garrysmod-issues/issues/3282

**Comment by robotboy655** [comment] 2017-11-13 14:53
If you can make it happen at will, please do post the steps EXACTLY. If it happens at certain view angle or position, POST THEM.

**Comment by mcNuggets1** [comment] 2017-11-13 14:54
Ok I am now gonna tell you exact positions.

**Comment by mcNuggets1** [comment] 2017-11-13 14:55
http://steamcommunity.com/sharedfiles/filedetails/?id=837906408&searchtext=rp_downtown_evilmelon

setpos -9998.233398 8714.637695 49.031250;setang 5.593163 -7.892421 0.000000

**Comment by robotboy655** [comment] 2017-11-13 15:52
I thought you said you don't have any addons though?

Nothing happens for me when I spam select the camera with less than 0.2 delay on that map, not in given position, not anywhere else, running no mods on Dev in single player.

**Comment by mcNuggets1** [comment] 2017-11-13 15:53
I just got materials and models as mods.

**Comment by mcNuggets1** [comment] 2017-11-13 15:53
I deactivate everything and try it again.

**Comment by mcNuggets1** [comment] 2017-11-13 17:03
You are right, the crash issue is gone, when I unmount all my models/materials.
It likely is a material crash or some sort.

**Comment by mcNuggets1** [comment] 2017-11-13 17:17
Wait.
Actually it seems to be a code snippet which is the reason for this weird crash.
Switching to the camera removes an AvatarImage on the left corner of the screen.
This is causing this bug.

**Comment by mcNuggets1** [comment] 2017-11-13 17:18
local avatar
local function DrawPlayerAvatar(p)
	if !IsValid(avatar) then
		avatar = vgui.Create("AvatarImage")
		avatar:SetPos(64, ScrH() - 130)
		avatar:SetSize(56, 56)
		avatar:SetPlayer(p, 64)
		avatar:ParentToHUD()
	end
end

local function RemovePlayerAvatar()
	if IsValid(avatar) then
		avatar:Remove()
	end
end

hook.Add("HUDPaint", "DarkRP_HUDPaint", function()
	local ply = LocalPlayer()
	local wep = ply:GetActiveWeapon()
	if (IsValid(wep) and wep:GetClass() == "gmod_camera") then
		RemovePlayerAvatar()
		return
	end
	DrawPlayerAvatar(ply)
end)


This code is able to crash the game.

**Comment by mcNuggets1** [comment] 2017-11-13 17:26
But for some reason it only crashs on this specific position.
Enough tests done.
Gonna take a break.

**Comment by willox** [comment] 2017-11-13 18:44
Let me know if this is fixed on the dev branch once the update hits (30 minutes or less)

**Comment by mcNuggets1** [comment] 2017-11-13 20:41
It is not.
To this date.

**Comment by willox** [comment] 2017-11-14 09:10
Try it again and post any new crash dumps you get. Make sure the version on the main menu is 2017.11.13 or higher.

**Comment by mcNuggets1** [comment] 2017-11-14 09:13
https://www.dropbox.com/s/r36khon2z2gthzl/hl2_171113_crash_2017_11_14T9_13_0C0.mdmp?dl=0

**Comment by willox** [comment] 2017-11-14 11:05
Thanks a lot. I'll see if I can get a fix for this on to the dev branch soon.

**Comment by mcNuggets1** [comment] 2017-11-14 11:06
If you still need my help in anything, just contact me.
I am glad to help anyone of you :P

**Comment by mcNuggets1** [comment] 2017-11-14 11:53
It is fixed, bud.

**Closed** 2017-11-14 11:53 UTC
Labels: crash
