### ISSUE TITLE
[Dev] Unable to change gamemode

### ISSUE THREAD

**Issue by T-Rizzle12** [Facepunch/garrysmod-issues#5915] opened 2024-06-21 00:52 UTC
### Details
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 10:08:52 Jun 19 2024 (9356) (4000)
GMod version 2024.06.19, branch: dev, multicore: 1
Windows 32bit

I was creating a navmesh for a gamemode of mine in Sandbox when I attempted to change to my gamemode, upon creating the server it loaded in Sandbox again instead of to my gamemode. I do believe the fix you applied to the x86-64 branch was not applied to the dev branch which might be the cause of this!

### Steps to reproduce
1. Load into any gamemode, Example Sandbox
2. Change the gamemode, Example changing the gamemode from Sandbox to Trouble In Terrorist Town
3. Start a new game and wait for the loading screen to finish
4. After loading in notice that the gamemode was the same as before

**Comment by robotboy655** [comment] 2024-06-21 09:43
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5912

**Closed by robotboy655** 2024-06-21 09:43 UTC
