### ISSUE TITLE
"New game" menu freezing - Linux (Ubuntu 14.04)

### ISSUE THREAD

**Issue by ElectricFreaker** [Facepunch/garrysmod-issues#1790] opened 2015-02-14 23:22 UTC
Trying to change game from single player to multiplayer causes the GUI to freeze. The background images still cycle and the Workshop window updates addons. All the addons are disabled. I believe, but cannot verify if it is the awesomium process.

Installed it twice today, steam as well.

**Comment by robotboy655** [comment] 2015-02-14 23:48
Duplicate of #86

**Closed by robotboy655** 2015-02-14 23:48 UTC
Labels: duplicate
