### ISSUE TITLE
Crash at x86-64 with Entity:FireBullets

### ISSUE THREAD

**Issue by klen-list** [Facepunch/garrysmod-issues#4973] opened 2021-06-08 14:49 UTC
### Details
Works with all launch options (32, 64) and only at x86-64 branch.

Exe version 2020.10.14 (garrysmod)
Exe build: 16:52:49 May 26 2021 (8236) (4000)
GMod version 2021.06.02, branch: x86-64, multicore: 1
Windows 32bit

I use 3 addons:
1. [ArcCW] Arctic's Customizable Weapons (Base Only):
https://steamcommunity.com/sharedfiles/filedetails/?id=2131057232
2. [LFS] - Planes:
https://steamcommunity.com/sharedfiles/filedetails/?id=1571918906
3. And some weapon pack for ArcCW, for example, [ArcCW] Gunsmith Offensive:
https://steamcommunity.com/sharedfiles/filedetails/?id=2257255110

### Steps to reproduce
1. Download addons
2. Switch game to x86-64 branch
3. Start server with 2 players
4. bot
5. bot_zombie 1
6. bot_mimic 1
7. Give bot weapon
8. Take weapon and and turn around so that the bot can shoot you
9. Start shooting at the same time as the bot until your death
10. Bot kill you and game get crashed

I tested this crash with a friend and it looks like you need to shoot at the same time as the one who shoots you until you die.
I discovered this thanks to two players on my server playing on this branch of the game and get crashed.

-Lua Stack Traces-
==================
Crash stack:
 0  client.dll + 0x148789
 1  client.dll + 0x10bc7a
 2  lua_shared.dll + 0x494fc
 3  client.dll + 0x587a30

Executable: Steam\steamapps\common\GarrysMod\bin\win64\gmod.exe

  Client
    0. OldFireBullets - [C]:-1
      1. FireBullets - addons/base_lfs/lua/autorun/lfs_basescript.lua:41
        2. ProgressPhysBullet - addons/base_arccw/lua/arccw/shared/sh_physbullet2.lua:266
          3. fn - addons/base_arccw/lua/arccw/shared/sh_physbullet2.lua:151
            4. (null) - addons/system_ulib/lua/ulib/shared/hook.lua:109

  Server
    Lua Interface = NULL

  MenuSystem
    *Not in Lua call OR Lua has panicked*

lfs_basescript.lua:41
```lua
local EntityMeta = FindMetaTable("Entity")
local OldFireBullets = EntityMeta.FireBullets
function EntityMeta:FireBullets( bulletInfo, suppressHostEvents )
	if self.LFS then
		bulletInfo.Distance = math.min( (bulletInfo.Distance or simfphys.LFS.MaxBulletDistance), simfphys.LFS.MaxBulletDistance )
	end
	OldFireBullets( self, bulletInfo, suppressHostEvents )
end
```
sh_physbullet2.lua:266
```lua
...
              if CLIENT then
                -- do an impact effect and forget about it
                if !game.SinglePlayer() and bullet.PhysBulletImpact then
                    attacker:FireBullets({
                        Src = oldpos,
                        Dir = dir,
                        Distance = spd + 16,
                        Tracer = 0,
                        Damage = 0,
                        IgnoreEntity = bullet.Attacker
                    })
                end
                bullet.Dead = true
                if IsValid(bullet.Weapon) then
                    bullet.Weapon:GetBuff_Hook("Hook_PhysBulletHit", {bullet = bullet, tr = tr})
                end
                return
            elseif SERVER then
...
```

sh_physbullet2.lua:151
```lua
function ArcCW:DoPhysBullets()
    local new = {}
    for _, i in pairs(ArcCW.PhysBullets) do
        ArcCW:ProgressPhysBullet(i, FrameTime())

        if !i.Dead then
            table.insert(new, i)
        end
    end

    ArcCW.PhysBullets = new
end
hook.Add("Think", "ArcCW_DoPhysBullets", ArcCW.DoPhysBullets)
```

### Crash dumps:
https://cdn.discordapp.com/attachments/786061154622373938/851786568758591508/62b772fc-3f33-4259-abcd-6137e1cd147a.dmp
https://cdn.discordapp.com/attachments/786061154622373938/851786570242850817/3932a1b3-1dce-4fd4-9448-8b50cb66d5b8.dmp

**Comment by michak89** [comment] 2021-06-13 14:58
Since last update my dedicated x86 linux server crashes like 7 times a day with similar issue:  https://pastebin.com/bw8GmLBa

**Comment by michak89** [comment] 2021-06-13 16:00
I noticed similar crash on my dedicated x86 server since last update: https://pastebin.com/ufHw5LM1 
Server crashes on average 7 times a day, always with this.

**Comment by robotboy655** [comment] 2021-06-13 16:36
That one is fixed already on both beta branches.

**Comment by robotboy655** [comment] 2021-06-14 08:32
Yes, it's that same crash which should be fixed on latest versions.

**Comment by MagentaIris** [comment] 2021-07-01 21:22
This is a still problem, util.Decal on the Client realm can sometimes cause the extra same lua stack crash output (x86-64 branch)

It happens with FireBullets too on occasion, Absolutely no idea how and why it happens but just calling FireBullets or util.Decal on the client can cause it at random, perhaps specific objects/surfaces.

Happens more on Listen Server clients than the host though.

Seems to be something to do with calling a trace function via hooks, plausibly to do with how its being called into C?

**Comment by robotboy655** [comment] 2021-07-02 08:13
Please read this article on how to report crashes:
https://wiki.facepunch.com/gmod/Crash_Reporting

**Comment by MagentaIris** [comment] 2021-07-02 08:43
[Crash_Shit.zip](https://github.com/Facepunch/garrysmod-issues/files/6753278/Crash_Shit.zip)

Yeah okay here's some stuff, This crash is extremely consistent on CLIENTS who join a LISTEN SERVER.

This crash happens with FireBullets, but I decided to remove FireBullets entirely and make my own library to counter act that, only to find out that util.Decal does the same thing too.

These crashes are from a Client who connected to me as we where testing these issues.

As it says in most of the TXT outputs, it will say that FireBullets or Decal was the cause of the crash.

`Executable: E:\Steam_Games\steamapps\common\GarrysMod\bin\win64\gmod.exe

-Lua Stack Traces-
==================
  Client
    0. FireBullets - [C]:-1
      1. v - gamemodes/thehiddenirisedition/entities/weapons/wepshityeahcool/game_cl_clientbullets.lua:1095
        2. (null) - lua/includes/modules/hook.lua:84

  Server
    Lua Interface = NULL

  MenuSystem
    *Not in Lua call OR Lua has panicked*`

**As a note though:**
using the following
`function util.Decal() end`
in a shared environment (after removing FireBullets from my stuff entirely) fixes every single crash as of this issue for my friend when testing in my listen server.

Something was changed in recent times that caused this to happen, Don't know where you'de even start looking but as long as you have some form of version control it shouldn't be too hard to find what was fecked up.

**Comment by robotboy655** [comment] 2021-07-02 09:50
From what I can tell it's a multicore rendering crash, but I cannot reproduce no matter how many bullets I fire at bots and props and the world as a player on a listen server.

**Comment by MagentaIris** [comment] 2021-07-02 10:23
> From what I can tell it's a multicore rendering crash, but I cannot reproduce no matter how many bullets I fire at bots and props and the world as a player on a listen server.

Jank.

This never used to happen so there's been a change somewhere.

**Comment by thegrb93** [comment] 2021-07-02 22:33
> 
> 
> From what I can tell it's a multicore rendering crash, but I cannot reproduce no matter how many bullets I fire at bots and props and the world as a player on a listen server.

Probably requires another player to be shooting

**Comment by robotboy655** [comment] 2021-07-02 22:42
I tested with mutlirun.

**Comment by thegrb93** [comment] 2021-07-03 00:36
Probably some more multithreading convars needed then. Usually players enable more than just mcore_test

**Comment by thegrb93** [comment] 2021-07-03 00:37
That or its platform specific

**Comment by MagentaIris** [comment] 2021-07-03 11:12
If you're looking for all the convars assigned to this stuff then this is usually what is used.

```
cl_threaded_bone_setup 0
mat_queue_mode -1
cl_threaded_client_leaf_system 1
r_threaded_client_shadow_manager 1
r_threaded_particles 1
r_threaded_renderables 1
r_queued_ropes 1
studio_queue_mode 1
gmod_mcore_test 1
```

**Comment by MagentaIris** [comment] 2021-07-03 13:17
Managed to crash again by shooting a wall as a listen server host, 64 bit with multicore enabled, util.Decal is overriden in this instance with

```
function util.Decal()
end
```

FireBullets isn't called once i'm pretty sure, but heres the crash anyway.

[oops_crash.zip](https://github.com/Facepunch/garrysmod-issues/files/6758462/oops_crash.zip)

**Comment by Minc3** [comment] 2021-07-04 11:13
I'm also having this issue.
I have the following convar auto enabled for my players:

  cl_threaded_bone_setup 0
  r_threaded_renderables 1
  cl_threaded_client_leaf_system 1
  r_threaded_client_shadow_manager 1
  r_threaded_particles 1
  r_queued_ropes 1
  mat_queue_mode -1
  studio_queue_mode 1

  gmod_mcore_test 1

Sometimes when I shoot I crash straight to my desktop.
Other players on my server are having the same issue. Not all of them crash to desktop.

I have ask a few players to give me there crash dump file:
[mdump.zip](https://github.com/Facepunch/garrysmod-issues/files/6759789/mdump.zip)

**Comment by robotboy655** [comment] 2021-07-05 14:20
This **should** be fixed on x86-64/dev betas. Let me know if that is not the case. Obviously you need to update the client first before testing.

**Closed by robotboy655** 2021-07-05 14:20 UTC
Labels: Crash

**Comment by MagentaIris** [comment] 2021-07-05 22:05
[crashu.zip](https://github.com/Facepunch/garrysmod-issues/files/6766324/crashu.zip)

Uh oh.

Just to note, the decal call looks something like this:
`util.Decal( DECAL_TABLE[DEC], (Trace.HitPos + Trace.HitNormal), (Trace.HitPos - Trace.HitNormal), self )`

Grabbing a decal string from a table, the usual position output, and then Filtering the entity on the fourth argument so the decal doesnt hit the entity its being emitted from.

**Comment by Minc3** [comment] 2021-07-06 03:06
It's still happening.
[crashing.zip](https://github.com/Facepunch/garrysmod-issues/files/6767068/crashing.zip)

**Comment by robotboy655** [comment] 2021-07-06 09:32
I missed a spot, THIS time it really should be fixed.
