### ISSUE TITLE
Setting $basetexture on a unlitgeneric material created with CreateMaterial causes border problem?

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#2425] opened 2016-02-02 03:38 UTC
Details are here https://facepunch.com/showthread.php?t=1503924&p=49654443#post49654443

Sample code here https://facepunch.com/showthread.php?t=1503924&p=49647618&viewfull=1#post49647618

Basically, using surface.DrawTexturedRect with a material created this way will cause the edges of the texture to not be visible unless the UVs or $basetexturetransform are manipulated.

**Comment by thegrb93** [comment] 2018-05-30 03:05
Finally found the answer.
http://wiki.garrysmod.com/page/surface/DrawTexturedRectUV

solved by replacing surface lib with render lib
https://github.com/thegrb93/StarfallEx/issues/433

**Comment by robotboy655** [comment] 2020-11-06 17:44
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/4715 or https://github.com/Facepunch/garrysmod-issues/issues/3173

Closing this instead of the other stuff because links to forums are dead.

**Closed by robotboy655** 2020-11-06 17:44 UTC
