### ISSUE TITLE
Letter keys register as numbers in the addon search

### ISSUE THREAD

**Issue by BorealBlizzard** [Facepunch/garrysmod-issues#5128] opened 2021-12-30 20:23 UTC
### Details
While trying to search through my installed addons using the search bar anytime I type it only outputs numbers, this doesn't happen elsewhere. Works perfectly fine in console or game chat

### Steps to reproduce
Not really sure how to reproduce, most of my addons are disabled except some maps, and outfitter but it was still like that when those where disabled.

Video showing example
https://youtu.be/uDdSPOqoCIE

**Comment by robotboy655** [comment] 2021-12-30 22:54
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/4464

**Closed by robotboy655** 2021-12-30 22:54 UTC
Labels: Duplicate
