### ISSUE TITLE
[x64] GMod doesn't run on Antergos Linux

### ISSUE THREAD

**Issue by CaptainPRICE** [Facepunch/garrysmod-issues#3758] opened 2019-02-17 18:41 UTC
### Details
In x64 (testing) branch of GMod, the game fails to launch on Antergos Linux:
![image](https://user-images.githubusercontent.com/9789070/52917310-32f27f80-32ea-11e9-8d70-a950e4a4cae3.png)

I can confirm the file it is trying to lookup (`engine_client.so`), does exist at `./bin/linux64`.

Also tried launching it directly using Terminal:
```
> ./bin/linux64/gmod -steam -game garrysmod
```

Have tried copying all files from `./bin/linux64` into updir `./bin`:
```
> ./bin/gmod -steam -game garrysmod
```

Both attempts fail, producing the following error:
> Failed to load the launcher (launcher_client.so: cannot open shared object file: No such file or directory)

Something is preventing it from finding necessary files in the right place.

NOTE: Garry's Mod (32-bit/x86) runs fine otherwise (the public stable/master branch).

### Steps to reproduce
- Download and install Antergos Linux (x64) operating system.
- Download and install Steam, and Garry's Mod.
- Switch to x64 branch:
![image](https://user-images.githubusercontent.com/9789070/52917389-1c98f380-32eb-11e9-9e3a-0f0120dc9cde.png)
- Start Garry's Mod (64-bit) using Steam interface.

**Comment by CaptainPRICE** [comment] 2019-02-18 02:02
I should also add, I have tested x64 branch on Ubuntu 18.10, and it works fine there.
It is something specific to Antergos.

**Comment by robotboy655** [comment] 2019-02-18 02:48
Duplicate of #3668 I guess.

**Closed by robotboy655** 2019-02-18 02:48 UTC
Labels: linux

**Comment by CaptainPRICE** [comment] 2019-02-18 02:52
Well. Why not close the other one instead? Here is more useful information.
(imo, I'd have closed the other issue, just saying.)

**Comment by Bo98** [comment] 2019-02-18 03:31
I notice that it’s a different file when you run from the command line. Is LD_LIBRARY_PATH set correctly? Does hl2.sh still work?

**Comment by CaptainPRICE** [comment] 2019-04-07 17:15
**FIXED** (solved by hand, tracing what GMod is actually doing)
> AppFramework : Unable to load module engine_client.so

Apparently, `engine_client.so` is not an issue... (Blame CEF here.)
Open terminal, and enter these commands:
```
sudo ln -s /usr/lib/libedit.so /usr/lib/libedit.so.2
sudo sysctl kernel.unprivileged_userns_clone=1
```

If you have `/usr/lib64` folder, also perform these commands:
```
sudo ln -s /usr/lib64/libcurl.so.4 /usr/lib64/libcurl-gnutls.so.4
sudo ln -s /usr/lib64/libedit.so.0 /usr/lib64/libedit.so.2
```

The first command creates a symlink of `libedit.so` file, this is an actual file that GMod is searching for, but fails to find it.
The second command is to do with CEF sandbox (search up `--no-sandbox`).
Then, finally you can launch 64bit GMod on (GNU) Linux such as Antergos using `./hl2_x64.sh`.

Enjoy playing 64-bit GMod on GNU Linux:
![screenshot](https://user-images.githubusercontent.com/9789070/55686881-001e4c80-5967-11e9-9ddf-0131aac22533.png)

-----

Credits goes to my Linux buddy, fors. Cheers.

**Comment by willox** [comment] 2019-04-24 14:07
@CaptainPRICE Both of these issues should be fixed. We no longer depend on libedit and the game won't try to load Chromium if it thinks the unprivileged user namespaces aren't available (there's no visual indication of this though, so you'd just have a blank main menu and no HTML support.)

Some error message for Chromium can be added later.
