### ISSUE TITLE
x86_64 Chromium crashes shortly after startup with no crash reports or errors, Mac Monterey 12.6

### ISSUE THREAD

**Issue by bedrockperson** [Facepunch/garrysmod-issues#5487] opened 2023-06-22 17:04 UTC
### Details
 
June update rolled out. Tried to launch G-Mod, it crashed almost immediately. Re-installed the [Codec fix](https://github.com/solsticegamestudios/GModCEFCodecFix), G-Mod now stays up for about 15 seconds, then hard crashes.

No crash files are generated. The Mac Problem reporter is not triggered. 

And because I just know it is coming: No, this is not a duplicate of [#5001](https://github.com/Facepunch/garrysmod-issues/issues/5001).

### Steps to reproduce

1. have mac
2. launch game
3. suffer

**Comment by robotboy655** [comment] 2023-06-22 17:11
What makes you so sure it's not a duplicate?

**Comment by bedrockperson** [comment] 2023-06-22 17:18
> What makes you so sure it's not a duplicate?

point's kind of moot since this is now longer an issue (isn't technology grand?) but you've pretty much subsumed *any* issue regarding the codec submitted in the past year and a half into the .dylib discussion

**Comment by robotboy655** [comment] 2023-06-22 18:00
`GModCEFCodecFix` is not official by any means, any issues with it should be reported to its authors, not here.

Since you have stated nothing to make me believe otherwise, I am closing this as a duplicate of #5001 i.e. the crashes you are/were experiencing are most likely caused by either incompatibility between `x86-64`'s CEF build and newest MacOS versions, or due to 3rd party modifications you had installed.

**Closed by robotboy655** 2023-06-22 18:00 UTC
Labels: Platform: MacOS
