### ISSUE TITLE
"hammer_update_entity" functionality is broken

### ISSUE THREAD

**Issue by Matt2468rv** [Facepunch/garrysmod-issues#2004] opened 2015-05-03 22:51 UTC
When optimizing a map, it is very important to settle the physics props and have them start asleep to save valuable CPU cycles when the map spawns, and for props not to visually drop into place.  The method of doing this can be found here:

https://developer.valvesoftware.com/wiki/Map_edit#Using_map_edit_to_settle_physics_props

When I get to step 7 and type "hammer_update_entity prop_physics" into the console, Garry's Mod crashes and completely closes to the desktop.  When I go back to Hammer, the viewports are frozen as if Hammer is in "locked" mode.

The above method works properly in other source games such as HL2, but not in Garry's Mod.  I haven't tested any other hammer-related console commands besides this one.

**Comment by TheFreeman193** [comment] 2015-05-04 16:15
I can confirm this occurs on Dev branch 2015.05.03. Appears to be a crash in server.dll.

@Matt2468rv Your issue with the freezing is just a result of running *map_edit* on the map; hammer becomes read-only when you do this, and doesn't return to normal because the game crashes before releasing it.

**Comment by robotboy655** [comment] 2015-05-04 18:15
Can you confirm this NOT happening in non Dev?

**Comment by Matt2468rv** [comment] 2015-05-04 18:16
@TheFreeman193 Yes, that's what I figured.  Hammer doesn't get unlocked because the game crashes.

@robotboy655 By my testing, this does happen on both dev and non-dev branch.

**Comment by TheFreeman193** [comment] 2015-05-04 22:44
@robotboy655 Yep, this is occurring on live branch too; it's probably something that's been lying around unnoticed for a while.

**Comment by robotboy655** [comment] 2015-10-05 13:39
Can anyone test whether this was fixed in Dev? I have updated hammer to the latest version.

**Comment by TheFreeman193** [comment] 2015-10-20 22:14
Still crashing for me.

**Comment by Ataman** [comment] 2016-05-27 12:30
This still happens one year later, any fix in sight?

**Comment by KyuuGryphon** [comment] 2018-01-09 00:03
Can confirm this is still happening, over a year and a half later.

**Comment by Matt2468rv** [comment] 2018-01-09 00:21
I don't think it's been fixed.  I got around this issue by getting my map running in CS:S and doing everything there.  But it was a hassle having to go do that for any new physics prop I added.

**Comment by robotboy655** [comment] 2018-01-09 10:55
Should be fixed in Dev

**Closed by robotboy655** 2018-01-09 10:55 UTC
