### ISSUE TITLE
Garry's mod crashes when loading a map

### ISSUE THREAD

**Issue by FirepantsCZ** [Facepunch/garrysmod-issues#2132] opened 2015-06-27 17:58 UTC
(sorry for the spelling, i am not english)
So, when i try to load a map the last thing it says is initializing game data and then the game crashes to desktop. This only happens when i am subscribed to specific addons in the steam workshop.
I already tried to verify game cache integrity and it says all files successfully verified (or something like that) but the game keeps crashing. Then i tried to run the dev vesion of the game and i tried to unsubscribe to some addons (sometimes that helps,sometimes not) can someone please explain how to fix it? btw i have cca 353 addons if that helps.

**Comment by robotboy655** [comment] 2015-06-27 18:06
You know it helps if you tell us all the information you know, like the "specific addons" you are subscribed.

This is not a place to get help. Get help @ http://facepunch.com/forums/16

Duplicate of #2131

**Closed by robotboy655** 2015-06-27 18:06 UTC
