### ISSUE TITLE
Studiomdl destroys lod 0 when $lods are used

### ISSUE THREAD

**Issue by TiberiumFusion** [Facepunch/garrysmod-issues#4832] opened 2021-02-11 05:25 UTC
# Details
When I compile a certain model with $bodygroups and $lods, studiomdl fucks up the vertices on lod 0 (and only on lod 0) when at least 3 lods are present. When only 2 lods are present, the issue does not occur.

## Demo 1:
Relevant qc: [https://pastebin.com/WJCrufsJ](https://pastebin.com/WJCrufsJ)
Compile result:
![Demo 1](https://user-images.githubusercontent.com/6332277/107687448-78957900-6c74-11eb-834b-fd66159794dc.png)

## Demo 2:
Relevant qc: https://pastebin.com/RENbxB3z
Compile result:
![Demo 2](https://user-images.githubusercontent.com/6332277/107604677-d2f3f280-6bfe-11eb-9bda-b48a70c05ba7.png)

## Other notes
- SMD vs DMX has no effect.
- As shown in the demos, the model has 4 submeshes in a bodygroup. If I remove 1 submesh so there are only 3 submeshes in the body group, then the issue does not occur when 3 lods are present. I can even add a 4th lod and the compiled model is still fine. Perhaps this means the issue is triggered when the total amount of geometry studiomdl has processed passes a certain threshold.

I am not particularly interested in sharing the model source files if this issue can be diagnosed without them.

### Tested Versions
Issue occurs with the studiomdl included with:
• x86-64 2021.02.10
• Vanilla 2021.02.05
• Vanilla 2020.08.18
• Vanilla 2020.01.21
• **Vanilla 2019.09.03**

These versions of studiomdl all produce the exact same result as shown in Demo 1 and Demo 2.
**See my next comment for additional testing with *different* results.**

**Comment by TiberiumFusion** [comment] 2021-02-11 20:23
# Additional tests
While testing various studiomdl versions, I encountered different (but still mangled) results.

## Demo 3
**Studiomdl versions**
• Vanilla 2019.07.02
• Vanilla 2019.04.30
• Vanilla 2019.02.19
• Vanilla 2018.12.15

Relevant qc: [https://pastebin.com/gbnYK6GH](https://pastebin.com/gbnYK6GH)
Compile result:
![Demo 3](https://user-images.githubusercontent.com/6332277/107692306-9665dc80-6c7a-11eb-8c39-ebf834088a8e.png)
### Key notes
- Compared to Demo 1, this qc is my full model compile with all 4 lods (3 regular + shadow lod).
- Only submesh 3 has been destroyed in lod 0. All other submeshes are fine. All other lods are fine.
- Note that the way submesh 3 was mangled is *different* compared to the later studiomdls, as shown in my OP.
- When I repeat this test (Demo 3's qc) with any of the studiomdl versions listed in the OP, I get results like what is shown in Demo 1's picture (i.e. lod 0 submesh 2 and 3 are destroyed, all other submeshes are fine). The mangling will be even more pronounced, however (more verts out of place). I suspect this is tied to the difference in geometry between the lowest lod and the highest lod.

## Other notes
**These tests indicate that between 2019.07.02 and 2019.09.03, studiomdl changed in some way that altered the behavior of this issue.**

**Comment by TiberiumFusion** [comment] 2021-02-11 21:31
# Notes on other games's studiomdls
I can already hear rubat typing "this is how Studiomdl has always worked since HL2" so I've taken the liberty of preemptively testing that claim.

### Studiomdls that destroy the model
- **Gmod** (as we've already seen). Has two different studiomdl behaviors as shown by Demo 1 and Demo 3.
- **TF2.** Produces models that looks like Demo 1, not Demo 3. In other words, this studiomdl is consistent with the gmod's 2019.09.03 and later studiomdls, but **not** with gmod's 2019.07.02 and earlier versions.
- **HL2 Ep2.** Produces models that looks like Demo 3, not Demo 1. In other words, this studiomdl is consistent with the gmod's 2019.07.02 and earlier studiomdls, but **not** with gmod's 2019.09.03 and later versions.
- **Portal.** Same as HL2 Ep2.
- **Left 4 Dead 2.** Same as HL2 Ep2.

### Studiomdls that get the model _correct_
- **SFM.** But I'm not sure if it produces a v48 or v49 model, since my model does not use vertex animation.

**Comment by robotboy655** [comment] 2021-04-20 10:47
I will need to model sources that compile to the problematic mesh if this is to be debugged further.

It was caused by CS6324 on 22.08.2019. A rollback is not really an option as both versions are bad.

**Comment by TiberiumFusion** [comment] 2021-04-20 21:47
@robotboy655 I have emailed you the relevant source files.

**Comment by robotboy655** [comment] 2021-04-22 14:35
Well I found a fix, but I don't know what side effects will occur if I push it.

May be related issue:
https://github.com/Facepunch/garrysmod-requests/issues/1637

**Comment by robotboy655** [comment] 2021-04-30 14:03
Added `-vpfix` command line option to our `studiomdl.exe` for you to try on the Dev beta. I have restored the default behavior to how it is in HL2/L4D2/In GMod before, as it is clearly better, but I was unable to find the proper fix for this and I have tried a bunch of things including copying over CS:GO's studiomdl almost entirely, (CS:GO studiomdl.exe appears to not suffer from this)

**Comment by TiberiumFusion** [comment] 2021-04-30 17:56
@robotboy655 You say "I was unable to find the proper fix", so then what exactly does this new `-vpfix` option do? If it is not a "proper fix", then what are the caveats?

**Comment by robotboy655** [comment] 2021-04-30 18:58
I don't know what sideeffects it may have on the model, that's why its behind a command line option.

**Comment by TiberiumFusion** [comment] 2021-04-30 19:14
@robotboy655 When I compile the demo I sent you with your mysterious `-vpfix` option, the model looks just fine in hlmv, as I am sure you have already done yourself. I have not tested the model in gmod itself, however, and I surely would not know the proper means and extent to test it for "side effects".

I get correct models from SFM's studiomdl, and gmod seems to handle those v49 mdls without any issues. Since SFM's studiomdl doesn't require a mystery argument with unknown side effects, I don't have any reason to go back to gmod's studiomdl and use your blackbox `-vpfix` option.

**Comment by robotboy655** [comment] 2021-05-03 10:04
The point is for you to use it on a bunch of models and see if it creates any issues (that being fucked up meshes), but suit yourself.

**Comment by TiberiumFusion** [comment] 2021-05-04 07:53
@robotboy655 Ok, I'll add that to my list for the week and get the report on your desk by Friday.

Actually, wait, no, I don't recall being hired by Facepunch to fix _your_ bugs in _your_ game when I bought gmod. I must admit, though, I am surprised you got this far into the ticket before saying "ehhhh good enough" and expecting a user to do the rest of your work for you.

If the point really is for me to do the boring part of your job for you, then just put a check in the mail and I'll get right on with it. I'll cut you a sweet deal at $15/hour.

**Comment by Goldermor** [comment] 2024-10-17 21:33
With -vpfix
![Image](https://github.com/user-attachments/assets/22ac7494-64a9-4a99-a862-394ce81da44a)
Without
![Image](https://github.com/user-attachments/assets/64337ac8-9a46-438d-907b-87a286de48d4)

Some vertexes are distorted at the UV seams

**Comment by robotboy655** [comment] 2024-10-18 15:58
I see. Thanks. Well that was my only guess as to what has changed in the outlined timeframe of 2019.07.02 to 2019.09.03. On 22 Aug 2019 there was a change (ported from TF2) that changed the "POSITION_EPSILON" from 0.05 to 0.01 which I suspect what caused the differences outlined in the OP. The command line switch `-vpfix` changed the epsilon to 0.1 instead, but I see now that it causes other unwanted issues, so I will delete the switch.

I guess the model goes wonkers when there are vertices between the LODs that are not in the exact same positions when studiomdl tries to calculate a "optimized" VTX file, or something to those lines.

Since I have no model to test with, there's nothing I can really do here but speculate.

**Comment by robotboy655** [comment] 2024-10-18 16:54
I think I found the fix for this issue (meshes getting destroyed), it will be committed to `dev` beta today.

**Closed by robotboy655** 2024-10-18 16:54 UTC
Labels: Confirmed Bug, Tools
