### ISSUE TITLE
Serverside lua_error_url config sends errors from several different servers.

### ISSUE THREAD

**Issue by callumok2004** [Facepunch/garrysmod-issues#5352] opened 2022-11-11 00:21 UTC
### Details
https://wiki.facepunch.com/gmod/Lua_Error_Logging

Recently I have been using `lua_error_url` to send all client and serverside errors received to a URL. I noticed errors from several different servers were coming through. I have it protected with an auth key, so it is very unlikely the url was found and key was also found, as I changed it several times while this was happening. The errors were coming from several different gamemodes across several different IPs.

### Steps to reproduce
Set `lua_error_url` in your server.cfg file, have somewhere to see what is being sent to the URL.
Notice how several different servers are sending errors to that url, alongside the server it was set on, makes no sense...
It may take a bit for errors to come through, watch for at least 20 minutes, though, you may notice them in a much shorter time.

Contact on discord if more information is required. Callum#6052

**Comment by robotboy655** [comment] 2022-11-11 03:14
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/5348

**Closed by robotboy655** 2022-11-11 03:14 UTC
