### ISSUE TITLE
Offline Workshop subscription of several files -> duplicated .gma files

### ISSUE THREAD

**Issue by EstevanTH** [Facepunch/garrysmod-issues#4039] opened 2019-10-27 21:00 UTC
### Details
Hi,

I have subscribed on the Workshop to a map then its contents, before starting Garry's Mod.

After starting the game, not finding the map in my list, I check my addons. I have 2 identical `.gma` files!

I removed the wrong `.gma` file, restarted the game, then it was re-downloaded and now it works.

Versions: *Garry's Mod 2019.10.25 dev branch*, *Steam 2019-10-02 11:49:12* (reformatted date)

### Steps to reproduce
1. Do not start Garry's Mod.
1. Subscribe to [Rp_NewExton2](https://steamcommunity.com/sharedfiles/filedetails/?id=1318768443) then [Rp_NewExton2 Content](https://steamcommunity.com/workshop/filedetails/?id=1565323177), in that order.
1. Start Garry's Mod.

### Thanks
Thank you all!

Momo :heart:

**Comment by robotboy655** [comment] 2019-10-28 16:39
Cannot reproduce it using your steps to reproduce. I don't know how you got 2 identical .gma files, you should've taken a picture of that because I don't think it is even possible, at least on Windows, and especially considering the files end in the workshop id, which is always unique.

I get the 2 proper files:
![image](https://user-images.githubusercontent.com/3299036/67698014-30384600-f9b2-11e9-878a-3e3ccb412c46.png)

**Comment by Kefta** [comment] 2019-10-28 19:59
Perhaps you had two unique workshop addons with the same name?

**Comment by EstevanTH** [comment] 2019-11-01 11:17
Well, what is for sure is that both `.gma` files contained the files of `rp_bewexton2_content` because I extracted them. And file sizes matched as well. I browsed for comments about such a problem on respective Workshop pages, not finding anything I compared the displayed download sizes. That is how I have concluded that a bug was going on.

Is it possible that the bug belongs to Steam and not from Garry's Mod? Because what I think I know so far is that Steam downloads the compressed file from the Steam Cloud into a location of its own, and then Garry's Mod extracts it into its `addons` folder.

How could I have 2 unique Workshop addons with the same name? 🤔

**Comment by neico** [comment] 2019-11-01 12:02
It's unlikely this bug will be present with the newer ISteamUGC API,
and I wouldn't know either how such a case is possible, unless it was somehow of an old version?
Looking at both workshop item's changelog one can assume that the content one was added later on and probably wasn't uploaded correctly at the time you installed it first, which then for some reason didn't get updated further?

One issue I've observed over the years is that due to having the workshop item name inside the filename (instead of its global, unique ID only) it can happen that with an update the name is changed and the old gma not being cleaned up properly, which would sound like what happened here.

But as rubat said, without you having made a backup, a screenshot or having written down the `exact` name of the files in question it's unlikely we'll ever be able to reproduce that.

**Comment by robotboy655** [comment] 2019-11-01 13:37
You cannot have 2 files with the exact same filename, its physically impossible. Old .gma files (If an addon changes its name for example) will not be mounted.

**Comment by EstevanTH** [comment] 2019-11-01 16:44
This was the very first time I ever subscribed to this couple of addons. I sent this report a short moment after sorting out what happened.

And yeah, unfortunately, I have kept no trace (no screenshot & nothing in the recycle bin). ☹️

**Comment by robotboy655** [comment] 2019-11-08 14:49
Going to have to close this as I cannot reproduce this. I tried having a floating addon that is a copy of a workshop map and the map still worked.

**Closed by robotboy655** 2019-11-08 14:49 UTC
Labels: cannot confirm/reproduce
