### ISSUE TITLE
CSS and CSGO Hammer Entity Compatibility issues

### ISSUE THREAD

**Issue by wackod** [Facepunch/garrysmod-issues#4935] opened 2021-05-02 20:59 UTC
These problems will affect many CSS custom maps(almost All Zombie Escape Maps)
func_physbox_multiplayer

this Entity in CSS will Not collide with players by default   and  can hit trigger like trigger hurt
but in gmod  this entity will collide  with players , Of course you can use SetCollisionGroup  ,  but it have another problem
example :
A weapon was put in a func_physbox_multiplayer     in gmod ,by default  you can not go through the box  and can not pickup weapon in the box ,    when you use SetCollisionGroup()  , yes  you can go through ,  but this func_physbox_multiplayer will not be able to trigger  any trigger  entity  .   you can use COLLISION_GROUP_DEBRIS_TRIGGER  then you can go through the box  , and box can hit trigger entities but you can not pick up the weapon in this box (pickupweapon hook will not call)
in CSS or CSGO by default  you can  go through func_physbox_multiplayer and you can pickup the weapon in this box  and this box will still be able to trigger something

DEV texture 
tools/toolsinvisible
if you use this texture  on func_breakable (or something else), in gmod   the bullet can not hit the entity  but in CS  bullet can hit it

**Comment by robotboy655** [comment] 2021-05-03 09:10
Partially or entirely duplicate of https://github.com/Facepunch/garrysmod-issues/issues/2825

**Closed** 2021-05-03 22:57 UTC
