### ISSUE TITLE
util.BlastDamageInfo on npc_metropolice server crash

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#3213] opened 2017-06-03 00:35 UTC
There's some sweps that run util.BlastDamageInfo repeatedly for area damage over time like gas or whatever. If it encounters npc_metropolice, the server crashes.

Repeated call to this, 1 each frame next to a group of npc_metropolice.
This is code to a flame thrower
```
local flame = DamageInfo()
flame:SetDamageType(DMG_BURN)
flame:SetAttacker(self.Owner)
flame:SetInflictor(self)
flame:SetDamage(8)

util.BlastDamageInfo( flame, flamepos, 128 )
```

**Comment by thegrb93** [comment] 2017-06-03 00:37
Here's another one that crashes.
This is code to nerve gas.
```
local poisonowner
if IsValid(self) then 
	if IsValid(self.Owner) then 
		poisonowner = self.Owner
	elseif IsValid(self.Entity) then
		poisonowner = self.Entity
	end 
end
if not IsValid(poisonowner) then return end
	
util.BlastDamage(self, poisonowner, pos, radius, damage)
```

**Comment by robotboy655** [comment] 2017-06-03 01:13
Have you tried testing Dev branch in case its already fixed? I cannot reproduce this.

**Comment by thegrb93** [comment] 2017-06-03 02:00
I think it only happens with dedicated server with players. I'm testing now atm.

**Comment by robotboy655** [comment] 2017-06-03 02:09
Post crash dumps. I cannot reproduce it on dedicated server either.

**Comment by thegrb93** [comment] 2017-06-03 02:28
Okay I got it to happen

https://www.dropbox.com/s/6a6kn79xxgc1q41/hl2_170525_crash_2017_6_3T2_26_38C0.mdmp?dl=0

**Comment by robotboy655** [comment] 2017-06-03 02:33
Its already fixed in Dev...

**Comment by robotboy655** [comment] 2017-06-03 02:34
It has to do with Attacker not being set

**Closed by robotboy655** 2017-06-03 02:33 UTC
Labels: crash

**Comment by thegrb93** [comment] 2017-06-03 02:40
Attacker is set though.
